### ISSUE TITLE
Udemy Plugin 0.9.0 Unexpected Error

### ISSUE THREAD

**Issue by evaspaceman** [matthuisman/slyguy.addons#1]
When trying to watch a course video via the Kodi Udemy plugin, the following unexpected error is occuring (all videos tested trigger the same error).

Kodi versions tested: Latest Leia 9.2.6 & the past several Matrix nightly builds (latest 4/22/2020).
System: Raspberry Pi 4

Attribute Error:'NoneType' object has no attribute 'get'

File "plugin.py", line 229, in play
  streams = stream_utls.get('video') or stream_urls.get('Audio') or
File "plugin.py", line 44, in decorated_function
  return f(*args, **kwargs)
File "plugin.py", line 79 in decorated_function
  return f(*args, **kwargs)
File "router.py", line 188, in dispatch
  function(**params)
File "signals.py", line 31, in throwable
  yield

**Comment by matthuisman** [comment]
Thanks for the bug report. I'll investigate and get it sorted asap :)

**Comment by matthuisman** [comment]
@evaspaceman 
could you just try logout and log back in?
Does that fix it?

**Comment by evaspaceman** [comment]
Did not fix...
I tried logging out and back in; unfortunately, that did not help.  In addition, I uninstalled and reinstalled the plugin, but that did not help either.  I also tried the plugin on another instance of Kodi/LibreELEC, but receive the same error.  

There was a typo in the error received.  The File "router.py", error is line 118, in dispatch, not 188.

**Comment by matthuisman** [comment]
Could you please get me a full debug log?

**Comment by evaspaceman** [comment]
What is the best way to capture and send the debug log?

**Comment by matthuisman** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by evaspaceman** [comment]
Attached is my Kodi.log file.

Thanks

Chris

**Comment by matthuisman** [comment]
Did you forget the attachment? I'm not sure if you  can attach via email reply

**Comment by evaspaceman** [comment]
I attached the file to an email response.  Here's the file.

[01_KODI.log](https://github.com/matthuisman/slyguy.addons/files/6370843/01_KODI.log)

**Comment by matthuisman** [comment]
ok, i see that on some of my content.
They are moving over to Widevine encrypted media and I can't yet get it to playback in Kodi...
Will keep trying

**Comment by matthuisman** [comment]
@evaspaceman
just pushed 0.9.1 that should fix the issue :)

**Comment by lundeen-bryan** [comment]
Big thank you for fixing this issue and documenting the way to share the log file. I really appreciate your work Matt!
