### ISSUE TITLE
Samsung TV Plus Update error.

### ISSUE THREAD

**Issue by betatester3016** [matthuisman/slyguy.addons#100]
Hi Matt, this just FYI. 

Some error showed up during the update to 0.1.8. It doesn't seem to create issues with the update process itself, and the addon is working fine.

![IMG_20211209](https://user-images.githubusercontent.com/49594656/145498577-59c2067e-2435-4f69-89c6-e697d50c9d75.jpg)

**Comment by matthuisman** [comment]
has the error came back?
Sometimes these errors happen if something tries to access the addon during the update.

should be a one-off?

**Comment by betatester3016** [comment]
Hi Matt,

I think you're right.

It happened again and this time I noticed the Netflix addon was still doing it's magic in the background when this error showed. To test, I disabled the Netflix addon, set updates to manual, and waited for the next update. No error showed during the manual update.

For now I am leaving updates to notify / manual.
