### ISSUE TITLE
Paramount+ Sport

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#101]
Hey Matt is there any chance of moving the sport menu onto the main menu of Paramount? not a big deal if not but for some reason my shortcut keeps breaking as if the sport category is moving destinations within the app

**Comment by matthuisman** [comment]
the ID probably changes.

I have just added a new feature that allows telling my add-on to automatically select a folder within a folder by matching it's name.

If your using favourites, then edit the favourites.xml and set it to
`<favourite name="Sport" thumb="C:\Users\Matt\AppData\Roaming\Kodi\19\portable_data\addons\slyguy.paramount.plus\icon.png">ActivateWindow(10025,&quot;plugin://slyguy.paramount.plus/?_=featured&amp;_autofolder=sport#0&quot;,return)</favourite>`

The plugin path is plugin://slyguy.paramount.plus/?_=featured&**_autofolder=sport#0**
That tells my add-on, get the Featured folder. now look for any folders that matches the pattern sport
And then select the 1st occurrence 0 (python list indexes start at 0)

There is also _autoplay which behaves the same except it looks for playable items and starts playback

**Comment by scottydulton** [comment]
thanks @matthuisman thats awesome sorry for the late reply
