### ISSUE TITLE
Bein Sports Connect - Unable to find video asset

### ISSUE THREAD

**Issue by RHStonks** [matthuisman/slyguy.addons#102]
When I go to live and click on Bein Sport 1 and the Bein Sports Extra it pops up an error message "Unable to find video asset" when there is a live game on.

**Comment by matthuisman** [comment]
Does it work on website using the same VPN etc?

**Comment by RHStonks** [comment]
I'm not using a VPN at the moment but it works using it on a web browser. I believe this is a Bein Sports Connect Kodi addon issue.

**Comment by matthuisman** [comment]
What country are you in?

**Comment by RHStonks** [comment]
New Zealand

**Comment by matthuisman** [comment]
please try with latest version v0.3.8
maybe also try logout and login again

**Comment by RHStonks** [comment]
Cheers Matt. Working perfectly now. May I ask what was the issue?

**Comment by matthuisman** [comment]
they update their app to send a new "buildno" field
https://github.com/matthuisman/slyguy.addons/commit/e6e52471b0f44dfba015d55eabd2cff2ecdf2331#diff-f089cb962df51ceaf300ce470c7c3768bd21621e333713606c57fe3860d4949fR37

**Comment by RHStonks** [comment]
Same issue again. 

May need to add new "buildno" field
into the add-on.
