### ISSUE TITLE
ESPN - No Items

### ISSUE THREAD

**Issue by usphil** [matthuisman/slyguy.addons#105]
After update version 0.2.6, the add-on plays fine in one day and now Live section is "No Items" again

**Comment by matthuisman** [comment]
If you go to espn website, what is the name above the live tiles?

**Comment by usphil** [comment]
From Home it is sorted as follows:
Featured Live, Also Live, Leagues, Sports, Top Picks, Upcoming, Exclusively on ESPN+ v.v...
In the add-on I just seen Featured Live and Upcoming only

**Comment by matthuisman** [comment]
Right. So yesterday it swapped to a single "Live" and today it's back to "Featured Live" and "Also Live". So I suspect it switches to a single Live when not many games. 

We want to use either Live or Also Live. Featured live doesn't have all the live games.

Ill push a temp update shortly to revert back and then work on a better way

**Comment by matthuisman** [comment]
ok, 0.2.7 just pushed
this will first look for "also live" and then "live"

**Comment by Brandon1212b** [comment]
I am having this same issue. Live and Upcoming both show ~ No Items ~
