### ISSUE TITLE
WIndows10 Kodi19.3 IPTVMerge , Plex, Pluto Samsung, Stirr, No channels

### ISSUE THREAD

**Issue by markosjal** [matthuisman/slyguy.addons#107]
WIn 10
Kodi 19.3
IPTVMerge
Plex Live
Pluto
Samsung TV
Stirr

I use this on LibreElec and it works fine but getting blank channel list in Windows 10 in IPTVSimple Client on Kodi 19.3.

Any ideas ? I have reinstalled all addons still no joy

**Comment by matthuisman** [comment]
full debug log please
