### ISSUE TITLE
[Android] Widevine videos will not play on Oculus Go

### ISSUE THREAD

**Issue by moocow1452** [matthuisman/slyguy.addons#112]
http://paste.kodi.tv/wujewofubu

Not entirely sure if anything can be done about this, but I'm playing around in the unlocked build for Oculus Go, and sideloaded Kodi with your channel addons. Nebula, Stirr and Pluto worked flawlessly, but Disney and Hulu were giving me trouble, starting a video in the background and when I went back to Kodi's main screen, the video looked like a grey static block with some odd artifacting. The native Netflix and Amazon apps on the device work fine, and when I had Hulu sideloaded, it was able to work okay, so I don't know if it's your stuff, Kodi, or some weird Oculus deal.

**Comment by matthuisman** [comment]
closing this as it would be out of my hands either way to get this working. either a inputstream adaptive or kodi or oculus issue to fix
