### ISSUE TITLE
Bein Sport Connect - Unable to find video asset

### ISSUE THREAD

**Issue by RHStonks** [matthuisman/slyguy.addons#114]
#102

Same issue again. May need to update addon with new buildno.

**Comment by matthuisman** [comment]
actually a different issue. Problem is I'm not showing the error returned from Bein.
But a generic error. 

just pushed  0.3.9 that should show a better error message.
If yours is the same as mine, it tells me I need to relogin.
After doing that - then playback is fine.

Please report back with the error you see and if that helps

**Comment by RHStonks** [comment]
It's working again thanks. 

I did not need to login again.
