### ISSUE TITLE
Spark Sport Kodi addon causes my Mi Box S to reboot or back out of the stream often or close Kodi

### ISSUE THREAD

**Issue by RHStonks** [matthuisman/slyguy.addons#115]
The other addons I have installed such as Sky Go don't cause my Mi Box S to reboot but for some reason Spark Sport Kodi addon causes my Mi Box S to reboot or back out of the stream or close the app automatically often. 

Not sure whether this is due to Mi Box S not having enough ram to run Spark Spork but it doesn't do this with the other SlyGuy addons I use. 

Let me know if you know what the issue is. Thanks

**Comment by matthuisman** [comment]
What version Kodi are you using?
Pretty sure this issue was fixed in 19

**Comment by RHStonks** [comment]
> What version Kodi are you using?
> 
> Pretty sure this issue was fixed in 19

I'm using the latest version of Kodi 19.3. 

But the weird thing is that I don't get this issue with Sky Go. This only happens with Spark Sport.

**Comment by matthuisman** [comment]
Live only I suspect?
Vod is ok?

**Comment by RHStonks** [comment]
> Live only I suspect?
> 
> Vod is ok?

I don't use VOD so I'm uncertain but definitely happens when I play live either through live channels or live event.

**Comment by matthuisman** [comment]
i think it may be the same issue as this:
https://github.com/xbmc/inputstream.adaptive/issues/783

Spark uses multi-chapter live streams.
So I need to seek over these when playback starts to get to the live head.

**Comment by RHStonks** [comment]
> i think it may be the same issue as this:
> 
> https://github.com/xbmc/inputstream.adaptive/issues/783
> 
> 
> 
> Spark uses multi-chapter live streams.
> 
> So I need to seek over these when playback starts to get to the live head.

Thank you for figuring out what the problem is. I also posted about another issue that's happening with Sky Go which will have more detail about it on the post.

**Comment by matthuisman** [comment]
as spark sport will be gone in a few months, I dont want to invest any time into this sorry so closing this
