### ISSUE TITLE
Disney+ "No items" error, Portability feature doesn't work.

### ISSUE THREAD

**Issue by Shadow0man** [matthuisman/slyguy.addons#116]
Hello, I use my account from Netherlands in Poland using portability login. Unfortunately plugin doesn't work after login I can't see any content in folders (no items). Maybe it's due to the way addon is logging in to account. To login with portability I have to use this address : https://www.disneyplus.com/eu/login and it says there that is for portability purpose only. I wonder if you could look at it and maybe there is a way to activate the proper log in with this type of connection to service. 
I really need a solution to change audio stream to Atmos because broken software in my Samsung TV is disabling Atmos audio from original Disney+ app. Even if my TV is capable of lossy Atmos. This addon is my only hope. 

I read few closed issues with "No items" and the thing I see is that site is reading probably  my region as PL in this addon which is Poland and here Disney+ is not officially  available but there should be a way to change it to portability region which is 'EU' after login into site by browser my address looks like this https://www.disneyplus.com/eu/home

To clarify portability feature of Disney+ exist due to EU law which commits Disney to let the user from one EU country use the same digital content in other EU countries even if content (Disney+) is not available there.

In queries.py there is something related to portability " portabilityLocation { __typename countryCode } " which makes me think that something in addon is not configured properly to execute it through addon.

**Comment by Shadow0man** [comment]
I read few closed issues with "No items" and the thing I see is that site is reading probably  my region as PL in this addon which is Poland and here Disney+ is not officially  available but there should be a way to change it to portability region which is 'EU' after login into site by browser my address looks like this https://www.disneyplus.com/eu/home

**Comment by matthuisman** [comment]
Thank you for explaining why there is portability :)
I'm sure I can work it out.

So to confirm:
There is no Disney+ in Poland?
Your Disney+ login is for Netherlands.
But if you use the /eu/ website, your Netherlands login works fine in Poland?

**Comment by Shadow0man** [comment]
1. Yes 2. Yes 3. Yes 
I think it is the same library as Netherlands. I'm not 100% sure, but seems like it.

**Comment by Shadow0man** [comment]
Thanks for looking into it. It would be a dream if it worked :)

**Comment by matthuisman** [comment]
could you please try the latest Disney+ version 0.11.1
pretty sure it should work - but cant test myself as dont have an EU login

**Comment by Shadow0man** [comment]
It worked! Thank you very much :) Now I can enjoy The Mandalorian in Atmos on my Sonos Beam 2 :D

**Comment by matthuisman** [comment]
Yah! Thank you for taking time to explain the issue clearly. Made it much easier :)
