### ISSUE TITLE
Prompting for playback quality not always asked

### ISSUE THREAD

**Issue by stuckinthe** [matthuisman/slyguy.addons#118]
I am running Matrix on a Rpi 3+ running Arch Linux v7. Thank you for providing a great addon that I installed from your repo (0.21.7). I am having an issue when prompting for playback quality which is set to ask. On some channels it asks and on others it doesn't ask. It seems the ones it doesn't ask are the ones that I have some buffering issues hence the reason I want to lower the quality. Also, my context menu doesn't show playback quality options as it just shows switch channels and navigate.

**Comment by matthuisman** [comment]
What addon of mine are you using? Only in my add-ons will you get the quality control etc

**Comment by stuckinthe** [comment]
Sorry I forgot to add this info. I am using IPTV Merge. Some of the channels will prompt and some won't.

**Comment by matthuisman** [comment]
Oh. Quality control is a feature of my addons. So any channels that come
from them will prompt. For others, you can feed them through my system be
enabling the setting "use proxy" under playback in IPTV settings.

Try enable that and run merge again. Then try

**Comment by matthuisman** [comment]
If that is already enabled, then those channels must not being using a multi quality manifest. So can't change quality

**Comment by stuckinthe** [comment]
Yes I had it enabled. I think it has to be enabled to use the playback quality. I see. I had a feeling the stream wouldn't allow it but I figure I would ask. Thanks for the help.
