### ISSUE TITLE
Sky go

### ISSUE THREAD

**Issue by jamos316** [matthuisman/slyguy.addons#12]
Hi
Are you still updating the sky go addon?
My login details don’t work

**Comment by matthuisman** [comment]
have you switched to the new version?
**slyguy.skygo.nz v0.1.6**

**Comment by jamos316** [comment]
Am on 0.1.6
Still my registered email & password is invalid

**Comment by matthuisman** [comment]
Your sky go new Zealand correct??

**Comment by jamos316** [comment]
Ah sorry thought it was sky go in uk
