### ISSUE TITLE
HBO Max - A couple of issues

### ISSUE THREAD

**Issue by RHStonks** [matthuisman/slyguy.addons#120]
1. I have subtitles automatically turned on for all kodi addons but for some reason it's always disabled when using HBO Max.

2. Some tv shows and movies don't work and whenever I play it looks like it is a music file only with no video. This happened with Justice League and others.

**Comment by matthuisman** [comment]
1) Check the subtitle settings inside HBO Max
2) Odd. Your using American login? What quality are you selecting when asked?

**Comment by RHStonks** [comment]
> 1) Check the subtitle settings inside HBO Max
> 
> 2) Odd. Your using American login? What quality are you selecting when asked? what is your device?
> 
>    Debug log would be great

1) In HBO Max addon there is no option called Include Forced and non-forced subs like the Hulu addon so that might be why subtitles aren't automatically enabled when using HBO Max. 

2) Yes using America login. I have quality set to best and using Mi Box S.

How do I use debug log?

**Comment by RHStonks** [comment]
I think the reason why Justice League Synder Cut wasn't playing is cause of the aspect ratio of the film is movie box so that's why it wasn't playing. 

Only issue I have now is subtitles are not automatically enabled when playing video.

**Comment by matthuisman** [comment]
also, with quality set to max, you may be getting H265 content which I know the Mi Box doesnt like.
I think there is a setting to turn off H265 to make sure that doesnt happen

**Comment by matthuisman** [comment]
also, those two sub settings in Hulu dont actually do anything. They should actually be hidden.

You may just need set the Default Subtitle to **en** (or whatever language you want)
That should force my addon to set the en subs to default.
You can also use the Subs Whitelist so only the language you want is availalbe

**Comment by RHStonks** [comment]
> also, with quality set to max, you may be getting H265 content which I know the Mi Box doesnt like.
> 
> I think there is a setting to turn off H265 to make sure that doesnt happen
> 
> 
> 
> 

Ok I have no idea. I turn it off and see what happens

**Comment by matthuisman** [comment]
You may just need set the Default Subtitle to en (or whatever language you want)
That should force my addon to set the en subs to default.
You can also use the Subs Whitelist so only the language you want is availalbe

**Comment by RHStonks** [comment]
> also, those two sub settings in Hulu dont actually do anything. They should actually be hidden.
> 
> 
> 
> You may just need set the Default Subtitle to **en** (or whatever language you want)
> 
> That should force my addon to set the en subs to default.
> 
> You can also use the Subs Whitelist so only the language you want is availalbe

I have set Default subtitle to en but this still does not automatically turn on subs. I have to manually turn it on still. Do you think the HBO Max addon might need updating to support turning on subtitles automatically?

**Comment by matthuisman** [comment]
nope, it all uses the same backend that takes care of doing the subs.
keep trying

**Comment by matthuisman** [comment]
ive just tested now. HBO > Suicide Squad
I set "Default Subtitle" to en and Kodi automatically enabled the english subtitle.

**Comment by RHStonks** [comment]
> nope, it all uses the same backend that takes care of doing the subs.
> 
> keep trying

Seems weird that it only happens on HBO Max but Hulu and Disney+ automatically turns on subs fine. 

I have set default subtitle as en but still the same issue. 

I'll just manually turn it on each video if that's the case.

**Comment by matthuisman** [comment]
you sure using **en** and not eng (has to be **en**)
what is your kodi subtitle setting set to?

**Comment by RHStonks** [comment]
> you sure using **en** and not eng (has to be **en**)
> 
> what is your kodi subtitle setting set to?
> 
> 
> 
> your also running the latest version of the add-on right?
> 
> My addons should always be the latest. otherwise we just waste time 

On the HBO Max addon under playback, default subtitle is set as en. The HBO Max addon is on version 0.8.2.

My Kodi subtitle setting set to under player, language, preferred subtitle language is set to use interface language which is english. I've also enabled parsing for closing captions and under accessibility has prefer subtitles for the hearing impaired on.

**Comment by matthuisman** [comment]
kodi 19 on Android Mi Box S

**Comment by RHStonks** [comment]
> kodi 19 on Android Mi Box S

Kodi 19.3 on Android Mi Box S. 

Only HBO Max requires me to enabled subtitles manually by turning the subtitle switch on. 

Hulu and Disney+ has the subtitle switch on automatically so no issues with these 2 addons

**Comment by matthuisman** [comment]
Yes. You said that.
 I'm telling you I can't replicate

**Comment by matthuisman** [comment]
OK, found the issue

When Kodi is set to "use interface language", it doesn't fallback to [Default] language.
Well, doesn't automatically enable it.

Change this Kodi setting to "original language" for now and it should work.

**Comment by RHStonks** [comment]
> OK, found the issue
> 
> 
> 
> When Kodi is set to "use interface language", it doesn't fallback to [Default] language.
> 
> Well, doesn't automatically enable it.
> 
> 
> 
> Change this Kodi setting to "original language" for now and it should work.

Thank you, I can't believe it works now. Maybe you should note that somewhere if someone else has the same issue as me or will that be fixed in the future.

**Comment by matthuisman** [comment]
i think ive found a work-around.
Ill just change any en-us to just en in the manifest.

**Comment by matthuisman** [comment]
**ok, fixed with slyguy common 0.49.5**
once thats updates, you can switch back to " use interface language" and should work
