### ISSUE TITLE
GPIO Monitor Question: Migrate mapping?

### ISSUE THREAD

**Issue by nandbert** [matthuisman/slyguy.addons#127]
Hi Matt, is there a way to migrate the GPIO mapping from one Kodi to another?

I.e. have the same functionality on the other system w/o entering all the mappings manually again in the GUI?

Thx!

**Comment by matthuisman** [comment]
Just copy the userdata folder for the gpio monitor addon :)

**Comment by nandbert** [comment]
:+1:
