### ISSUE TITLE
Iptv merge not install in my PC

### ISSUE THREAD

**Issue by guiworldtv** [matthuisman/slyguy.addons#130]
I'm trying install iptv merge to use with kodi 19 version, but cannot install, i'm try install separately and nothing
After i'm trying install with the zip file all the addon's together, but too not work
i'm try install in two pc's with windows 10 but not sucessfull
Only say not install the add'on

**Comment by matthuisman** [comment]
YOU must install the repo, and then install IPTV Merge from the repo.
You can not install the addons by themselves

**Comment by guiworldtv** [comment]
> YOU must install the repo, and then install IPTV Merge from the repo. You can not install the addons by themselves

Oh yeah, i do this and can install the iptv merge
thanks
by the way you know some addon from kodi for record the signal of the channels m3u?
i know another app but i want do this in kodi, the interface its better than other app

**Comment by matthuisman** [comment]
try
https://forum.kodi.tv/showthread.php?tid=329991
but will only work with non-encrypted channels.

ask there for any help with that - i dont personally use it
