### ISSUE TITLE
Disney plus - No Plot Description of Movies. 

### ISSUE THREAD

**Issue by iansutherland74** [matthuisman/slyguy.addons#134]
Disney plus - No Plot Description of Movies.  Can't find any plot description of Movies.  When I play a movie it gives a plot description under the info.

**Comment by matthuisman** [comment]
correct - they dont provide that data in the api results.
**You can click "Full Details" via context menu to access it which will fetch it**

same as there website etc - if you get a big list of movies - you wont have descriptions until you click into it

I could fetch the details for every movie listed - but that means 50+ more API calls before the list appears
