### ISSUE TITLE
Disney Plus api request failed: forbidden error 

### ISSUE THREAD

**Issue by iibosshog75** [matthuisman/slyguy.addons#135]
I've never had this issue before. There is no way I can't login. I reset and reinstalled the addon without success. It is also followed by instructions on how to perform an OAuth request. (Settings-login-Oauth..) which I don't know how to work out. I'm on Kodi 19.3 Diggz Xenon Plus 7.6.

**Comment by matthuisman** [comment]
Full debug log please

**Comment by iibosshog75** [comment]
I just logged in and now everything seems to work just fine. Weird...

Il gio 3 mar 2022, 00:21 Matt Huisman ***@***.***> ha scritto:
