### ISSUE TITLE
Paramount at_token

### ISSUE THREAD

**Issue by 89z** [matthuisman/slyguy.addons#136]
Do you know how these are derived?

https://github.com/matthuisman/slyguy.addons/blob/c06d8ccd1a579205e014f87cc18f82e783f22119/slyguy.paramount.plus/resources/lib/config.py#L10-L21

I was able to capture my own, but they seem to differ depending on the path of the request URL.

**Comment by matthuisman** [comment]
Pulled from the source of their android apks

**Comment by 89z** [comment]
You sure about that? I just searched extracted with JADX, and searched for:

~~~
ABCq
~~~

and:

~~~
G30P
~~~

and didnt find anything. I used this APK:

~~~
GET https://android.clients.google.com/fdfe/details?doc=com.cbs.app
Title: Paramount+ | Peak Streaming
UploadDate: Feb 22, 2022
VersionString: 8.0.54
VersionCode: 210805434
~~~

**Comment by matthuisman** [comment]
Yup. Either that or via the api calls there app makes. Either way, the app
would need to know the tokens either via a request or built in.

95% sure it was hardcoded in the android tv apps

**Comment by 89z** [comment]
I dont think its hardcoded.

**Comment by matthuisman** [comment]
I can't recall then sorry

**Comment by 89z** [comment]
Found it:

~~~
PS D:\Desktop\com.cbs.app-210805434\sources> rg -F '.setCbsAppSecret('
com\cbs\app\dagger\DataLayerModule.java
40:        dataSourceConfiguration.setCbsAppSecret("6c70b33080758409");
PS D:\Desktop\com.cbs.app-210805434\sources> rg -F 'SecretKeySpec(b('
com\cbs\app\androiddata\retrofit\util\RetrofitUtil.java
65:                SecretKeySpec secretKeySpec = new SecretKeySpec(b("302a6a0d70a7e9b967f91d39fef3e387816e3095925ae4537bce96063311f9c5"), "AES");
~~~

Looks like you can generate the token with those. I wonder how long the pregenerated ones work. I was thinking it was only seven days. Do you know how long approximately?

**Comment by matthuisman** [comment]
You can see from the commit history when I added and it still works.

They have different tokens if I recall. Some are long lasting.

**Comment by 89z** [comment]
The below code seems to work. I just tried a request with it:

~~~py
import base64
import os
import pyaes
import time

aes_key = '302a6a0d70a7e9b967f91d39fef3e387816e3095925ae4537bce96063311f9c5'
tv_secret = '6c70b33080758409'

def at_token():
   payload = '{}|{}'.format(int(time.time())*1000, tv_secret)
   key = bytes.fromhex(aes_key)
   iv = os.urandom(16)
   encrypter = pyaes.Encrypter(pyaes.AESModeOfOperationCBC(key, iv))
   ciphertext = encrypter.feed(payload)
   ciphertext += encrypter.feed()
   ciphertext = b'\x00\x10' + iv + ciphertext
   return base64.b64encode(ciphertext).decode('utf8')
~~~

**Comment by 89z** [comment]
Looks like the code can be way simplified:

~~~py
import base64
import pyaes

aes_key = '302a6a0d70a7e9b967f91d39fef3e387816e3095925ae4537bce96063311f9c5'
tv_secret = '6c70b33080758409'

def at_token():
   payload = '|' + tv_secret
   key = bytes.fromhex(aes_key)
   iv = b'0123456789ABCDEF'
   encrypter = pyaes.Encrypter(pyaes.AESModeOfOperationCBC(key, iv))
   ciphertext = encrypter.feed(payload)
   ciphertext += encrypter.feed()
   ciphertext = b'\x00\x10' + iv + ciphertext
   return base64.b64encode(ciphertext)
~~~

Time doesnt have to be supplied at all. Also, since youre sending the IV in plain, you dont need to even use random, you can just hardcode it. So the token should last until they change the AES key or secret.

**Comment by matthuisman** [comment]
that key and secret are for USA or International?

**Comment by 89z** [comment]
I pulled those from `com.cbs.app`, they were the only ones I found in the APK.

**Comment by matthuisman** [comment]
com.cbs.ott is the USA AndroidTV app
com.cbs.app is the USA Mobile app
com.cbs.ca is international (tv and mobile)

**Comment by 89z** [comment]
Again, the APK doesnt contain the token, only the AppSecret and SecretKey. Its possible that the APK included token in older versions, but I doubt it. Someone probably captured the current tokens with MITM, or encrypted their own with a similar function to what I put.

**Comment by matthuisman** [comment]
maybe i just captured it then :) was a wee while ago.

I cant how they would expire though if the time doesnt matter?
If they changed the other 2x parameters - the code would need to be updated anyway.
Essentially what I have currently is the stored output of your script above

**Comment by 89z** [comment]
I dont think they expire. Initially I did, because the function has an optional time argument. But it seems that they just use the time argument, in combination with random, in order to disguise the fact that its basically a fixed token. If they disable old secrets, then they will be breaking the app for anyone who has updates disabled. So I suspect that the generated token should last quite long indeed.

**Comment by matthuisman** [comment]
ill add your code as a comment in the add-on so is there if need it in the future.
Thank you!

**Comment by 89z** [comment]
Not sure if you're interested, but I have noticed that the app secret seems to change with each version. Here are some:

~~~
0: "439ba2e3622c344a", // 12.0.28
1: "79b7e56e442e65ed", // 12.0.27
2: "f012987182d6f16c", // 12.0.26
3: "d0795c0dffebea73", // 8.1.28
4: "a75bd3a39bfcbc77", // 8.1.26
5: "c0966212aa651e8b", // 8.1.23
6: "ddca2f16bfa3d937", // 8.1.22
7: "817774cbafb2b797", // 8.1.20
8: "1705732089ff4d60", // 8.1.18
9: "add603b54be2fc3c", // 8.1.16
~~~

They all seem to work, even going past these to the oldest I could find.

**Comment by matthuisman** [comment]
very interesting! thanks again for the info :)
