### ISSUE TITLE
Use without Kodi

### ISSUE THREAD

**Issue by 89z** [matthuisman/slyguy.addons#138]
It is possible to use this outside of Kodi? I tried this:

~~~py
from resources.lib.plugin import plugin

item = plugin.play('eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU')
print(item)
~~~

but I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\slyguy.addons-master\slyguy.paramount.plus\play.py", line 2, in <module>
    from resources.lib.plugin import plugin
  File "D:\Desktop\slyguy.addons-master\slyguy.paramount.plus\resources\lib\plugin.py", line 7, in <module>
    from slyguy import plugin, gui, settings, userdata, signals, inputstream
ModuleNotFoundError: No module named 'slyguy'
~~~

**Comment by matthuisman** [comment]
Not really. Even if you did include the dependencies, it'll break at any Kodi related functions

Have a look at this:
https://github.com/matthuisman/kodi.proxy
It basically replaces the Kodi functions with terminal friendly equivalents.

**Comment by 89z** [comment]
https://github.com/matthuisman/kodi.proxy/issues/6

**Comment by 89z** [comment]
As a workaround, you can set proxy in Kodi settings. Then shut down Kodi, set this variable:

~~~
$env:REQUESTS_CA_BUNDLE = 'C:\Users\Steven\.mitmproxy\mitmproxy-ca.pem'
~~~

Then start MITM Proxy, then start Kodi.
