### ISSUE TITLE
[HBO Max] Portability feature doesn't work

### ISSUE THREAD

**Issue by samukas** [matthuisman/slyguy.addons#146]
Hi there! Similar to #116 , if an HBO Max account is created within a EU country where the service is officially available, that account can "travel" across other EU countries - even countries that don't have the service yet - and maintain the origin catalog. For example, an account created in Spain or The Netherlands works in Germany, even though Germany doesn't have the service.

Right now, it doesn't seem to be possible to login, either with email/password or tv signin. The Android app however, has a "log in" button even when accessed from a country/IP where the service is not (yet) officially available.

But even after using a VPN to sucessfully login, as soon as the VPN is turned off, it's no longer possible to navigate the different categories or start playback:

"HBO Max has detected your out of region. Check your IP is in correct region"

If you need more information, do let me know. Thanks in advance!

**Comment by matthuisman** [comment]
can you confirm there app / website works with roaming EU?

**Comment by samukas** [comment]
Cheers for the prompt answer!
I can confirm that both the Android app (mobile) and the website work with Roaming EU.

**Comment by matthuisman** [comment]
are you able to provide a temporary EU login to test with?
I only have a USA login

**Comment by samukas** [comment]
Sure, let me know where I should send it to ?

**Comment by matthuisman** [comment]
blog@matthuisman.nz

**Comment by samukas** [comment]
Thanks, sent

**Comment by matthuisman** [comment]
portability should now work in latest 0.8.9 version
