### ISSUE TITLE
[HBO MAX] No FullHD resolutions

### ISSUE THREAD

**Issue by Rohlik** [matthuisman/slyguy.addons#151]
Hey there 👋🏽 and thanks for this great Kodi plugin!
HBO Go swtiched to HBO Max in Czechia recently and I'm having problem with available resolutions on my Raspberry Pi 4 (LibreELEC 10 with Kodi 19).
The maximal resolution what plugin offers is just **960*544** 😢 . In the recent past, I was able to watch HBO Go with FullHD resolution on the same device without any issues.
I think that main cause for this is something with **_Widevine_** component.

**Comment by matthuisman** [comment]
Sorry, not possible as HBO max limits to these resolutions for non-vmp level 3 widevine devices
