### ISSUE TITLE
[10 Play] 'Short Films' Category/Section Missing

### ISSUE THREAD

**Issue by sliceanddice9** [matthuisman/slyguy.addons#152]
The 'Short Films' Category/Section from the 10 Play app is missing on the Kodi add-on. These 'Short Films' are windowboxed when played on my Smartphone. Sadly the default 10 Play app  itself has no zoom function, let alone aspect ratio controls, to correctly fit and size the image on the display.

**Comment by matthuisman** [comment]
why was this closed?

**Comment by sliceanddice9** [comment]
Hi Matt. I closed it because it seems as though that the 'Short Films' from the 10 Play default app are now available on your 10 Play Kodi add-on.

**Comment by matthuisman** [comment]
oh, i didnt make any changes. so i suspect they added that category to whatever categories my addon already requests :)
yah - that was easy fix. haha
