### ISSUE TITLE
[Foxtel GO] Generic Android (Fake L1) not playing

### ISSUE THREAD

**Issue by Bottlefrog** [matthuisman/slyguy.addons#162]
Hi Matt,

I have been getting this error on my Android X96 box since this morning. I have logged out and logged back in, restarted the box, uninstalled the app, reinstalled it, reset the app, and all to no avail. 

I am running 0.8.8 and it has been working perfectly for months and months.

I have confirmed using other devices on my network that I can log into and view shows from my Foxtel account without problems.

I read up here on the forums about similar issues with the HBO Max app, but nothing that I read seemed to help.

Do you have any suggestions?

I see a number of people are having the same issue today with the Foxtel Go addon here:
https://forums.whirlpool.net.au/archive/3wwnqx63-2

**Comment by band1959** [comment]
Having same problem here as well. Was all good last night but not working this morning

**Comment by matthuisman** [comment]
I'll try look into tonight and report back. Something has changed at foxtel

**Comment by matthuisman** [comment]
should be fixed now with v0.8.9

How to force update:
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by Bottlefrog** [comment]
Matt,

The playback is still blank and appears to be 457928:44:48 behind current time?

**Comment by matthuisman** [comment]
what is your device and what content are you playing

**Comment by Bottlefrog** [comment]
Hi Matt,

It's an X96 Android Box, trying to play Sky News on Foxtel Go. I have been using this addon for ages perfectly.

I have been trying to play Live TV and I have just tried older stuff, but while the app appears to be playing, there is no video or audio, and when I select to go full screen, it's black with that -45000 number on the bar.

**Comment by matthuisman** [comment]
oh, fake L1 android device...

**Comment by Bottlefrog** [comment]
I am not getting the JSON error any more which is great!, and I have tried a variety of quality settings including disabled and bypass, custom, best, lowest and ask. Still no images or audio. Thanks

**Comment by matthuisman** [comment]
try addons > services > slyguy common > advanced > widevine level > L3
then restart kodi and then try the addon.

if that works, then ill make some more changes

**Comment by Bottlefrog** [comment]
Sorry it's taken me so long to respond, but for some reason everything is running slowly, probably all the things it does at startup.
I set the Widevine to L3 and tried all the quality settings again and still the same result, appears to be playing, but no video or audio

**Comment by matthuisman** [comment]
try addons > inputstream > inputstream adaptive > configure > expert > try not to use secure decoder (or whatever its called)
then try foxtel

**Comment by Bottlefrog** [comment]
Ok so L3 AND try not to use secure decoder, again tried all qualities... still nothing. Worked soo well yesterday.  I still completely love your apps by the way. You do good work mate!

**Comment by matthuisman** [comment]
Between then and today foxtel removed the endpoint we were using for these
chinese android boxes. We now be out of luck... Might send you a few test
versions to try 2moro night

**Comment by Bottlefrog** [comment]
No worries Matt, thanks again. I will await further deliveries of hope and experimentation.

Best Regards

**Comment by band1959** [comment]
Thanks Matt all good here using firestick.

**Comment by conofam** [comment]
Thanks matt, looking good this morning!

**Comment by matthuisman** [comment]
Two test addons attached to try please

[plugin.video.foxtel.go-TEST1.zip](https://github.com/matthuisman/slyguy.addons/files/8377628/plugin.video.foxtel.go-TEST1.zip)
[plugin.video.foxtel.go-TEST2.zip](https://github.com/matthuisman/slyguy.addons/files/8377629/plugin.video.foxtel.go-TEST2.zip)

**Comment by Bottlefrog** [comment]
Hi Matt,

Thanks for these Test files.

I have tried both of these files.

Left the L3 setting, tried both forcing not to use secure decoder and not forcing settings.

Both had no JSON errors, but both still failed to play video or audio and certainly appeared to be trying.

The play/time position scrollbar for each stream still shows -457950:47:28/30:00 for the program I was trying to watch.

I hope that provides the diagnostic info you require?

Thanks again for all you do.

**Comment by Bottlefrog** [comment]
Also tried Widevine Level as Auto with and without forcing secure decoders in inputstream adaptive. Same result for what it's worth.

**Comment by matthuisman** [comment]
Not looking good for the generic android devices..

**Comment by ptaylor1608** [comment]
Ah well, we had a good run. Fingers crossed the old TV dies soon and i can get a proper Android one where the official app works.
Really appreciate all your work man.

**Comment by skomo83** [comment]
> Two test addons attached to try please
> 
> 
> 
> [plugin.video.foxtel.go-TEST1.zip](https://github.com/matthuisman/slyguy.addons/files/8377628/plugin.video.foxtel.go-TEST1.zip)
> 
> [plugin.video.foxtel.go-TEST2.zip](https://github.com/matthuisman/slyguy.addons/files/8377629/plugin.video.foxtel.go-TEST2.zip)
> 
> 

Would you recommend to try these for an x86 Linux mint install running kodi that has the exact same issue ??

**Comment by smkranz0506** [comment]
> Would you recommend to try these for an x86 Linux mint install running kodi that has the exact same issue ??

I am also seeing same issue (no playback, no sound) from Debian install and Kodi v19.3 and Foxtel 0.9.0 plugin.
Tried both TEST1 and TEST2 and i do not seem to get any luck.
What's interesting is that this occurs for Kodi on two boxes in my local network (one is behind the linux router and one is the actual router).
I also tried to log into watch.foxtel.com.au on my browser and when selecting a channel it reports error "PE6007".
I can try to provide a log from debian Kodi if you need it.

**Comment by smkranz0506** [comment]
Just to add to this, from within my home network, i was able to successfully stream from watch.foxtel.com.au website on a windows 10 PC with chrome without issues.  
As reported in my previous comment, using Chromium on Debian 11 (with user agent string set as Windows / Chrome) on different PC but in same home network does not work.
The kodi plugin is running on Debian machines and will not play.  Does this have to do with the way kodi and /or plugin  "advertises itself" to foxtel service?

**Comment by matthuisman** [comment]
No. It's widevine DRM issue

**Comment by skomo83** [comment]
When I set the Widevine Level to Auto or L3, I can view channel 621 Bloomberg, but its the only channel that works. 
Let me know if there is any thing I can do to try and help...

**Comment by Gordohat** [comment]
Hi Matt,

For me I think there is an issue now with the Widevine AUTO setting.  I get  constant buffering on a couple of channels eg channel 600, which is in 720p for me.  Not an issue it seems on the 576P Foxtel steaming channels though.

I tried setting manually to L3 and also L1, and both settings work much better without the constant buffering.

I am using an Odroid-N2 running CoreElec 19.4 Matrix and on 100/20 Mbps  Superloop NBN.

I am leaving it on L1 (Secure) setting for now.  Not sure if there is any pros and cons of L1 vs L3 from an end user point of view when running your Foxtel Go app?

**Comment by matthuisman** [comment]
I bet you've updated widevine to latest version via inputstream helper.
Latest widevine causes buffering. Disable inputstream helper then go to
add-ons > services > slyguy common > playback > reinstall widevine DRM >
select the latest listed. Install and reboot kodi

**Comment by Gordohat** [comment]
Yes correct.  I got prompted to do it from the Netflix app.  I always have the "should I or shouldn't I" thoughts when prompted with this.  I usually give it a few days in case early issues need to be sorted.
 I will reinstall Widevine as you mentioned.

**Comment by matthuisman** [comment]
Yes. Issue is that one is automated. I only push mine when needed / tested.

**Comment by Gordohat** [comment]
Thanks Matt, that is handy to know.
All working well again on AUTO setting with your tested version or Widevine.

**Comment by smkranz0506** [comment]
Hello Matt,
(also skomo83)

a few more tests from my side.
I have an older LE9.2.7 raspberry pi and foxtel works on that.  That uses widevine 4.10.2252.5.
I fiddled a bit more and my firefox on debian 11 desktop can stream foxtel from watch.foxtel.com.au if i use chrome 99 / windows 10 user agent string.  However, i think it doesn't provide the highest quality.  Firefox on the desktop is using widevine 4.10.2391.0.
Still not working for kodi on the same linux desktop (amd64).

I've removed the inputstream helper plugin and deleted the files.  I deleted the libwidevinecdm.so from .kodi/cdm and the foxtel plugin force installed the lib again (4.10.2391.0) but still no go with kodi.

I checked the libwidevinecdm.so from firefox and from your forced install and they appear to be exactly same binaries.

So where does this leave users of kodi on linux amd64 (i.e. std desktops)?
Are there anymore ideas?

**Comment by aljclarke** [comment]
Also now having playback issues. Using Android Nubia phone. Everything working fine until about a week ago and now nothing plays, just circle loading graphic. Tried cycling through L1, L3 options and toggling use secure codec on and off and still no luck. Also tried test 1 and 2 foxtel add ons.

Any help would be appreciated, and as always love your work Matt. Thanks in advance.

**Comment by matthuisman** [comment]
Yeh, I got Ubuntu working in windows wsl so could actually test and confirm issue and fix it yesterday:)

I'll close this issue now..enjoy
