### ISSUE TITLE
[ESPN] MLB.tv games - Could not find source for this content

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/slyguy.addons#165]
Hello - when selecting an MLB.tv game within the add-on, a "Could not find source for this content" error appears. Log attached
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/8375536/kodi.log)
.

**Comment by lionsnob** [comment]
@matthuisman I've been troubleshooting this a bit using kodi.proxy. When I pass the contentid instead of the eventid the content plays fine. In the json this is page -> buckets -> contents -> streams -> id.

**Comment by matthuisman** [comment]
just done a big [v0.2.8](https://github.com/matthuisman/slyguy.addons/commit/0d66c71c348d6d5ac7edb2c0fb6e8fbd99c5e14b) update. can you see if that fixes this issue?

it should now pass the content_id and fallback to using that if it cant find a stream via the event_id

**Comment by lionsnob** [comment]
Works!
