### ISSUE TITLE
[Disney+] All of the chapter markers get compressed at the end of the video

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/slyguy.addons#168]
Log attached.
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/8375586/kodi.log)

**Comment by matthuisman** [comment]
that is a kodi feature. all credits at end of disney+ are there own chapter.
nothing i can do my end

**Comment by matthuisman** [comment]
That's not a bug. Literally all those credits are each there own chapter as
Kodi thinks

**Comment by lionsnob** [comment]
Thanks Matt - shall I close the issue now?

**Comment by matthuisman** [comment]
Already is closed. GitHub is doing weird stuff. Adding my really old email comments to tickets that didn't originally go through
