### ISSUE TITLE
Download items

### ISSUE THREAD

**Issue by 89z** [matthuisman/slyguy.addons#170]
Hello, thank you for this great project. I used this add-on:

https://github.com/matthuisman/slyguy.addons/tree/master/slyguy.paramount.plus

it works great. However, can you download media with this? I am able to play videos using Kodi, but can they be saved to the computer. Sorry if this has been answered, I searched but didn't see this question addressed.

**Comment by matthuisman** [comment]
Not with my addon sorry. Pretty sure they use widevine DRM so I'd imagine it's not possible

**Comment by 89z** [comment]
When I installed your addon, it had me also install the Widevine DLL. I wonder if it would be possible, instead of using the DLL to decrypt at play speed, you could decrypt the video at download speed, and then capture and save the result somehow. Have you thought about this?

**Comment by matthuisman** [comment]
Not that easy. Widevine DRM is a major DRM. Your best looking elsewhere for
info on how to break it. I have no interest in doing so.

**Comment by 89z** [comment]
no worries. I solved the problem myself a while back. I wrote my own Paramount and Widevine packages that work well
