### ISSUE TITLE
Paramount Plus Incomplete list of Movie Documentaries

### ISSUE THREAD

**Issue by moosifur** [matthuisman/slyguy.addons#174]
Hello, I'm having an issue with Paramount Plus, where the list of documentary movies stops at three pages, which only includes titles ranging from "A" to partway through "I". The last title is "Incredible Flying Jet Packs". The final page (Page 3) has 49 results, with no "Next Page" option. My log file is located here:

https://paste.kodi.tv/wutetuwizu.kodi

I'm running WIndows 10, Kodi 19.3 and 0.4.6 of the Paramount add-on. I'm in the US region. Any ideas on why the list would be incomplete? I haven't noticed any issues with the other categories. Thanks very much!

**Comment by matthuisman** [comment]
sorry for the delay. This pagination issue has now been fixed in [v0.5.2](https://github.com/matthuisman/slyguy.addons/commit/f0b43960eafb33314b8cc2bd0e0d9289daf0243e)
