### ISSUE TITLE
Sky Go Unexpected Error

### ISSUE THREAD

**Issue by makapaka23** [matthuisman/slyguy.addons#175]
I am getting this error when I try login with username/password to Sky Go (0.2.3)

```
KeyError: 'location'
File "structures.ph", line 54, in __getitem__
return self._store[key.lower()...
File "api.py", line 189, in login
parsed = urlparse(resp....
File "plugin.py", line 87, in login
api.login(username, password) ...
```

I can't copy paste the whole thing so hopefully there is enough there to advise 
thanks

**Comment by matthuisman** [comment]
you are in NZ correct with a NZ ip address?

**Comment by makapaka23** [comment]
oh wait, I thought it was the UK version , no ? I was using UK ip

**Comment by makapaka23** [comment]
Damn, I just read the part where it says its NZ lol oops, my bad, you don't have Sky Go UK ?

**Comment by matthuisman** [comment]
nope. skygo uk not really possible

**Comment by makapaka23** [comment]
ok thanks for the quick reply
