### ISSUE TITLE
[HBO Max] Child's profile should not show restricted media

### ISSUE THREAD

**Issue by gsziklai** [matthuisman/slyguy.addons#177]
In original app, child profile has different navigation, and the unplayable items are not shown. 
The plugin does not have this distinction, and thus it is cumbersome to browse and find videos they can and should see. 
Furthermore there are posters for horror and other restricted movies shown that could be disturbing for a child.

- Filter out unplayable/restricted items from lists so that they won't show up
- Adhere to original app's (website's) menu structure for child profile

**Comment by matthuisman** [comment]
closing as HBO MAx wont be getting any new features due to deprecated for Max
