### ISSUE TITLE
Paramount+ demuxer error

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#178]
Hey, cannot play any content in P+ getting the log error
ERROR <general>: CVideoPlayer::OpenDemuxStream - Error creating demuxer

**Comment by matthuisman** [comment]
full debug log. thats a generic kodi player error = means nothing

**Comment by scottydulton** [comment]
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/8480779/kodi.log)

**Comment by matthuisman** [comment]
should be fixed now in 0.4.7

how to force update:
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html
