### ISSUE TITLE
ESPN stream lags every second.

### ISSUE THREAD

**Issue by Timbo303** [matthuisman/slyguy.addons#179]
Tried watching a mlb game with mobile data on the espn official app was garbage quality so I tried streaming it here on the kodi app and it lags every second whenever I try to play something with it turning black sometimes. Happens for any espn plus content not sure about espn itself. Also hulu doesn't seem to list this game on their app as i have the intergration with espn+ on hulu which is stupid making this fix necessary.

**Comment by matthuisman** [comment]
If it lags, turn down the quality...
