### ISSUE TITLE
[Disney+ / HBO Max] - Won't autoload the subtitles because Swedish use `sv` and not `sv-se`

### ISSUE THREAD

**Issue by Sopor** [matthuisman/slyguy.addons#182]
When watching `Disney+` and `HBO Max` it seems that they sometimes use `sv` (the correct one for Swedish subtitles) and sometimes `sv-se` (se is Northern Sami and that is wrong) (i think i have seen `swe` too, but it could be in another addon).

The problem is that i can't get it to autoload `sv-se` subtitles. I have to manually enable it every time even if i do a resume on the video.

I don't know why it sometimes will be `sv` and sometimes `sv-se`, but maybe you can fix it, so it will always be `sv` for Swedish subtitles and NOT `sv-se`, `se` or `swe`, so it autoload subtitles. Maybe you have a better solution?

I don't know if it is your addon that choose `sv-se` or if the addon gets it from the streaming service? If i open a movie in my web browser i can only see Swedish, no language codes.

**Comment by matthuisman** [comment]
Use the Disney+ addon setting > playback > default subtitle > sv

**Comment by Sopor** [comment]
I have tried that already, but it doesn't work. If the subtitle use sv-se it fails. I have even tried to add `sv,sv-se,se,swe` but it doesn't work either :(

I read somewhere that it was possible to use commas as separators.

**Comment by matthuisman** [comment]
Sv should match both. Makes sure kodis subtitle setting is set to original

**Comment by matthuisman** [comment]
Basically follow below but use sv

https://forum.kodi.tv/showthread.php?tid=358484&pid=3094474#pid3094474

**Comment by Sopor** [comment]
Can't use `Preferred subtitles languages - Original` must be set to Swedish because it will not be Swedish subtitles in other videos if i use `Original`.

**Comment by matthuisman** [comment]
@Sopor 
ok, try with latest slyguy common [v0.51.8](https://github.com/matthuisman/slyguy.addons/commit/b5a7a4f29efdb10e8e82feabc6facaf24dfe833b)

**Comment by Sopor** [comment]
It seems to work perfect, thanks!

**Comment by matthuisman** [comment]
Hmm, yes. That would be an issue. Problem is that my addon would mark
preferred subs as Default. And if you have that Kodi setting set to a
language, it won't fallback to default subs.

**Comment by matthuisman** [comment]
sv should match both. Make sure kodis preferred subtitle is set to original
