### ISSUE TITLE
[Hulu] issues with streaming with ads

### ISSUE THREAD

**Issue by joshuachris2001** [matthuisman/slyguy.addons#183]
hello, I am using an RPI3+ to connect to via composite video with help from retropie, from what I could tell the hulu plugin works just fine until an ad comes on and off. in summery it treats the video stream as it has ended or someone hit the stop button upon switching.

**Comment by matthuisman** [comment]
That's an issue with ffmpeg & inputstream adaptive not fully supporting x-discontinuity. Nothing I can do my end unfortunately.

**Comment by joshuachris2001** [comment]
Is this a similar issue of when some channels have absolutely no audio?
