### ISSUE TITLE
Stan login with email/password

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#184]
hey matt ive used your code to allow login to stan with email/password however its returning invalid credentials, activating via device code on stan website works fine, not a huge issue but thought i would bring it to you attention

**Comment by matthuisman** [comment]
ive had username/password disabled in the addon for about 8 months due to them requiring captcha. 
So maybe you need to update the add-on?
it shouldn't give you usernmae / password option
