### ISSUE TITLE
[HBO] Dolby Atmos stutters

### ISSUE THREAD

**Issue by mkaflowski** [matthuisman/slyguy.addons#185]
I have a problem with Dolby Atmos. When I use it it stutters. It get some very short mute fragments (and I see on AVR that there is no sound for a moment). When it happening the subtitles disappear for that moment too.
I have tested on Marantz and Denon AVRs and Nvidia Shield 2017 and Pro.
I can deliver video if that helps.

**Comment by matthuisman** [comment]
Nothing I can do my end sorry. You'll need to open an issue with Kodi or
inputstream adaptive

**Comment by mkaflowski** [comment]
Thank you for response. I will. Is it common problem or just me? I think Atmos works on Netflix.

**Comment by matejdro** [comment]
It appears to be the common problem. Also happens to me.

However, it only appears on HBO for me, Netflix (and local atmos files) do not have this issue.

**Comment by cralcubo** [comment]
Hi @matthuisman 
I have the same issue, here a brief description of my case:

**Add On used:**
HBO Max v0.9.9

**System setup:**
Hardware: Nvidia Shield Pro 2019
OS version: Android TV 11
Kodi version number: 19.3

**Issue:**
Inconsistent Dolby Atmos streams are presented for the same video.

Sometimes the stream information shown is:
* English - Atoms - DD+ - 16 channels
and other times
* English - Atoms - DD+ - 3 channels

Only when the number of channels is 16 the audio stutters.

Any idea why there is such inconsistency with the Atmos audio stream for the same video?

**Comment by matthuisman** [comment]
try kodi 20

**Comment by cralcubo** [comment]
Hey @matthuisman 
I have now Kodi 20.0 Alpha and the problem persists. I also checked that the version of InputStream Adaptive is 20.2.3

Why do you think the audio stream sometimes is 16 channels and other times 3?

As I mentioned before, the stuttering only happens when the audio stream is: Atoms - DD+ - 16 channels.

**Comment by matejdro** [comment]
It might not be limited to Atmos. Similar also happens with AC3 (not DD+) streams. And again, only on HBO Max.
