### ISSUE TITLE
After latest IPTV Merge, Pluto tv is showing 0 channels

### ISSUE THREAD

**Issue by SoreTissue** [matthuisman/slyguy.addons#19]
After updating to 0.18.1 IPTV Merge, Pluto Tv is showing 0 channels within IPTV Merge. 

If you go into the Pluto TV addon, all channels are working, but after running merge it shows in IPTV Merge/playlists/Pluto TV as 0 channels (it's showing as green). Same with EPG. Ran Merge multiple times. Even did a clean install of kodi with the only repo as slyguy and only pluto tv/IPTV Merge/simple client installed.

Issue is on both Windows 64bit and Android tv installation of Kodi.

**Comment by matthuisman** [comment]
https://www.matthuisman.nz/2020/10/pluto-tv-kodi-add-on.html
Scroll down to TV / EPG

**Comment by SoreTissue** [comment]
Thx for the fast reply. This fixed it. Thx for your awesome work
