### ISSUE TITLE
[plugin.program.iptv.merge] streamlink 4.0

### ISSUE THREAD

**Issue by richard74** [matthuisman/slyguy.addons#190]
Is it possible to plugin.program.iptv.merge add playlist links streamlink 4.0 to the plugin for kodi 19 example in this form http://127.0.0.1:8088/https://www.youtube.com/channel/UC9qcppdMvksoZ2wlzNwrB-g/live

**Comment by matthuisman** [comment]
If that's a path that Kodi can play, just manually add it to your playlist.

**Comment by matthuisman** [comment]
Just add a YouTube.url like that manually to your playlist. Don't use the
127.0.0.1 address though. Just the plugin:// YouTube path
