### ISSUE TITLE
Channels disappearing from the list after updating the add-on.

### ISSUE THREAD

**Issue by adityapv** [matthuisman/slyguy.addons#191]
Hi Matt,

Appreciate the work that you do.

I have recently updated slyguy add-on and I noticed that some of the channels from India group are disappearing. It started with 9XM, 9XJalwa and 9XJakaas and now recently added Discovery channels. Could you please look into the same?

**Comment by matthuisman** [comment]
Nothing that I'm doing. They are all automatically scrapes. Check the
official apps
