### ISSUE TITLE
Slyguy addons overwrite "NOSECUREDECODER" setting of InputStream Adaptive

### ISSUE THREAD

**Issue by MauriceW67** [matthuisman/slyguy.addons#192]
The InputStream Adaptive addon (current version 20.2.0) has an option in the Expert menu called "Try avoiding the use of secure decoder" that can be toggled on or off. The help text states that in case of a black screen during playback, this option should be enabled on devices that are Widevine L1 certified.

When I enable this option on my Nvidia Shield 2019 Pro, and then start the HBO Max addon, the setting is overwritten and set to disabled again.

I feel it should be left to the user to decide if this option needs to be enabled or disabled in his/her particular situation and not having it overwritten by an addon without warning.

**Comment by matthuisman** [comment]
FYI: on "real" L1 devices you want it disabled (default)
On "fake" L1 (lots of chinese android tv boxes) - you need it enabled else get black screen.

**Comment by MauriceW67** [comment]
Ok, thanks for that information.

**Comment by matthuisman** [comment]
i have just updated the code to only set that setting to True when on a L3 device.
So on a L1 device, you can set it how you like
