### ISSUE TITLE
[HBO Max] Show content as thumbnails with titles

### ISSUE THREAD

**Issue by adi2kx** [matthuisman/slyguy.addons#193]
Hey Matt, thank you for creating this add-on. It's great to have it after the HGo EU add-on was discontinued with the migration to Max. I would like to suggest porting over a feature that was present in the other add-on. Like myself, I know many others prefer using the Wall or InfoWall viewtype in Kodi as it makes navigation and spotting content a lot quicker and easier. Currently, when you're listing items of only one type, like movies or series, they are showing as vertical posters with no titles below. It cuts off the sides of the images only showing the middle part because they are downloaded as horizontal thumbnails and/or backgrounds. This makes it difficult to identify the content. But, if you have a folder that shows a mix of movies and series, like My List, then all the items are shown as horizontal thumbnails which matches the shape of images and shows their titles right below them. The feature could be found in the settings of the other add-on and was named "Use generic video media type in listings". From what I understood it was changing the content type of the listed items from movies and series to regular videos or files, which then was making Kodi list the items as thumbnails. As a side note, a thing I noticed in the thumbnail view of your add-on is that the images are zoomed in and all the margins are slightly cut off. You can observe this easier if the images have text in them. It would be much appreciated if you could port this feature over. Thank you.

**Comment by matthuisman** [comment]
there is an issue about this already:
https://github.com/matthuisman/slyguy.addons/issues/104

Basically I plan to make a "views" menu where you can tell the add-on which content to use for content.

For now, the "show_series_folders" setting in slyguy common I think will do what you want for tv shows / series

**Comment by matthuisman** [comment]
great, yeh that basically forces all content to be "video" type
