### ISSUE TITLE
Showmax issu3s

### ISSUE THREAD

**Issue by dvaai** [matthuisman/slyguy.addons#194]
Good day, Matt

Kindly note that Showmax addon search function does not work.

The showmax pops out an error message on page 17 and one can not view next page.

**Comment by matthuisman** [comment]
ive just tested search and it works fine.
You need to create a new search, and then click on it after it's created to run the search

**Comment by matthuisman** [comment]
also for page 17, I can only test upto page 11 in NZ as showmax has less content here.

Probably best you get me a full debug log showing both issues / errors.
https://kodi.wiki/view/Log_file/Easy

otherwise there is no more I can do

**Comment by matthuisman** [comment]
i managed to get a SA access and can navigate pass page 17 and also search works fine.
closing this issue
