### ISSUE TITLE
Paramount alternate MPD

### ISSUE THREAD

**Issue by 89z** [matthuisman/slyguy.addons#198]
This code:

https://github.com/matthuisman/slyguy.addons/blob/8d11443bb213c0ccfd6e42d7b8ca673f6677d655/slyguy.paramount.plus/resources/lib/api.py#L312-L315

Produces a URL like this:

<https://www.paramountplus.com/apps-api/v2.0/androidphone/video/cid/eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU.json?at=ABAAAAAAAAAAAAAAAAAAAAAAllAdZ6mDhF74gwOlMlndMKU5zcd9%2B2A8QGEmkmwlJjE%3D>

which returns this MPD:

<https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2021/08/31/1940767811923/993595_cenc_precon_dash/stream.mpd>

However if you use the web client, you find another MPD is available:

<https://vod-gcs-cedexis.cbsaavideo.com/intl_vms/2021/08/31/1940767811923/993595_cenc_dash/stream.mpd>

I think the web client MPD is better, because it uses a single period for the whole video, rather than four periods from the Android client. Is it possible to get the "good" MPD with the Android client?

**Comment by 89z** [comment]
This seems to work:

**Comment by 89z** [comment]
These seem to work:

https://can.cbs.com/thunder/player/videoPlayerService.php?partner=cbs&contentId=eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU

http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/eyT_RYkqNuH_6ZYrepLtxkiPO1HA7dIU?assetTypes=DASH_CENC&formats=MPEG-DASH

**Comment by matthuisman** [comment]
should now be fixed in 0.4.8
