### ISSUE TITLE
Not automatically displaying subtitles on next video after Enabling & Setting as Default

### ISSUE THREAD

**Issue by yrp888** [matthuisman/slyguy.addons#199]
My old Leia boxes were wiped for Matrix over the past week and the SlyGuy Addons installed.

One thing we've noticed is that the Player won't automatically show subtitles on 7plus, 9Now, 10 play when a show starts (these are the only ones we use).

Have to go into Player Settings, Subtitles and turn on Enable Subtitles, then turn on Set as default every time, the Enable subtitles option keeps appearing as Off after starting a new video.

Using iView from AussieAddons works fine, the Player subtitle settings are correct and the subtitles display automatically on any show that has them.

I thought it was my Matrix loads (LibreElec, Intel NUC), spent ages looking through all the settings. Tested fresh Kodi Matrix load on a Window 10 notebook, same. Tested Kodi Leia on a Windows 7 notebook, same.

7+ example - Categories/Premium Dramas/Battle Creek

Seems that the settings for Subtitles are not being read ... ?

**Comment by matthuisman** [comment]
Ok, with latest versions of the add-ons, go into there Settings > Playback > Default Subtitle and set it to **en**
Do that for each add-on and it will auto enable english subs when available.
Couldnt find anything on 10play with subs, but confirmed the other two works and 10 should work

**Comment by yrp888** [comment]
Thanks Matt, will update and test.

**Comment by yrp888** [comment]
Yep tested AOK as you say on 7+ & 9Now, I also had problems finding something on 10play with subs.

Many thanks for sorting this out, greatly appreciated
