### ISSUE TITLE
Udemy Plugin Failed to Play

### ISSUE THREAD

**Issue by evaspaceman** [matthuisman/slyguy.addons#2]
When trying to watch a course video via the Kodi Udemy plugin, the following error is received.  The log file is attached.

"One or more items failed to play.  Check the log for more information about this message."

Udemy Plugin version 0.9.1.  
Kodi versions tested: Latest Leia 9.2.6 & the multiple LiebreELEC Matrix nightly builds (latest tested 4/30/2020).
System: Raspberry Pi 4

[01_KODI.log](https://github.com/matthuisman/slyguy.addons/files/6405585/01_KODI.log)

**Comment by matthuisman** [comment]
Hmm. Is this on all content?
Can you enable debug logging and get me a new log please

**Comment by matthuisman** [comment]
@evaspaceman
bump

**Comment by evaspaceman** [comment]
I will check other content and have a log uploaded on about an hour.

**Comment by evaspaceman** [comment]
I tried to launch content from 4 courses with mixed results.  The plugin seems to play some content fine, but won't play other content.  Here is the outcome:

- 1st course: 1st lesson tried played normally.  No additional lessons attempted.
- 2nd course: 3 lessons tried and all 3 failed to play.  Message reported -- "One or more items failed to play. Check the log for more information about this message."
- 3rd course: 2 lessons tried and both failed to play.  Same failure message reported.
- 4th course:  3 lessons tried, the 1st & 3rd played normally and the 2nd lesson failed to play.  Same failure message reported.

Attached is the log file associated with these successes and failures.
[01_KODI.log](https://github.com/matthuisman/slyguy.addons/files/6424370/01_KODI.log)

**Comment by matthuisman** [comment]
ive confirmed by loading up Raspberry Pi OS on a Pi4 and trying the udemy website.
It errors on the same videos that now need widevine.

So, it looks like VMP (verified media path) isn't working on Windows or Linux ARM.
I have updated the code so you get a warning now.

Nothing can be done unless Udemy allows widevine requests from non-vmp.

They do work on Android Kodi though.

**Comment by lundeen-bryan** [comment]
I also have been having this problem sporatically and I'd like to see if I can talk to someone at Udemy to see if they will allow "widevine requests." So do I ask them to just allow widevine requests or is there a certain plugin or some specific programming verbage that I need to explain to them?

**Comment by matthuisman** [comment]
They need to turn off VMP (verified media path) enforcement.

**Comment by lundeen-bryan** [comment]
Thanks Matt, I love your addon and hope I can convince them to turn off VMP hope I can convince them.
