### ISSUE TITLE
Samsung TV Plus - IPTV Merge unable to generate EPG

### ISSUE THREAD

**Issue by betatester3016** [matthuisman/slyguy.addons#20]
Hi Matt,

Great work on the STV+ addon. 

Only one thing I noticed: IPTV Merge appears to be unable to generate an EPG for STV+

Here some screenshots and a [log](http://ix.io/3rPH). 

![screenshot00001](https://user-images.githubusercontent.com/49594656/124357379-c8072200-dbe0-11eb-8e83-078eb8d07d14.png)
![screenshot00002](https://user-images.githubusercontent.com/49594656/124357380-c8072200-dbe0-11eb-8f78-dd45f2411250.png)
![screenshot00003](https://user-images.githubusercontent.com/49594656/124357381-c89fb880-dbe0-11eb-9a0e-a8d3b03e947b.png)

**Comment by matthuisman** [comment]
Please read the Tv / EpG section below
https://www.matthuisman.nz/2021/06/samsung-tv-plus-kodi-add-on.html

**Comment by betatester3016** [comment]
Thank you.

**Comment by matthuisman** [comment]
Or you can hide channels in IPTV Merge. A bit more reliable than via Kodi tv manager
