### ISSUE TITLE
Request - Please add support for Veely.tv IPTV Channels

### ISSUE THREAD

**Issue by kevwag** [matthuisman/slyguy.addons#200]
### Feature Request
Hi Matt, could you possibly make an IPTV addon for the six channels provided by [Veely.tv](https://veely.tv) please?
I recently requested veely be added to the [Catch-up-TV-and-More](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore) addon and although they did oblige, they added it to their "websites" section of the addon, whereas other similar platforms (such as UKTV Play) are split across the addon's two primary sections - "Catch-up" for the on-demand content and "Live TV" for live channels. The channels in the "Live TV" section are also available for integration into IPTV Manager / IPTV Merge but live channels in the "Websites" section are not. The veely website has an EPG TV guide so that data is readily available. 
I'm not sure why they chose to add it as a website and not enable the integration side. It was probably just easier that way added to the fact that the addon's EPG data hasn't been working properly for about a year anyway.

I've pasted the original feature request I submitted to _Catch-up-TV-and-More_ below, as it has all the relevant info & URLs. Obviously the on-demand part has already been done (although I can't help feeling that you would have made a better job of it), so it's just the six IPTV channels and EPG that matter.

### Content description
[Veely](https://veely.tv) is the online platform of Little Dot Studios Ltd
It includes 6 Live [IPTV channels](https://veely.tv/live/) with [EPG guide](https://veely.tv/tvguide):

- [Real Stories](https://veely.tv/live/realstories)
- [Timeline](https://veely.tv/live/timeline)
- [Wonder](https://veely.tv/live/wonder)
- [Real Crime](https://veely.tv/live/realcrime)
- [Real Wild](https://veely.tv/live/realwild)
- [Real Life](https://veely.tv/live/reallife)

It also has [On-Demand](https://veely.tv/explore/6165) content from 10 of their channel brands:

- [Real Stories](https://veely.tv/explore/6912)
- [Timeline](https://veely.tv/explore/6913)
- [Wonder](https://veely.tv/explore/6914)
- [Real Crime](https://veely.tv/explore/9600)
- [Real Wild](https://veely.tv/explore/9601)
- [Real Life](https://veely.tv/explore/7316)
- [Real Drama](https://veely.tv/explore/11547)
- [Real Royalty](https://veely.tv/explore/14102)
- [Spark](https://veely.tv/explore/11692)
- [Don't Tell The Bride](https://veely.tv/explore/9455)

* Name: Veely
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: 6x TV Channels and 10 On-Demand services
* Website URL: [https://veely.tv](https://veely.tv)
* Content language/country: English / Multiple cCountries

### Content access

- [x] All Veely content is free and does not require an account.

### More information

Veely is available on the [Veely website](https://veely.tv) and on the Veely apps for Android and IOS.

**Comment by matthuisman** [comment]
Sorry, I won't be doing this service.
 Best to ask in addon requests section in Kodi website or tackle it yourself :)
