### ISSUE TITLE
No audio if merged with other PVR

### ISSUE THREAD

**Issue by irontes** [matthuisman/slyguy.addons#201]
Me and my friends have 2 problems with your addons and hope you can help us in order to resolve them, I have installed IPTV merged with Samsung addon and Pluto Addon from your repo.
The first problem happen often is when while watch a Pluto channel in PVR and the advertises happen the video freeze on  advertises and I have to change the channel and then return to it in order to let it work again (Could be a inputstream problems?).
The second problem is that when I merge Pluto Playlist or Samsung Playlist or both and I have also Zattoo Pvr addon installed when I switch from a samsung channel or from a pluto channel into a zattoo PVR channel I lose the audio. In order to let it work I have to disable the Inputstream in the Pluto addon and/or in Samsung addon.
I hope you can help me in order to solve this annoying problem.

**Comment by matthuisman** [comment]
I can't help with either of those sorry. The ads issue is an inputstream
addon issue. The other issue I'm not sure about sorry. Maybe ask Kodi
forums?
