### ISSUE TITLE
[SkySportNow] Timeshift not displayed correctly when watching live from EPG

### ISSUE THREAD

**Issue by kontell** [matthuisman/slyguy.addons#208]
When playing a livestream directly from the SkySportNow addon, timeshift is correctly displayed on the the OSD. As in, when you skip back/ forwards it correctly shows your position within the 2 hours of available timeshift.

When playing from the EPG, timeshifting works but isn't shown correctly on the OSD if you skip backwards (it shows the progress as if watching live).

It is shown correctly if the stream is paused and a timeshift is allowed to be built up.

**Comment by matthuisman** [comment]
That is outside of my control unfortunately. Possibly open an issue with Kodi. Supply screenshots etc
