### ISSUE TITLE
beIN Connect is not working

### ISSUE THREAD

**Issue by kelnaqib86** [matthuisman/slyguy.addons#209]
Hello, 

I have beIN Connect installed on Kodi and when trying to open the add-on to watch it doesn't work and I got the following error
![IMG_20220605_213152](https://user-images.githubusercontent.com/106931043/172069104-fe222fb2-e220-4935-b11c-88ebfa524d83.jpg)
![IMG_20220605_214205](https://user-images.githubusercontent.com/106931043/172069119-1dcf4bad-03d3-4cef-a461-2970ce399741.jpg)

I ever uninstalled the add-on and reinstall it , but no luck at all

**Comment by matthuisman** [comment]
Please provide full debug log and also what country you are in

**Comment by matthuisman** [comment]
fixed now with [v0.2.3](https://github.com/matthuisman/slyguy.addons/commit/329b3f53e1efb894a726af1a8350c3f9bad507cd)
