### ISSUE TITLE
Samsung TV Plus

### ISSUE THREAD

**Issue by AntiBigmac** [matthuisman/slyguy.addons#21]
First of all, thank you very much for the new add-on for the Samsung TV Plus. 

Since I have installed at my Shield TV Pro 2019 and Apple TV 4K 2021, both devices has, some channels says "playback failed" "One or more items failed to play.  Check the log for the more information about this message."

Any idea?  Thanks. :)

**Comment by AntiBigmac** [comment]
Self solution. Disable "Use Inputstream HLS for Live Streams" then it will be all good.

**Comment by matthuisman** [comment]
Can you advise a troublesome channel?

**Comment by AntiBigmac** [comment]
> Can you advise a troublesome channel?

Korea -> TV Series #555

**Comment by matthuisman** [comment]
found the issue - there was some weird characters at the end of the url.
Fixed now :)

**Comment by AntiBigmac** [comment]
> found the issue - there was some weird characters at the end of the url.
> 
> Fixed now :)

Thank you so much. It is very appricaited from us, who is Korean.
