### ISSUE TITLE
STAN - add support for 4K video

### ISSUE THREAD

**Issue by chad-coutman** [matthuisman/slyguy.addons#210]
Premium Subscribers can access 4K UHD streams with Stan.
https://help.stan.com.au/hc/en-us/articles/115005618227-4K-Ultra-HD-Streaming-on-Stan

It would be great if your Kodi Add On supported this.

**Comment by matthuisman** [comment]
it already supports 4k. You need a L1 android device (eg. nvidia shield) and then enable 4k in the addon settings
