### ISSUE TITLE
[Paramount+] Error viewing some soccer content

### ISSUE THREAD

**Issue by dpetersOZ** [matthuisman/slyguy.addons#212]
I'm getting an error dialog come up when trying to play recent Soccer content i.e. Australian International - Socceroos or AFC U23 Asian Cup:

> **Paramount+ - Error
> None of the available releases match the specified AssetType,
> ProtectionScheme, and/or Format preferences**

Older soccer content in the same category plays OK, and some random Movies and Shows I tried play OK too.

The troublesome soccer videos play OK via https://paramountplus.com/au/ in a web browser, so I can only assume that these are encoded differently or protected differently, etc.

I've tried this under Matrix 19.4 on both Windows 7 and LibreElec RaspberryPi with the same issue.

**Comment by dpetersOZ** [comment]
Here's the debug log file: https://paste.kodi.tv/egemedulok.kodi

**Comment by matthuisman** [comment]
fixed now in [v0.5.1](https://github.com/matthuisman/slyguy.addons/commit/3f1073158dce01c731363253a7f46306dd423de7)
