### ISSUE TITLE
no working subtitles on Disney+ & Paramount+ & Netflix

### ISSUE THREAD

**Issue by jjplano** [matthuisman/slyguy.addons#214]
hi! great work!

but there's no way to use subtitles on those add-ons. also, if the Netflix one is also yours, there they work but the first and second line change places and get on different positions of the screen.

please make an addon for Star+, in Latin America force us to use that garbage to view Fox content. it's exactly the same as the Disney+ app, but you have to log in with its own credentials. really annoying...

keep up the good work!

**Comment by matthuisman** [comment]
I have no idea what your saying sorry. Closing this issue. Create new issue for specific problem and provide logs
