### ISSUE TITLE
subtitles malfunction on Paramount+ addon

### ISSUE THREAD

**Issue by jjplano** [matthuisman/slyguy.addons#215]
I'm using Kodi 18.9 on a raspberry pi 3 with LibreELEC 9.2.8

when I use the subtitles that comes with the Paramount+ content (specifically Spanish, there's no English available), they look like in the pictures:

![IMG_20220611_231818551](https://user-images.githubusercontent.com/59522625/173211705-2140d58b-8e54-4a1b-b4c9-4b1932fa7575.jpg)
![IMG_20220611_231823334](https://user-images.githubusercontent.com/59522625/173211709-decb23e0-6ba1-4e0f-9154-b5a77e38bb0c.jpg)

I use the HBOMax addon and there they work perfectly fine. same if I a download external subtitles from a service.

please let me know if you need anything and how to get it, before marking the issue as resolved. thanks.

**Comment by matthuisman** [comment]
I can't help with Kodi 18.9
Try Kodi 19.4 for a start

**Comment by jjplano** [comment]
yeap, I've upgraded and it's no longer an issue, thanks

but now I can't play x265 files, lol

anyways, thanks again!
