### ISSUE TITLE
Star+ addon (same as Disney+)

### ISSUE THREAD

**Issue by jjplano** [matthuisman/slyguy.addons#216]
hi! I hope it's ok to put this here

in Latin America, because of sports broadcasting rights or something like that, we have two separate entities: Disney+ and Star+ (Fox content, basically)

so it's pain having two identical apps, one for each service. and on Kodi, there's no Star+ app of course

I wanted to ask if it would be possible for you to develope that addon, as the system (and API and the rest, I assume) is identical to the Disney+ one

I could help with login info I think

let me know

thanks!

**Comment by matthuisman** [comment]
Addon requests are best to go in Kodi forums
There is also a request thread there
https://forum.kodi.tv/showthread.php?tid=364610
