### ISSUE TITLE
IPTV Merge

### ISSUE THREAD

**Issue by AntiBigmac** [matthuisman/slyguy.addons#22]
1. When try to add file in playlist, the system hault until hit the back button on the remote. 

2. Can't to make to work with the network drive(Samba) for the output(m3u8 & epg files) path. The output path could make to the network drive but there would be error to create actual files. The error comes when try to Run Merge.

It could be very good to use network drive as source, so could have same channel lists for the multiple devices in house. :)

Thanks.

**Comment by matthuisman** [comment]
1 - I don't understand...
2 - add the network path in Kodi File manager, you should then be able to browse to it via IPTV Merge

**Comment by AntiBigmac** [comment]
1. When try to add file with "Add Playlist", system response nothing until I cancel with the remote of my TV Box.

2. I did add my smb drive with Kodi File Manager.  After I did make my smb directory as output directory get error - 

"IPTV Merge (0.18.1)
FileNotFoundError: [Errno 2] No such file or directory: 'smb://192.168.xxx.xxx/Kodi/M3u_EPG/playlist.m3u8

File "plug.py", line 553, in _setup
*******

File "plug.py", line 65 in decorated_function
******

File "router.py", line 113, in dispatch function(**params)
*******

- I even did copy "playlist.m3u8" into that path, but still get same error".

**Comment by matthuisman** [comment]
will need full debug log for the first issue

**Comment by AntiBigmac** [comment]
Here is log. 

https://paste.kodi.tv/emebibanag

**Comment by matthuisman** [comment]
you'll need to talk to the skin dev about #1
i suspect they haven't added support for DialogSelect.xml
or there is a bug in their skin.

ill get #2 fixed

**Comment by AntiBigmac** [comment]
> you'll need to talk to the skin dev about #1
> 
> i suspect they haven't added support for DialogSelect.xml
> 
> or there is a bug in their skin.
> 
> 
> 
> ill get #2 fixed

Always, I am very appriciated.

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/commit/77b742195251fc44b46d9a5d975ef36283e0a7c2 should now allow remote paths to be used as output dir

**Comment by AntiBigmac** [comment]
Thanks. 👍👍
