### ISSUE TITLE
[ESPN] certain streams are throwing what appears to be a JSON error and not playing

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/slyguy.addons#227]
Log attached.
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/9033357/kodi.log)

**Comment by lionsnob** [comment]
Screenshot below.
![screen](https://user-images.githubusercontent.com/54520364/177010010-efc707de-adf1-418f-817b-a332a1f67b09.jpg)

**Comment by matthuisman** [comment]
Hmmm. Do the same streams work on ESPN website or app?

**Comment by matthuisman** [comment]
ok, try  v0.3.0 just released. you will need a MLB entitlement obviously

**Comment by lionsnob** [comment]
The next baseball game on ESPN+ is at 4:10pm local time about 8 hours from now. Will test then.

Appreciate you fixing this.

Thanks! Steve

**Comment by lionsnob** [comment]
Confirmed the remaining "issues" are entitlement related (so not really issues), so I think this can be closed.

**Comment by lionsnob** [comment]
There’s a Cubs-Brewers game that isn’t working right now but it’s not showing in the app as a current game. So I’m not sure if it’s really being broadcast.




The other game is working though. I can get a log later.

Thanks! Steve

**Comment by matthuisman** [comment]
i cant see any Cubs-Brewers game showing up in the addon for me

**Comment by lionsnob** [comment]
Hello Matt - this is really old and I believe it's already fixed.
