### ISSUE TITLE
Disney+ and Star+ addon language settings

### ISSUE THREAD

**Issue by victormm21** [matthuisman/slyguy.addons#230]
It happens that, I am Latin American and when I play any movie or series, it is played by default in English DD+ and well, I practically have to change the language every time I play something, I even select the option "set as default for all media" but, If you go to the next episode again it's in English... Then I realized that in the addon settings you can write what audio to use by default, if I put "eng" it uses English, so I guessed that if I put "es" I would use Spanish and it happens that if you choose Spanish, but the Spanish of Spain, not the Latin Spanish... And then I don't know what diminutive to use so that it uses the Latin Spanish by default instead of the one from Spain...
![Captura de pantalla (16)](https://user-images.githubusercontent.com/108901291/177880232-af3414a0-d07e-4719-bb2f-4b6d30ccd6f1.png)
![Captura de pantalla (17)](https://user-images.githubusercontent.com/108901291/177880243-89750a89-b748-4371-8a41-b39a5654b1f7.png)
![Captura de pantalla (18)](https://user-images.githubusercontent.com/108901291/177880248-2385fda0-55f4-4609-abac-91641457b608.png)

**Comment by matthuisman** [comment]
Try **es-419**

**Comment by victormm21** [comment]
@matthuisman Thank you very much!!!, if it works correctly when typing "es-419" :)

**Comment by krisu5** [comment]
> Try default audio: **es-419**

Is there list for these values?

**Comment by matthuisman** [comment]
https://datatracker.ietf.org/doc/html/rfc5646
