### ISSUE TITLE
HBO MAX not update the "continue watching"

### ISSUE THREAD

**Issue by victormm21** [matthuisman/slyguy.addons#231]
HBO MAX does not update what I see, if I finish a chapter and return to the menu to the "continue watching" section, it simply does not change, it continues that same chapter, it only changes if I see something from the browser or on the mobile but from kodi it does not change any :(

**Comment by matthuisman** [comment]
So Kodi isnt sending up your position to HBO basically? If can retrieve it
but not send it?

**Comment by victormm21** [comment]
@matthuisman I uninstalled and reinstalled the addon and now it's ok, I know I shouldn't ask about another platform but in Paramount there is no option to activate "continue watching"

**Comment by matthuisman** [comment]
Correct. There is an open issue about adding supporting for that. No eta

**Comment by victormm21** [comment]
@matthuisman Hmm I understand, whatever your addons are of great help to me, hopefully in the future that option will be available but for the moment the rest of the addons are great, thanks.
