### ISSUE TITLE
Foxtel Go: VOD not working

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#233]
"My log file [https://paste.kodi.tv/rehekuwaju.kodi](https://paste.kodi.tv/rehekuwaju.kodi) is simply me starting Kodi going to the Foxtel Go addon and trying to play a stream and then exit."

                                                   resources.lib.api.APIError: Failed to get video asset.
                                                   Server Message: Error retrieving media information. Error Code: 500

**Comment by girkers** [comment]
This is only for On-Demand, Live TV is still working as normal

**Comment by matthuisman** [comment]
should be now fixed in [v0.9.2](https://github.com/matthuisman/slyguy.addons/commit/2444a3dab4b0c47ba45d27bbebb5298ac0698646)

**Comment by matthuisman** [comment]
actually, vod seems to be fine. closing this again
