### ISSUE TITLE
Bein connect mena

### ISSUE THREAD

**Issue by adelsolange** [matthuisman/slyguy.addons#234]
Hello friend,
There is an error from last official update Bein connect.
Can you fix it please
Thank you so much
![PXL_20220711_144953986](https://user-images.githubusercontent.com/14030898/178293249-fff84fad-1cf8-4781-b799-a2a62039d533.jpg)

**Comment by matthuisman** [comment]
i have just tested and login working fine for me.
i suspect your vpn is being blocked or bad login credentials

**Comment by matthuisman** [comment]
user was using a Satellite provider login.
[v0.2.4](https://github.com/matthuisman/slyguy.addons/commit/a35c1c24c8d81732055df5c013f82ac26639a278) of the addon added support for this
