### ISSUE TITLE
Foxtel GO

### ISSUE THREAD

**Issue by stevieland58** [matthuisman/slyguy.addons#238]
Hello, there seems to be an issue with playback via Foxtel GO, when you play any channel it just hangs there with the timer all scrambled... 
I think its something to do with older devices as works fine on my Android TV but not on my Android Box.
The issue started in the last few days.
Any help would be appreciated!
🙏🏼

**Comment by matthuisman** [comment]
should be fixed now with [v0.9.3](https://github.com/matthuisman/slyguy.addons/commit/41671fbf65c6b10fe106a2caa1944c4599a85cdd).

**Comment by stevieland58** [comment]
Thanks! I'll buy you a coffee...

Just wanted to add that Live Channels are working now but VOD's are not.
Tried out some random ones and the video seems to freeze up and audio plays then drops out... there's no error log.

**Comment by matthuisman** [comment]
oh crap. so we are back to the original issue that was fixed with the changes that break better quality. it will need some more investigation

**Comment by stevieland58** [comment]
Ok, enjoy a coffee!

**Comment by matthuisman** [comment]
actually, vod is working fine for me. maybe you just need to reduce the quality a bit?

**Comment by stevieland58** [comment]
Hey mate, on my new Sony TV it all works great, but on my TV box i have and have set up for all cousins and friends, settings are set at custom 8 which generally plays back at high end 720p, and vod was working at those settings last week but not now...
Will try it at custom 7 tonight and let you know.

I remember you used to have a tick option for older devices when this problem occurred last a while back, is that option no longer plausible?
Also, its only that way with Foxtel, Kayo vod playback is fine at any resolution if that helps.

**Comment by stevieland58** [comment]
Hey mate,

I tried it at lower resolutions and the VOD's were playing fine pretty much from 720p down.
Is there a way to implement resolution settings in Foxtel GO to maximise playback to 720p? I use your custom playback settings but even if I lower it to say custom 5 it will still play things at 1080p resolution as the bandwidth for some 1080p shows are 4.5 mbit/s and if I go that low I'll then lose quality on shows at 720p which already work fine at a higher bandwidth.

I tried using kodi imputstream settings max playback at 720p but that made no difference as it played 1080p shows after a restart.

Thanks for your help also! 🙏🏼

**Comment by matthuisman** [comment]
Can you please provide a debug log

**Comment by stevieland58** [comment]
Sure mate, 

I generated a new log and replicated the issues straight away so you'll be able to see what's going on as soon as you open it.

I played first VOD at best quality 1080p, then second best at 1080p, - where they both failed, then at next best 720p where it played fine.

**Comment by stevieland58** [comment]
Says the log passes the character max when pasting it, is there any other way I can share it to you?

**Comment by stevieland58** [comment]
Let me know if this works.

**Comment by stevieland58** [comment]
Sorry mate, was using the app and it wouldn’t let me upload the log, using desktop now so here it is.

[kodi.zip](https://github.com/matthuisman/slyguy.addons/files/9168062/kodi.zip)

**Comment by stevieland58** [comment]
Hey mate, any luck re the log?

**Comment by stevieland58** [comment]
Thank you 🙏🏼

**Comment by matthuisman** [comment]
? Fixed?

**Comment by stevieland58** [comment]
> ? Fixed?

Apologies mate, I replied to the wrong thread.

Same issue with 1080p playback still, sent the log in previous message so hopefully you can tell me the errors when you have time.

Cheers!
