### ISSUE TITLE
HBO Max addon stopped working

### ISSUE THREAD

**Issue by SimonaSerbu** [matthuisman/slyguy.addons#239]
Hi! I’m having an issue with the HBO Max addon, it just stopped loading videos. As soon as I hit play, it gets stucked on the loading screen and nothing else happens. I’ve tried reinstalling, but it just doesn’t play content anymore… Any idea why? Thaaank you!!!

**Comment by matthuisman** [comment]
Full debug log please. No other reports so suspect something in your setup. What country are you in? No VPN or dns service involved?

**Comment by SimonaSerbu** [comment]
I don’t how to send the debug log :( No DNS or VPNs. And it worked perfectly fine until now… I’m not sure what could’ve changed to stopped working…

**Comment by matthuisman** [comment]
What device are you using?

**Comment by SimonaSerbu** [comment]
I’m using Philips Android TV (https://www.p4c.philips.com/cgi-bin/cpindex.pl?scy=IT&slg=EN&ctn=55PFT6550/12)

**Comment by matthuisman** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by matthuisman** [comment]
closing due to no other reports or log provided
