### ISSUE TITLE
IPTV AU - Channel Seven Playback Error

### ISSUE THREAD

**Issue by PJPMax** [matthuisman/slyguy.addons#240]
When I select Seven from the EPG "Playback Error" is displayed then AusBiz (the next channel in the EPG) is played.
I can however open the Seven live channel in the 7Plus addon and it opens fine. 
7Two, 7Flix and 7Mate behave the same way.

This behavior is consistent on both of my Kodi setups (all SlyGuy addons up to date):
1. RPi4/LE 10.0.2/Kodi 19.4
2. Chromecast Google TV/Kodi 19.3

No VPN enabled in either setup.

This is a log of selecting Seven from the EPG after reboot: [https://paste.kodi.tv/ulakiwucer](https://paste.kodi.tv/ulakiwucer)

**Comment by matthuisman** [comment]
I'm aware the issue, thank you for creating a GitHub issue to remind me.
Should get it fixed tomorrow

**Comment by PJPMax** [comment]
All good - using the 7Plus addon is a viable workaround so not urgent.

**Comment by matthuisman** [comment]
fixed :)

**Comment by PJPMax** [comment]
Confirmed - fixed on both of my systems.
Thanks Matt.
