### ISSUE TITLE
Widget loding...

### ISSUE THREAD

**Issue by Klops83** [matthuisman/slyguy.addons#241]
So I don't know if this is a bug or not but when I create a widget from Disney+ the content is never updated.  I then have to redo the widget to get new content.  Is this normal or what could be the reason?

Please help

**Comment by Klops83** [comment]
Or is it a problem of the skin?

**Comment by Klops83** [comment]
I've also tried autowidget, but the content still doesn't change

**Comment by matthuisman** [comment]
Not sure sorry. Best to ask the skin guys. Ml
