### ISSUE TITLE
Stan Sport - missing categories

### ISSUE THREAD

**Issue by TomHarrop** [matthuisman/slyguy.addons#242]
Hi Matt,

Love the addons - thanks  for your work on them.

The Stan addon doesn't show some categories under Sport, and this means you can't get to the videos via Kodi.

The general structure on the Stan **website** is Sport / Football / [Competition] / [Category]

The Competitions are:

- UEFA Champions League
- UEFA Europa League
- UEFA Europa Conference League
- UEFA Super Cup

The Categories are:

- Live & Upcoming
- Replays & Extras
- Minis
- Highlights
- Classic Minis
- Rapid Recaps

In the addon I just see an assortment of Categories, but not all of them. For example, none of the Mini categories show up. This means you can't watch those videos...

Is there any way to add the other categories? Or is this because Stan doesn't expose those categories to the API?

Cheers!

**Comment by matthuisman** [comment]
I'll need to take a look. For now can you search and find them?

**Comment by matthuisman** [comment]
As in use the search function of the addon

**Comment by TomHarrop** [comment]
Thanks, I hadn't tried that...

Just tried and those videos don't show up in a search either.

**Comment by matthuisman** [comment]
fixed in [v0.3.7](https://github.com/matthuisman/slyguy.addons/commit/80b8a44fcf5c554e2a85c0a8131b3d18bfe28047) just released
