### ISSUE TITLE
Bug Disney+

### ISSUE THREAD

**Issue by djdirty60** [matthuisman/slyguy.addons#243]
Good day,

The season numbers are no longer displayed for the series on Disney+.  As a result, you can no longer play or find the addon with TheMovieDb.  Can you maybe look at that?

 thanks in advance

![16599117986226252696227574070696](https://user-images.githubusercontent.com/13561831/183313667-a8dc3cdb-866a-4d6e-a82b-ff178c02d5db.jpg)

**Comment by matthuisman** [comment]
what language is this?

**Comment by djdirty60** [comment]
> what language is this?

Dutch

**Comment by matthuisman** [comment]
fixed with [slyguy.disney.plus > v0.12.2](https://github.com/matthuisman/slyguy.addons/commit/d81532d5b9800e4be0220d2b42730fcc97a176a4)
