### ISSUE TITLE
(Request) HBOmax and Disney+

### ISSUE THREAD

**Issue by djdirty60** [matthuisman/slyguy.addons#244]
Good day,

Is it maybe possible that this addon get library integration?  Would be a nice addition.  Then you can watch your episodes much faster and immediately in the library if there is a new episode, instead of searching in the addon

 thanks in advance

**Comment by matthuisman** [comment]
Please use better issue names :) 
eg. Request: Library integration for Disney+

Anyway - its a maybe for the future.
For now, there are other addons that can do this.

**Comment by djdirty60** [comment]
> 

Which add-ons?

**Comment by matthuisman** [comment]
https://forum.kodi.tv/showthread.php?tid=349912

I think OSMOSIS is more worked on
