### ISSUE TITLE
Is it possible to change the dstv now catalog to the east african or KE guide

### ISSUE THREAD

**Issue by markmutai** [matthuisman/slyguy.addons#245]
Thank you so much for making such an awesome addon. 
The only issue i've ever had on it is the difference in DSTV guides by region. I'm using it in Kenya and the guide seems to be for ZA and makes the timings/what's on wrong on some channels or doesnt have any data on others - especially the sports ones are blank. Is there a way to adjust this? I'm also very willing to learn how to go about it if possible and be able to adjust and hopefully contribute any technical skills to it in the future.

Thanks again

**Comment by matthuisman** [comment]
i source that EPG from https://github.com/tinuva/epg so you would need to ask there :)
