### ISSUE TITLE
No 1080p support??

### ISSUE THREAD

**Issue by drag0nst0ne** [matthuisman/slyguy.addons#246]
I'm using KODI on PC W11, I've tried Disney+, HBO and Star+. When I play a video it doesnt show me the option to run it in 1080p. Only lower resolutions. Even on content that has 4K available on the original platform.

**Comment by drag0nst0ne** [comment]
Uncharted it only goes to 540p which is insanely low. I have a 1080p monitor and a 4K TV. And my connection is very good so its not that either.

![image](https://user-images.githubusercontent.com/50338430/184140432-7d0dbfef-9453-41e1-99e9-373b1f48d45b.png)

**Comment by matthuisman** [comment]
You need L1 widevine device. Same as if using a browser. The providers
block higher quality for l3 widevine devices

**Comment by drag0nst0ne** [comment]
Is there a way i can bypass that on PC?? I don't even know what is a L1 Device.

I understand what it means, but I dont know what devices are in that category.

**Comment by drag0nst0ne** [comment]
I got a pretty good combo on Star+, Disney+ and HBO Max. I got super excited and deleted most of my 1080p/4K collection of torrents. Almost 2Tb of stuff. Now I going to have to download it all again.

**Comment by matthuisman** [comment]
use the browser then - but that will be the same limited quality.
Take it up with the services :) its them who limit it.
Its quite clearly stated on my blog posts for the addons what is required to get better quality
