### ISSUE TITLE
Request: Addon for FITE TV

### ISSUE THREAD

**Issue by Spartan51150** [matthuisman/slyguy.addons#248]
I know this isn't really the place to put this but I am not sure whether you check mentions on kodi forums. https://forum.kodi.tv/showthread.php?tid=332844&pid=3101360#pid3101360

I am looking to fork and build out this add-on https://github.com/ArberDev/repository.arber/tree/master/plugin.video.fite.tv

Not sure where to start in regards to sourcing stream information or handling auth? No obvious API I can identify.

Any help or tool suggestions would be greatly appreciated.

**Comment by matthuisman** [comment]
Hi,

Best place is to keep asking on the kodi forums to be honest. Hopefully
someone can help you or you'll just need to keep at it :)

Thanks,
Matt
