### ISSUE TITLE
HULU playback issues

### ISSUE THREAD

**Issue by xicobiu** [matthuisman/slyguy.addons#251]
Stream or playback does not keep. When the schedule goes to break or when the break goes back to schedule, the transmission stops. No matter the quality of the stream (480p,720p) or fps, it is always interrupted. In the browser it works normally through the hulu site, but in kodi it doesn't.

Tests made on PC and Android.

**Comment by matthuisman** [comment]
That is due to limited support in inputstream adaptive for x-discontinuity. Out of my hands unfortunately
