### ISSUE TITLE
[REQUEST] Sky Sport Now to display more categories

### ISSUE THREAD

**Issue by meang** [matthuisman/slyguy.addons#253]
The iPad and web app has a section called browse with multiple categories for example Premier League and Rugby Union etc which if selected lists a bunch of videos.

There is similar functionality in the Spark Sports addon and I would love to have this also implemented in the Sky Sports Now Addon as well.

**Comment by matthuisman** [comment]
ill take a look after they do there big new version in a week

**Comment by matthuisman** [comment]
Big update by them now out. Luckily waited as complete rewrite :) I'll make a start tonight

**Comment by matthuisman** [comment]
good progress :) vod should be in by end of weekend hopefully

**Comment by matthuisman** [comment]
Complete in [v0.4.1](https://github.com/matthuisman/slyguy.addons/commit/f030de33cc2d016f90bd20c5a184be4fdc30cb49)
