### ISSUE TITLE
IPTV Merge Hidden channels keep resetting

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#254]
Hey @matthuisman, i have all of the channels in IPTV AU hidden except for sky racing 1 and 2, since last week they keep reappearing in my guide and i have to go back into manage tv and manually hide them all again, any idea why or if im doing something wrong?

**Comment by matthuisman** [comment]
so after changing them the initial time last week, have you had to hide them again?

**Comment by scottydulton** [comment]
Yeh i had to do it last week, then again day before yesterday, ill keep an eye on it now i know it shouldnt do it again.

oh awesome, thanks for the tip :)

**Comment by matthuisman** [comment]
Any further changes needed?

**Comment by scottydulton** [comment]
Hasn't reverted back yet mate so all good, ill close
