### ISSUE TITLE
Sky Sport Now | Can't Skip Past Video Start Time 

### ISSUE THREAD

**Issue by kontell** [matthuisman/slyguy.addons#256]
This is awkward to explain...

If I play a video from live and skip back 10 minutes the OSD will show "23:50:00 / 24:00:00".

As the video plays the OSD should stay roughly the same, as in it should show the video is 10 minutes from the "live edge" unless you manually skip. 

Instead, the first part of the OSD will go up with the time until it reaches 24:00:00. At this point the video will continue to play but it is no longer possible to skip forward towards the real live edge. 

Another way to show this issue is to play a video from live and pause it for a couple of minutes. The OSD will show a timeshift but you won't be able to skip forward.

With the first version of the addon after the rewrite - thanks for that - it did behave as expected, this issue I believe started with version 0.4.1/2 (if you can point me to previous versions of the addon I'll confirm).

**Comment by matthuisman** [comment]
If your playing via epg then that's a Kodi ui limitation.

**Comment by matthuisman** [comment]
Sorry, I misread. I'll take a look

**Comment by matthuisman** [comment]
ive looked into this and appears its a limitation with kodi.
The manifest has a 24 hour buffer window and kodi takes it from the start instead of the end.
cant see anything i can do about this unfortunately

**Comment by kontell** [comment]
Is there an issue associated with this or should I open one in Kodi/ Inputstream?
