### ISSUE TITLE
[Showmax] Feature Request: Add support for Showmax Pro sport streaming 

### ISSUE THREAD

**Issue by silvatyrant** [matthuisman/slyguy.addons#259]
Showmax Pro has a sports streaming service bundled with regular Showmax features. It would be great to have the ability to use this within Kodi too.

**Comment by matthuisman** [comment]
I'd need a Pro login provided to test with for starters

**Comment by silvatyrant** [comment]
I can help you out with that. 😉 How would you like me to get that to you?

**Comment by matthuisman** [comment]
Hold off for now. I'll reach out when I have time to do it. Could be
awhile. 😂

**Comment by silvatyrant** [comment]
👍🏽 No worries! Lemme know when you're keen!

**Comment by markeymark** [comment]
With the current issues on DSTV, hopefully sports can be looked at on Showmax....lol

**Comment by KODINETFLIX** [comment]
Is show max shorted

**Comment by bongwe0412** [comment]
hi Matt, any plan to bring back the showmax add-on for Kodi?

**Comment by matthuisman** [comment]
No plans sorry
