### ISSUE TITLE
[Paramount+] audio desync for live Serie A soccer's italian audio track.

### ISSUE THREAD

**Issue by puppinoo** [matthuisman/slyguy.addons#263]
Hi,
Just installed this addon.
Everything works great but for some live Serie A events (not all of them) the second audio track (Italian one) is desynced. I noticed it also happens with the US official app so maybe it's an issue with the service.
Not sure if I must provide a log cause no error appears (sorry if souding lazy. It's just I am at work now).

EDIT IMPORTANT: Using Us servers with Nord VPN or Getflix smartdns.

Thanks.
Pino.

**Comment by matthuisman** [comment]
if its doing it with their official app, then it will be something on their side sorry.
Maybe contact them and let them know
