### ISSUE TITLE
Tvnz+

### ISSUE THREAD

**Issue by catchbag** [matthuisman/slyguy.addons#265]
Hi.
Errors trying to load episodes. "Could not find a media source from Brightcove"
Server message: access to this resource is forbidden by access policy.

Cheers

**Comment by matthuisman** [comment]
Are you physically in NZ? Does the same episode work on their website or official app? They block most vpns

**Comment by catchbag** [comment]
Hey Matt,

Yes in NZ. Had been working fine until approx last week. Do recall an app
update for tvnz÷ recently, but otherwise no changes I can recall just yet.

Im running kodi19 on nvidia shield with Dns4me. Will test dns4me settings
to check nothing leaking a geo location as offshore. I can run native tvnz+
on shield from android apps and play episodes, albeit with Ads just fine.

Cheers

**Comment by matthuisman** [comment]
is the error shown on all episodes?
Or can you give me example of an episode that fails?

**Comment by matthuisman** [comment]
i just tested on a few random shows and all working for me
