### ISSUE TITLE
Hulu h265 issues on Kodi 20 Nightly

### ISSUE THREAD

**Issue by yeahme49** [matthuisman/slyguy.addons#267]
I'm running into issues playing H265 Hulu content on Kodi 20 nightlies. When I try to start a show it just spins and never starts playing. If I try to exit Kodi, it freezes on closing and I have to force close it through Task Manager. If I use Kodi 19 Matrix it works fine. This is running on Windows 11. It used to work with Kodi 20 but stopped working at some point, not exactly sure when.

Kodi 20 log https://paste.kodi.tv/rorejuveke.kodi

**Comment by matthuisman** [comment]
this will be out of my hands unfortunately

**Comment by yeahme49** [comment]
I did some testing, built 20.1.2-Nexus (https://github.com/xbmc/inputstream.adaptive/releases/tag/20.1.2-Nexus) and it played fine on Nexus. Then built 20.2.0-Nexus (https://github.com/xbmc/inputstream.adaptive/releases/tag/20.2.0-Nexus) and Kodi crashed when trying to start playing. Should I close this bug here and open one on the inputstream adaptive page instead?

**Comment by matthuisman** [comment]
yes, please open issue there. please follow their template and provide debug logs etc :)
