### ISSUE TITLE
Error starting Slyguy common service

### ISSUE THREAD

**Issue by CHJ85** [matthuisman/slyguy.addons#268]
Hi there. Since the latest update, your service is unable to start because it's looking for an non-existing module "dns".

```
2022-09-29 16:04:27.373 T:33      FATAL <general>: Failed to import Slyguy common service
2022-09-29 16:04:27.374 T:33      ERROR <general>: Traceback (most recent call last):
                                                   
2022-09-29 16:04:27.374 T:33      ERROR <general>: 
2022-09-29 16:04:27.374 T:33      ERROR <general>:   File "/home/chris/.kodi/addons/script.module.slyguy/service.py", line 8, in <module>
                                                       from resources.lib import service
                                                   
2022-09-29 16:04:27.374 T:33      ERROR <general>: 
2022-09-29 16:04:27.374 T:33      ERROR <general>:   File "/home/chris/.kodi/addons/script.module.slyguy/resources/lib/service.py", line 5, in <module>
                                                       from slyguy.session import Session
                                                   
2022-09-29 16:04:27.374 T:33      ERROR <general>: 
2022-09-29 16:04:27.374 T:33      ERROR <general>:   File "/home/chris/.kodi/addons/script.module.slyguy/resources/modules/slyguy/session.py", line 11, in <module>
                                                       import dns.resolver
                                                   
2022-09-29 16:04:27.374 T:33      ERROR <general>: 
2022-09-29 16:04:27.374 T:33      ERROR <general>: ModuleNotFoundError: No module named 'dns'
       
```              

I have no idea what that module does, because the addons work after removing the line requesting this module.
Although, the addons are looking for this module upon starting a video. The videos still play though.
Where can I find this module and what does it do?

**Comment by matthuisman** [comment]
https://forum.kodi.tv/showthread.php?tid=340691&pid=3112611#pid3112611

**Comment by CHJ85** [comment]
Thank you!

**Comment by CHJ85** [comment]
So this happened again now. Do you have a permanent fix for this?  Having to delete the dns module line every time there's an update is a bit annoying.
What does that dependency do anyway? Because like I said earlier, the videos play just fine without it. I mean, if it's causing trouble every time there's an update and it doesn't seem to affect the video playback or anything, does it have to be there?
Sorry if I'm wrong. I'm not a programmer or nothing.

**Comment by matthuisman** [comment]
It's been removed ..

**Comment by matthuisman** [comment]
Have you updated slyguy dependencies yet?
All the add-ons rely on each other being upto date.....

**Comment by matthuisman** [comment]
Maybe it's time to provide a full debug log

**Comment by matthuisman** [comment]
**kodi settings > system > addons > manage dependencies > slyguy dependencies.
Needs to be  v0.0.7 or higher**

You should have automatic updates on else going to have issues like this more often than others.
Slyguy common relies on slyguy dependencies module being upto date

**Comment by matthuisman** [comment]
If you do have updates on, then maybe issue in Kodi not auto updating dependencies for some reason. If you think this is the case, a debug log or at least what version Kodi on what platform may help so I can let them know

**Comment by CHJ85** [comment]
I did. Just didn't understand what it meant. 
I've never had this happen before.
i wouldn't even know how to update manually. Thought it just happened in the background.

**Comment by CHJ85** [comment]
Anyway. I updated everything from the github master and everything is working fine now. Thanks for your help and I'm sorry to bother you.

**Comment by matthuisman** [comment]
Kodi is meant to auto update. Have your been manually installing add-ons from GitHub? Don't do that. There is even a warning on the GitHub to not do that  Install via the repo in Kodi. Also, what version Kodi on what device are you using?

**Comment by CHJ85** [comment]
Nah I always keep it on auto update. But somehow, the dependencies were stuck on 0.0.3 and wouldn't let me update when I tried doing it manually. Hence why I had to update through github now.

**Comment by matthuisman** [comment]
What version Kodi and what device please?
Sounds like a Kodi bug

**Comment by CHJ85** [comment]
It's version 19.4.0 on a laptop running Ubuntu 22.04.

**Comment by matthuisman** [comment]
Thanks. I'd recommend you navigate to the dependency in Kodi, select update and then select the latest version listed for the repository. This should set it up to auto update in the future to stop this happening again

**Comment by CHJ85** [comment]
Thank you. Oh and btw. Completely off-topic but important. Paramount+ and Peacock TV have started merging into SkyShowtime. They already launched in the Scandinavian countries earlier this month and are coming to the Netherlands and other countries later this year. So it's not something you have to worry about just yet I think. But still. Thought you should know.

**Comment by matthuisman** [comment]
I probably won't make new addon for that as Sky is annoying. I suspect
that's just a Europe only thing?

**Comment by CHJ85** [comment]
At first, yes. But Europe tend to be beta testers.
Comcast owns Sky. That's where the name comes in.
But at least give it a try, please. Because eventually they're gonna start shutting down Paramount+ and move us over to SkyShowtime. I just hope it isn't all DRM protected like Peacock.

**Comment by matthuisman** [comment]
From what I just read, it's using the same platform as peacock. So
basically rebranding peacock and adding more

**Comment by CHJ85** [comment]
Okay. So it's basically a worldwide thing. Because I'm looking at the website, and they have all these logos from Universal, Paramount+, Paramount Network, Nickelodeon, Showtime, DreamWorks and Sky.
I just went to Paramount+'s website using a Norwegian VPN, and it says "ANNOUNCING SKYSHOWTIME www.SkyShowtime.com  As of 20/9, the new home for Paramount+ favorites."
Which leads me to believe that Paramount+ is soon going bye bye.

**Comment by CHJ85** [comment]
And btw. Paramount+ Norway on facebook has also been rebranded, so it seems to be a merger between the two like I first suspected.

**Comment by matthuisman** [comment]
It'll be Europe only on I . Sky is unknown in USA. Paramount+ will still
for USA, Australia etc I suspect.

**Comment by CHJ85** [comment]
Yea I guess.

**Comment by matthuisman** [comment]
We need to find out if the new service works in a browser on Linux.
Hopefully they making it less locked down

**Comment by matthuisman** [comment]
Good inDfo
https://www.skygroup.sky/article/-skyshowtime-announces-official-launch-date-and-content-line-up

**Comment by matthuisman** [comment]
Kodi is meant to update them automatically. Can you advise what Kodi
version on what device please?
