### ISSUE TITLE
No successful DNS lookups without urls.txt

### ISSUE THREAD

**Issue by Firesphere** [matthuisman/slyguy.addons#269]
Since today/this evening.

I didn't have any `urls.txt` file in my addons folder. This evening, all channels and on-demand for all SlyGuy-Freeview addons stopped working and throwing a 30 seconds time-out error.

Looking at the logs of my DNS server, I noticed that every query (e.g. Netflix, Youtube, Disney+ etc.) came through, except for the NZ Freeview ones. Those seemed to "disappear"

Adding a urls.txt with `r:1.2.3.4 *` solved the problem. But I doubt it's supposed to be the solution

(1.2.3.4 obviously replaced with an actual, functional DNS server IP)

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/smart_urls.py#L22

Does 1.1.1.1 dns server not work on your network?

I may have to remove those defaults

**Comment by Firesphere** [comment]
> Does 1.1.1.1 dns server not work on your network?
> 
> I may have to remove those defaults

No, nothing goes outside my network on DNS port 53, all DNS is forcefully routed to my PiHole, which does the upstream DNS work (or block things...).
It does explain what happened (and how my fix worked)

**Comment by matthuisman** [comment]
good to know - i was trying to fix issues where networkwide ad blocker or ISP dns would block my domains or block dai.google.com hls streams. But I have now removed those and leave it up to the end-user to sort those issues

**Comment by Firesphere** [comment]
Maybe document it somewhere? I wouldn't be surprised if among Kodi users, the percentage of PiHole users is above average :)

Cheers for the quick reply!
