### ISSUE TITLE
[Nebula] Video duration sometimes not shown

### ISSUE THREAD

**Issue by matejdro** [matthuisman/slyguy.addons#270]
Not sure if this is something that can be fixed by this plugin, but recently, some videos from Nebula do not have duration. At first they appear as very short (20 or so seconds), but after progress bar reaches the end, it just keeps going until the actual end of the video:

https://user-images.githubusercontent.com/507922/193394958-00c0c6d8-9a06-4cc0-9409-afb12c2a6ce6.mp4

(Video from above example: https://nebula.tv/videos/hai-why-it-takes-pixar-3-years-to-render-a-movie)

This happens with Kodi 19 Nightly (from couple of weeks ago) on Nvidia Shield (ARM) and Kodi 19.4 Stable on x86, so I don't think it's related to Kodi version. Addon version is 0.2.0.

**Comment by matthuisman** [comment]
i just tried this video and it shows as 5:42 long for me.
Kodi 19.4 Windows x64

**Comment by matejdro** [comment]
It also happens on stock skin. But I've checked on another machine and I also cannot reproduce there, so it might be somehow related to my installation. Will report more info here if I find it.

**Comment by matejdro** [comment]
Found the cuplrit: `Use Inputstream for HLS for VOD Stream` setting. It seems it has been enabled for some reason.

Was this default a while back? I don't remember changing it manually, but maybe I did it accidentally.

What does this option do?

**Comment by matthuisman** [comment]
i just tried on 19.4 with IA for VOD enabled on Pixar 3 years to render a movie and still got the correct duration.
What version kodi using?

**Comment by cas--** [comment]
Afraid I can't add anything new but I am seeing the exact same issue. I used to be able to seek within videos but it stopped working a few weeks ago and now only shows 20s timeline but run to completion.

Kodi 19.04 on Ubuntu 

Thanks for suggesting disabling IA for Vod as a workaround

**Comment by matthuisman** [comment]
Managed to see the issue on "How Boulevards Change Paris Forever".
I see what the problem is, and have opened a ticket on Inputstream Adaptive
https://github.com/xbmc/inputstream.adaptive/issues/1054

I'll see if I can somehow fix it in my proxy in the meantime....
Might be a bit tricky apart from removing the subtitle all together

**Comment by matejdro** [comment]
Thanks for checking it out. Can you tell us what the VOD option does and what do we loose by not using it?

**Comment by matthuisman** [comment]
Lose nothing :) just turn it off. I'll do an update to disable it
