### ISSUE TITLE
Paramount+ A-League live games not showing

### ISSUE THREAD

**Issue by Bob-git1** [matthuisman/slyguy.addons#272]
Paramount+ A-League live games not showing in Kodi add-on.

**Comment by matthuisman** [comment]
sorry, i don't currently have a valid login for this service so unable to develop.

If you can help, see here:
https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by scottydulton** [comment]
@matthuisman did you get my email? 
i just found something odd, when i add Paramount to IPTV Merge i can see and watch the game in the tv guide, however in paramount itself there use to be "Live Matches" in the Izuzu A-League Men category, it is no longer showing

**Comment by matthuisman** [comment]
I did but having a settings.xml for addon doesnt help me view the requests their apps / website make unfortunately

**Comment by scottydulton** [comment]
@matthuisman ohhh of course, ill see if they offer a trial account and let you know, unless @Bob-git1 can assist?

**Comment by matthuisman** [comment]
yeh, pretty hard to work "blindly" :)
I did actually manage to get it going after your clue.

[v0.5.4](https://github.com/matthuisman/slyguy.addons/commit/3529435b71932902a33e7b33c6db84c20b1c18ae) released which should work

A login would still be handy for any future issues though

**Comment by scottydulton** [comment]
@matthuisman ive just emailed you a login ill have to cancel in 6 days if you need to have a quick look

**Comment by Bob-git1** [comment]
Hi Matt, just emailed you my login, hope it helps.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by scottydulton** [comment]
i looked at the source of the video, it was calling from "shows" then izuzu a-league men, so i went into shows, then all shows and scrolled down to izuzu a-league and that menu showed live events, i could access it that way, alot more of a run around then the shortcut i had to sports haha

**Comment by matthuisman** [comment]
"however if you go into sport then into the A league you cant access it from there"

There is no Sport main menu item in the add-on yet (hopefully i can eventually add)
Featured > Sports > izuzu a-league  > live schedule is how I've been accessing it

**Comment by scottydulton** [comment]
i can now, however it doesnt list the teams playing like it used to

**Comment by scottydulton** [comment]
Edit, yes it does on the info panel
