### ISSUE TITLE
Site Request: new NHL.tv

### ISSUE THREAD

**Issue by feerlessleadr** [matthuisman/slyguy.addons#273]
Hi - the NHL has moved away from bamtech as their backend provider for NHL.tv. and so the legacy addon in Kodi no longer functions. I'm not sure if the dev plans on updating the legacy addon, so was hoping that you might be willing to create an addon (or fork his addon with the appropriate changes). 

If necessary, I'd be happy to share login credentials as well. 

Thanks for your consideration.

**Comment by matthuisman** [comment]
Best to post your addon request here
https://forum.kodi.tv/forumdisplay.php?fid=251
