### ISSUE TITLE
Hbo Max and Trakt? 

### ISSUE THREAD

**Issue by FloydKulis** [matthuisman/slyguy.addons#278]
Is it possible to somehow combine the expansion and the movies watched in tract?  I would like the watched movies to be automatically added to the route.  My country of application is Poland.  I heard that when I change the region to states it should work then.

**Comment by matthuisman** [comment]
trakt addon doesnt need anything special to work with other addons. it looks at whats playing.
as long as addons set good meta data on the content, trakt can figure it out.
closing this as HBO Max / MAX do add good meta data
