### ISSUE TITLE
Peacock TV

### ISSUE THREAD

**Issue by 89z** [matthuisman/slyguy.addons#279]
requesting support for this service to be added. I tried to MITM the Android app:

https://play.google.com/store/apps/details?id=com.peacocktv.peacockandroid

but I get this error when trying to sign in:

> An error has occurred. Please try again.

maybe you can work some magic?

**Comment by Liqianyu** [comment]
Also expect matthuisman to work his magic, but for now...  I came through Apple TV to MitM Peacock TV.

**Comment by matthuisman** [comment]
Closing as there already request for this on Kodi forums

**Comment by 89z** [comment]
can you please link to what you are talking about
