### ISSUE TITLE
Intermittent Pixelated Video with Foxtel Go Add-On

### ISSUE THREAD

**Issue by peteallelite** [matthuisman/slyguy.addons#28]
When watching the video keeps getting distorted every 5-10 seconds, no matter what playback quality I choose.
My Sony Android TV uses Widevine CDM level 1. I have tried different channels and all do the same guy with the add-on.
Other add-ons don't have a distorted video.

**Comment by matthuisman** [comment]
see here:
https://forums.whirlpool.net.au/thread/3wwnqx63?p=68#r1356

**Comment by peteallelite** [comment]
I have the built in Inputstrem.adaptive plugin already installed though

**Comment by matthuisman** [comment]
You need to update it to the one linked in that thread

**Comment by peteallelite** [comment]
Thank you so so much! It works well now
