### ISSUE TITLE
[Disney+] No Atmos track anymore.

### ISSUE THREAD

**Issue by Shadow0man** [matthuisman/slyguy.addons#281]
I can't get Atmos track in addon anymore. Option is checked in settings but is not displaying in audio options list. It was working one month ago. It is not working on my Chromecast with Google TV and Firestick 4K Max aswell.

**Comment by matthuisman** [comment]
i wonder if its on disney+ side?
https://www.reddit.com/r/AndroidTV/comments/w43g7v/disney_took_away_atmos_on_2020_android_tv/

I cant see any atmos tracks in the returned playlist..
Can you try official app?

**Comment by matthuisman** [comment]
ok, think i need to switch to their new manifest request endpoint

**Comment by Shadow0man** [comment]
After I wrote this I found that is bigger problem with it. Many people are not getting Atmos in their apps. Maybe they're tinkering with it so it made some things in addon obsolete.

**Comment by matthuisman** [comment]
is Atmos back yet?
Looks like the official apps Atmos came back about 10 days ago. Wondering if the addon is now also working?

**Comment by matthuisman** [comment]
fixed in latest version
