### ISSUE TITLE
Paramount+ is not available in your region

### ISSUE THREAD

**Issue by jabcodes23** [matthuisman/slyguy.addons#282]
Received the error in the first picture today. I am not using a VPN. I tried logging out to log back in and got the error in the second picture. I tried actually using a VPN even though I am in the US but that did not work. Neither did uninstalling and reinstalling the addon. All my other SlyGuy addons are working fine. Any idea what's happening?

![83AA496D-48DE-4F0E-BB01-B297C91118C0_1_101_o](https://user-images.githubusercontent.com/76067405/196826983-ab7be0c1-9b6a-445d-8406-cb2a8a1e531c.jpeg)
![976C6CBD-9C70-4637-BDE9-C57634935E53_1_101_o](https://user-images.githubusercontent.com/76067405/196826994-3203538b-7f1f-49a5-bbf8-4cd877a767a0.jpeg)

**Comment by matthuisman** [comment]
fixed last night. update to latest version
