### ISSUE TITLE
Addon for HiDive please?

### ISSUE THREAD

**Issue by CHJ85** [matthuisman/slyguy.addons#283]
Hi there Matt. I've been using Crunchyroll for the longest time, and they do have an addon for Kodi. But as HiDive keep expending its anime library, I decided to switch it up. I love HiDive. It's a lot more organized than Crunchyroll. However, there aren't any Kodi addons  yet for whatever reason, which brings me to this request. 
Do you think you could develop a HiDive addon for Kodi please?
Btw. Hidive.com works great on Linux, so there shouldn't be any DRM related issues.
Thank you.

**Comment by matthuisman** [comment]
Leaving this here for future me
https://play.google.com/store/apps/details?id=com.twentyfouri.androidtv.hidive

**Comment by matthuisman** [comment]
Addon requests best to go here for maximum visibility
https://forum.kodi.tv/forumdisplay.php?fid=251

**Comment by CHJ85** [comment]
Okay, thanks.
