### ISSUE TITLE
ESPN Addon - FORBIDDEN LOCATION

### ISSUE THREAD

**Issue by RenegadesTV** [matthuisman/slyguy.addons#287]
Hi. 

I have just installed the ESPN addon, and logged in with the credentials on the ESPN+ website(confirmed working with US VPN) - Enter my login details in addon and link to account(confirmed)

However when i try to playback, it says API Request Failed - server-error - Forbidden Location

Is this happening for anyone else?

**Comment by matthuisman** [comment]
no reports of this. Does sound like its detecting your vpn maybe?
