### ISSUE TITLE
DSTV Now not working

### ISSUE THREAD

**Issue by markmutai** [matthuisman/slyguy.addons#289]
Hey. Been having issue with dstv, it seems to attempt ot connect, but throws an error when starting to play the video. I've tried login back in & resetting, still the same issue. I've also tested on their android app incase the account was the issue, but it works fine. I've attached the log below, what could be the issue? Thank you for the continuous awesome work with all these addons btw!

[dstvslyguy_log.txt](https://github.com/matthuisman/slyguy.addons/files/9893287/dstvslyguy_log.txt)

**Comment by matthuisman** [comment]
that issue was fixed in v0.16.0 (released 5 days ago)

also, please only provide full logs. I can't tell what versions of addons your using with partial logs
