### ISSUE TITLE
channel freezes, buffers

### ISSUE THREAD

**Issue by poltom30** [matthuisman/slyguy.addons#29]
hi Matthusisman

would you pls check this channel out for me?

Country: NewZealand
Channel: Breeze TV

It should be in HD (strangely only with Wuffy Player open it up in HD) every other player plays it in SD. Of course I'd like to watch this with Tivimate's internal player, I don't want to use any other external player.

It freezes and buffers all the time, even though everythings is fine on my end (every other channel works fine).

Thank you!

Best,
Tom

**Comment by matthuisman** [comment]
I can't help sorry.
I just grab their official stream

**Comment by poltom30** [comment]
thanks for the info
