### ISSUE TITLE
Kayo token

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#290]
Hey @matthuisman,

Would you be able to check if something on Kayos end has changed with the way the token is refreshed? twice in a week ive got the 'failed to refresh token' dialog and had to log out and log back in, im using device code as way of login.

**Comment by matthuisman** [comment]
seems to be fine for me. just tried the addon which i havnt used in weeks and it refreshed token fine.
Are you doing anything "special" like sharing logins etc?

**Comment by scottydulton** [comment]
no its refreshing fine, but logged me out again a few days later again
