### ISSUE TITLE
Memory leak from open URL connections?

### ISSUE THREAD

**Issue by pointybirds** [matthuisman/slyguy.addons#292]
Hi,

Since I did an upgrade on OSMC (Rpi 3) in September, I've noticed a memory leak somewhere in Kodi. Digging in a bit further, memory usage climbs about 24K at the same time every hour, which coincides with an hourly repository check that I can see in the Kodi debug logs:

```
2022-11-03 06:58:11.881 T:27837   DEBUG <general>: script.module.slyguy - Attempt 1/2: GET https://k.slyguy.xyz/.repo/addons.xml.md
5
2022-11-03 06:58:12.128 T:27837   DEBUG <general>: script.module.slyguy - Attempt 1/2: GET https://k.slyguy.xyz/.repo/addons.json.gz
```
Using netstat, I can see a growing list of HTTPS connections to 172.67.172.228 in the CLOSE_WAIT state. Is there something that's stopping these connections from closing?

I'm using the current OSMC (2022.10-1), which runs on Debian 11.5 and uses Kodi 19.4. Everything was running fine before the big OSMC update to Debian 11 in September, which I guess might make the culprit hard to find.

Kind regards

Dan

**Comment by matthuisman** [comment]
hopefully the latest Slyguy common fixes this. Please re-open this issue if it doesnt
