### ISSUE TITLE
Latest update crashing

### ISSUE THREAD

**Issue by AndrewWNZ** [matthuisman/slyguy.addons#293]
Sky Sport Now updated automatically last night to 0.4.5.
Now live tv is crashing after 10 secs. Screen just freezes.
Tried rebooting, uninstalling and re-installing, cant figure out how to fix/resolve.

Any help appreciated.

Cheers

**Comment by AndrewWNZ** [comment]
noticed that just before it crashes, the buffering sign pops up, gets stuck at 1% and stays there.

**Comment by matthuisman** [comment]
should now be fixed with [0.4.6](https://github.com/matthuisman/slyguy.addons/commit/b81285c8fc19ce9f7f57b80c0cd97df92fc41a2a)
