### ISSUE TITLE
ABC News in 90 seconds doesn't update

### ISSUE THREAD

**Issue by Ozman** [matthuisman/slyguy.addons#295]
Everything else appears to be working well except the above. It just plays the same afternoon edition from several weeks ago.

**Comment by matthuisman** [comment]
thanks for letting me know. Now fixed 

I see they do sport, buisness and weather in 90 seconds too now, so im going to open
Ive opened an issue to add those here: https://github.com/matthuisman/i.mjh.nz/issues/30

**Comment by Ozman** [comment]
Wow, that was fast! ABC News in 90 seconds now works. Looking forward to business and weather. :+1: 
Thanks so much.
