### ISSUE TITLE
Sky Sport Now, unable to play any channels

### ISSUE THREAD

**Issue by AndrewWNZ** [matthuisman/slyguy.addons#296]
Sorry Matt but looks like I have issues with play back again. Was working but now unable to play live or from the beginning on any channel.
Whats the process for sending error logs?

**Comment by matthuisman** [comment]
You using latest version? Didn't you downgrade at one stage?

**Comment by AndrewWNZ** [comment]
Currently have 0.4.6 installed. I dont recall downgrading but I did experience the same issue with an older version and I think from memory a temp fix was to install a version with the ability to play from beginning option removed.

**Comment by matthuisman** [comment]
You could try revert to 0.4.4. https://slyguy.uk/.repo will have zips of that older version

**Comment by AndrewWNZ** [comment]
tried them all 0.4.2 to 0.4.6, all the same. What is weird is I'm sure one of those versions didnt have the play from beginning option but they all seem to now.

**Comment by matthuisman** [comment]
just pushed 0.4.8 that should fix
