### ISSUE TITLE
Pluto tv AD

### ISSUE THREAD

**Issue by numbernumero** [matthuisman/slyguy.addons#297]
Hi, I am noticing that at times when I play a channel on Pluto TV, the channel will freeze when an advertisement comes on.  I am forced to stop the channel and restart it again in order to continue watching it.  This occurs more than 50% of the time when watching Pluto TV Italy.  I have tried to enable and disable the advertisements in the settings but it does not fix the issue.   Why is this occurring or what can I do to resolve this problem?

**Comment by matthuisman** [comment]
this will be due to hls continuity which Inputstream Adaptive doesn't seem to work 100% with yet. Same goes for Kodis internal ffmpeg.

You could try Pluto TV > addon settings > playback and then disable "use inputstream adaptive for hls" and see if that helps

**Comment by matthuisman** [comment]
this is out of hands as it requires better support for dynamic ad insertion in inputstream adaptive / kodi core
