### ISSUE TITLE
Channel 7 stream links not working

### ISSUE THREAD

**Issue by Smark223** [matthuisman/slyguy.addons#298]
Channel 7 stream links eg. https://i.mjh.nz/7-syd.m3u8 aren't working

**Comment by matthuisman** [comment]
Are you in Australia? Do the same channels work on their website for you?

**Comment by Smark223** [comment]
I'm not but they've always worked before, using either Smart DNS or an Australian VPN. Streams on the 7Plus website work fine.

**Comment by SoreTissue** [comment]
Channel 7 channels are not working for me either. I'm in Australia.

https://paste.kodi.tv/awerecixor.kodi

**Comment by baty0man** [comment]
Me neither.

**Comment by matthuisman** [comment]
Fixed last night
