### ISSUE TITLE
Bein Connect MENA playback issues

### ISSUE THREAD

**Issue by Chukridam** [matthuisman/slyguy.addons#299]
Hi,
All channels stop after exactly 9 minutes of playback. Then I’ve to relaunch again, stop after another 9 minutes and always like that for the last week or so.
I’ve tried to logout and login again many times but nothing. Have also tried to play with the router (disabling ipv6) but no luck.
Any tip? Is this happening to others? It was working perfectly before and I really enjoyed the addon. 
Many thanks in advance

**Comment by matthuisman** [comment]
hopefully have time over next few days to look at this.
I suspect we need to refresh the token every few minutes

**Comment by 3araby80** [comment]
same issue here since last update (0.2.6)

**Comment by matthuisman** [comment]
this issue should now be fixed with [v0.2.7](https://github.com/matthuisman/slyguy.addons/commit/b324be2d4c68492b1c082c13f88cf864b9d47cb1)
