### ISSUE TITLE
[Disney+] Api bad request

### ISSUE THREAD

**Issue by twerkingsmurf** [matthuisman/slyguy.addons#30]
Since yesterday i get Server error:Bad request.
It looks like it's logged on but can't navigate or do anything.
![Clipboard](https://user-images.githubusercontent.com/20704362/126609338-62226c9f-aa4e-4215-bef0-68dc3c0b687b.jpg)

**Comment by matthuisman** [comment]
https://forum.kodi.tv/showthread.php?tid=353316&pid=3050629#pid3050629

**Comment by twerkingsmurf** [comment]
Ok, sorry. I didn't know it was a known issue.
Just wanted to report it.
Thanks for the answer. Hope it will be possible to fix it

**Comment by matthuisman** [comment]
@twerkingsmurf 
See my updated comment above. Maybe you can help

**Comment by balta3** [comment]
I have the same issue. I could provide you with credentials, but I do not know if Disney+ is region bound. My account would be german. As I'm a developer myself you could also give me instructions where to look and I could try to create a pull request.

**Comment by matthuisman** [comment]
argh. OK.
I will need to update the add-on to use their latest api (quite a big process)
It also means we will get less data back. eg. won't get TV show descriptions as their latest api doesnt return this data as the apps / websites use images only

**Comment by Liqianyu** [comment]
I have the same issue.I think this will soon advance to all users.

**Comment by matthuisman** [comment]
OK, here is a version to try:
**https://f.mjh.nz/slyguy.disney.plus-RC1.zip**

If all is OK, I'll push it out to the repo

**Comment by matthuisman** [comment]
Just pushed the changes

So fixed in 0.7.5
https://github.com/matthuisman/slyguy.addons/commit/beefa703fc2bfa447e31b73e18462916f4bb9e84
