### ISSUE TITLE
Feature request - automatically select AAC instead DD+ audio track

### ISSUE THREAD

**Issue by mauriciogoncalves** [matthuisman/slyguy.addons#300]
First of all, you addown is awsome. I am using a lot!

I have some issues wih audio language
I have kodi (18.4) at my Raspberry Pi 4 with  Raspbian 10 (buster)

For some reason in my kodi got a weird behaviours 
I cant play audio tracks in DD+ format only in AAC audio tracks works .. 
I have no issues on other addons like Netflix, but domehow DD+ encode from disney source is not working for me

The Automatic selection of audio in my language (portuguese) is working fine... 
BUT ...   it always select Portuguse DD+ automatically  and it not works for me 
It opens mute and video seek keeps 
forwarding seconds... play ... forwarding seconds... play ... for ever, tying to sync audio and video i think...
After i manually select some AAc audio track it starts to work fine...

Is it possible to do something for automatically  select AAC instead DD+ ?

This is the kodi log when opening a movie:
![image](https://user-images.githubusercontent.com/24781994/201551550-51a62ac2-2150-439e-bc29-eb7635aceda9.png)

**Comment by matthuisman** [comment]
I think I already have a Disney+ addon setting to do this?

**Comment by matthuisman** [comment]
Actually, no there isn't. I'll see if I can add

**Comment by matthuisman** [comment]
You can now do

Addons > Services > Slyguy Common > Settings > Playback > Dolby Digitial Plus (EC-3) and disable that.
