### ISSUE TITLE
SkyGo Addon not logging in

### ISSUE THREAD

**Issue by PhilDun** [matthuisman/slyguy.addons#301]
Hi
Just installed Kodi 19 matrix, and added Slyguy SkyGo, but it won’t let me login!

get “Failed to fetch auth token” error.

not geo-blocked as in UK, but tried Nord set to UK just in case.

can login using official app on other devices (x5) and have 1x device left, so don’t think it’s that.

totally stuck sorry. Andy advice welcome.

TIA

**Comment by PhilDun** [comment]
Forgot to mention, this is on Firestick…two different sticks, one 4k one standard

**Comment by matthuisman** [comment]
My skygo addon is for sky go in new Zealand only
