### ISSUE TITLE
Enhancement - Claro TV+

### ISSUE THREAD

**Issue by xicobiu** [matthuisman/slyguy.addons#302]
Can you add this streaming service?

"Claro TV+" works in Latin America
https://www.clarotvmais.com.br

This repo can help you build:
https://github.com/olavopeixoto/plugin.video.brplay
Here you take advantage of the structure and make modifications for the best functioning.

In the "Now Online" tab, now "Claro TV+" is where the old code was written, but it is not working after the migration. I think there is some error in the player.

log:
https://github.com/olavopeixoto/plugin.video.brplay/files/9842146/kodi.log
https://github.com/olavopeixoto/plugin.video.brplay/files/9766882/kodi.log

**Comment by matthuisman** [comment]
Addon requests can be made here
https://forum.kodi.tv/forumdisplay.php?fid=251
