### ISSUE TITLE
Can't watch USA region

### ISSUE THREAD

**Issue by Christiancoding** [matthuisman/slyguy.addons#306]
USA region channels are not working. I tried to uninstall and reinstall it but it didn't work. So far, all other regions work. 
![16690846000631962044406299674991](https://user-images.githubusercontent.com/47830757/203207245-33b19075-a1ca-432f-be31-935a39759644.jpg)

**Comment by matthuisman** [comment]
see issue: https://github.com/matthuisman/samsung-tvplus-for-channels/issues/6
