### ISSUE TITLE
Bein connect MENA 4K channel not working

### ISSUE THREAD

**Issue by bu-rakan** [matthuisman/slyguy.addons#307]
Hi I have issue with the 4K channel in Bein connect add-on there is no picture or sound no matter which quality I choose
Using android phones and android TVs 
And the the other channels are working without any problem
And if I use the original bein connect app the 4k channel working perfectly

**Comment by bu-rakan** [comment]
> try Kodi 20

Tried kodi 20 nexus beta 1 and it working perfectly thank you so much

**Comment by matthuisman** [comment]
@glennguy Any ideas what may have been fixed in Kodi 20 or latest IA?
I want to figure out if it's originally an IA issue or Kodi issue.
I can get you a manifest and logs between the two tonight

**Comment by matthuisman** [comment]
Manifest
[Uploading in.mpd.txt…]()

Kodi 19 (funny colours on playback)
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/10073002/kodi.log)

Kodi 20 (ok)
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/10073011/kodi.log)

**Comment by glennguy** [comment]
Hey Matt.

I think this would be to do with CBCS:
![image](https://user-images.githubusercontent.com/11909320/203542048-b3dc2283-7605-4468-8488-72192d4ad9fa.png)

I would bet that this stream has multiple subsamples which aren't decoded properly in IA Kodi 19 (Optus had this issue too, among several others 😄 )

**Comment by matthuisman** [comment]
Oh, I didn't even spot the cbcs in there!! For some reason I didn't think a dash manifest would use cbcs as only seen in cmaf until now. Thank you 😌
