### ISSUE TITLE
[Disney+] no video only audio on some movies

### ISSUE THREAD

**Issue by sideshowbob84** [matthuisman/slyguy.addons#310]
Hey,
thanks a lot for this finde addon. Most of my series and movies play fine. But on some movies i have the problem that the video is black. I am on libreelec 11 on a raspberry pi. I tried to reinstall and update widevine. I if seek in the movie very often (10s forward, 10s, forward, and so on) i sometimes get a lucky punch and the movie plays. But if want to got backwards because i missed the beginning video stops working again. But like i wrote most videos play fine not like in #236 . On example where this happens is the movie "Willow".
I created a debug log https://paste.kodi.tv/oyeboniwul.kodi .The example show very much seeking the second last seek was a lucky punch and the movie played.
Thanks a lot and kind regards!

**Comment by matthuisman** [comment]
can you please try go into the Disney add-on settings > advanced > re(install) widevine CDM > select the 2nd from the top.
Let that install. Restart the system and then test

**Comment by sideshowbob84** [comment]
thanks for your help. But that did not change anything. The second from the top was the version 4.10.2449 was that the correct one?

**Comment by matthuisman** [comment]
@sideshowbob84 try disable "DRM PRIME decoder"

**Comment by matthuisman** [comment]
actually, https://github.com/LibreELEC/LibreELEC.tv/pull/7173 may have fixed the issue.
**Have you tried with a recent nightly??**

**Comment by matthuisman** [comment]
closing as no response

**Comment by sideshowbob84** [comment]
sorry, i was not fast enough :) 
Disabling "DRM PRIME decoder" solved the issue for me. I updated to latest nightly 2023-01-14 (eebbd03), but if i reenable DRM PRIME Decoder. The problem is still there. Should i still open an upstream issue at libreelec? Thanks a lot!
