### ISSUE TITLE
HTTP API Server - Playlist format Question

### ISSUE THREAD

**Issue by xtreamjava** [matthuisman/slyguy.addons#314]
Hi, Thanks for your work on these addons. 

I have tested IPTV Merge with Kayo, It works fine using "PVR IPTV Simple Client.

I tried to use HTTP API Server, I have tried to call playlist on another device and it seems to get the playlist but It is not playing. I have looked into the playist and it comes as the following format.

`#EXTINF:-1 channel-id="500" group-title="Kayo Sports" tvg-chno="500" tvg-id="53217" tvg-logo="https://vmndims.kayosports.com.au/api/v2/img/5bcefccee4b0a8faf3c14aef-1658195201775?location=carousel-item&imwidth=415",Fox Sports News
plugin://plugin.video.kayo.sports/?_=play&id=53217&_is_live=1&_noresume=.pvr`

I did follow your response in a [forum](https://whrl.pl/Rggrw9)

When i tried to play channel from the playlist on another device, 1st it asked me to install Kayo addon and then when i did, it was throwing error that I need to login.

My understanding from the above mentioned forum was that, we need to login into kayo on 1 device and then we can use the playlist to play on 2nd device. Am I wrong?

**Comment by matthuisman** [comment]
"Note:
For now, if the merge is relying on certain installed plugins – they will
need to be on all devices..
I'm working on a way around this though Smile"

That means installed and logged in. Unfortunately I didnt find a way around
that. Probably possible but not enough hours in the day. 😂

If you want a network wide single kayo instance, check out my kayo for
channels docker container. You could use that. Then point IPTV merge /
simple IPTV at the url for that container
