### ISSUE TITLE
Need specification of provider for HBO Max Addon

### ISSUE THREAD

**Issue by fbrier** [matthuisman/slyguy.addons#316]
This may be similar to the [fix for the Paramount Addon](https://github.com/matthuisman/slyguy.addons/issues/50), but appears to not be available for the HBO Max Addon. Customers of AT&T fiber get HBO Max included in their service. When you go through the login process, you first specify the provider (AT&T) and then your username and password for your AT&T service. The three items form a valid credential. The Kodi HBO Max AddOn has the option of username/password OR device, but does not appear to have fields for provider/username/password. On a customer's account overview page, these instructions are provided.

INCLUDED ON US WITH INTERNET
![image](https://user-images.githubusercontent.com/764652/206966376-ec46b053-92cf-4130-bda9-b6fa8483e322.png)
You've got HBO Max! To sign in, select AT&T as your provider. Then, enter your AT&T user ID and password to start streaming.

Would it be possible to add this? Thank you.

**Comment by matthuisman** [comment]
Why can't you use device login?

**Comment by fbrier** [comment]
My apologies. Despite my having used device logins before, I did not connect it to this use case. Worked great. Sorry and thank you.
