### ISSUE TITLE
IPTV Merge stripping Logos and other data

### ISSUE THREAD

**Issue by markosjal** [matthuisman/slyguy.addons#324]
I am trying to use IPTV Merge and getting a result as listed below as an example. I noticed something was off when I lost the logos.

input=
`#EXTINF:-1 channelID='9233008939' tvg-num='56' tvg-chno='56' tvg-name='Olympic Channel' tvg-id='9233008939' tvg-logo='https://mysecetdomain.com/Logos/US/olympics.png' group-title='Sports',Olympic Channel
http://10.0.0.250:5004/MyList/watch/9233008939`

This is the output of IPTVMerge for that channel (no logo and other info missing)=
`#EXTINF:-1 tvg-chno="184" tvg-id="Olympic Channel",Olympic Channel
http://10.0.0.250:5004/MyList/watch/9233008939`
(no idea how to fix the missing line break in the pasted code above it is across 2 lines as normal)

Not sure but maybe this has to do with the single quotes used instead of double quotes? This is only one source having this issue. I check the other three sources and they show logos , etc.

**Comment by markosjal** [comment]
Just confirmed changing all quotes in the playlist to double quotes make IPTV Merge happy but would still call it a bug.

**Comment by matthuisman** [comment]
Yup it'll be single quotes.

**Comment by matthuisman** [comment]
I think the spec for m3u8 states double quotes. I'll see if I can make
merge accept either.

If you our your playlist directly into IPTV Simple client with single
quotes, does it work?

**Comment by matthuisman** [comment]
[0.22.8](https://github.com/matthuisman/slyguy.addons/commit/d7db75067f004a47fa325c0e8323d0eb90d20dd8) now supports ' attributes
