### ISSUE TITLE
HBO max addon - no new items 

### ISSUE THREAD

**Issue by Dohnerd** [matthuisman/slyguy.addons#325]
I've installed the Hbo max addon on my 2 Raspberrys (different tvs), and everything is working fine, except it dosn't add new material, only thing listed is the things that where there at the time of install.

So all new tv shows etc. dosn't show up.

**Comment by matthuisman** [comment]
i dont understand. the addon wont add anything to your library. simply go into the addon and navigate the various menus inside the addon

**Comment by Dohnerd** [comment]
It dosn't add anything, new things just don't show up... like i.e. the show "the winchesters" on the first rasp i installed it on there is 3 episodes, on the second there are 6 episodes (recent install).. but by now there are 7 episodes... and its like that on all the shows ...

**Comment by Dohnerd** [comment]
Hi Matt.... going insane here.... trying to find out where it stores the data... is there a way to clear the cache so it remembers login and settings but clears everything else... I'm not able to find any db or alike....

**Comment by Dohnerd** [comment]
Still nothing on this one?

**Comment by matthuisman** [comment]
please provide full debug log.
not having this issue anywhere else. so suspect your not using the addon is the normal way?
