### ISSUE TITLE
DStv Addon not playing

### ISSUE THREAD

**Issue by dvaai** [matthuisman/slyguy.addons#328]
I have tried to uninstall the Kodi Addon and re-enter the Kodi code. The addon does not want to play DStv

**Comment by dvaai** [comment]
I have also tried to play it via Laptop Kodi and on the cellphone the issue persists

**Comment by SlickoRico** [comment]
I'm faced with the same issue... Did you find a solution yet?

**Comment by dvaai** [comment]
@matthuisman  

I have attached a log file, now I am getting an error "Playback failed check log for more info"

https://www.pastefile.com/3zdbch

Regards

**Comment by SlickoRico** [comment]
I'm getting the exact same error on all of my devices. "playback failed check log for more info" 

Thanks for the reply bro

**Comment by matthuisman** [comment]
fixed with [script.module.slyguy > v0.57.0](https://github.com/matthuisman/slyguy.addons/commit/60d3e992c2e7fa5fd7f1798c671c2518931c7477)

**Comment by SlickoRico** [comment]
Thank you so much sir!!

**Comment by joukie22** [comment]
Does anyone uses iptv tru iptv simple  Client?

**Comment by Prokiidsa** [comment]
> Does anyone uses iptv tru iptv simple  Client?

Yes
