### ISSUE TITLE
Add support for Disney+ 2FA login (email code)

### ISSUE THREAD

**Issue by splashcrum** [matthuisman/slyguy.addons#329]
After succesfully logout and login in the Kodi Disney Addon its occure the Error:
API Request is failed. Server Error: Your Credential are incorrect. Please try it again.

After Login in the Web Browser on the PC a new 2FA Request is appear: 
"Check your email inbox
Please confirm your email address. We have sent a
6-digit code to xxx@xxx.xyz
which will expire in 15 minutes. Please enter this
code below."

Maybe the Addon needs an update to handle this prcedure....

Greetings
Stephan
[20220103_DP_Login_Error.txt](https://github.com/matthuisman/slyguy.addons/files/10340105/20220103_DP_Login_Error.txt)

**Comment by matthuisman** [comment]
Yes it does, but I don't have a login that shows that behaviour yet so can't reverse engineer

**Comment by blueman8** [comment]
Having the same issue with the Disney+ add-on today on a clean install too.

**Comment by matthuisman** [comment]
@splashcrum @blueman8 

I want to add support for 2FA logins like yours.
I require a login that have that behavior's as Disney only enable on some accounts.

Can either of you provide a login temporally for me to use to add support for them?
If yes, see here:
https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by matthuisman** [comment]
[v0.13.4](https://github.com/matthuisman/slyguy.addons/commit/c5ec84efe19dd81501c715cfd87bb41c831584ad) now supports 2FA email code :)
