### ISSUE TITLE
[HBO Max] error opening episode list

### ISSUE THREAD

**Issue by flaocta** [matthuisman/slyguy.addons#33]
I live in Brazil and when I try to see "Greg News with Gregório Duvivier" the addon HBO Max displays an unexpected error message, and in the browser I can see it normally.  I use a raspberry pi 3 with Libreelec. here is my log: https://paste.kodi.tv/kapimimecu.kodi

**Comment by matthuisman** [comment]
does it work on their website or app...
I suspect it isn't actually available

**Comment by flaocta** [comment]
yes, it works normally on the android app and on the website.

**Comment by matthuisman** [comment]
im trying to reproduce. your in Brazil?

**Comment by flaocta** [comment]
yes, I'm in Brazil.

**Comment by matthuisman** [comment]
try v0.3.4 (just pushed)

i can't test as I have no VPN that works into Brazil so it's basically "guess"

**Comment by mmarshall540** [comment]
Was also getting an error with the HBO Max add on. Probably the same, but I'm not certain. After updating the add-on, no more error.

**Comment by matthuisman** [comment]
oh, was that an unexpected error in the corner of kodi?
Or an actual pop-up error in middle?
If it was the 1st, that was a bug in slyguy common that was fixed - not related to above

**Comment by flaocta** [comment]
After the last update the following message appears in the center of the screen: "hbo max - error. API request failed. Server error: we can't find that title right now. Please try again later".

**Comment by matthuisman** [comment]
@flaocta 
please try version 0.3.5

If that doesn't work - then I can't help until I can test properly.
Currently none of my vpn brazil servers work with hbo so dead end

**Comment by matthuisman** [comment]
Closed?
Does that mean fixed or not?

**Comment by flaocta** [comment]
Sorry, I closed it by mistake. The issue has been successfully resolved. Thank you!

**Comment by matthuisman** [comment]
Oh wow. I wasn't expecting it to work :)
That's great. I hate not being able to fix something so was getting quite annoyed I couldn't test it!
