### ISSUE TITLE
Paramount+: Support more languages via api

### ISSUE THREAD

**Issue by GTSFWL** [matthuisman/slyguy.addons#333]
Hallo super Addon, es würde mich freuen wenn in dem Addon die Betriebs Sprache entsprechen einstellen könnte wie die Info über den Inhalt, ich hab mich mal dran gesetzt und eine Übersetzung des "resource.language.de_de" in Deutsch, aber das geht nur für das Menü.
Ich hänge sie gerne dran.
[resource.language.de_de.zip](https://github.com/matthuisman/slyguy.addons/files/10376126/resource.language.de_de.zip)

MFG GTSFWL

**Comment by matthuisman** [comment]
thank you. I have added in your menu translation in latest version.

I will try see if I can have option to set language for the API calls in the near future

**Comment by GTSFWL** [comment]
Hello , thanks for considering this, please that I could help.keep it up, you are doing a good job. MFG GTSFWL Gesendet von Mail für Windows Von: Matt HuismanGesendet: Dienstag, 10. Januar 2023 11:28An: matthuisman/slyguy.addonsCc: GTSFWL; AuthorBetreff: Re: [matthuisman/slyguy.addons] Paramount+ (Issue #333) Reopened #333.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Basti83x** [comment]
Hi. @GTSFWL . Könntest du vielleicht nochmal schauen im menü ist noch einiges in englisch. Könntest du den rest vielleicht noch in deutsch übersetzen?

Mfg

**Comment by Basti83x** [comment]
is actually still being worked on that the film/series names and descriptions are in German?  I've looked through everything and found that a few films even have German descriptions.  

Mfg

**Comment by matthuisman** [comment]
merged in changes by @StollD as above that should now allow some content to be displayed in your paramount+ locale language
