### ISSUE TITLE
HBO Max Dolby Atmos

### ISSUE THREAD

**Issue by pguasta** [matthuisman/slyguy.addons#337]
With the nightly version of Kodi 21 released today (11-01-23), the only issue where Dolby Atmos does not work right is with HBO Max.
The sound sometimes goes mute, and then comes back. When it comes back, it shows the HDR or Dolby Vision logo on my tv.  I think that means that the video is reset as well.

I live in South America and the official app is famous for being very bad. Always output the worse quality possible (720p and stereo sound). Maybe its because of the source or the app.

**Comment by matthuisman** [comment]
this doesnt sound like an issue from the addon sorry. I can't control playback that much. maybe a kodi issue or internet issue
