### ISSUE TITLE
HBO Max returns no results in several words searches

### ISSUE THREAD

**Issue by xaviron** [matthuisman/slyguy.addons#339]
Hey great job! I'm using both Disney anda HBO Max addons anda they work perfect!! Congrats!
Although, I've found an issue when searching in HBO Max with several words... 
But, if you change the blank spaces for /b it does the job perfectly, maybe there is the clue.

Thank you so much!

P.d.: in Disney it works fine even with the blanks spaces

**Comment by matthuisman** [comment]
thanks. hbo search with spaces fixed in [v0.10.2](https://github.com/matthuisman/slyguy.addons/commit/11b9e5ff74b28060ab7956979d0d8e6986f22369)
