### ISSUE TITLE
Stan Playback error

### ISSUE THREAD

**Issue by Bjr86** [matthuisman/slyguy.addons#341]
Since slyguy common was updated stan no longer works, i noticed the change you made earlier today fixed foxtel/binge/paramount addons but stan still getting playback error.
Below is the screenshot of the error popping up in the log. Hopefully thats enough info for you.

Thanks again for all your efforts!!!

![image](https://user-images.githubusercontent.com/122590073/212243368-2bb20d4c-6e99-4995-a582-904fa0391c57.png)

**Comment by matthuisman** [comment]
Go into slyguy common settings > playback and enable h265.

See if that helps

**Comment by Bjr86** [comment]
it did, thanks very much.

All working now

**Comment by matthuisman** [comment]
I'll leave this open as I'm sure they have h264 streams so something going on. Also my code shouldn't error if no options but instead do something else. Haha

**Comment by Bjr86** [comment]
hahah oh k mate, no worries.

Thanks again.

**Comment by matthuisman** [comment]
fixed the root issue on latest slyguy common. thanks for bringing to my attention
