### ISSUE TITLE
Turning off HDR/DV in HBO MAX

### ISSUE THREAD

**Issue by volme** [matthuisman/slyguy.addons#342]
Hello!
Any way to turn off HDR/DV but still getting 4K resolution in HBO MAX?

**Comment by matthuisman** [comment]
Yes. in the addon settings. 

Enable 4K
Enable H265
Disable Dolby Vision

On House of the Dragon, I then have 4k H265 streams

**Comment by volme** [comment]
I changed some options about Playback quality from "ask" to "bypass" then again to "ask" etc and now i can see 4k stream but still have hdr activated. Just no way to choose SDR.

**Comment by matthuisman** [comment]
What content are you trying?

**Comment by volme** [comment]
Game of Thrones, House of the Dragon or The Batman (2022). I guess it would be like this in any content available in 4k. 
For example in Netflix addon next to option "Disable Dolby Vision" i have option to disable HDR too "Disable HDR" or sth like this  and there it works. I use Android TV Kodi v19.3 if its important.

**Comment by matthuisman** [comment]
When you select the quality, does it say it has HDR or not?

**Comment by volme** [comment]
I have like "28,94 Mbit/s 3840x2160 23.98 FPS H265" and tv detect HDR signal automatically. If i disable HDR in tv setting it looks like playing HDR mkv movie at SDR display without tonemaping so it isn't a point in this case.

**Comment by matthuisman** [comment]
Oh right. I didn't think those had hdr as I didn't detect it in the signal and works fine on my non-hdr monitor.  

Let me have more of a look.

**Comment by volme** [comment]
I guess the same "problem" could be in Disney+ add-on where there are options like "4k/hdr" and "Dolby vision". But I've never used that Disney+ add-on before and i don't have Disney+ account anyway, just checked options.

**Comment by matthuisman** [comment]
Disney I know only have 4k in hdr

**Comment by matthuisman** [comment]
Have you done any research to see if HBO even supports what your asking?
Does the official app let you do 4k without hdr?

**Comment by volme** [comment]
In official apps they don't let change anything about quality. Everything is adjusting into internet speed quality and display device. So I was hoping for that possibility via add-on in kodi app as i have that possibility f.e in Netflix add-on from other repository.

**Comment by matthuisman** [comment]
So your TV is hdr? But you don't want to display in hdr?

**Comment by volme** [comment]
Exactly

**Comment by matthuisman** [comment]
if you select the lowest quality H265 stream, does that have HDR as well?

HBO seem to use a single container for the H265 which seems it must include HDR as well.
however, it looks fine for me.
So I think it (kodi) must detect if HDR compatible and then enable it in the stream

**Comment by volme** [comment]
For every resolutions up to 1080p i can choose SDR, HDR and also DV. On the list it looks like:

3 Mbit/s 416x234 23.98 FPS H265 
3 Mbit/s 416x234 23.98 FPS H265
3 Mbit/s 416x234 23.98 FPS H265 Dolby Vision.

These two called same but one is SDR, second is HDR. On that list i have more streams to choose but different is only in bitrate value and others are h264.

Unfortunately for resolutions higher than 1080p like 2k, 4k etc i got only 2 streams on the list and they are only HDR and DV.
28,94 Mbit/s 3840x2160 23.98 FPS H265 (this one have HDR)
28,94 Mbit/s 3840x2160 23.98 FPS H265 Dolby Vision

**Comment by matthuisman** [comment]
so i managed to be able to detect HDR streams in their manifest. only hint was codec : hvc1.2.x vs hvc1.1.x
this lets it mark these streams as HDR and there is now a setting to disable HDR to put them at the bottom.

this still doesnt help with your issue, but at least now they can be removed.

as far as I can tell, just like Disney+ - they dont return any 4k streams without HDR.
ill keep an eye out though

**Comment by volme** [comment]
Still better than official app.
