### ISSUE TITLE
No longer able to Play Paramount+ live streams by Way of IPTV Merge/IPTV Simple Player

### ISSUE THREAD

**Issue by markosjal** [matthuisman/slyguy.addons#343]
Suddenly I can no longer play Paramount + live streams that I have always used in IPTV Merge and IPTV Simple player. I also see that my most recently updated addon is "SlyGuy Common (0.57.3)" , so I believe it to be suspect. I am unable to see an older version to roll back to or I would try that.

**Comment by matthuisman** [comment]
please always provide debug logs when opening issues.
should be fixed now with [v0.57.5](https://github.com/matthuisman/slyguy.addons/commit/88d6cc33ba74ea6268619609faf05395c56cfa28)

**Comment by markosjal** [comment]
might be nice to leave the old version when updating so we can roll back when it goes bd. Thanks a bunch

**Comment by matthuisman** [comment]
nope as that will break a bunch of other stuff and stops future auto updates.

It has literally been broken for about an hour or two.
Pretty good uptime for a free hobby

**Comment by markosjal** [comment]
yep pretty fast I must say , thanks again

**Comment by matthuisman** [comment]
yeh, as soon as someone pins an old version - it stops updating.
Then it wastes hours and hours in the future when X addon stops working due to running old common.

Best everyone runs latest and issues just get fixed quickly :)

**Comment by markosjal** [comment]
I wanted to address the issue of debug logs.... You need to understand that
in many cases like mine debug logs can contain very private information
such as passwords . I have passwords for things like public SFTP servers
and ftp servers. Sometimes relying on sanitizing a log is not 100% and i
think your expectation of a full log is pretty presumptuous. I have no
desire to share my private passwords publicly and your users need to be
educated to that danger here rather than hearing that they should share all
of their personal information by default.

**Comment by matthuisman** [comment]
what are you talking about? i didnt even ask you for a log.

Your just trolling now so i will be blocking you.
I'm not wasting more of my time trying to go back and forth with a user getting the info I need (os, kodi version, what version of addons installed etc). 

If they have configured such services with passwords, then its on them to sanitise.
Im not a content moderator. Im a busy dev who cbf with fluffing about.

**Comment by stevehartwell** [comment]
@matthuisman [last comment](https://github.com/matthuisman/slyguy.addons/issues/343#issuecomment-1384565207)
> what are you talking about? i didnt even ask you for a log.

@matthuisman [first comment](https://github.com/matthuisman/slyguy.addons/issues/343#issuecomment-1383063577)
> please always provide debug logs when opening issues.
