### ISSUE TITLE
Feature Suggestion for Plex addon , use Favourites for IPTV Merge

### ISSUE THREAD

**Issue by markosjal** [matthuisman/slyguy.addons#344]
Just wanted to make a feature suggestion for Plex addon.

As I think it would be nice to add a few channels from Plex into my IPTV Merge, but not the whole Plex  list, maybe it would be possible to add only the Favorites in Plex to IPTV Merge? Plex unlike some of the other SlyGuy addons does not have "My Channels" which can be used in a merge, so the alternative would be to add something like "my Channels" 

It seems at present you add ALL Plex channels or  none.

**Comment by matthuisman** [comment]
add my channels to plex in [v0.0.9](https://github.com/matthuisman/slyguy.addons/commit/a4d11ecab780f6316c03dd81d2c68548a234d54b)
