### ISSUE TITLE
Star+ content does not play.

### ISSUE THREAD

**Issue by flaocta** [matthuisman/slyguy.addons#345]
Hi!
I use Libreelec 9.2.8 and the Star+ addon has problems with content playback. I click on some link, the gear appears (as if it were going to load) and nothing plays. Sometimes I can even play with just one click, but most of the time I have to click multiple times before I can watch something. Finally, the Brazilian Portuguese subtitles are gone. Here is the log: https://paste.kodi.tv/ovupaxitoj.kodi. I appreciate the help and congratulations on the work!

**Comment by matthuisman** [comment]
can you please re-upload a new log if this is still an issue?
