### ISSUE TITLE
Disney+  0.13.4 - can't log in - unexpected error 

### ISSUE THREAD

**Issue by dragonlexus** [matthuisman/slyguy.addons#349]
Hello. I reinstalled Kodi 19.5 from scratch but after installing the Disney plus addon, after I enter the password it shows an unexpected error _ I have attached image.Previously, a few months ago when I first installed the Disney Plus addon, I did not have this problem. Now I have the addon Disney Plus version 0.13..4. error is: error: module resource.lib.queries has no atribute LOGIN,  followed by details.

Can you check please? 

PS: Thank you very much for all your work sir, your addons are amazing!

![IMG_20230120_184116](https://user-images.githubusercontent.com/122963894/213756540-e07dcf1d-c684-49b0-a8f1-cc900c59527f.jpg)

**Comment by matthuisman** [comment]
oops. i have fixed now in [v0.13.5](https://github.com/matthuisman/slyguy.addons/commit/6fd2a5af6d7ccd9dd54f7a07e05b1630b45e33c4)

**Comment by dragonlexus** [comment]
Thank You! you answered and solved amazingly fast!
