### ISSUE TITLE
DirectvGo Brazil/Latin America

### ISSUE THREAD

**Issue by Rferreira2k** [matthuisman/slyguy.addons#351]
Hi!

Would it be possible to create an addon for the directGo Brazil service? DirectvGO is a linear pay channels service. I use several of your addons that work perfectly in my country, having a DirectvGo addon with 3rd provider access wold be great.

Playstore DirectvGO apk:  https://play.google.com/store/apps/details?id=com.directv.dtvlatambr&hl=pt_BR&gl=US&pli=1

sorry for the bad english :)

Thanks a lot!

**Comment by matthuisman** [comment]
Your best to request addons below 
https://forum.kodi.tv/forumdisplay.php?fid=251
