### ISSUE TITLE
DSTV Now/South Africa 

### ISSUE THREAD

**Issue by dvaai** [matthuisman/slyguy.addons#354]
![20230128_010830.jpg](https://user-images.githubusercontent.com/37695923/215250590-7b9761b4-eb7a-4b53-be60-405ba94cc07d.jpg)

After updating to slyguy.uk, I login, I watch TV for 2 minutes, the addon keeps asking me to  logout and back in.

**Comment by matthuisman** [comment]
You'll need to have a chat to dstv and ask why the password is getting blocked

**Comment by Kallie2312** [comment]
Any updates on DSTV now app.... I see theres a message saying its broken.
