### ISSUE TITLE
Failed to fetch JSON data  on kodi dstv now

### ISSUE THREAD

**Issue by SparksPlug-max** [matthuisman/slyguy.addons#357]
Hi does anyone have the same error as mine.Originated today the 30th January 2023

Error : Failed to fetch JSON data
           Make sure your IP address is allowed(not geo-blocked).Try accessing the content 
           through other means(Official app/website) to test if it's a kodi add-on issue.

Please help!!!

**Comment by wynand1982** [comment]
I have the same problem, the normal DSTV app works perfectly, please let me know how I can fix this

**Comment by gonein60sec** [comment]
I also get the same message. Let me know if there was a fix found.

**Comment by SparksPlug-max** [comment]
@wynand1982  yip dstv app works fine.When did you guys issue start?

**Comment by wynand1982** [comment]
@SparksPlug-max  switched on kodi when I got back from work, was still working this morning before I left for work

**Comment by SparksPlug-max** [comment]
@gonein60sec same here.So I guess we just wait for Matt to reply

**Comment by SparksPlug-max** [comment]
> @SparksPlug-max switched on kodi when I got back from work, was still working this morning before I left for work

Same here

**Comment by wynand1982** [comment]
Im sure matt will have the answer to our Kodi/DSTB demon

**Comment by SparksPlug-max** [comment]
@wynand1982 I hope so because I'm only running kodi 🤣

**Comment by matthuisman** [comment]
Duplicate issue

**Comment by SparksPlug-max** [comment]
@matthuisman How can we fix this or can you direct us to link to do so please.

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/355#issuecomment-1409079703
