### ISSUE TITLE
Dstv Now 

### ISSUE THREAD

**Issue by Munech** [matthuisman/slyguy.addons#358]
Hey Matthuis, from today, a large number of us in Africa have been facing an issue with the Failed to fetch Json data. Make sure your IP address is allowed (not geo - blocked) Try accessing the content via other means (official app/website) and to test if it's a Kodi add-on issue. Hope you can help @matthuisman

**Comment by matthuisman** [comment]
Please look for existing issue before opening.  This is the 5th one about the same thing. It's really annoying
