### ISSUE TITLE
Disney+ - Not all subtitles and audio languages available on plugin

### ISSUE THREAD

**Issue by DVDdisk7** [matthuisman/slyguy.addons#36]
The plugin miss sometimes some of the languages for subtitle or audio stream. Those are on disney+ app en web but not in the kodi plugin

**Comment by matthuisman** [comment]
Your on Kodi 18 I assume?
If so, that's a limitation of Kodi 18.
Either update to 19 or use the subtitle and audio whitelist setting in the
addon settings

**Comment by DVDdisk7** [comment]
Thank you. I am indeed on kodi 18.

**Comment by matthuisman** [comment]
Your on Kodi 18 I assume?
If so, that's a limitation of Kodi 18.

Basically, Kodi 18 can only handle X amount of streams (video / audio / subtitle)
So it's essentially skipping a bunch of subs / audio from the Disney+ manifest.

Fix is to either Upgrade to Kodi 19 or

Go into the **Disney+ > Settings > Playback** 
Now you can limit the streams the add-on sends to Kodi by changing the various settings
  

- Audio Allow List
Comma separated list of ISO 639-1 audio languages to keep  eg. en,de,fr (empty = all)

- Subtitle Allow List: 
- Comma separated list of ISO 639-1 subtitle languages to keep eg. en,de,fr (empty = all)
- 
- Include Forced Subs:
- When enabled, forced sub tracks are included
- 
- Include Non-Forced Subs: 
- When enabled, non-forced sub tracks are included
- 
- Include Audio Description Tracks: 
- When enabled, audio description audio tracks are included
