### ISSUE TITLE
Samsung TV Plus Addon: Channel DAZN FAST+ cannot be played

### ISSUE THREAD

**Issue by werimail** [matthuisman/slyguy.addons#360]
Hi @matthuisman in Samsung TV Plus Addon the channel DAZN FAST+ from the German channel list cannot be played with Kodi. Greetings Weri
[kodi_samsung.log](https://github.com/matthuisman/slyguy.addons/files/10546976/kodi_samsung.log)

**Comment by matthuisman** [comment]
looks like some of the channels are going DRM with a short 10min token, so won't be able to work with the current system.

I have updated the code to ignore these such channels.
They will therefore be removed shortly
