### ISSUE TITLE
Dstv now playback failed

### ISSUE THREAD

**Issue by Warricker** [matthuisman/slyguy.addons#361]
It gives me a playback failed on different devices

**Comment by Prokiidsa** [comment]
> It gives me a playback failed on different devices 

Same here

**Comment by D6932999** [comment]
any advice on what to do

**Comment by cgfrans** [comment]
Same playback error. Dstv

**Comment by D6932999** [comment]
@matthuisman  do you have any advice what could cause this playback error perhaps? thank you in advance and much appreciated

**Comment by Ston3br3ak3r** [comment]
everything seems to be fine now again, its working
not sure whats happened please confirm

**Comment by matthuisman** [comment]
There was a new update to the addon. Not sure how long it'll last though

**Comment by tinuva** [comment]
> There was a new update to the addon. Not sure how long it'll last though

I hope I am wrong, but possibly tomorrow when they back at work at Multichoice

**Comment by matthuisman** [comment]
closed this issue in favor of the existing issue here:
https://github.com/matthuisman/slyguy.addons/issues/355

**Comment by Warricker** [comment]
Good day Matt.

I hope you are well.

Dstv now is giving me an unexpected error as attached.
I did download the latest version.
Please advise what I can do on my side to get this working

Kind regards
Jaun Warricker
0713332684
