### ISSUE TITLE
Dstv still giving playback error

### ISSUE THREAD

**Issue by Clintk2023** [matthuisman/slyguy.addons#362]
After last night seeing the comments I tried it and it worked but this morning it was off again

**Comment by joeycpt** [comment]
yeah for me to], latest versions of kodi and slyguy addon

**Comment by D6932999** [comment]
lol kodi is now like eskom  , never had so much issues with this app. what is going on

**Comment by Rockfordgun** [comment]
Im having the same issue.
reinstalled widevine.
Also tried different versions.
select a channel it will ask the quality then just dissapear

**Comment by Ston3br3ak3r** [comment]
hi Matt mentioned last night that there is another is and that he and Jeremy will see if they can find a long lasting fix so its going to take time unfortunately at this point it seems multichoice is the main problem
