### ISSUE TITLE
Optus sport live channel wont play in Nexus

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#364]
Optus sport live channel wont play in Nexus however still plays fine in 19.5, testing on Amazon Fire Tv

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/10570600/kodi.log)

**Comment by matthuisman** [comment]
just pushed an update to add a setting "use cmaf for playback (nexus)" under playback. please disable that and itll use the hacky 19.5 method
