### ISSUE TITLE
DSTV NOW DOWN

### ISSUE THREAD

**Issue by DrMambokadzi** [matthuisman/slyguy.addons#366]
"One or more items failed to play. Check the for more information about this log" Please assist

**Comment by Stefanver1** [comment]
![Capture](https://user-images.githubusercontent.com/124024559/216395640-300a0b81-efbc-44b0-9cbc-03ccff8b33f8.JPG)

**Comment by matthuisman** [comment]
There is an existing issue!!! Please look before opening
