### ISSUE TITLE
DSTV Now Not playing

### ISSUE THREAD

**Issue by dreyerc6554** [matthuisman/slyguy.addons#368]
For the past 3 days, I can't get DSTV now to play. I have updated everything even reinstall but the problem remains. When selecting a ch and pressing play, it shows the ch in the top right corner, gives me the option to select a stream from the list, and when selected it for a moment at the top just flashes the time.
Any suggestions I can try to resolve the issue.

**Comment by matthuisman** [comment]
please see the existing issue. Getting quite sick of people opening duplicate tickets. The other issue is even stickied for goodness sake

**Comment by D6932999** [comment]
guys please give @matthuisman time to resolve this issue , he knows there is a problem and he is trying to sort it out. everything takes time and can't be done ASAP we will get it done when he has some time on hand. @matthuisman thank u for all your service's and keep well
