### ISSUE TITLE
Dstv

### ISSUE THREAD

**Issue by RiaanTh** [matthuisman/slyguy.addons#370]
My dstv is still making new issues.. will attached picture
![IMG-20230203-WA0014](https://user-images.githubusercontent.com/124387624/216666186-e102b13f-9651-4aed-9511-f786e67d94bb.jpeg)

**Comment by RiaanTh** [comment]
I have done all the previous updates.. even uninstall kodi and reinstalled it and redit all the repo

**Comment by matthuisman** [comment]
Stop making new issues. There is an existing issue. From now on,  every new issue created will delay a fix by 24 hours
