### ISSUE TITLE
How to activate addons

### ISSUE THREAD

**Issue by Rob11122** [matthuisman/slyguy.addons#371]
Hey new to this Kodi, I have added the add-ons but when trying to activate them It gives me a TV provider sign in then a code? What do I have to do here I have been to the website then add the code it asks me for a password then can't get past that part. 

Thanks for your help

**Comment by Rob11122** [comment]
![Screenshot_20230204_012441_Kodi](https://user-images.githubusercontent.com/124388071/216667569-2ccf4a98-cba7-4077-ab82-b5deb2fa2863.jpg)

**Comment by matthuisman** [comment]
You need a subscription..... it's not free
