### ISSUE TITLE
Dstv now error

### ISSUE THREAD

**Issue by Stefanver1** [matthuisman/slyguy.addons#372]
Hi Everyone, any one else get this error co
![image](https://user-images.githubusercontent.com/124024559/216677676-46d1594d-3bb3-4b77-9875-2f1c89dae2a7.png)
de?

**Comment by matthuisman** [comment]
Stop making new issues. There is an existing issue. every new issue created will delay a fix by 24 hours
So congrats. You've delayed a fix by 24 hours
