### ISSUE TITLE
DSTV now on Kodi  0.16.7 error ? Pls assist+24

### ISSUE THREAD

**Issue by GustavEat** [matthuisman/slyguy.addons#375]
+24

_Originally posted by @matthuisman in https://github.com/matthuisman/slyguy.addons/issues/374#issuecomment-1417023396_

**Comment by Gerrit405** [comment]
I also have the same problem, were you able to fix it?

**Comment by Hein051627** [comment]
Hi Matt,  I can see these guys joined today I think they don't know how the issue system works. They probably joined after searching the net for answers because of the Dstv add-on not working as normal.

**Comment by matthuisman** [comment]
There is an existing issue
