### ISSUE TITLE
How to use IPTV Simple + IPTV Merge with another PVR ?

### ISSUE THREAD

**Issue by siliconhippy** [matthuisman/slyguy.addons#378]
This relates to Issue #347 that I tried to close...
-----
(Also posted this in the Kodi Arctic Zephyr-Reloaded forums, #5277
https://forum.kodi.tv/showthread.php?tid=337862&page=352
)

I am on AZR Nexus and the menus set up are working fine, with Live TV menu handled by TVLink PVR on my PC x86 11.1.0 https://alexelec.tv/ distro, a fork of CoreElec.

I just also installed a second PVR, Simple IPTV (the default one.) Both PVRs show in my installed repo list and are enabled.

So now how do I select the PVR Simple to show in a menu ? I have used the Matt Huisman IPTV Merge addon to merge channels and EPG from Plex Live (another Matt Huisman video addon) and channels from the SONY Crackle video addon. Apparently things went fine, and there were no errors...

When I go to Live TV, it only shows a single list of sub menus (Live Channels, Last Played, etc.), and from what I assume, this Live TV menu is tied to my first PVR, TVLink.

In the default Estuary menu, it is the same situation: only TVLink PVR channels and info are displayed under the TV menu to the left. 

So how are people using multiple PVRs?

**Comment by matthuisman** [comment]
i am not sure sorry. best to ask on kodi forums which i see you have done
