### ISSUE TITLE
DSTV NOW not working after update

### ISSUE THREAD

**Issue by nightcrawlerfemi** [matthuisman/slyguy.addons#380]
The dstv now work briefly after the update but soon started showing these errors.I waited a couple days to see if it would rectify itself but it didn't. 
Please assist 
![IMG_20230207_105028](https://user-images.githubusercontent.com/73402337/217212959-8ea45486-35b7-4aeb-a630-74a7e3e0c869.jpg)
![IMG_20230207_105009](https://user-images.githubusercontent.com/73402337/217213129-9c6581c3-be9b-4fae-87b1-5d4903dc7d01.jpg)

**Comment by Ston3br3ak3r** [comment]
oh dam another 24 :(
