### ISSUE TITLE
Is SONY Crackle addon supported by IPTV Merge?

### ISSUE THREAD

**Issue by siliconhippy** [matthuisman/slyguy.addons#382]
From here:
https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html

I got supported addons list:
https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons

This doesn't include Crackle, or Plex Live either !

Question: So is SONY Crackle supported, or any plans ?

I tried IPTV Merge with Plex Live and plugin.crackle... but merging results in an empty playlist. However Plex Live merge operation alone is successful, with playlist and epg.

**Comment by matthuisman** [comment]
you'd need to ask the Crackle developer to add support for either IPTV Merge or IPTV Manager.

As for Plex Live, if it shows when adding an Addon source, then it is supported.
Thats my add-on so I support it.

I have no idea how you tried to add crackle manually - you can't do that.
If it doesn't show under Source > Add > Addons - then its not supported and the dev of the addon needs to add support
