### ISSUE TITLE
New Issue- Object is not subscript able

### ISSUE THREAD

**Issue by itsdee22** [matthuisman/slyguy.addons#383]
Hi Matt.

I appreciate what you are doing.  Kindly see attached image. I have done the updated method you have suggested previously , about the data.  I would appreciate any help to resolve this issue.
@matthuisman 

![IMG20230208081724](https://user-images.githubusercontent.com/124763360/217450713-744233f2-1b3d-4fd2-87f5-4cbdb81f665b.jpg)

**Comment by matthuisman** [comment]
There already an existing issue!
