### ISSUE TITLE
Stan Not Working in Kodi 20 (Nexus)

### ISSUE THREAD

**Issue by Ty9866** [matthuisman/slyguy.addons#385]
I can log into Stan, however I can't play any video content.  This issue started with Nexus.  Stan worked great on Matrix19.

![image](https://user-images.githubusercontent.com/124845993/217686600-1aea0f0f-e08f-4b2c-b6d9-4096197c3a2d.png)
![Uploading image.png…]()

Thanks for your hel0 Matt

**Comment by matthuisman** [comment]
32bit Android device I suspect?

**Comment by Ty9866** [comment]
Yes, most of my android devices are 32 bit.  However, I get the same error on my 64 bit android device.  Other SlyGuy addons work fine.  I appreciate any help that you can provide.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Huisman ***@***.***> Datum: 08.02.23  16:58  (GMT-08:00) An: "matthuisman/slyguy.addons" ***@***.***> Cc: Ty9866 ***@***.***>, Author ***@***.***> Betreff: Re: [matthuisman/slyguy.addons] Stan Not Working (Issue #385) 
32bit Android device I suspect?

**Comment by Ty9866** [comment]
![image](https://user-images.githubusercontent.com/124845993/217711677-304c9d0e-b600-4372-827f-fce73c259453.png)
T

**Comment by matthuisman** [comment]
could you check your running latest inputstream adaptive addon ([v20.3.3 (2023-02-08)](https://github.com/xbmc/inputstream.adaptive/commit/a5d1987544b6b9fc204830d20f54cb015b100b5c))

**Comment by Ty9866** [comment]
Yes, that is the correct inputstream adaptive addon version running.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Huisman ***@***.***> Datum: 08.02.23  19:43  (GMT-08:00) An: "matthuisman/slyguy.addons" ***@***.***> Cc: Ty9866 ***@***.***>, Author ***@***.***> Betreff: Re: [matthuisman/slyguy.addons] Stan Not Working (Issue #385) 
could you check your running latest inputstream adaptive addon (v20.3.3 (2023-02-08))

**Comment by matthuisman** [comment]
try setting "attempt to not use secure decoder" setting in the Inputstream Adaptive settings and see if that helps

**Comment by matthuisman** [comment]
also, please provide a full debug kodi log

**Comment by Ty9866** [comment]
Hey Matt,I apologize that it took so long to get this to you.  I'm a new to Kodi user, so still figuring stuff out.  Below is the hastebin link of my complete log/debugging log:https://paste.kodi.tv/anotekavupHopefully, I've done this correctly.  I truly appreciate your assistance!!TylerVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Huisman ***@***.***> Datum: 08.02.23  23:10  (GMT-08:00) An: "matthuisman/slyguy.addons" ***@***.***> Cc: Ty9866 ***@***.***>, Author ***@***.***> Betreff: Re: [matthuisman/slyguy.addons] Stan Not Working (Issue #385) 
also, please provide a full debug kodi log

**Comment by Ty9866** [comment]
Link:  https://paste.kodi.tv/anotekavup

**Comment by Ty9866** [comment]
I did try changing the setting "attempt to not use secure decoder" in the Inputstream Adaptive settings.  Unfortunately, it didn't work.  I really do appreciate your assistance.  By the way, I have no issues watching Stan through the app itself and all other NZ & AU Kodi addons work flawlessly. Thank you Matt.

**Comment by matthuisman** [comment]
are you able to go back to 19.5 and see if it then works?
I suspect it will and this is a bug in Kodi 20 or newer Inputstream Adaptive

**Comment by Ty9866** [comment]
Hey Matt - I did what you suggested and your hunch was correct.  Stan works flawlessly on 19.5.  Well, at least we know it's definitely a bug in Kodi 20 and is just a temporary issue.  At least, I can use the actual Stan app until the bug gets fixed.  Thanks for all of your help!!!Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Huisman ***@***.***> Datum: 12.02.23  12:09  (GMT-08:00) An: "matthuisman/slyguy.addons" ***@***.***> Cc: Ty9866 ***@***.***>, Author ***@***.***> Betreff: Re: [matthuisman/slyguy.addons] Stan Not Working (Issue #385) 
are you able to go back to 19.5 and see if it then works?
I suspect it will and this is a bug in Kodi 20 or newer Inputstream Adaptive

**Comment by Ty9866** [comment]
Hi Matt, That didn't work either, but it was worth a try. Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matt Huisman ***@***.***> Datum: 15.02.23  02:20  (GMT-08:00) An: "matthuisman/slyguy.addons" ***@***.***> Cc: Ty9866 ***@***.***>, Author ***@***.***> Betreff: Re: [matthuisman/slyguy.addons] Stan Not Working in Kodi 20 (Nexus) (Issue #385) 
does playback work if you disable H265 in the add-on settings?

**Comment by glennguy** [comment]
@Ty9866 any chance you could provide a debug log from stan in Kodi 19.5 where it's working?

**Comment by glennguy** [comment]
Alternatively, for Kodi 20 could you try installing the appropriate inputstream.adaptive zip from here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1149/1/artifacts

**Comment by Ty9866** [comment]
Yes, I will have to re-install matrix 19.5 again on one of my devices as it keeps updating automatically to nexus within a day or two.  It's not a problem to reinstall and send you the Stan debugging log.TylerVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Glenn Guy ***@***.***> Datum: 18.02.23  23:47  (GMT-08:00) An: "matthuisman/slyguy.addons" ***@***.***> Cc: Ty9866 ***@***.***>, Mention ***@***.***> Betreff: Re: [matthuisman/slyguy.addons] Stan Not Working in Kodi 20 (Nexus) (Issue #385) 
@Ty9866 any chance you could provide a debug log from stan in Kodi 19.5 where it's working?

**Comment by glennguy** [comment]
inputstream adaptive pull request for reference -https://github.com/xbmc/inputstream.adaptive/pull/1149

**Comment by matthuisman** [comment]
@Ty9866 stan addon [v0.3.9](https://github.com/matthuisman/slyguy.addons/commit/219499fef1945c67cb19c2c300c20261790f9734) should fix playback on Kodi 20 32bit Android.

Its not a root fix, but it works around the issue :)
ill close this ticket and open a new one on IA for the core issue
