### ISSUE TITLE
DStv now error 

### ISSUE THREAD

**Issue by Gersh91** [matthuisman/slyguy.addons#386]
Anyone tell us how to fix this or if it's gonna be fixed. 
![Screenshot_20230209_110103](https://user-images.githubusercontent.com/124876320/217774536-54d8511d-f63f-4d94-9e87-6523cac91412.jpg)

**Comment by Ston3br3ak3r** [comment]
there is already an Issue posted please check open issues first now we have to wait another 24 hours as Matt has had it already
