### ISSUE TITLE
IPTV merge: allow adding search results as favorite

### ISSUE THREAD

**Issue by DanielArrhenius** [matthuisman/slyguy.addons#388]

**Comment by DanielArrhenius** [comment]
Change default action to play when added to favorites

**Comment by matthuisman** [comment]
[v0.23.6](https://github.com/matthuisman/slyguy.addons/commit/dec68bb0ff73adae0860603e7b3164d9cc74dbcd) now has default action of play so you can add to favorites

**Comment by DanielArrhenius** [comment]
Great! Thx
