### ISSUE TITLE
not an issue, just a question 

### ISSUE THREAD

**Issue by D6932999** [matthuisman/slyguy.addons#390]
hi @matthuisman i know dstvnow has a problem , just want to know how many 24hrs is remaining I've lost track. can u please let me know when u will have time to check, and I'm doing this question with respect not anything else since i know u are busy and has alot on the plate . thank u for any feed back and keep well

**Comment by matthuisman** [comment]
that 24hrs thing was just a joke / deterrent. I'm not delaying anything on purpose.
I just don't have time at present. 
Hopefully over the next week.

Be prepared for single stream in the addon as well
