### ISSUE TITLE
After logging out and logging back in this is what it shows:

### ISSUE THREAD

**Issue by petir17** [matthuisman/slyguy.addons#393]
After logging out and logging back in this is what it shows:

![image](https://user-images.githubusercontent.com/37695923/215513017-9d0addc3-98a5-4882-8639-ab368441cf40.png)

_Originally posted by @dvaai in https://github.com/matthuisman/slyguy.addons/issues/355#issuecomment-1408782895_

**Comment by petir17** [comment]
Unexpected error dstv now 16.7? What's going on?

**Comment by Hein051627** [comment]
There is an existing issue #355

**Comment by petir17** [comment]
But there is no feedback???

**Comment by Hein051627** [comment]
any updates on the issue will be posted here #355 **** it's now a time for **patience**
