### ISSUE TITLE
Star+ no subtitles

### ISSUE THREAD

**Issue by pguasta** [matthuisman/slyguy.addons#397]
Hello,

Using the last couple of nightly versions of Kodi, Star+ add-on does not show subtitles. I tried X-Files and MotoGP Unlimited (I am in the Latin American zone). The current version I am using is: kodi-20230115-eccb6e85-master-27892-armeabi-v7a

(I am aware that using Nightly version will have a lot of bugs, so this post is more to announce that there is an issue).

Kind regards

**Comment by matthuisman** [comment]
Suspect issue in inputstream adaptive

**Comment by matthuisman** [comment]
did you test with Kodi 19 or 20?
Suspect this was a mast issue?
