### ISSUE TITLE
Change this and... Never Gonna Give You Up... Haha...

### ISSUE THREAD

**Issue by Raspifan2020** [matthuisman/slyguy.addons#4]
Haha....

Der Typ ist echt so dumm, schadet nur allen Usern, die sein Addon nutzen und die Listen von Free-IPTV!

                if 'free-iptv' in line.lower():
                    free_iptv = True
                    free_iptv = MattHuisman_IDIOT

**Comment by matthuisman** [comment]
that would cause an error - try it yourself :)
