### ISSUE TITLE
New IpTV Merge setup itv simple client feature works correctly but disables itv simple client

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#400]
the new itv simple client setup feature in iptv merge successfully setup itv simple client however it also disabled the itv simple client add-on

**Comment by matthuisman** [comment]
fixed in [v0.23.5](https://github.com/matthuisman/slyguy.addons/commit/20a37c1f0ba14202ff088940e8c6ea9cb0e4aa8a)
