### ISSUE TITLE
Kayo freezing

### ISSUE THREAD

**Issue by Carty89** [matthuisman/slyguy.addons#402]
Gday mate just thought I’d let you know Kayo is now freezing 

Cheers mate

**Comment by matthuisman** [comment]
Full Kodi debug log please

**Comment by Carty89** [comment]
Yep no worries mate how do I do that?

**Comment by matthuisman** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by Carty89** [comment]
![image](https://user-images.githubusercontent.com/125644192/219939645-cac0a77f-2496-4e36-9dc0-2bb9f2f8ad7d.jpg)

**Comment by Carty89** [comment]
I’m using Kodi through firestick mate do those instructions work for that aswell?

**Comment by Carty89** [comment]
Gday mate.

I will try again when I get home mate . I appreciate it Matt 🍻

**Comment by matthuisman** [comment]
moving this to an existing issue:
https://github.com/matthuisman/slyguy.addons/issues/63

**Comment by Carty89** [comment]
Updated kayo version and working all weekend mate 

cheers

**Comment by Carty89** [comment]
Gday mate kayo keeps freezing again 

cheers

**Comment by matthuisman** [comment]
nothing has changed. it'll be your internet or device. nothing i can do sorry
