### ISSUE TITLE
SBS on demand and abc iview and ctv plus

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#404]
Is it possible for you to make addons for these services with iptv merge support

**Comment by matthuisman** [comment]
no plans to support these sorry

**Comment by liam8888999** [comment]
Is there a reason behind this or just not enough interest/too much work. Thanks for all the great addons you do anyway

**Comment by matthuisman** [comment]
both your reasons. you could ask the devs who make those to add support for either IPTV Manager or IPTV Merge (merge supports both)
