### ISSUE TITLE
Disney Addon Api Error

### ISSUE THREAD

**Issue by Digger7169** [matthuisman/slyguy.addons#407]
Hi 
I am getting API request failed Server Error: invalid Token, Any help would be appreciated thanks

**Comment by matthuisman** [comment]
Please provide full Kodi debug log

**Comment by camokarzi** [comment]
FYI I have no issues with Disney, just check. App is working perfectly. Check your account login details.

**Comment by matthuisman** [comment]
closing as no other reports.

@Digger7169 simply logout and login again.
