### ISSUE TITLE
Error watching 4k videos on hbo max and disney+ addons on my samsung phone

### ISSUE THREAD

**Issue by edersonmax21** [matthuisman/slyguy.addons#408]
Good morning, I would like to report two errors that have been happening to me on my Samsung cell phone, I have an S10+ that accepts content in 4k and hdr, the problem is that when watching content in 4k or 1080p on my monitor connected to my cell phone through dex ,the video just loads and does not start. When I use the cell phone without being connected to the monitor, I can watch hbo max in 4k, but disney+ in 4k the screen goes black, it only works in 1080p.

Kodi log samsung dex connect monitor : https://paste.kodi.tv/iwequnubos.kodi

Kodi log samsung phone no connect monitor : https://paste.kodi.tv/daduzegumo.kodi

**Comment by matthuisman** [comment]
try enable "ignore HDCP" setting in Inputstream adaptive addon settings

**Comment by edersonmax21** [comment]
@matthuisman I activated this option but it didn't work, I also activated the option : Try avoiding the use of secure decoder but it didn't work either.

**Comment by matthuisman** [comment]
I have no further ideas sorry. Does Disney 4k work directly on the phone itself ok?

**Comment by edersonmax21** [comment]
@matthuisman Disney+ works in 1080p on my phone and hbo max in 4k, on samsung Dex hbo max only loads and doesn't start, disney+ works in 1080p

**Comment by matthuisman** [comment]
closing this as nothing i can do to support dex
