### ISSUE TITLE
NZ Freeview tv not connecting

### ISSUE THREAD

**Issue by Gbroon2** [matthuisman/slyguy.addons#415]
It started for me yesterday out of the blue none of my Slyguy NZ Freeview channels will connect. Only affecting Slyguy links. Can anyone offer a solution?

**Comment by matthuisman** [comment]
Are you physically in NZ?

**Comment by Gbroon2** [comment]
Yes, thank you for your reply however I have found that it works on one of
my devices so must be my android tv having the issues.
