### ISSUE TITLE
IPTV merge - simple iptv displays channel name instead of current program title

### ISSUE THREAD

**Issue by mr-pineapple-nz** [matthuisman/slyguy.addons#417]
After one of the latest updates of IPTV merge/IPTV NZ, watching freeview via iptv does not display the ongoing programme title (channel display/info panel during play) instead, the channel name. "Next" programme name is correctly displayed.

OS: osmc / kodi latest (matrix)
HW: pi4

Thanks,

**Comment by matthuisman** [comment]
thanks for letting me know. Should now be fixed with [v0.61.6](https://github.com/matthuisman/slyguy.addons/commit/085ec31a0319304a7e074c9b07315249dd0973ce)
