### ISSUE TITLE
Paramount+ A-league live streams not working

### ISSUE THREAD

**Issue by Bob-git1** [matthuisman/slyguy.addons#418]
A-league 
![PXL_20230311_061912814](https://user-images.githubusercontent.com/115219488/224468711-f45aadd9-72c4-4eed-baaa-5f2b69ed4834.jpg)
Live streams not working, getting error message, see attached.

**Comment by scottydulton** [comment]
@matthuisman debug log attached for above error

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/10952665/kodi.log)

**Comment by scottydulton** [comment]
@matthuisman is there an ETA on this issue mate? no pressure just seeing if it will be resolved or not :)

**Comment by dpetersOZ** [comment]
If it helps, I get the same error too

**Comment by gw3583** [comment]
The error occurs at https://github.com/matthuisman/slyguy.addons/blob/e44870e98052d160bba22150831c2feb82fc53c6/slyguy.paramount.plus/resources/lib/api.py#L449

I logged out the return value of `data` and it is `{'success': True}`, so there is no longer a `dmas` key in the returned response.

I locally changed that line to instead be `return None;`.

It was then able to find the live channels and play back the a-league streams fine. It all seems to be working, though I'm not sure what the `dmas` functionality is intended for, and whether it is likely to break anything else.

@matthuisman Thoughts?

**Comment by matthuisman** [comment]
good hunting @gw3583 .
dma is used for "local channels" i think maybe in usa only.

They used to return success: false for other regions but now seem to return True.

ive just done a quick update to try/except around the code

**Comment by gw3583** [comment]
That's great, thanks Matt!
