### ISSUE TITLE
error playing content with iptv merge

### ISSUE THREAD

**Issue by upibis** [matthuisman/slyguy.addons#42]
I have created my own list and I loaded it with iptv merge. 
when I use proxy or vpn the list is loaded correctly with epg and logos, but I can't play all channels. ( I am convicted that there is problem internal in kodi 19.1, python v3 ?, when I use a proxy ). In particular when I try to play one channel 2 or 3 weeks ago everything was ok, but now appears slyguy common - error, failed to fetch/parse playback URL.....etc. 

If I try to play this channel without proxy everything is ok.

thank you.

**Comment by matthuisman** [comment]
Full debug log showing the issue please

**Comment by upibis** [comment]
I am not able to display or view log file, can you indicate me a valid addon. My kodi don't create a log file, I don't have it in any android folder....

**Comment by matthuisman** [comment]
can you advise the stream that doesn't work then?
I take it it works directly in Kodi when your not using IPTV Merge?

**Comment by upibis** [comment]
I have been able to create log. I had to reinstall everything. The error in question appears at 2021-08-02 00:52:45.525. 
[kodi#3.log](https://github.com/matthuisman/slyguy.addons/files/6919463/kodi.3.log)

**Comment by matthuisman** [comment]
its a bad link
https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/playlist.m3u8
returns error for me too
