### ISSUE TITLE
Foxtel Go

### ISSUE THREAD

**Issue by krackajack** [matthuisman/slyguy.addons#420]
receiving the following when logging into Foxtel Go:

_Failed to fetch JSON data
Make sure your IP address is allowed (not geo-blocked)
Try accessing the content via other means (offical app / website) to test if it's a Kodi add-on issue_

**Comment by matthuisman** [comment]
full debug log please :)

**Comment by krackajack** [comment]
Refer screenshot attached.

 

 

John Payne

0414 441 798

**Comment by matthuisman** [comment]
that doesnt help.

full debug log gives me a lot of crucial information that a screenshot of an error does not

**Comment by krackajack** [comment]
I'm sorry...but don't know where to find this. Layman with this stuff :(

**Comment by matthuisman** [comment]
oh ok, ill first check if I can reproduce the error myself.
If I can't, then ill bother you for debug log

**Comment by matthuisman** [comment]
working OK for me.

If your not physically in Australia, I'd suspect they have blocked your VPN.
If you are physically in Australia, make sure all slyguy addons are upto date
Failing that, this is how to get a log: https://kodi.wiki/view/Log_file/Easy

**Comment by krackajack** [comment]
![20230313_200222](https://user-images.githubusercontent.com/127704634/224656033-800e85d6-bfd9-4a98-9f3b-a17b5ffb4bd8.jpg)

**Comment by matthuisman** [comment]
as suspected, your running quite old version of script.module.slyguy: v0.52.6 installed
latest is [v0.61.8](https://github.com/matthuisman/slyguy.addons/commit/00de719ea9d8480a6d9c43873a643531937ae7c5)

Please keep all my addons on auto update.
As this has just wasted a bunch of time due to you running old versions
