### ISSUE TITLE
Can't access sports in foxtel go

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#421]
Getting json parse error when trying to access the sports section in foxtel go. It works in the app

**Comment by matthuisman** [comment]
ive had another report of this but I couldn't reproduce.
Maybe its a rollout thing and i'll get the same soon enough

**Comment by liam8888999** [comment]
If you have email or something I can send you my password to test if that will help at all On 15 Mar 2023, at 12:24 pm, Matt Huisman ***@***.***> wrote:﻿
ive had another report of this but I couldn't reproduce.
Maybe its a rollout thing and i'll get the same soon enough

**Comment by liam8888999** [comment]
Or more logs if you need

**Comment by matthuisman** [comment]
just tried and still working for me.
maybe set your password to something random and email me it then you can change it back after

**Comment by liam8888999** [comment]
sent an email

**Comment by matthuisman** [comment]
thanks @liam8888999 

should be fixed in  [v0.9.5](https://github.com/matthuisman/slyguy.addons/commit/4ff8777fd390d25801b58cf8c00260f1186e7c7f)
