### ISSUE TITLE
Foxtel go - Some content refuses to play on some devices.

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#422]
I have a Mac and firestick where everything works perfectly. On my android tablet and Linux x86 machine some things refuse to play where it just stays on working but some other things do work. Could be a possibile duplicate of issue #162

**Comment by matthuisman** [comment]
full debug logs for both devices showing them failing to play

**Comment by liam8888999** [comment]
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/10990477/kodi.log)
this is the debug log for the linux machine

**Comment by liam8888999** [comment]
Any updates on this

**Comment by matthuisman** [comment]
Nope. Have you tried Kodi 19.5?

**Comment by liam8888999** [comment]
I'm on kodi 20.1 would you suggest downgrading

**Comment by matthuisman** [comment]
ive tried Fox Cricket on my Windows Pc and Android shield and is OK.
Unable to test on ubuntu.

I see in the log that yours and mine both use the same key, but yours gets a 

AddOnLog: inputstream.adaptive: GetCapabilities: Single decrypt failed, secure path only
but in my windows I get
WV_CencSingleSampleDecrypter::GetCapabilities: Single decrypt possible

**Comment by liam8888999** [comment]
Yeah it works on windows, Mac and firestick. Ubuntu doesn't but it does allow some channels which is a bit strange. Is there any other ways of troubleshooting that you can think of

**Comment by matthuisman** [comment]
the same channel wont play on the android tablet? Is it a "chinese tablet"? 
what widevine version? L1 or L3

**Comment by liam8888999** [comment]
Sent an email reply but I'm not sure if it worked so if a similar message comes up that is what has happened. Majority of the channel's and on demand content don't play there are only a couple that do. The tablet is a Samsung galaxy tab 3 but has been rooted so the official Foxtel app refuses to play. I don't think Ubuntu it's self has widevine support however kodi has never had issues playing drm content in other addons such as binge or Disney

**Comment by matthuisman** [comment]
give some examples of which work and which dont
selecting lowest quality makes no difference?

**Comment by liam8888999** [comment]
Selecting lowest quality makes no difference. Fox sports 501 is a channel that definitely does not work, fox one is a channel that does work

**Comment by matthuisman** [comment]
think I managed to fix it with [v0.9.8](https://github.com/matthuisman/slyguy.addons/commit/b3af2ce7ecd15c6037e8018d8c1c8b074aeb968d)

Confirmed no playback for me on x86_64 Linux Ubuntu in 0.9.7 but with 0.9.8 I get playback
