### ISSUE TITLE
Disney+ - Because you watched {title}

### ISSUE THREAD

**Issue by Sopor** [matthuisman/slyguy.addons#424]
If i open `Featured` two of them shows {title} instead of the movie title `Because you watched {title}`.

![image](https://user-images.githubusercontent.com/5789283/225763707-107815f4-468a-4dd1-88bf-c4cea1ef46ad.png)

Is this really correct?

Kodi 19.5 and 20.1

Disney+ 0.13.6

**Comment by matthuisman** [comment]
no, they should be replaced. looks like disney may have swapped the template tags from ${title} to just {title}

**Comment by matthuisman** [comment]
ill get a fix out later tonight

**Comment by matthuisman** [comment]
fixed with [v0.13.7](https://github.com/matthuisman/slyguy.addons/commit/a8e51c295a495068edbce7386e54d3be262a7db7)
