### ISSUE TITLE
All SlyGuy Addons disappeared?

### ISSUE THREAD

**Issue by Bob-git1** [matthuisman/slyguy.addons#426]
On Kodi 19.5, went to addons and all SlyGuy addons gone, with message in top right corner saying "Failed to install a dependency."
Tried to reinstall the addons but got the same error.
Using GCCwGTV.

**Comment by matthuisman** [comment]
you need to go through and make sure slyguy.common and slyguy.dependencies and slyguy.repo are all upto date and set to automatics updates

**Comment by Bob-git1** [comment]
Thanks Matt. Reinstalled from zip file and all working again. Not sure what happened, never seen that before.

**Comment by matthuisman** [comment]
The addons bumped what versions of dependencies they needed. I suspect at
one point you had pinned one of those and it wasn't getting updated

**Comment by matthuisman** [comment]
PS: What exact addon did you need to install via zip to fix? the repo?

**Comment by Bob-git1** [comment]
I just went to Addons - Install from zip file - SlyGuy and reinstalled the zip file.

Seems to have fixed everything. I didn't even have to log back into the addons.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
