### ISSUE TITLE
Star Plus support OTP email code login

### ISSUE THREAD

**Issue by ricgamerdj23** [matthuisman/slyguy.addons#428]
login with password not working.

**Comment by markeymark** [comment]
> 

working fine here......are you using a shared account?

**Comment by matthuisman** [comment]
maybe in India? and getting confused with Hotstar?
Hotstar uses a completely different backend

**Comment by matthuisman** [comment]
[v0.0.10](https://github.com/matthuisman/slyguy.addons/commit/7dd9e39781f3fbe41b670e7ba384a36dbb19144b) adds support for OTP email login
