### ISSUE TITLE
[feature request] [HBO Max] [Android] using the original HBO app to play content.

### ISSUE THREAD

**Issue by Enigma3000** [matthuisman/slyguy.addons#43]
Hi Matt, using your add-on on the Shield Pro 2019.

Regarding the ongoing inputstream adaptive issues causing audio problems and video buffering when surround is activated:

Would you be interested in adding a feature to play the video content with the official HBO add-on? 

Sandmann's Prime Video add-on for example already has this feature working (for 4k since the add-on somehow won't support 4k).

This way we would still be able to add titles to our Kodi library but at the same time not have any video/audio issues when enabling surround sound. 

It would be a nice workaround!

Let me know if that's something you would like to do. I can always assist by testing. 

Thank you!

**Comment by matthuisman** [comment]
sorry, this is just "too hacky" for me to do.
Need to start android activities etc.
And run system commands.
it just feels "icky".

Hopefully we can get to the bottom of the 5.1 audio issue.
I really just need some time to look into it more

**Comment by matthuisman** [comment]
@ Enigma3000
Could you try install this version of inputstream adaptive, seems to fix the 5.1 issue for me:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-732/9/artifacts

either install the android aarch64 or android armv7 build.
only one will install ok. Shield uses aarch64. mi box uses arm7

**Comment by Enigma3000** [comment]
I'm sure you'll find the clues! Always happy to test. Let me know....

**Comment by matthuisman** [comment]
please see here:
https://github.com/xbmc/inputstream.adaptive/issues/757#issuecomment-892425202
