### ISSUE TITLE
Sky news Au on Samsung

### ISSUE THREAD

**Issue by yendorsing** [matthuisman/slyguy.addons#431]
Not sure if this is the right forum but I see Sky News Au is starting on Samsung TV plus Australia March 23.  Wondering if this will become available.  Australia is not in the list of countries available.  Hope we can get this.

**Comment by matthuisman** [comment]
does this help?
https://forums.whirlpool.net.au/thread/3rvjvmqj?p=5#r86

**Comment by yendorsing** [comment]
I guess my question wasn't clear. Is there a way to get that channel in the samsung tv line-up available in 

https://i.mjh.nz/SamsugTVPlus/all.m3u8

This is for countries other than Australia.  Is it possible to add SamsungTV Plus Australia to the playlist.  Updating doesn't do anything.    

Thanks for your help and great work.

**Comment by matthuisman** [comment]
no. my addon uses the mobile app data. australia does not have the mobile app

**Comment by yendorsing** [comment]
ok, thanks
