### ISSUE TITLE
Pluto TV ... playback failed

### ISSUE THREAD

**Issue by Max11223344** [matthuisman/slyguy.addons#434]
Installed the latest slyguy repo version 0.0.8 on Raspi4b 4gb running under OSMC 2022.03-1 and  kodi 19.4
Searching in Pluto Version 0.6.2 - live tv - for CBS there are a lot of channels, but only a very few are working. Mostly there is an error message "playback failed". 
The log says Error general ......max retries exceeded with url /dns-query?name=dai.google.com&dns=google.com (caused by sslerror (sslcertverificationerror)

Running the same repo and the same Pluto version on Raspi 3b+ with Raspbian Buster i see much more CBS channels and no Error

**Comment by Max11223344** [comment]
Is there a way to transfer the Kodi 18.7 settings to Kodi 19.4 ?

**Comment by matthuisman** [comment]
pluto cbs issues should be fixed with latest slyguy common
