### ISSUE TITLE
Udemy: Add support for Personal Subscription Plan

### ISSUE THREAD

**Issue by Anmolfid1** [matthuisman/slyguy.addons#437]
@matthuisman Hi Matt, Can you please try to add a new feature in Udemy Addon? I have taken a subscription to the udemy personal plan, and it doesn't show any courses as I haven't purchased them, so they are not showing in my list.

I hope you will reply asap!

**Comment by matthuisman** [comment]
i dont understand. please explain a bit better and maybe link to examples / what is personal plan?

**Comment by Anmolfid1** [comment]
https://www.udemy.com/personal-plan/?locale=en_US
I am talking about this actually, I am using udemy subscription, that's why I am not having any purchased courses in my library

**Comment by matthuisman** [comment]
Oh right. It's not even available in my country yet and I won't have a subscription anyway so you might be waiting awhile for this feature. 

Can you maybe still add courses via website for them to show in addon?

**Comment by Anmolfid1** [comment]
Oh I see, i hope you will make update soon

well i haven't tried to add course, as i didn't felt need of it until now

Thanks for your reply

**Comment by matthuisman** [comment]
NZ now as these personal plan and has a 7day free trial. 
so shoud be possible to get that and implement the features needed (hopefully and when have time)

**Comment by zag2me** [comment]
Just confirming this for me as well, supporting the "My Lists" feature under the Personal subscription plan would be a game changer to me.

**Comment by matthuisman** [comment]
My Lists coming very soon!
Also figured out how to fix 1080 on most courses and on all platforms (not just widevine vmp)

Working on better search now :)

**Comment by matthuisman** [comment]
[plugin.video.udemy -> v0.12.0](https://github.com/matthuisman/slyguy.addons/commit/8f69b8b09ddcdd299f2f2376c92938fdbdec8455) just released

Add My Lists. 
Better search. 
Better playback. 
Edit lists via context menu
