### ISSUE TITLE
Direct library import from slyguy* vod addons.

### ISSUE THREAD

**Issue by wlincpdjhbxz** [matthuisman/slyguy.addons#443]
I've been working on a way to direct import to library from slyguy addons.

I'm near a solution to submit a PR but I've only done enough to import from Hulu series for testing and I would like this to be global from the slyguy common module.

Here's a rough outline of the way it works, please advise if this is even something to pursue for official releases or just keep it for myself.

The addon in question must implement medialibraryscanpath in order for Kodi to scrape it's content so this has to be added to addon.xml

    <medialibraryscanpath content="tvshows">/series</medialibraryscanpath>
    <medialibraryscanpath content="movies">/movies</medialibraryscanpath>

Then Kodi must know they are source paths, I have only been able to add sources directly to sources.xml and each series needs to be it's own entry due to a bug somewhere that recursion in scraping will eventually crash Kodi.

Example:

        <source>
            <name>Hulu Vikings</name>
            <path pathversion="1">plugin://slyguy.hulu/series/Vikings</path>
            <allowsharing>true</allowsharing>
        </source>

The major part needing to implement is the addons' ability to translate real paths to relative paths, I used the existing bookmarks mechanism to achieve this.

Implementing into the default.py of the Hulu addon

Check sys.argv[0] for /series/ to determine if we're asking for a series listing, if yes

from slyguy import bookmarks
shows = bookmarks.get()

Then iterate shows until matched show["label"] to the path requested, set sys.argv[2] to the path from bookmarks

sys.argv[2]=show["path"].replace('plugin://slyguy.hulu/','')

Then proceed as normal with plugin.dispatch(sys.argv[2])

I've tested it a few times and it does allow direct import, setting the respective source content to TVShows, Scraper TMDB, "Path contains single TVShow", but it is more or less a hack.

Movies could be implemented in a similar fashion, I'm currently using the folder flag in bookmarks to differentiate, if folder is 1 then its a series, if is 0 then its a movie.

It would be far more useful to implement globally script.module.slyguy then the additions to each addon individually would only be the 2 medialibraryscanpath entries in the addon.xml

Implementation would affect no existing users as it would only extend functionality not modify existing functionality.

**Comment by matthuisman** [comment]
maybe have a look at https://github.com/anxdpanic/plugin.video.composite_for_plex and see how it does it.

My plan was to just recursive the entire addons folder system and create .strm files for all movies etc into a folder and then kodi just scans that folder. This would work on older kodis too.

I think medialibraryscanpath is only kodi 20?

**Comment by wlincpdjhbxz** [comment]
That addon also implements medialibraryscanpath so I assume the same mechanism I'm attempting to use is also what they are using.

https://github.com/anxdpanic/plugin.video.composite_for_plex/blob/master/addon.xml#L11

I'm not sure how new medialibraryscanpath is, it seems to be largely undocumented, I first encountered it in embycon.

I am only currently testing with Kodi 20 and 21 Alpha, however.

Once I get something workable I will test more, still in experimental phase.

As far as strm, that is an ok solution, I already wrote a library export utility for that but I was hoping for something a little more direct the way plex/emby/jellyfin do it.

Using the bookmarks was a good way to select specific ones only instead of trying to scan in the entire Hulu library

Jellyfin inserts directly into the database though, not a method I want to explore.


-----

A little more testing and I was able to use JSON RPC VideoLibrary.Scan to scan in folders without the need for them to be added to sources.xml, I'm currently doing more tests with that because during my test the initial plugin path had to already be in the database in the path table and marked with a scraper.

Still, the addon needs to be able to list its contents from a normal full path the way I set it up in the PR.

**Comment by wlincpdjhbxz** [comment]
Further testing, I can add the path for Hulu into the database and then scan in any series served from that PR via bookmarks.

Even though directly inserting to the database doesn't make me comfortable, it seems relatively harmless as Kodi will add these paths eventually on it's own in time.

Test parameters:

Apply the PR
Bookmark 'Vikings' in Hulu
With a fresh and clean database, in a portable folder, I inserted the record for the path setting it up as content tvshows scraper tmdb
INSERT INTO path VALUES(1,'plugin://slyguy.hulu/','tvshows','metadata.tvshows.themoviedb.org.python','',0,0,'',0,0,1,NULL,NULL);
Issue a JSON RPC command to scan a path.
{"jsonrpc": "2.0", "method": "VideoLibrary.Scan","params":{"directory": "plugin://slyguy.hulu/series/Vikings/"}, "id": 1}


That SQL statement should be modified to use Column/Value pairs and allow the database to determine it's own index values, NULL values could be left out as well IF it is to be used in any production code.
I am only using it for testing alone.

That can be repeated for Hulu, Disney+ and Paramount+ addons so far.

**Comment by wlincpdjhbxz** [comment]
I simply cannot get this to work with any sort of consistency on current release versions, I don't think Kodi is able to handle streaming media sources in this way currently.

Tested back to 19.5 from Debian and it only crashes.
Retested 20 and 20.1, it only works 4/5 attempts.

Only consistently working on v21 ALPHA compiled from the Kodi master branch, which is good for a future release but not even close to good for anything else.
