### ISSUE TITLE
NOOBS Companion reboots stopped working in Pi 4:

### ISSUE THREAD

**Issue by Ulathar** [matthuisman/slyguy.addons#448]
Hey there,

I am running a multi-boot system on one of my Pi 4s with the following systems/partitions:

1. PINN 
2. LibreElec (Default Boot)
3. RetroPi
4. Raspian 

Alongside this I used to use your great addon to be able to quickly switch / boot between these 4 systems. Worked like a charm!
For reasons I am unable to figure out these switches now stopped working. I can not exactly tell when or why it stopped working because I use LibreElec most of the time (which is the default boot partition).
Now whenever I select any other system from within LibreElec using your addon the Pi reboots but ends up back in LibreElec again instead of the selected system I wanted to boot to.

Is there a way I can log this process in order to be able to find out what is going wrong?

Also found this old issue at NOOBS: https://github.com/raspberrypi/noobs/issues/551 which sounds somewhat related but because I had it working before (using sdhci.debug_quirks2=4) I am not really sure. Is it possible that a more recent PINN, LibreElec or Firmware Update broke this somehow?

**Comment by matthuisman** [comment]
as far as I know https://github.com/raspberrypi/noobs/issues/551 is the reason.
I havn't really been in the Pi scene for some time now so unsure if that has changed sorry
