### ISSUE TITLE
German language on Paramount+

### ISSUE THREAD

**Issue by Basti83x** [matthuisman/slyguy.addons#449]
Hi.  Is it possible to set the addon language to German so that the film/series names are German?  and maybe the description of the films/series is in German.  I'm very happy with this addon, the only thing missing is German.  I thank you in advance for your help.

**Comment by matthuisman** [comment]
I have over 50 addons. Please specify name of addon in the issue title :)

**Comment by Basti83x** [comment]
I mean the paramount plus addon

**Comment by matthuisman** [comment]
there is an existing issue:
https://github.com/matthuisman/slyguy.addons/issues/333

Therefore closing this :)
