### ISSUE TITLE
[HBO Max] implement My List

### ISSUE THREAD

**Issue by DoctorBR** [matthuisman/slyguy.addons#45]
I am using **HBO MAX** in **Brazil** with **Kodi 18.9** installed in a **Xiaomi Mi Box,** and even 4K content with HDR works without problem, except for the fact that I need to leave only stereo. 

But I miss the content on "My List" (Bookmark in the add-on gets empty (no items)).  

![Screenshot_20210727-191747 - Add-on HBO Max (sem Minha Lista - Bookmark)](https://user-images.githubusercontent.com/25212010/128105027-8891fe50-3c18-4d82-9bbc-2f5c3887d7d5.png)

Is there anything to do to avoid that problem? 

Thank you so much for creating and keeping this add-on!

**Comment by matthuisman** [comment]
Bookmarks is not the same as My List
Bookmarks are an add-on feature.
You can add to them via the context menu "Add to Bookmarks"

My List is not supported (yet)
No ETA

**Comment by matthuisman** [comment]
Started working on my list, as well as continue watching and syncing playback too today 
Hopefully have it released over next few days

**Comment by matthuisman** [comment]
My List added in 0.4.1
You can remove and add items via context menu
