### ISSUE TITLE
Channel 9 not playing live

### ISSUE THREAD

**Issue by Deacs3939** [matthuisman/slyguy.addons#452]
G'day mate, great add ons.
I noticed that this morning channel 9 isn't playing live tv and keeps referring back to a previous recording when using IPTV through IPTV simple client.
The nine now add on seems to play live tv fine.
Thanks heaps.

PS in a house with 2 kids we couldn't survive without your add ons. Cheers.

**Comment by skaface** [comment]
yes I am seeing the recording of the beer powered motorcycle too on channel 9. If you choose the channel 9 720p channel further down in the list, that works fine

**Comment by Chrisdeacon82** [comment]
Lol.... Yep, exactly the same as what I get.
Must be an issue with the link the feed is coming from.

**Comment by matthuisman** [comment]
fixed last night

**Comment by reaper09king** [comment]
any update regarding dstv now

**Comment by matthuisman** [comment]
read last few pages here: https://mybroadband.co.za/forum/threads/release-dstv-now-kodi-add-on.977513/page-144
