### ISSUE TITLE
Foxtel Go issue

### ISSUE THREAD

**Issue by nickneos** [matthuisman/slyguy.addons#455]
Started getting the below issue maybe in the last hour or so.

Have tested the official foxtel app and my login works fine. 

![20230524_165400](https://github.com/matthuisman/slyguy.addons/assets/29367905/7b752acb-993b-431c-a216-385275ffb67d)

**Comment by nickneos** [comment]
issue still persists for me even with slyguy common 0.64.7

**Comment by matthuisman** [comment]
what device

**Comment by nickneos** [comment]
Amazon Fire Stick 4k max.

Tested on 2 separate ones

**Comment by matthuisman** [comment]
try latest slyguy common just pushed
