### ISSUE TITLE
Kayo not working 

### ISSUE THREAD

**Issue by Bob-git1** [matthuisman/slyguy.addons#459]
Tried reinstalling the addon but now cannot login, getting errors per attached pic ?

**Comment by Bob-git1** [comment]
Also confirmed officiall Kayo app is working ok.

**Comment by Bob-git1** [comment]
![Uploading PXL_20230526_015932457.jpg…]()

**Comment by Bob-git1** [comment]
Seems to be working now. Not sure if you did something Matt but I will close the issue.

**Comment by matthuisman** [comment]
yes, there was an update :)
