### ISSUE TITLE
Frequent crashes with Disney+

### ISSUE THREAD

**Issue by Mutant** [matthuisman/slyguy.addons#460]
Hi,

Kodi frequently crashes when seeking during Disney+ playback (including resuming from a previously watched point).

Debug log: https://paste.kodi.tv/jiloziqake.kodi

All other addons work fine, including other slyguy addons.

**Comment by glennguy** [comment]
Hi @Mutant 
I'm sorry to say that there won't be any future releases for inputstream.adaptive on Matrix which would likely fix this issue.
OSMC has test builds available that use Kodi 20.1 if you'd like to try upgrading.

**Comment by matthuisman** [comment]
@Mutant are you able to advise what inputstream adaptive version it's now using?

**Comment by Mutant** [comment]
20.3.9
