### ISSUE TITLE
Disney+ on RPi 4 - Video issues

### ISSUE THREAD

**Issue by d1nuc0m** [matthuisman/slyguy.addons#461]
**Platform**
Kodi 20.1 on Raspberry Pi 4 Model B (4GB RAM), LibreELEC 11.0.1

Tested my connection multiple times and I get a consistent 30 Mbps download/3 Mbps upload with low ping and jitter, so it shouldn't be a connection issue. Addon settings are at default

**Issue**
Videos always start with a black screen with audio only. At lower resolutions (640 x360 up to 854x480) skipping forth and back brings up the video, but then it goes out of sync if skipping again. At higher resolutions, it is impossible to get a working video, even if the hardware is capable of playing 1920x1080 on other addons.

Maybe related to #458 and #460 ?

**Comment by games647** [comment]
Reproducible with older Pi's (Pi 3) too.

**Comment by sosodev** [comment]
I'd highly recommend that you try installing Kodi on 32-bit Raspberry Pi OS. I recently switched to it over LibreElec on my RPi4 and have found that it performs better with far fewer glitches.

**Comment by matthuisman** [comment]
closing as no log provided
