### ISSUE TITLE
Possible foxtel go issue

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#463]
Sometimes the channel will just go black with no video or audio when playing or changing channel, once it is playing it seems to go fine apart from occasionally freezing but that is likely network issues. Everything is fully updated https://pastebin.com/sLW6RsXG

**Comment by liam8888999** [comment]
Another log paste bin.com/9u6EzY63

**Comment by matthuisman** [comment]
try 0.65.5 :)
