### ISSUE TITLE
DISNEY + black screen on playing 1080p or hdr content on samsung s21 fe

### ISSUE THREAD

**Issue by iamkgehlot** [matthuisman/slyguy.addons#468]
Hello , i have samsung s21fe with widevine l1 certification. The device is able to play hdr content on prime and other apps. But it is not able to play 1080p or hd content.  Audio is audible but screen is black.

**Comment by Norbiros** [comment]
I can reproduce this bug, but it doesn't display black screen, it just “freezes” on 1st frame. HBO MAX works correctly.

**Comment by wolgast** [comment]
I had the same problem. My issue was that I had set the default language to "sve" (swedish) but the correct short form of swedish is "swe". Changing this solved my problem. Maybe not the best behavior to show a black screen if the language option is wrong...

**Comment by matthuisman** [comment]
Thanks for the info. it most definitely isn't the expected behaviour so
suspect a big somewhere. I'll try to reproduce and fix

**Comment by Norbiros** [comment]
This bug happens to me when I start playing new video. It doesn't show black screen, but it “freezes” video (most of movies start with black screen). I found out that a temporary solution is to start playing film from 5:03 and that rewind back, for example, to 4:53, then video works correctly.

**Comment by matthuisman** [comment]
please always list your kodi version and what OS
