### ISSUE TITLE
Binge Widevine issue

### ISSUE THREAD

**Issue by Mylorite** [matthuisman/slyguy.addons#471]
Binge addon is doing the "widevine licence request failed" thing again.

**Comment by Mylorite** [comment]
Getting auth error on Binge and Kayo now.

**Comment by matthuisman** [comment]
you need to update to latest slyguy common as per my comment

**Comment by matthuisman** [comment]
they all sure the same api basically. so when one errors- they all will

**Comment by Mylorite** [comment]
OK, update has just come through, all good now.  Thanks!

**Comment by Mylorite** [comment]
Spoke too soon. Getting the widevine error again.

**Comment by tent-icle** [comment]
Sorry to say I am seeing this again too. It was fixed yesterday with 0.65.9 but seems to be broken again since 0.66.1 auto-installed a couple of hours ago.

Unsure if the cause is on our side or theirs. I’ll try to reinstall 0.65.9 and see what happens

**Comment by Mylorite** [comment]
Working again.

**Comment by tent-icle** [comment]
Yep, same here. 0.66.2 just auto-installed and this now appears to be resolved
