### ISSUE TITLE
Can not login to stan

### ISSUE THREAD

**Issue by sunshine69** [matthuisman/slyguy.addons#474]
Hi,

Not sure if it si known issues but when I tried to login (use device login) I got error 

Failed to login / refresh token
Message: Streamco.Login.InvalidLogin

Kodi and the browser to get the activate link run on the same machine that is a Ubuntu 23.04 OS. I did also tried that one machine run kodi and the other one run the browser with same result.

I do not use VPN and stan on browser works fine. It just one of the device is struggling to play with decent quality due to slow CPU when using browser thus I am looking to kodi to see it improves. In the same box, kodi can easily play 1080P but browser is struggling to play that for the AU IPTV add on which works fine.

Please let me know if u want me to do more debugging etc..

Thanks

**Comment by matthuisman** [comment]
i cant reproduce sorry
I tested windows and ubuntu and on both I get the activation code and can login without issue.

**Comment by sunshine69** [comment]
Thanks for reply, I canceled my trial with Stan thus having no chance for more debugging anyway. Should it be a trial account is the cause? I am not sure.
