### ISSUE TITLE
Kayo/Binge failed to fetch auth token

### ISSUE THREAD

**Issue by Bjr86** [matthuisman/slyguy.addons#476]
Hey Matt,

It seems the failed to fetch auth token error for Kayo and Binge is back again. I wasn't sure if you were aware.
Running slyguy common 66.3.

Thanks mate, appreciate all your work.

**Comment by matthuisman** [comment]
please try 66.4

**Comment by Bjr86** [comment]
Back working again.
Thanks again, sorry about the late reply
