### ISSUE TITLE
Foxtel Go: images not showing (blocked) on linux

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#483]
The issues appear to be images are not loading and frequent buffering/losing sound
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/11827909/kodi.log)

<https://watch.foxtel.com.au/app/imageHelper.php?id=3889324:206:CHANNEL:IMAGE:png&appID=GO2&w=400#FOX%20Comedy> Failed: HTTP response code said error(22)

**Comment by matthuisman** [comment]
buffering / sound - nothing i can do. 

Image issue - probably they just blocking based on headers

**Comment by liam8888999** [comment]
Thanks. The buffering/sound came back after I posted it so was probably something on the network somewhere (yet to track down what though).  I saw an update a week or so ago about the images but they haven't come up at all since then that I have seen

**Comment by matthuisman** [comment]
I think I only fixed internal images. Not the channel ones vis pvr

**Comment by matthuisman** [comment]
oh, are you using any slyguy smart urls to route via smart dns etc?
IF so - they dont work on images (yet) as the images dont through my internal proxy (yet)
So, the image server can see your real location

**Comment by liam8888999** [comment]
No. I am not using anything like that

**Comment by matthuisman** [comment]
great. what OS were you using again?
images working on windows.
suspect linux?
if so - same SSL issue.
Images dont go via proxy so just use kodis curl ssl settings which i suspect they blocking

**Comment by matthuisman** [comment]
yup. confirmed not working on linux for me

**Comment by liam8888999** [comment]
Yes. I'm on Linux (Ubuntu)

**Comment by matthuisman** [comment]
should be fixed with latest slyguy common as it now passes all artwork via the proxy :)

**Comment by liam8888999** [comment]
I am getting the images within the addon but iptv merge doesn't seem to be displaying them in the epg

**Comment by liam8888999** [comment]
When I go in iptv merge I can see the channel logos though
