### ISSUE TITLE
Channel names not changing

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#484]
I'm not sure if it's some setting with my setup but when I run foxtel go through the iptv merge the channel names don't change in the guide, this is noticeable particularly with channel 402 which is used as a pop up movie channel and changes name every week or so but it is always shown as movie hits

**Comment by matthuisman** [comment]
you'd probably need to go into kodi pvr settings and clear guide data so it forces a refresh?

Has a merge run after the name changed?
does the name in the addon -> live change?
does the name change in kodis TV view?
does the name change in IPTV Merge > Manager Tv > Foxtel go?
