### ISSUE TITLE
TVNZ sport content not playing

### ISSUE THREAD

**Issue by simongreen-net** [matthuisman/slyguy.addons#487]
Hi Matt,

With the TVNZ+ app, content in the Sports page is not loading. For example, Sports » Latest Replays » England V Australia: 2nd Test - Day 1

I suspect it is because of some copy protection added to this content as mentioned in the below article. Would be great if this could be fixed. Other TVNZ content plays fine. I am using DNS4Me, so it could be a problem at that end if it works for you.

https://www.rnz.co.nz/news/business/492977/older-digital-tvs-won-t-be-able-to-stream-tvnz-content

**Comment by matthuisman** [comment]
what is your device? most devices should support Widevine. Most of the content on TVNZ is using widevine

**Comment by matthuisman** [comment]
please provide a kodi debug log

**Comment by matthuisman** [comment]
oh, DNS4Me - yeh - they wont be aware of the new domains to route

**Comment by matthuisman** [comment]
These will need to be added if not already:

apis-public-prod.tech.tvnz.co.nz
replay.vod-tvnz-prod.tvnz.io
apis-public-prod.tvnz.io


Or just wait a few weeks. the official apps will use these same domains so eventually someone will let DNS4ME know

**Comment by simongreen-net** [comment]
Thanks for looking into this. Yes, it does seems like a DNS4Me issue. A few coffees coming your way.
