### ISSUE TITLE
[Hulu] Stream downloads begin failing with HTTP 410, causing video to stall

### ISSUE THREAD

**Issue by dapharsyde** [matthuisman/slyguy.addons#488]
Video playback works for a few minutes, but then it stalls because it is unable to download the next video segment.  Issue occurs on multiple channels, regardless of whether an advertisement is playing or not.

Relevant part of log includes lines like this:

`2023-07-01 03:42:09.203 T:51349   error <general>: CCurlFile::CReadState::FillBuffer - (0x7f053c11a330) Failed: HTTP returned code 410`

Attached is the full kodi debug log of two consecutive occurrences of the errors, and the manifest file from the inputstream.adaptive plugin.  If there's anything else I can help provide to debug this, please let me know.

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/11925627/kodi.log)
[manifest_1688207725.txt](https://github.com/matthuisman/slyguy.addons/files/11925628/manifest_1688207725.txt)

Edit: log file is from latest nightly builds, but the same issue occurs with latest stable release from libreelec 11.

**Comment by dapharsyde** [comment]
Update:  Been noticing this same issue on all channels now.  Every stream stops working after ~5 minutes, with a 410 error.

I'm not sure if this will be helpful, but as part of another (probably unrelated?) issue I opened with inputstream.adaptive I was provided a [test release of IA](https://github.com/xbmc/inputstream.adaptive/issues/1290#issuecomment-1620304342) that produces more debug manifest files.

Attached below are the log file from a Windows Kodi 20.2 installation and the manifests provided from the test version of inputstream.adaptive provided by CastagnaIT.

[manifests.zip](https://github.com/matthuisman/slyguy.addons/files/11952706/manifests.zip)
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/11952707/kodi.log)

**Comment by matthuisman** [comment]
the issue could be that inputstream adaptive doesnt support <location>
you'll notice in manifest, that points to
https://livem-ftc-na.media.hulustream.com/v1/live/dash/continue/d34a8320-c6a3-4b44-a949-ab82e8edd357/manifest.mpd...
but we keep using 
https://livem-ftc-na.media.hulustream.com/v1/live/dash/initial/d34a8320-c6a3-4b44-a949-ab82e8edd357/manifest.mpd....

**Comment by dapharsyde** [comment]
Issue appears to be resolved by the latest nightly Omega IA builds.  After upgrading, however, I started seeing these errors in the logfile:

2023-07-05 02:36:25.084 T:21668   error <general>: script.module.slyguy - list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\dapha\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 293, in do_GET
                                                       self._parse_dash(response)
                                                     File "C:\Users\dapha\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 688, in _parse_dash
                                                       selected = self._quality_select(streams)
                                                     File "C:\Users\dapha\AppData\Roaming\Kodi\addons\script.module.slyguy\resources\lib\proxy.py", line 387, in _quality_select
                                                       return qualities[self._session['selected_quality']]
                                                   IndexError: list index out of range

I'm not sure if this is due to the new version of IA or from upgrading from Nexus to Omega, but I just thought I'd mention it.

**Comment by matthuisman** [comment]
@dapharsyde that was me i think. [v0.67.8](https://github.com/matthuisman/slyguy.addons/commit/46ea578b93130beeaf8517014cc002de13824a09) should fix that

**Comment by dapharsyde** [comment]
issue appears to be fixed by a collection of PRs to the omega branch including [this update](https://github.com/xbmc/inputstream.adaptive/issues/804) to inputstream.adaptive.

Also can confirm the list index errors are no longer present in v0.67.8
