### ISSUE TITLE
Any way to get UHD for Stan?

### ISSUE THREAD

**Issue by GeorgeSama** [matthuisman/slyguy.addons#49]
I think its driven by the params on the login?

**Comment by matthuisman** [comment]
@GeorgeSama 
i probably could get it working.
I'd need a "premium" login to find the required calls first.
Even then, it may be locked down to premium accounts pretty goodl

**Comment by matthuisman** [comment]
i have actually checked, and the stream eligibility is built-in to the user token that is sent to the server when requesting the manifest. I'm asking my user who provided the login to update to premium for a month (its actually on sale for same as standard for 1 month) so I can test and confirm i can get it working for the premium users :)

**Comment by GeorgeSama** [comment]
Cool, let me know if I can help

**Comment by matthuisman** [comment]
success, managed to get a premium login and got the data i needed.
Looks like the 4k will need a L1 widevine device though..
still testing.

Also not sure if it will work with non-premium logins.
I don't have a non-premium login to test with..
is your login non-premium? 
If so, would you be able to set the password to something unique and lend it to me to try?
If yes, see bottom of here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by GeorgeSama** [comment]
> success, managed to get a premium login and got the data i needed.
> Looks like the 4k will need a L1 widevine device though..
> still testing.
> 
> Also not sure if it will work with non-premium logins.
> I don't have a non-premium login to test with..
> is your login non-premium?
> If so, would you be able to set the password to something unique and lend it to me to try?
> If yes, see bottom of here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

sorry, mine is premium too

**Comment by matthuisman** [comment]
just pushed 0.3.2 that adds 4K support for supported devices.
Supported devices are Android Level 1 Widevine (eg. Shield) with HDCP 2.2
