### ISSUE TITLE
Fbi radio stream not working

### ISSUE THREAD

**Issue by Tyreless** [matthuisman/slyguy.addons#490]
When I try to stream fbi radio in iptv radio au I get an error message “Radio au - Error. failed to connect to host:streamer.fbiradio.com. Check your internet connection".

**Comment by matthuisman** [comment]
should be fixed within next 30mins. thanks

**Comment by Tyreless** [comment]
Thanks - working now. Cheers, Geoff On 9 Jul 2023, at 3:59 pm, Matt Huisman ***@***.***> wrote:﻿
should be fixed within next 30mins. thanks
