### ISSUE TITLE
HBO Max became MAX

### ISSUE THREAD

**Issue by tyshiro** [matthuisman/slyguy.addons#493]
Will this be updated to work on Kodi in the US?

**Comment by matthuisman** [comment]
see https://github.com/matthuisman/slyguy.addons/issues/454 
closing this as duplicate

**Comment by tyshiro** [comment]
Is there an update? Thanks

**Comment by matthuisman** [comment]
no update. when there is, itll be posted on that other ticket :)

**Comment by tyshiro** [comment]
How do I view the other tickets?

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/454 is the existing ticket.
Click on that and you can subscribe to it to get notifications on updates

**Comment by tyshiro** [comment]
Thank you so much🙏🏼🙏🏼🙏🏼
