### ISSUE TITLE
Use InfoTagVideo setter for Kodi 20+

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#498]
etting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.

**Comment by jurialmunkey** [comment]
FYI - If you want a quick and simple way to do this which stays compatible with the infolabel dictionary for setInfo() you can use my script.module.infotagger module (in the official Kodi repo).

See ReadMe for usage
https://github.com/jurialmunkey/script.module.infotagger

**Comment by matthuisman** [comment]
Legend. that makes life easier!

[slyguy.dependencies -> v0.0.14](https://github.com/matthuisman/slyguy.addons/commit/301d306a86cd23b35f210e5e7209228af9334c26)
[script.module.slyguy -> v0.69.9](https://github.com/matthuisman/slyguy.addons/commit/01d97304a90619c7bfe06045a19d07229a43b3a0)
now using your module

thank you
