### ISSUE TITLE
SkyGo Addon not logging in

### ISSUE THREAD

**Issue by mminehanNZ** [matthuisman/slyguy.addons#5]
Hi Matt,
We went to use the SkyGo addon (with Kodi 19 on Windows 10 Pro) yesterday and keep getting an 'internal server error'. Logged out of SkyGo and tried to login again and keep getting "Failed to login. Server message: internal server error".
Checked the password by logging in to SkyGo using a web browser and the SkyGo Android app.  No issues logging in via these methods.
Would you mind taking a look.

**Comment by matthuisman** [comment]
You'll need to switch to my new SkyGuy add-on.
Currently it only supports Live channels, but VOD should be coming over the next few weeks.

It's called "Sky Go (New)" in my repo
