### ISSUE TITLE
[Disney+] Subtitles not working when using the "Resume from" option

### ISSUE THREAD

**Issue by pachulo** [matthuisman/slyguy.addons#500]
Hi @matthuisman ! I'm using a Xiami Box S with Kodi 20.2 and lately I've observed a problem with, at least, the Disney+ add-on: when I reproduce something using Kodi's "Resume from hh:mm:ss" option, the subtitles don't work.

If I do play the same content from the beginning, they work correctly. Is this a known problem?

Thanks again for all your hard work!

**Comment by Carty89** [comment]
Hey mate just a question do you need a Disney subscription to watch it through Kodi?

**Comment by matthuisman** [comment]
@Carty89 of course you do :)

**Comment by matthuisman** [comment]
@pachulo that is probably a kodi / inputstream adaptive issue.
Ill see if i can reproduce and then ill try kodi 21 as i think that has some subtitle fixes

**Comment by pachulo** [comment]
Hi @matthuisman ! Where you able to reproduce this on kodi 20?
Thanks!

**Comment by keiem** [comment]
I have the same issue on libreelec 11.  When starting from a resume point, I don't have subtitles (dutch subtitles in case that matters.)

**Comment by matthuisman** [comment]
has anyone tried Kodi 21 yet?

**Comment by matthuisman** [comment]
from kodi forum
"in the Disney+ add-on, continue watching, when trying to continue any movie, the normal subtitle not visible, which I choose and set earlier.
Visible just, when I play from beginning of the movie, via pop-up menu. When I select continue, is not visible.
Tested in android kodi 20 and 21, and CoreElec kodi 20 and 21.
The HBOMax add-on from you works fine."


So 21 may also have same issue

**Comment by matthuisman** [comment]
have opened an issue here: https://github.com/xbmc/inputstream.adaptive/issues/1419

**Comment by gmjh123** [comment]
> > Hey mate just a question do you need a Disney subscription to watch it through Kodi?
> 
> Yes but you can download its video

What do you mean by "it's video"?

**Comment by gmjh123** [comment]
> > its
> > Disney+

Ok I give up.

**Comment by matthuisman** [comment]
there are now test builds https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1454/3/artifacts for a fix to this issue

They will require Kodi 21.

Can anyone test?

**Comment by gmjh123** [comment]
> there are now test builds https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1454/3/artifacts for a fix to this issue
> 
> They will require Kodi 21.
> 
> Can anyone test?

I could test it on Android but I don't know what to install.

**Comment by matthuisman** [comment]
Code merged. Will be in the next Omega release of Inputstream Adaptive
