### ISSUE TITLE
ShineTV - NoneType error when browsing

### ISSUE THREAD

**Issue by simonsezdothis** [matthuisman/slyguy.addons#502]
Browse function not working.
Fixable?

![20230718_215550](https://github.com/matthuisman/slyguy.addons/assets/139869769/b789477c-67cf-4657-961f-e7269ab1fc88)

**Comment by matthuisman** [comment]
just pushed [slyguy.shine.tv -> v0.0.6](https://github.com/matthuisman/slyguy.addons/commit/cfa4a4965275c147b02536e056731c9c29d5602e). please update and let me know if that fixes your issue

**Comment by simonsezdothis** [comment]
Solved THANKYOU 😁
Caffeine pending.
Cheers

**Comment by matthuisman** [comment]
awesome. i gave the other stuff a bit of an overhaul too. Better season / episode numbering etc
There source data is pretty "rough" but with a bit of magic / logic can clean it up for them! haha

**Comment by simonsezdothis** [comment]
Great work!
Really appreciate your commitment to this project, and the near instant support!
Take care
Cheers
