### ISSUE TITLE
Nebula - videos listed in random order since last update

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#504]
reddit:

"
It appears that one of the changes in the last few days causes videos to be listed in random order, making it difficult to find a creator's latest videos. Maybe someone else watching could confirm?"

**Comment by gc248** [comment]
Please let me know if I can help by testing, providing logs or anything.

**Comment by matthuisman** [comment]
i think the issue is for some content - its picking sort by episode as the default view.
Changing to DEFAULT and then reloading the view fixes it

**Comment by matthuisman** [comment]
ill find a fix so workaround not needed

**Comment by matthuisman** [comment]
fixed with https://github.com/matthuisman/slyguy.addons/commit/8c7ecf6349313141f63f34ae13bb5eedaee73f68
