### ISSUE TITLE
Slyguy commons needs to be installed on Kodi 20 every day

### ISSUE THREAD

**Issue by Sobersally** [matthuisman/slyguy.addons#506]
The header says it all. I don't understand what is happening.  I went from 19.5 to Kodi 20 and everyday I turn my kodi on, I have to update slyguy common. Do you have any suggestions on what might be causing it?
Thanks!

**Comment by matthuisman** [comment]
It's simply  updated often. Turn on auto updates and don't worry about it.
Or uninstall it. Those are the choices

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/commits/master shows the updates going out
