### ISSUE TITLE
[Hulu] Playback Quality Video Tracks Missing

### ISSUE THREAD

**Issue by Liqianyu** [matthuisman/slyguy.addons#507]
Add-on Settings-Playback-Playback Quality Set to Ask,Enable H265\4K\HDR.
Some content (e.g. AHS S11) will not display all resolutions. Only the first episode displays 4K resolution, the other episodes have a maximum resolution of 1080p.
This is not a content issue, as 4K resolution can be played through the ISA's built-in stream selection menu if Playback Quality is set to disabled or bypassed.

**Comment by matthuisman** [comment]
i cant replicate. AHS S11 E1 i only get 1080p and IA only gives 4K.
Are there different subscriptions to Hulu that give better quality?

**Comment by matthuisman** [comment]
what device are you using?

**Comment by matthuisman** [comment]
oh. i see. i enabled to fake HDCP as well.

**Comment by matthuisman** [comment]
what version of KODI are you using?

**Comment by matthuisman** [comment]
right. Ive found IA's "quality select" only gives 1080p

And I know why.
AHS has a short 5s 1st period where its max quality is 1080
The 2nd period has the higher qualities.
My code and obviously theres just works on the 1st period...

**Comment by matthuisman** [comment]
ill need to think about how to approach this. I guess I can merge in all "unique" qualities I find. then whatever is chosen is set as "maximum bandwidth". Then each periods has its single video selected based on whatever is less than this quality. if none less - then just the lowest

**Comment by matthuisman** [comment]
try [script.module.slyguy -> v0.69.6](https://github.com/matthuisman/slyguy.addons/commit/7afbbb96c75c73a989e6d634af21399eea3bce05)
