### ISSUE TITLE
Foxtel Go - Android - Live channel logs not showing

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#508]

**Comment by J-a-y-B-e-e** [comment]
HI Matt,
Thanks heaps for taking a look.
https://paste.kodi.tv/zanavotobu

**Comment by matthuisman** [comment]
will be fixed now with latest round of updates :)

**Comment by J-a-y-B-e-e** [comment]
Cheers Matt, appreciate your time.
