### ISSUE TITLE
Foxtel GO - Stale Folder (not updating)

### ISSUE THREAD

**Issue by Help-Want-ed** [matthuisman/slyguy.addons#509]
23/07/2023 : Everything 'appears' to work correctly, other than the files under the Sports --> Combat Sports Folder.
A new UFC event has been uploaded and is 1st on the play list on my iPad and the video is playable.
On my Fire TV with Kodi & Foxtel GO the list of watchable programs seems stale (hasn't updated in a while). There is no latest UFC event, even last weeks Holm Vs someone else isn't visible.

If you go to the main menu, use the Search Folder and search for UFC or Fight, a small subset of the ufc videos appear, including the one I'm looking for. However the video is not playable, it gives the generic server Error -
Failed to get video asset.
Server Message: error retrieving media information. Error Code: 500.

I have a feeling it has something to do with the MAX array size of the folder, combat sports has 10529 videos? All other folders are less than 5000 videos. TV Shows --> A-Z has 4044 'All Videos', but I'm guess they are in subfolders again, by Show, and more subfolders by Season. Example, Shameless has 11 Seasons all individually listed and 11 / 12 shows in each season.

All sports are less than 2000 with League being the largest.

24/07/2023 :
Still not updated in the Combat Sport folder.
Is searchable in the search function using ufc - Appears as UFC Fight Night Aspinall v Tybura --> Season 2023 --> Prelims
                                                                                                                                                                                       Main Card

**Comment by matthuisman** [comment]
im trying this now.

The addon shows the "see all" equivalant.
I've compared to the website, and for combat - this "see all" is different to the "limited" number of results.

Can you check when you click "see all" for combat sports - if that matches the addon?

Im going to just have the addon show the "limited results" and then a link to "show all"

**Comment by Help-Want-ed** [comment]
The iPad selection is the same if I click sports, scroll down the page to combat sport and click 'see all'.
If I select Sports then scroll down the drop down list and click combat the screen loads the exact same selection.

the Add-On on Fire-TV is different.

**Comment by matthuisman** [comment]
i dont use ipad. the addon follows the same as android app.

Please try their website and see if the "see all" matches the addon

**Comment by Help-Want-ed** [comment]
Could be a Foxtel App Bug.  On MS Edge, logged in and clicked on demand --> Sport  Scroll Down to combat,  that selection looks like the latest shows.  Click 'See all' and get

<img width="311" alt="image" src="https://github.com/matthuisman/slyguy.addons/assets/140390149/561b98d0-ec17-4394-9242-4d13ec61d666">

**Comment by Help-Want-ed** [comment]
No Luck, same result :-(

**Comment by matthuisman** [comment]
what does the "limited view" give you on the website? ie. the list before you click "see all" ?
that should now match kodis

**Comment by matthuisman** [comment]
i assume when clicking "see all" you get the big in-correctly ordered 10,000 list?

**Comment by Help-Want-ed** [comment]
In the Add-on,
Or,
On Web?

**Comment by Help-Want-ed** [comment]
Failed to fetch JSON data.

Which I assume replicates the same issue the Website has.
