### ISSUE TITLE
[Disney+] Not all subtitles are available

### ISSUE THREAD

**Issue by Liqianyu** [matthuisman/slyguy.addons#51]
《Pirates of the Caribbean: Dead Men Tell No Tales》shows different subtitles in different region and displays correctly on both the app and the browser.
https://www.disneyplus.com/movies/pirates-of-the-caribbean-dead-men-tell-no-tales/7PFQVnMu2UCz

If in Singapore
![image](https://i.loli.net/2021/08/13/hkiqateIWBzlocd.png)

If in the United States
![image](https://i.loli.net/2021/08/13/JXc24dil1tE9FTD.png)

However, the add-on can only display English, Spanish, and Portuguese, and does not display Chinese (Hong Kong), Chinese (Traditional), or Korean in the United States.

*The region here refers to the network IP region, and has nothing to do with the account registration or payment region.

**Comment by matthuisman** [comment]
try selecting your profile again in kodi after changing regions

**Comment by Liqianyu** [comment]
@matthuisman 
Thankfully, when I selected Profile again, the subtitles were displayed correctly. But since I only have one Profile, I don't usually use the Profile selection feature.
I think some kind of prompt should be added for multi-region(VPN) users? Remind them that they should select Profile again after switching regions.

**Comment by matthuisman** [comment]
could just refresh the config on before every call but that adds overhead.
must users wont be switching regions like that.
maybe ill add a new setting that does that

**Comment by matthuisman** [comment]
just pushed 0.9.1
this will fetch the profile data on every view request.

**Comment by matthuisman** [comment]
ok 0.9.2 should fix it

**Comment by Liqianyu** [comment]
@matthuisman 
0.9.2 Perfect work, nice job.
