### ISSUE TITLE
[Hulu] Most actions fail with error "The JWT token is invalid"

### ISSUE THREAD

**Issue by fragmental** [matthuisman/slyguy.addons#510]
When I try to do anything in the addon I receive the error "The JWT token is invalid".  The only selections that don't have this error are logout, settings, bookmarks, and search.

**Comment by matthuisman** [comment]
logout and login again?

**Comment by fragmental** [comment]
> logout and login again?

Yeah, that worked

**Comment by fragmental** [comment]
Oops didn't mean to close it yet.  Misclicked.  You can close it if you want to, though.

I had to log out and log back in on both devices, both Windows 10, and Google TV

**Comment by matthuisman** [comment]
the addon should refresh its token. but if its not used for some time - the refresh token may also expire.

Do you know how it got into this state? just not used for some time maybe?

**Comment by fragmental** [comment]
I don't know how it got into that state.  At most it's probably been about a month since I used the addon.
