### ISSUE TITLE
TVNZ+ App

### ISSUE THREAD

**Issue by charlieglue** [matthuisman/slyguy.addons#511]
When trying to play any VOD I get the error;
TVNZ+ - Error
Could not find a media source from Brightcove Server Message: {error}

seems to be any one that i've tried so far

**Comment by matthuisman** [comment]
fixed now with [script.module.slyguy -> v0.69.5](https://github.com/matthuisman/slyguy.addons/commit/ea219f1b51817a387e0d2e40e7eb7b243b76b3f7)

**Comment by charlieglue** [comment]
thank you so much, will that auto update or do i have to force it?

**Comment by matthuisman** [comment]
should auto update within 30mins of it going out.
Or you can force update by following: https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html
