### ISSUE TITLE
Stremium error

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#512]
Stremium version 0.1.8 just started showing Widevine (installed version is 4.10.2557.0) error , trying to play some channels. The channel(s) will start playing after few seconds, in the background, with the error overlaying it.

This is the error (was trying to upload a screenshot with no luck) "Please check your Widevine CDM is up to date A Widevine CMD update dialog will appear when you play this content again Widevine Server Response: <HTML> <head><title>403 Forbidden 403 Forbidden. I double checked my subscriptions to both Stremium and Spectrum are up to date, and the Stremium app works fine on my Android TV. Thank you in advance for your advice.

**Comment by matthuisman** [comment]
Currently blocked as no access to a login with spectrum channels

**Comment by matthius7** [comment]
If I use downloader and get stremium apk and install outside of Kodi ,spectrum channels are working fine. Maybe I'll just use this route till it's sorted.

**Comment by matthuisman** [comment]
Yes. That's a good idea. I can't fix until I can test

**Comment by matthius7** [comment]
If I can help at all in the process I'll be glad to.

**Comment by matthuisman** [comment]
if you have a stremium login with Spectrum i can borrow - then that should be everything i need.
That way I can see what has changed.
See here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by matthius7** [comment]
Sent to our private chat.

**Comment by matthuisman** [comment]
that login does seem to have spectrum channels so dont think it will help

**Comment by matthius7** [comment]
***@***.***
Baracuda123+
Log into Stremuim with this. Sorry you asked for spectrum login.

**Comment by matthuisman** [comment]
that doesnt seem to work with the previous email address you provided.

Can you please email me the:

email / password for a Stremium login that has Spectrum channels attached to it

thanks

**Comment by matthuisman** [comment]
figured it out. :)

Do the Spectrum channels work via their website for you?
I see on chroma devtools - the license fails with the same error as kodi does

**Comment by matthuisman** [comment]
ill take a look at their android apps later tonight to see what they are doing

**Comment by matthius7** [comment]
***@***.***
Baracuda123+

**Comment by matthius7** [comment]
Did it work? That's stremium login info

**Comment by matthius7** [comment]
Yes the side loaded android app outside of Kodi works fine with spectrum TV. Just the addon from slyguys.

**Comment by matthius7** [comment]
And yes on stremium website it works also

**Comment by matthuisman** [comment]
now fixed with latest updates. there wv server nearly always returns a 404 error when requesting license. There apps / website will retry. my code didnt retry - but now does

**Comment by matthius7** [comment]
Your a legend sir. Thank you

**Comment by matthius7** [comment]
Can confirm after updating stremium and sly guy common and restarting .
Everything is functioning as it should through spectrum TV channels. !!

**Comment by matthius7** [comment]
Just one question. Since I have subscription for stremium I don't need a
VPN when using correct?. I know using Fen with Rd I'm ok because it only
shows connected to Rd servers and I'm subscribed there but what about live
TV. I mean spectrum is my Isp ..just unsure and I know you know the answer.
