### ISSUE TITLE
Disney+ - German film/series description

### ISSUE THREAD

**Issue by Basti83x** [matthuisman/slyguy.addons#513]
Hello.  Is it possible to set the addon language to German so that the film/series names are German?  and maybe add the description of the movies/series in German.  I have no descriptions of series and films.  I'm very satisfied with this addon, I'm only missing German.  Thank you in advance for your help.

**Comment by matthuisman** [comment]
Which add-on are you referring to.?

**Comment by Basti83x** [comment]
A sorry. On disney+

**Comment by matthuisman** [comment]
the language comes from the profile. if your Disney+ profile language is set to German - you should get series/movie names in german. 
description not possible (see https://github.com/matthuisman/slyguy.addons/issues/181)
You can use context menu to load it though

**Comment by matthuisman** [comment]
i also just pushed [slyguy.disney.plus -> v0.14.1](https://github.com/matthuisman/slyguy.addons/commit/9c3360165b265fd59cb0c9ecbe070902298287bd) which lets you override the profile language in the addon settings.

So you could set App Lanaugage to de-DE to override whatever the profile uses
