### ISSUE TITLE
slyguy.10play - 'ascii' codec can't encode character u'\u2026' in position 44: ordinal not in range(128)

### ISSUE THREAD

**Issue by bamzero** [matthuisman/slyguy.addons#515]
Encountered this error in 10play 0.1.1 while trying to view the list of episodes for Masterchef - Season 15. Other series/seasons working ok.
```
AppData\Roaming\Kodi\addons\slyguy.10play\resources\lib\plugin.py", line 191, in _parse_episode
  search = '{} {} {}'.format(row['customFields'].get('clip_title', ''), row['customFields'].get('episode_name', ''), row.get('name', ''))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 44: ordinal not in range(128)
```

Running Kodi 18.9 (same result in Windows and CoreELEC)

**Comment by matthuisman** [comment]
fixed with [slyguy.10play -> v0.1.2](https://github.com/matthuisman/slyguy.addons/commit/5a2c00410bf30b083c32ae1f3703ee4462c47f32)

**Comment by bamzero** [comment]
> fixed with [slyguy.10play -> v0.1.2](https://github.com/matthuisman/slyguy.addons/commit/5a2c00410bf30b083c32ae1f3703ee4462c47f32)

Thanks for the quick fix!
