### ISSUE TITLE
[Bug] ListItem.Plot not empty when no plot available ("[B][/B]")

### ISSUE THREAD

**Issue by jurialmunkey** [matthuisman/slyguy.addons#519]
When plot is empty, the plugins still add bold tags to ListItem.Plot `"[B][/B]"`

This causes issues for skins relying on checking `String.IsEmpty(ListItem.Plot)` as Kodi will evaluate that boolean to false despite `$INFO[ListItem.Plot]` returning no text. That prevents skins from providing a fallback label or a different layout when plot is empty.

I'm assuming this is due to an fstring adding the tags without checking if the plot actually has text.

I've noticed this in Stan and BiNGe plugins but I'd imagine it is elsewhere as well

**Comment by matthuisman** [comment]
I intentionally did that ages ago to hide the "plot empty" tag Kodi / skin adds as I think it looks "ugly" on the default skin anyway. Haven't heard any issues with doing it until now. Can you show screenshots,?

**Comment by jurialmunkey** [comment]
Kodi doesn't add a "plot empty" tag. That sounds like a skin specific issue that should be addressed in that skin.

In one of my skins I check `String.IsEmpty(ListItem.Plot)` and if empty I instead show the addon description so that I don't have a massive blank space. With your plugins I can't do that.

Here's how it looks currently because of the hack forcing a value in plot:
![screenshot00109](https://github.com/matthuisman/slyguy.addons/assets/4618719/a64ccd49-a3b9-4e5d-8947-658b3e7cfe41)

Here's how it should look when I can properly check for empty plot and display a fallback addon description:
![screenshot00110](https://github.com/matthuisman/slyguy.addons/assets/4618719/30bdca0f-ec6d-48d0-ada5-9fe874922821)


Side note: Your Container.Content type here is incorrectly listed as "videos" when the container does not contain videos. Incorrect content and mediatypes are also massive issues for skins as can be seen here where my skin is forced into displaying landscape aspect ratio (because the plugin reports videos) when it should display square (content type should be none because it is a menu folder and doesnt contain any playable content).

**Comment by matthuisman** [comment]
again with content type - its to make it show in the default skin less ugly-like

**Comment by matthuisman** [comment]
is there a way i can set art to show on the left but then set the folder icon to None?

**Comment by matthuisman** [comment]
[script.module.slyguy -> v0.69.8](https://github.com/matthuisman/slyguy.addons/commit/a02cb2f5ed73b855717dd4d5610fedd3c80d694e) just pushed that makes no content type for menus and removes the non-empty plot.

Added a setting to re-enable that behaviour if desired by end users

**Comment by jurialmunkey** [comment]
Thanks, much appreciated!

> is there a way i can set art to show on the left but then set the folder icon to None?

Possibly, but anything like that is going to be a hack which involves inputting incorrect metadata -- e.g. putting the icon into the poster artwork type instead will likely do that (fairly sure Estuary uses [this variable](https://github.com/xbmc/xbmc/blob/89cc33615d0c755daa69adb4ae4b583d80bb6eac/addons/skin.estuary/xml/Variables.xml#L75-L81) for the side panel) but the problem is that will then cause issues for other skins which expect art(poster) to be a poster.

> Added a setting to re-enable that behaviour if desired by end users

I'd say that's the best approach.

**Comment by matthuisman** [comment]
if too many complain - ill swap to that setting being enabled by default and users who use different skins that display better can disable it. see how we go :)

**Comment by jurialmunkey** [comment]
No worries. My main concern was the formatting tags anyway because it's impossible to check for them properly in a skin -- the skinning engine uses square brackets for grouping boolean conditions, so something like `String.IsEqual(ListItem.Plot,[B][/B])` will throw out a bunch of log messages about invalid conditions.
