### ISSUE TITLE
setDateTime on ListItems

### ISSUE THREAD

**Issue by iamsix** [matthuisman/slyguy.addons#524]
For any item that has 'aired' info can you do `setDateTime` on the ListItem so that things like Yatse when accessing via the API can sort by 'date' and get the correct episode order (especially for things like Nebula where there's no episode number to sort by)

As a very rough test I added 
`            li.setDateTime(item.info.get('aired'))` after [plugin.py#L702](https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/plugin.py#L702) which does make it work perfectly

Note [setDateTime](https://xbmc.github.io/docs.kodi.tv/master/kodi-base/d8/d29/group__python__xbmcgui__listitem.html#ga7d0eddeb80786c99c5a83cf164dd68e1) is new as of v20 however, so probably needs to be version gated.

**Comment by matthuisman** [comment]
[script.module.slyguy -> v0.70.3](https://github.com/matthuisman/slyguy.addons/commit/6b7dcc61839bc71a1111b2f126e25915c3b05fba) should fix that for you

**Comment by iamsix** [comment]
It looks like it's definitely doing setDateTime but it's apparently not correctly setting it.
The JSON-RPC API used to return:  
`'lastmodified': ''`  
After this change it returns:  
`'lastmodified': '1969-12-31 23:59:59'`  
With my hack it was returning:  
`'lastmodified': '2023-04-26 12:00:05'`  
(this matches the actual video posting date on nebula)

**Comment by matthuisman** [comment]
strange. ill take another look

**Comment by iamsix** [comment]
When I was testing this, despite that Kodi documentation saying that YYYY-MM-DD etc are supported, anything but the example format, and the `str()` of an `arrow` time seemed to produce that default date.

**Comment by matthuisman** [comment]
im confused, the latest code just takes the aired and does li.setDateTime() with it.
The dates are like 2023-08-12T15:42:18+00:00

So i cant see any difference to your workaround

**Comment by Kampfader** [comment]
@matthuisman 
the error still exists.

go to the Serie "The Mandalorian --> Extras" = Error

![081623143013](https://github.com/matthuisman/slyguy.addons/assets/23200748/b030eb7b-fde8-4a14-b886-c7b2e860f904)

**Comment by matthuisman** [comment]
@Kampfader now fixed
