### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by austreams** [matthuisman/slyguy.addons#525]
with the new common/dependencies update i am getting unexpected error on all addons (disney,stan,etc). 
xbmc.info tag video object has no attribute “set date time”

**Comment by matthuisman** [comment]
What version Kodi?

**Comment by austreams** [comment]
20.1

**Comment by matthuisman** [comment]
fixed in [script.module.slyguy -> v0.70.4](https://github.com/matthuisman/slyguy.addons/commit/114012167a1b30844c2bdb6bd002d790f9dda5d9)
