### ISSUE TITLE
Nebula - Opening any list of video items throws Unexpected Error

### ISSUE THREAD

**Issue by ThubLives** [matthuisman/slyguy.addons#526]
Over an hour ago, I saw the SlyGuy logo in the toast pop-up appear and disappear, indicating an updated component.  Kodi froze and apparently crashed (restarted automatically on LibreELEC v11.0.3 on Raspberry Pi 4).  After a restart, opening any list of videos in the Nebula app (e.g. xxx) results in an Unexpected Error message identifying "Nebula (0.2.8/0.70.3)":

> AttributeError: 'xbmc.InfoTagVideo' object has no attribute 'setDateTime'

I have already tried uninstalling and re-installing all SlyGuy add-ins from the repository and resetting the configurations.  See the attached log.
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/12268814/kodi.log)

**Comment by matthuisman** [comment]
fixed in [script.module.slyguy -> v0.70.4](https://github.com/matthuisman/slyguy.addons/commit/114012167a1b30844c2bdb6bd002d790f9dda5d9)
