### ISSUE TITLE
unable to update slyguy common

### ISSUE THREAD

**Issue by austreams** [matthuisman/slyguy.addons#527]
kodi 20.1 is not automating the update slyguy.common i tried manual also and nothing happens.

**Comment by matthuisman** [comment]
maybe the cache was old. ive purged that. should be ok now

**Comment by ebuckland81** [comment]
May need to re-open this issue? The latest version (v0.70.4 or v.0.70.5?) of the common scripts still won't update, either via auto-update or manually, at least in my setup. Info screen for manual update says three updates available and will be installed shortly, though there is no accept button and no update is executed.

My setup is: 
slyguy repository is 0.0.8, Kodi v. 20.1.0, common scripts v.0.70.3. Device is Rock 4 SE. LibreElec 11.0.1.

**Comment by matthuisman** [comment]
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

Navigate down to "add-ons won't update"

**Comment by ebuckland81** [comment]
Tried all those instructions a couple of times, but it worked now 👍😁 Great!

**Comment by matthuisman** [comment]
Hmmmm. Maybe your os doesn't allow updating more than once every 24hours?
