### ISSUE TITLE
IPTV AU - Commercial Channels not Showing

### ISSUE THREAD

**Issue by V0RTX** [matthuisman/slyguy.addons#531]
I've got KODI on my smart TV and Android phone, both are new devices.  ABC, SBS are working, but 10, 9, 7 are not.
Kodi version 20.2 and SlyGuy IPTV AU version 0.19.1
I am outside Australia.
I have tried with both VPN and no VPN.
Appreciate any info to support this issue
Thank you

**Comment by matthuisman** [comment]
they are all geolocked. They are also probably blocking your VPN.
All you need to do is try their own websites or apps to confirm they also dont work

**Comment by V0RTX** [comment]
That's sad.  Thanks for the prompt reply.
