### ISSUE TITLE
Disney+ install widevine error

### ISSUE THREAD

**Issue by RoboMod** [matthuisman/slyguy.addons#54]
First: thanks for all those great Kodi addons!

I got an issue with the Disney+ add-on on Kodi 19 running on OSMC. When I try to install Widevine I get the following message:

![IMG_20210814_123922](https://user-images.githubusercontent.com/1662655/129478976-7985ff5c-0455-4a24-aa29-cef5723c3711.jpg)

`
KeyError: 'version' 
File "language.py", line 15, in format_string  
string = string.format(*arcs, **kwargs)   
File " language.py", line 195, in __call__
return format_string(string, *arts, **kwargs)
File "inputstream.py", line 263, in install_widevine
wv['label'] = _(_.WV_INSTALLED, wv['label'])
File "plugin.py", line 295, in _ia_install 
inputstream.install_widevine(reinstall=True)
File "plugin.py", line 65, in decorated_function
item = f(*arcs, **kwargs)
File "router.py", line 117, in dispatch
function(**params)
File "signals.py", line 31, in throwable
yield
`

Any ideas about that issue?

Best, RoboMod

**Comment by matthuisman** [comment]
fixed with slyguy common 0.40.6
you can force update by following the below:
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by RoboMod** [comment]
I'm sorry but I have 0.40.6 installed.

**Comment by matthuisman** [comment]
i only pushed that 10mins ago...
