### ISSUE TITLE
Disney+ widevine licence request failed

### ISSUE THREAD

**Issue by zanshem** [matthuisman/slyguy.addons#544]
Error: Kodi 20.2, Android 13 and Fire TV

![Screenshot_1_Kodi](https://github.com/matthuisman/slyguy.addons/assets/132759901/c872a75a-5746-41f7-bcc4-c738bd1ae40f)

On Android, the update of Widevine CDM is not available in the Slyguy common addon:

![Screenshot_2_Kodi](https://github.com/matthuisman/slyguy.addons/assets/132759901/140982c3-91f6-414d-8e6b-7ff2a9a0dcfe)

![Screenshot_3_Kodi](https://github.com/matthuisman/slyguy.addons/assets/132759901/51f18249-d97a-4c4f-a2d7-8e8bc7fde66a)

On Android, the update of Widevine CDM is not available in the Slyguy common addon.

**Comment by matthuisman** [comment]
Android has widevine builtin. I suspect your android version is now too
old. You could test with the official d+ android app to confirm

**Comment by zanshem** [comment]
The official D+ app plays the content smoothly.
By the way, your HBO Max addon runs perfectly in the same devices. If the problem was with my Android-version, HBO Max wouldn't work either.
Country:Spain. A non 4K-subscription in Spain is not available
Thank you for your interest.

**Comment by matthuisman** [comment]
Can you send me a screenshot of what subscriptions they offer there?

**Comment by zanshem** [comment]
In Spain, as in many EU countries, a subscription is not possible depending on the resolution. 
2 subscriptions are offered: 8.99 € monthly or 89,90 € for one year.
Such a screenshot is not visible on the website. Sorry

**Comment by matthuisman** [comment]
Do you get same error if selecting a 720p quality?

**Comment by zanshem** [comment]
Yes

**Comment by matthuisman** [comment]
Can your display do 4k? Error suggests to me that it's saying the android system can't handle 4k and to downgrade to 1080

**Comment by zanshem** [comment]
My Display do 1080p. When I adjust the resolution to 1080p, the same error happens.

**Comment by matthuisman** [comment]
I asked about 4k :)

**Comment by zanshem** [comment]
My Display can´t do 4k.
I have found a solution: Disable HDR10/4k.
Thank you for your advice!

**Comment by matthuisman** [comment]
Excellent :) 
Unfortunately kodi doesn't have a way to detect if a device has capabilities so I need to have it as a setting

**Comment by zanshem** [comment]
Then I hope I have helped with the development. 
The issue can be closed.
