### ISSUE TITLE
No Dolby 5.1 in Disney+ Kodi Addon

### ISSUE THREAD

**Issue by pr0gstar** [matthuisman/slyguy.addons#547]
Disney+ app for my Sony android TV is not giving me Dolby 5.1 anymore so I tried using this addon but Dolby is here also not working

**Comment by matthuisman** [comment]
what content for example? if there official apps stopped, then maybe its something their end?

**Comment by matthuisman** [comment]
i just tested with guardians of galaxy vol3 and i get DD+ 5.1
![image](https://github.com/matthuisman/slyguy.addons/assets/6225961/c90137b1-bdf3-43c0-9528-febcca03087a)

**Comment by matthuisman** [comment]
check you have DD+ enabled in slyguy common settings

**Comment by pr0gstar** [comment]
Thanks @matthuisman I will check with guardians 3 later today. Yesterday with mandalorien it didn't worked. And I will check the DD+ setting in the addon.

**Comment by pr0gstar** [comment]
I already selected the DD+ sound of the movie. Tried it with guardians 3 but still only Stereo.
I searched for the DD+ setting in the addon but it isn't there.
I use an Android TV from Sony, maybe this is relevant. Other apps like Amazon prime is working great with Dolby sounds

**Comment by matthuisman** [comment]
So you can see and select the dd+ audio track but it doesn't work? Or you
can't see it at all?

**Comment by pr0gstar** [comment]
I can see it and select it but my Soundsystem tells me that it gets stereo Audio

**Comment by matthuisman** [comment]
Oh ok. Suspect something outside of add-on then. Could be Kodi. Could be
device. If you open the Kodi osd, it should show you how many audio
channels.

Also check Kodi audio settings. You may need enable passthrough etc

Anyway, closing this issue as not addon issue
