### ISSUE TITLE
[Sky Sport Now] Sky Sports 1 not loading.

### ISSUE THREAD

**Issue by Major87** [matthuisman/slyguy.addons#549]
For some reason Sky Sports 1 is not loading on the Sky Sports Now kodi addon. All other channels work all righ. I've also confirmed it's not a Sky issue as it plays on the SS Now phone app.

**Comment by matthuisman** [comment]
i dont have a sky sport now login to use for testing anymore unfortunately :(
I suspect it would be a simple fix if I could access the content to test.

Please see here https://www.matthuisman.nz/2018/06/looking-for-logins.html if you can help with that

**Comment by matthuisman** [comment]
Ive just tested and I cant reproduce the issue.

All Sky Sport Now channels showing as 1080p for me and play fine.

Could someone please provide a Kodi debug log showing the error.
Also, a log showing playing another channel that only has 720p would be interesting.

Make sure your running latest version of the addon as well which is [0.5.6](https://github.com/matthuisman/slyguy.addons/commit/5304040a172477047e1a11d2744054af72a359ea)

**Comment by DavidCNZ2** [comment]
And now it's working fine for me. I admit I hadn't tried it since Saturday morning, I had to failover to watching All Blacks vs France on a laptop. Sky Sport 2 was the same game at 720p with Te Reo commentary and it worked whereas Sky Sport 1 would just sit with spinning circles for a minute and then just revert back at the selection menu, no visible error. I'll try on another world cup game and if it fails I'll start logging.

**Comment by retiredbum** [comment]
i finally was able to fix the problem with the skygo live section not being able to play any channel........I dissabled the option SlyProxy in SlyGuy Common addon....this also worked for TVNZ+ addon....

**Comment by matthuisman** [comment]
@retiredbum what are your inputstream.adaptive settings set to?
can you provide 2x debug kodi logs of TVNZ+ without proxy (working) and with proxy (not working)
Same content etc. only difference is proxy on/off

**Comment by retiredbum** [comment]
I have no vpn or proxy settings....the same issue applies to skygo live section and several channels on nz freeview addon...and for some reason trackside2 will play on smplayer now and not just kodi...here are the debug kodi files you asked for.
https://ln5.sync.com/dl/15a5150f0/25xwf488-8ykx577r-i8u8t8v5-a96rz3zd     tvnz+without proxy
https://ln5.sync.com/dl/312135340/ztxipn6r-qmrmwd6e-amhr2cm8-ypjjxssf   tvnz+with proxy

**Comment by retiredbum** [comment]
https://ln5.sync.com/dl/15a5150f0/25xwf488-8ykx577r-i8u8t8v5-a96rz3zd
https://ln5.sync.com/dl/312135340/ztxipn6r-qmrmwd6e-amhr2cm8-ypjjxssf

**Comment by matthuisman** [comment]
do you recall when TVNZ was last working OK with proxy?

**Comment by retiredbum** [comment]
the issue with tvnz has only just happened in the last 3 to 4 days ago

**Comment by matthuisman** [comment]
also happening on Kodi 20? or do you only run Kodi 21?
Not sure if I tested with 21 originally

**Comment by retiredbum** [comment]
i happens on both versions of kodi...i also tried another pc and same issue will those addons

**Comment by retiredbum** [comment]
you have any idea what the issue could be regarding those addons?

**Comment by matthuisman** [comment]
Not yet. What channels on IPTV NZ also don't work with proxy enabled?
Trying to find common connection

**Comment by retiredbum** [comment]
tvnz 1, tvnz 2,  duke,  three sport.....those are the ones that don't work with proxy enabled

**Comment by retiredbum** [comment]
Hi..Great work in fixing the tvnz+ and nz freeview addons..both work great now...any chance at looking into the skygo live tv section as it also had the same issue with playback....if i do dissable slyguy proxy it only plays for about 30 seconds then picture freezes and there is only audio...

**Comment by matthuisman** [comment]
**I didnt make any changes to fix tvnz or nz freeview.**

**Comment by retiredbum** [comment]
good news then ..all the channels on those 2 addons all play perfect now......i have played skygo live tv on kodi 18.3 with slyguy proxy turnned off and so far no problems...what does a proxy do?

**Comment by theccap10** [comment]
I'm having the same issue with Sky Sports Now. Sky Sports 1 often stalls. Seems quite random. Usually when I want to watch something significant :). It Just has the "working" spin and halts eventually.
Log here https://pastebin.com/5ssN5kzH
Haven't changed anything.

**Comment by DavidCNZ2** [comment]
Same for me today for the world cup game, it happened for the first All Blacks game but has been fine since until today. I tried signing out and back in again but still the same. Worked fine on the TV app and on the mobile app.

**Comment by theccap10** [comment]
Just tried a fresh install on another platform (windows) same problem. Intermittent but more often than not.
