### ISSUE TITLE
Disney+ Error

### ISSUE THREAD

**Issue by UnclePsymon** [matthuisman/slyguy.addons#55]
Hi there, i got that error:

![Bildschirmfoto von 2021-08-16 13-39-11](https://user-images.githubusercontent.com/86851905/129558235-8fd7b25a-2081-4cd7-aa38-e577a4c4e4a4.png)
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/6995384/kodi.log)

Everything else works fine. I can watch Disney+ with the addon or in my browser. I am not geo-blocked and I do not use a VPN. 

Thx!

**Comment by matthuisman** [comment]
Full debug log please

**Comment by UnclePsymon** [comment]
Sorry, my first upload did not work

**Comment by matthuisman** [comment]
also looks like your using widgets... they can become outdated.

please only send me errors / logs when using the actual add-on.
I won't respond to widget issues
