### ISSUE TITLE
[skygo] Live playback failed

### ISSUE THREAD

**Issue by retiredbum** [matthuisman/slyguy.addons#551]
the live section of skygo has not being working for 2 days now

**Comment by matthuisman** [comment]
please provide a full kodi debug log.
Upload to sharing site and paste link here

**Comment by retiredbum** [comment]
> please provide a full kodi debug log. Upload to sharing site and paste link here

https://ln5.sync.com/dl/bebd354c0/5t32bqam-3tp72ga9-9vgzqrxa-3u4rbx4t

**Comment by matthuisman** [comment]
are you physically in NZ?

https://prod-skyonelive.akamaized.net/sky-sport-1.mpd  is giving 403 forbidden error.

I can download the above file without issue in my browser.
I havnt tried kodi addon yet - but it worked Saturday morning for me.

If the above file wont download in your browser on your vpn - then you have the answer

**Comment by retiredbum** [comment]
hi...im in new zealand  https://prod-skyonelive.akamaized.net/sky-sport-1.mpd does download in my browser..but fails to play in kodi...i have no vpn.

**Comment by matthuisman** [comment]
ok thanks. they may be blocking user-agent from kodi then.
ill try get fixed tonight. should be easy enough

**Comment by retiredbum** [comment]
thanks for your help and great work.......

**Comment by matthuisman** [comment]
i have just tested on windows x64 and works ok. strange.

Is is it still failing for you?
No smart DNS involved anywhere?

**Comment by matthuisman** [comment]
looking at your github - it does appear you do deal with vpns / smart dns.

I even tried with Nord VPN NZ server and get the same error / behaviour

I dont like my time being wasted when you say your not using a vpn.

**Comment by retiredbum** [comment]
hi again...sadly still the same issue with skygo addon (just live section) every thing else works fine with addon..also tvnz+ also has same problem..also in the live section of skygo addon and tvnz+ i am not getting asked the option of stream quality..but i do get that option in rest of addon....no smart DNS involved...and this has only started happening in last few days



***@***.***
 
From: Matt Huisman
Date: 2023-09-11 18:12
To: matthuisman/slyguy.addons
CC: retiredbum; Author
Subject: Re: [matthuisman/slyguy.addons] [skygo] Live playback failed (Issue #551)
i have just tested on windows x64 and works ok. strange.
Is is it still failing for you?
No smart DNS involved anywhere?

**Comment by matthuisman** [comment]
cant help sorry if i cant reproduce

good luck!
