### ISSUE TITLE
Feature: Allow changing empty folder to a notification instead of the popup

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#554]

**Comment by wlincpdjhbxz** [comment]
added a PR for this

https://github.com/matthuisman/slyguy.addons/pull/566

**Comment by matthuisman** [comment]
[v0.72.5](https://github.com/matthuisman/slyguy.addons/commit/3b04792019bc98953f60a03ee26d2811f524824c)
