### ISSUE TITLE
[Udemy]I can't watch the course on my mac

### ISSUE THREAD

**Issue by hollimaple** [matthuisman/slyguy.addons#556]
I am having trouble viewing the course on my mac.
I can watch it via web or apps, so I'll give up if there is no workaround.

It seems to work fine on Android.

Suspicious errors are as follows.
2023-09-16 09:33:12.294 T:709591   debug <general>: AddOnLog: inputstream.adaptive: LogDecryptError: Decrypt failed with error: 2 and key: 0B4E53C6D7EE4EFFAAFE81A3E917BAD2

Chip: Apple M2
macOS:Ventura 13.5.2
Kodi:20.2

<img width="1284" alt="スクリーンショット 2023-09-16 9 33 01" src="https://github.com/matthuisman/slyguy.addons/assets/5407800/91eb8513-1819-4e1e-810b-9d6416e6030c">

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/12629490/kodi.log)

**Comment by hollimaple** [comment]
I think it's the same reason, but it doesn't work on windows either, so any way to watch it would be great.
![スクリーンショット (2)](https://github.com/matthuisman/slyguy.addons/assets/5407800/48af65b8-905b-4488-9eed-6afd9af6602a)

**Comment by matthuisman** [comment]
The message explains it. Can't work on Kodi unless android. Just use your
browser instead?

**Comment by hollimaple** [comment]
I just wish there was a way to run it on Kodi, so I am not particularly troubled by the browser.
Thanks for the confirmation.
My apologies.
