### ISSUE TITLE
Can't login to Kayo

### ISSUE THREAD

**Issue by jamesgallagher** [matthuisman/slyguy.addons#557]
I've got an issue with the Kayo app. It started with getting intermittent WideVine warnings being shown. A suggestion was made to re-install so after reinstalling WV, I reinstalled the entire plugin. I now cannot log in at all ( https://imgur.com/a/C2NAANe )

I have tried the Kayo app and it works fine so there shouldn't be a connectivity issue (and I reside in AU). I can replicate the issue on my PC. Below is the log from a single session of trying to open Kayo (on Nvidia Shield) and attempt login. 

https://paste.kodi.tv/gokiyizive.kodi

A second log from the same process, but instead using a PC instead. 

https://paste.kodi.tv/vuxurusexa.kodi

Apologies if I am missing anything, I haven't had to look into logs before so this is a first. If I have attached the incorrect logs, please let me know and I'll do it again.

**Comment by jamesgallagher** [comment]
Including debug logs
[PC]
https://paste.kodi.tv/oxekahaxin.kodi

[Shield]
https://paste.kodi.tv/adejiwukeh.kodi

**Comment by matthuisman** [comment]
please try with v0.14.6 (just pushed)

**Comment by jamesgallagher** [comment]
Updated to v1.14.6 and v1.14.7 and log-in works now, but the video fails to play.
https://paste.kodi.tv/oyelibeluq.kodi

**Comment by matthuisman** [comment]
please try [v0.14.8](https://github.com/matthuisman/slyguy.addons/commit/d93933a68546633aa7034eea7c0aec86e6587bfd)

My private vpn i use is down so im sort of doing these "blind"

**Comment by jamesgallagher** [comment]
You're a legend, working fine (on my very short test). Was this anything to do with the WV issues early this week?

**Comment by matthuisman** [comment]
i think could be related... not 100% though :)
