### ISSUE TITLE
Scandinavian Samsung TV Plus channels

### ISSUE THREAD

**Issue by CHJ85** [matthuisman/slyguy.addons#561]
Hi. Please add Samsung TV Plus channels for Sweden, Denmark and Norway.
Thanks.

**Comment by matthuisman** [comment]
i can only add countries that are available on the official android app
If they are - then let me know

**Comment by CHJ85** [comment]
Thanks.

**Comment by matthuisman** [comment]
you could try this guy:
https://forums.whirlpool.net.au/thread/9nk6qzy3
He manually creates them :)

Im all about automation - so until they are available via the android app api - I cant automatically grab them.
No one has figured out the api the samsung tvs use :(

**Comment by CHJ85** [comment]
Right. Idk if they're available through android yet.

**Comment by CHJ85** [comment]
What about the Australian and/or New Zealand versions of Samsung TV Plus channels?
Are any of them available? I don't have a Samsung device, so I wouldn't know.

**Comment by matthuisman** [comment]
again, the android app isnt in nz/australia either

https://forums.whirlpool.net.au/thread/9nk6qzy3
his website has nz and au i believe
