### ISSUE TITLE
Optus Sport EPL  streams only 720p?

### ISSUE THREAD

**Issue by Bob-git1** [matthuisman/slyguy.addons#562]
Hi, I'm using Kodi 20 Nexus on a 4k Chromecast with Google TV and the EPL streams on Optus Sport addon are only 720p whereas the Live channel is 1080p? Not sure if others have this issue?
Also just checked official Optus Sport app and it is 1080p.

**Comment by matthuisman** [comment]
existing issue: https://github.com/matthuisman/slyguy.addons/issues/505
