### ISSUE TITLE
Add UniqueID support for InfoTagVideo in gui under slyguy common

### ISSUE THREAD

**Issue by wlincpdjhbxz** [matthuisman/slyguy.addons#568]
Currently there is no support to set a unique id for a List Item's Info Tag when adding items via plugin.Folder

After some back and fourth I found the best place to add it would be in gui under class Item

With that it would accept 1 additional parameter unique_ids=None (after dns_rewrites) here https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/gui.py#L222

Then apply them to the Info Tag under the requirement of Kodi Version >= 20 here https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/gui.py#L305

It all "seems" quite good except the existing function in listitem does not actually work, that function is here https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/listitem.py#L215

So, my solution is a little more involved, functional but I think it merits discussion before I submit anything for it.

Here is the code I added -

```
infotag = ListItemInfoTag(li, 'video')
infotag.set_info(info)
defid = True
for unique_id in self.unique_ids:
    infotag._info_tag.setUniqueID(str(self.unique_ids[unique_id]),unique_id,isdefault=defid)
    defid = False
```

That code would be inserted here - https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/gui.py#L309

and of course in __init__ of class Item there would be the additional parameter 'unique_ids' and an additional line at the end of the __init__ self.unique_ids = unique_ids or {}

Let me know your thoughts on this.

I am working on a few different things that would utilize this but I am trying to nail down the back end before proceeding.

**Comment by matthuisman** [comment]
what are unique ids used for?

And what are you working on? curious

**Comment by wlincpdjhbxz** [comment]
There are 2 main things right now I am working on

1 - Trakt API client
2 - Library Importer

The initial abandoned one I wrote is here - https://forum.kodi.tv/showthread.php?tid=374003

As far as the Unique IDs, when scanning items into the library Kodi will use the UniqueID from the Info Tag to insert it into the database. Without one set on the Info Tag it will be NULL in the database and causes issues.

As well, all my code is based around TMDBv3 API and I use the TMDB ID which then needs to be set as the UniqueID - irregardless of import.

I am reworking my addon to use your common framework because after we spoke in the other thread and I wrote a function in mine to test your framework I realized it was far better than mine and mine might have a second chance if I do.

It's all base work right now but I am planning on splitting the addon into 2 separate ones to serve each function.

**Comment by matthuisman** [comment]
oh, you are [jepsizofye](https://forum.kodi.tv/member.php?action=profile&uid=477027) on kodi forums?

**Comment by wlincpdjhbxz** [comment]
yes that's me

**Comment by matthuisman** [comment]
oh right makes sense.

how are you planning on using my framework?
Will you add a dependency and just bring in slyguy common / dependencies ?
Its not really designed as a framework for external use as I often make breaking changes and update addons as needed.
i try keep those minimal though

**Comment by wlincpdjhbxz** [comment]
Not heavy use, this is about all right now...

`<import addon="script.module.slyguy" version="0.63.1"/>`

`@plugin.route()
def parseTrending(res,refresh=False):
    folder = plugin.Folder("Trending")
    # retrieve/parse data
    folder.add_item(info=movieinfo,
                properties={'id.tmdb': tmdbid},
                unique_ids={'tmdb': tmdbid},
                art=artwork,
                path=url,
                playable=True)`

the items when played will just use setResolvedUrl

I don't see you changing anything that would break that, it would break most of your other addons - but if it did happen I would just update.

**Comment by wlincpdjhbxz** [comment]
On the other side of the coin though, the Library Import addon is being used by me specifically with your Hulu, Disney+ and Paramount+ addons to bring titles directly into Kodi.

If my code was using your code to import from your addons - there would be no reason you couldn't pull the code over, assuming it was up to par.

**Comment by matthuisman** [comment]
id like library export to come into my slyguy common eventually so all my addons just support it out-of-the-box :)
so would be interested in your code.

By biggest issue initially was that it relied on the filename created.
Be good if the name of movie could be in the nfo file itself and filename irrelavant.
I didnt want to have to do the utf-8 title to valid filename muck around

**Comment by wlincpdjhbxz** [comment]
It's not an export per se.

The current iteration I am working from keeps a bookmarks.json file instead of individual NFOs

A typical bookmark has 4 primary parts :

Title - The displayed title
Path - The internal path that setResolvedUrl is set to.
Folder - 0 or 1 to indicate whether it should be displayed as a movie or a tv show.
IDs - A dict of IDs for the entry, the only required one is TMDB but I have used Hulu EAB and a Disney+ content_id additionally in testing.

The bookmark entry is created from a context which uses the current sys.listitem to get title and year then looks up the TMDB ID with my TMDB APIv3 Module.

The latest version of the code presents a list of search results when the result count is > 1 so that a user can select the correct item from TMDB. This list shows the poster, title, year and language as returned in results.

When you list the path from the addon plugin://plugin.video.integrate/movies in Kodi, it parses out the bookmarks, ignores folder=1 (non-movies) and looks up the information for the Movie from TMDB which is added to the ListItem for Kodi to pickup when scanning with "Local Content Only". The source is setup in sources that points to plugin://plugin.video.integrate/movies with the content set properly.

The TMDB Scraper I have setup is using a parallel cache in a SQLite DB in it's addon_data folder.

The logic is if it's cached, return the cached item, if not return the result from TMDB. With an exception that "refresh=True" can be passed to the lookup function to ignore cache and reload from TMDB.

There is also caching for artwork, episodes cache grouped by season - showid_s01 = [{episode_dict: ep01},...] so that un-flattened seasons can be displayed or flattened either way.

Playback items are tagged by ID and resolved internally from the DB - PlayMedia(plugin://plugin.video.integrate/movies/?tmdbid=603) is all that is needed.


What I am trying to nail down here is listing enough information so that when scanned into Kodi an item will be indistinguishable from a physical item on disk.

**Comment by wlincpdjhbxz** [comment]
Rinse and repeat (many times) for Shows and Episodes.

**Comment by wlincpdjhbxz** [comment]
I looked into what would be required to add this directly into the SlyGuy common module.

It is doable, the common module would be able to serve the single entry points for /tvshows and /movies

Router needs an update to be able to route to the correct location based on one of those paths, currently if you tried to access plugin://script.module.slyguy/movies or /tvshows it re-routes to ?_=_settings

That entry point can be a new python module serving only that function as to keep the code compartmentalized and manageable.

Then there would need to be a back end function that your addons can call which would add a bookmark and cache the information, the bookmarks and cache can be saved by script.module.slyguy and into it's own addon_data folder so it would be global and independent of whichever addon is installed or called it.

There is still a need for a Unique ID but if shows, episodes and movies are imported internally from an addon it would technically have enough information already to add them to the Kodi library without a TMDB module, just not as nice because providers don't provide the same level of metadata or artwork.

A staged rollout might be to add TMDB scraping as an "Extended Info" feature from common so that even without importing you could browse Hulu, etc. and have clearlogos, cast and information like you would in the Kodi library.

In my own addon, there is barely a difference between direct listing content and listing looked up content, perhaps an additional ~500ms per item and you paginate to a low item count. My tests are fast and I choose to list 100 items per.

I am not familiar enough with your code to be able to add any of that unfortunately, I attempted to add to the router so it would handle the paths and it was not good.

Bare minimum, let's get the back end code for Cast and UniqueIDs working.

**Comment by matthuisman** [comment]
Router does have support for /movies etc now. Pretty sure you just need to
have the path you provide to the route decorator start with /

**Comment by wlincpdjhbxz** [comment]
With that, I tried again -

Duplicated def home from here - https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/lib/plugin.py#L12

changed the plugin.route('') to plugin.route('/')

and it only serves to further demonstrate I don't know your code

when accessing '/' specifically it will very briefly display added listitems but then redirects or exits and you are then looking at the generic Kodi files

when accessing '/movies' it still goes there but shows a message from your addon that the path was not found

**Comment by matthuisman** [comment]
oh, itll because your not using the new style "default.py"

Use the below in default.py (yes - 2 lines)
```
from resources.lib.plugin import plugin
plugin.dispatch()
```

**Comment by wlincpdjhbxz** [comment]
That is certainly workable with the modification to default.py

I am putting together a demo that will list 1-2 'static' movies (since they are the easiest) so you can see the import side of things and how it would be implemented from within the common module.

From there shows are not too bad but I have not ported any of that code to your framework yet, episodes are no fun but not insanely difficult.

Once it can list content for Kodi to import I will probably have a better idea how to facilitate the creation of the bookmarks to list. Likely start with Hulu as they offer a lot more information and it's faster.

-----

Looking forward to what it looks like you are working on there, here is what I did for trailers ...


```
import xbmc

if __name__ == '__main__':
    args=sys.argv[2].split("&")
    for arg in args:
        if "video_id" in arg or "videoid" in arg:
            vid=arg.split("=")[1]
            break
    playurl = "https://www.youtube.com/watch?v={}".format(vid)
    xbmc.log("YouTube Trailer URL {}".format(playurl),1)
    if hasattr(sys, 'getandroidapilevel'):
        playtube = 'StartAndroidActivity(,android.intent.action.VIEW,,"%s")' % playurl
        xbmc.executebuiltin(playtube)
```

yes, it is just calling android to play a trailer via the installed app as a 'deeplink'

**Comment by matthuisman** [comment]
thats what i need. I was wondering how to make the builtin youtube player
use my android youtbe to play!!

I was going to try use yt-downloader to just play the damn things without
logging in.
Calling external youtube be easier (but only works on android)

But that could be my first release

1) drop-in replacement for builtin youtube addon so skins work without mods
2) user-option to allow playing using android youtube app
3) enjoy life

**Comment by wlincpdjhbxz** [comment]
I have a demo up for movies, not set in concrete just a functional 'demo'.

Takes a little bit of setup since the front-end code hasn't been written yet.

Add additional modules - https://github.com/wlincpdjhbxz/slyguy.addons/tree/master/script.module.slyguy/resources/modules/integrate

The modules are self-contained but need an import - https://github.com/wlincpdjhbxz/slyguy.addons/blob/master/script.module.slyguy/resources/lib/plugin.py#L11

Reads bookmarks from a bookmarks.json from addon_data/script.module.slyguy/ - here is a simple sample https://gist.github.com/wlincpdjhbxz/144d898a05afe3c647453e65db27aa79


That in itself is enough to list the bookmarked movies when accessing plugin://script.module.slyguy/movies/ from Kodi


For Kodi to scan that path into it's library -

The addon.xml needs a 'medialibraryscanpath' - https://github.com/wlincpdjhbxz/slyguy.addons/blob/master/script.module.slyguy/addon.xml#L8

and you need an entry in sources.xml -

```
<source>
    <name>SlyGuy Movies</name>
    <path pathversion="1">plugin://script.module.slyguy/movies/</path>
    <allowsharing>true</allowsharing>
</source>
```

After the source is added, set it's content in Kodi to Movies with information provider  "Local Information Only".

Everything _should_ be working at this point, Kodi will scan the items into the library.

If I forgot anything let me know and I will back track.

It's a matter of duplicating in order to do TV Shows and Episodes.

**Comment by matthuisman** [comment]
why do you need to scrape info yourself?

cant we just return movie names and Kodi uses it scanner to lookup the info?

**Comment by wlincpdjhbxz** [comment]
Sure, you can leave it up to Kodi and see how it goes.

When doing this with the internal Kodi scraper was leading to a lot of crashes for me, those were resolved with setting Local Information Only.

Mine is about 100x faster than Kodi's and I can guarantee the title is scraped properly.

Everything is linked by TMDB Id right now but that could be anything, rand(64) would even work so long as there is some sort of Id.

**Comment by matthuisman** [comment]
got the deeplinking working for youtube. 
Not bad. Be nice if it exited back to kodi on back or video stop. but just a few back clicks and your back :)
worth it for reliable trailers

**Comment by wlincpdjhbxz** [comment]
yes that's the annoying part of the built-in youtube

https://github.com/yuliskov/SmartTubeNext will completely exit after playback stops returning you to Kodi

or if you have a programmable button on your remote you can just leave YouTube in the background and jump back to Kodi - YouTube will self-close eventually

**Comment by wlincpdjhbxz** [comment]
Nailed down the minimum information for that an addon will need to save to a bookmark for an episode in order to avoid scraping TMDB for episodes.

[ "tvshowtitle", "title", "season", "episode", "plot", "premiered", "duration", "mediatype" , "artwork"]

example for Castle Rock S1 E1

{
                                                       "tvshowtitle": "Castle Rock",
                                                       "title": "Severance",
                                                       "season": 1,
                                                       "episode": 1,
                                                       "plot": "An anonymous phone call lures death-row attorney Henry Deaver back to his home town of Castle Rock, Maine.",
                                                       "premiered": "2018-07-25",
                                                       "duration": 3272,
                                                       "mediatype": "episode",
                                                       "artwork": {"thumb": "https://www.themoviedb.org/t/p/w227_and_h127_bestv2/iy9ZVejtgDSIaNoQLzC7ooK5Oq5.jpg"}
                                                   }


It is plenty enough information to make me and Kodi happy and avoids a lot more code, as it is this should be attainable from most providers.

Code can still be expanded to scrape if desired but not required.

**Comment by wlincpdjhbxz** [comment]
With the last merge to my fork everything is working perfectly for imports handled directly by the common module.

I have a bare front-end module which only serves a context menu to add bookmarks, only for example, I will add it to my github after it is ready for consumption.

Still needs* (Even though working perfectly for me)

Bookmark management - currently there is none.
Refactor with optional TMDB lookup instead of default.
I need to rebuild the TMDB module as it has excess code and things can be done better.

As far as this issue is concerned*

Refactor UniqueIDs from the new point of view for backwards compatibility, once I have something that better suites the code base I will proceed with a PR.

In the interim I thank you for your time, it has been very informative and I hope that the changes in my fork are a good enough example until a time I see fit to try and submit PRs to bring the functionality over.

**Comment by matthuisman** [comment]
It can't use my exisiting bookmarks system?

**Comment by wlincpdjhbxz** [comment]
The issues with using the existing bookmarks framework as I see them -

Potentially breaks existing functionality users may already be using.

Limits the possibility for having both a bookmark and an import - I assume there would be good use cases for each individually.

Existing bookmarks save per addon in their own addon_data folder, this would not be good for a global solution.
- Though not impossible it would require determining which addons are installed and traversing all of their individual bookmarks.

**Comment by wlincpdjhbxz** [comment]
I have rebuilt the TMDB module, as soon as I find a better way to determine language and region it will be backwards compatible.

Tested all the changes on 19.5 by hardcoding those 2 values and not using locale, everything else is working.

Once I am finished testing I believe it will be pertinent to use a try/except on the import as in the case my code goes down it brings everything down with it.

**Comment by wlincpdjhbxz** [comment]
Everything is updated.

Uses xbmc.getLanguage instead of locale - is backwards compatible and more universal.

Can disable use of TMDB lookup and just list the title from the bookmark. see useTMDB in listing.py - True use it, False don't
This has strange behavior with the built-in TMDB Python Scraper
- Kodi sees the default thumb and uses it so everything ends up with the blue slyguy thumbnail for a poster until a force refresh on each item.
-  Is excessively slow by comparison
-  Unable to reproduce an issue where Kodi began scanning all contents of the Paramount+ addon -- still not sure why, likely due to testing.

Added artwork for Series as well as Movies.

Tested on 19.5 and 21ALPHA1 everything seems to work with both built-in scraper (aside from already noted) and "Local Information Only"

I'm going to put the back-end aside for now and start cleaning up the front-end context addon, possibly look in to internal code for Hulu and Disney+ to save bookmarks for import.

**Comment by wlincpdjhbxz** [comment]
Added a demo front-end context addon - https://github.com/wlincpdjhbxz/plugin.video.integrate.context

Generic import based on listitem for show and movie.
Uses JSON RPC to list the contents of Series to get the episodes.
Attempts to identify the provider id (provid) based on Hulu and Disney+ but defaults to TMDB.

Just enough code to call the back-end code.

-----

Added 'Remove Import' context on imported items, shows when listing the contents of either import folder in Kodi from Files.
Remove import has an optional 'Remove from Kodi' as well which will look up the ID in the database based on the ID and if found execute VideoLibrary.Remove* - if confirmRemove False or if user selects Yes on a confirmation dialog, default behavior is just remove.

Seems to be enough to handle everything, native importing from individual addons can be added later then the context would be able to ignore those paths if added to the addon.xml under the visible conditions.
