### ISSUE TITLE
HBO Max sign in

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#569]
Hi. I'm trying to sign in on the Max add on. The link you give http://hbomax.com/tvsignin just leads to a general max.com page and not the code page. If I do a Google search on HBO Max TV sign in I get to a page that asks for a code but it only accepts numbers. Your code is letters and numbers. Is the link on your add on no longer valid? (I can't use email and password because like most people I subscribe to HBO through a provider) Thanks.

**Comment by matthuisman** [comment]
please look at other issues before creating new ones
HBO Max != Max

Max = USA
HBO Max = ROW

New addon is needed.
No ETA on that new addon

Issue: https://github.com/matthuisman/slyguy.addons/issues/454
