### ISSUE TITLE
Runtime error script.module.slyguy

### ISSUE THREAD

**Issue by betatester3016** [matthuisman/slyguy.addons#57]
Hi Matt,

This issue has been opened for informational purposes only and is intended to make you aware the latest update of script.module.slyguy exits with following error:

![image](https://user-images.githubusercontent.com/49594656/130663723-f73d4b67-9302-4c6a-ab03-a2c152b1cd19.png)

The error does not appear to affect the Samsung TV Plus or any other addons and the update appears to be successful, despite the error message popping up.

OS: CoreELEC 9.2.7 (leia) and 19.2 RC3 (matrix) on SoC ARM

**Comment by matthuisman** [comment]
Reboot Kodi

**Comment by matthuisman** [comment]
You need to find why that module isn't installed
