### ISSUE TITLE
URL fail

### ISSUE THREAD

**Issue by ghowse** [matthuisman/slyguy.addons#570]
The following error is logged every hour, and occasionally in between the hourly log entries.

**ERROR <general>: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/johnny5-is-alive/iat-repo/master/linux-armv7/matrix/addons.xml.md5
ERROR <general>: CFileCache::Open - <https://raw.githubusercontent.com/johnny5-is-alive/iat-repo/master/linux-armv7/matrix/addons.xml.md5> failed to open
ERROR <general>: CRepository: failed read 'https://raw.githubusercontent.com/johnny5-is-alive/iat-repo/master/linux-armv7/matrix/addons.xml.md5**

My Kodi install is as follows:
Kodi (19.5 (19.5.0) Git:d35266df280165addefc3e931543b36f713aef84)
Platform: Linux ARM 32-bit
Using Release Kodi x32
Kodi compiled 2022-12-26 by GCC 10.3.0 for Linux ARM 32-bit version 4.9.255 (264703)
Hardkernel ODROID-N2 with CoreELEC (official): 19.5-Matrix, kernel: Linux ARM 64-bit version 4.9.269
Host CPU: Amlogic S922X rev a, 6 cores available
ARM Features: Neon enabled

I am not aware of any detrimental effects of the error on my system.

**Comment by matthuisman** [comment]
thats very old!
That hasnt existed in a long time.

Go into Kodi addons > repos and remove the "IAT Testing" repo

**Comment by ghowse** [comment]
Well that was easy!  I have removed the IAT Testing repo.

I now have the following Inputstream addins:
**Inputstream Adaptive by peak3d - 19.0.7.1
Inputstream FFmpeg Direct by  Ross Nicholson - 19.0.3.1
Inputstream Helper (Slyguy Wrapper) by SlyGuy - 99.05**

Is this OK?

**Comment by matthuisman** [comment]
perfect :)
