### ISSUE TITLE
Stan Movies/Tv Shows Folder Categories

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#572]
Hey Matt, when selecting 'Movies', or 'Tv shows' folder in Stan, it throws an error, the only category in movies that works, is 'Featured' and 'Crime and Thrillers' and the only category that works in Tv shows is 'Featured' and 'Stan Originals' everything else shows the following error 

![stan folders error](https://github.com/matthuisman/slyguy.addons/assets/64548287/480fbeb7-0611-4b6c-946c-081c5ccd83b9)

**Comment by matthuisman** [comment]
fixed with [plugin.video.stan.au -> v0.4.5](https://github.com/matthuisman/slyguy.addons/commit/743e834049a4f512c0f9eb0c548633a4f3afb6ea)
