### ISSUE TITLE
Kodi/Foxtel login

### ISSUE THREAD

**Issue by kmon86** [matthuisman/slyguy.addons#576]
Hi Team
Our foxtel keeps coming up with “you need to login to access content” is this happening for everyone or just our end? Any fixes?!

**Comment by austreams** [comment]
have you tried log out then login again? and are you subscribed to the package you’re trying to access?

**Comment by kmon86** [comment]
Subscribed u see Downunder tv

**Comment by kmon86** [comment]
How do I do a debug log?

**Comment by kmon86** [comment]
Have just enabled logging. Seems my foxtel has logged out but all the others in kodi are working.

**Comment by liam8888999** [comment]
> Subscribed under Downunder tv

what does this mean? did you buy an account from some random?

**Comment by kmon86** [comment]
Sorry wrong msg. I have fixed now. My app wouldn't except my normal login but I deleted and reinstalled now all good.
