### ISSUE TITLE
Hulu no resume points from favorites

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#577]
Hi. The issue is described in detail here. 
https://forum.kodi.tv/showthread.php?tid=374491&pid=3166811
Your Disney add on is referenced here as an add on that does *not* have the issue, is coded correctly and does have a resume point from favorites. 
The Hulu resume point however doesn't work from favorites. It asks if you want to resume or play from beginning but just plays from the beginning if you choose the resume point. The link I posted suggests this is not a kodi issue and needs to be resolved by individual add on creators. This seems to be true as Disney works as it should and Hulu doesn't. Thanks

**Comment by matthuisman** [comment]
That forum says it's a svt play add-on with the problem... are you saying my Hulu add-on has the same issue?

**Comment by gmjh123** [comment]
Yes. The same thing. Any movie etc that gets favourited (if such a word exists) in Hulu doesn't save the resume point when you choose it from favorites. It asks if you want to resume or start from the beginning. If you choose resume it ignores it and starts from the beginning. The resume point is there if you go from Hulu to movie to the specific movie. But not from favorites. I presume you can reproduce it on your end easily.

**Comment by matthuisman** [comment]
Thanks. Ill take a look. Ill also post on that thread

**Comment by matthuisman** [comment]
see my reply here:
https://forum.kodi.tv/showthread.php?tid=374491&pid=3167591#pid3167591

Can workaround it though
 fixed with [script.module.slyguy -> v0.73.2](https://github.com/matthuisman/slyguy.addons/commit/a6cb655fdb92ec25809cb2d961366c33653f97f7)

**Comment by gmjh123** [comment]
I think you're correct on the Kodi forum. I noticed it also happened with a bbc iPlayer file favorite I tried it resume. I'm not sure what to do with your workaround. Is that going to be part of a sly guy update? Or do I paste it into your common files? If so, where? Thanks again

**Comment by matthuisman** [comment]
It'll auto update in next 30mins and then just be fixed for all my addons

**Comment by gmjh123** [comment]
👍
