### ISSUE TITLE
Kayo & Binge & Flash news Unexpected Error

### ISSUE THREAD

**Issue by hansenandrew** [matthuisman/slyguy.addons#580]
Both my Kayo and Binge apps are coming up with Unexpected Error. I have tried resetting the app but then won't let me login. Comes up with this error trying to get the code.
I have logged into my account via the website and it is fine.

![20230930_143403](https://github.com/matthuisman/slyguy.addons/assets/17509205/89c08b99-e4f6-447f-be9f-bb13dfa3f77b)
![20230930_143411](https://github.com/matthuisman/slyguy.addons/assets/17509205/98ef7ff4-9b48-4028-b2dc-6c70df560774)
![20230930_143457](https://github.com/matthuisman/slyguy.addons/assets/17509205/86376325-9db4-41a0-8783-ae502641ff26)
![20230930_143505](https://github.com/matthuisman/slyguy.addons/assets/17509205/34313e32-874a-418e-97d7-65bcff23fd6b)

**Comment by CV8R** [comment]
Bugger, same error here.

**Comment by CV8R** [comment]
Made a debug log of the issue on a fresh kodi install.

[https://pastebin.com/kwt8CUwq](url)

**Comment by davecham76** [comment]
Think the error is exactly the same - this is for Kayo

![kayo1](https://github.com/matthuisman/slyguy.addons/assets/146598204/4c411cf5-474f-4e34-bd27-2bdcd3e06dd0)
![kayo2](https://github.com/matthuisman/slyguy.addons/assets/146598204/5e901ad0-abb6-4fe7-9871-9c2d63851d29)

**Comment by davecham76** [comment]
Already workimg for Kayo again.  Thanks for fixing this as Kayo is so much better in Kodi.
cheers
dave

**Comment by CV8R** [comment]
Appears to be working again with 15.1  First time using device code wasn't working.  Used email/password which logged in.  I logged out and tried device code and this time it worked.

Thanks for sorting it. As @davecham76 says, Kayo and Binge on Kodi are light years ahead in usability compared to the native apps.

Wife can breath again...

**Comment by CV8R** [comment]
Not sure what's happened but it's broken again. Access denied.

**Comment by matthuisman** [comment]
all i can think is once everyones updates go live, a bunch of the same user-agent comes through and akamai blocks it...
Might have to try a different approach

**Comment by davecham76** [comment]
Its good for me now

**Comment by matthuisman** [comment]
i pushed another update. not sure how long will last

**Comment by CV8R** [comment]
not long ;-) This feels like whackamole.

**Comment by matthuisman** [comment]
can people let me know if last night changes fixed Binge / Kayo / Flash news?
Flash / Binge seem to have tighter vpn detection so im doing those "blindly"

I also curious to see if latest gets blocked again....
Really want to move back to my  "Youtube that just works" add-on for users who just use it for trailers and dont want to login / auth etc!

**Comment by CV8R** [comment]
I am unable to login with the latest changes.  I will forward you a log via pastebin.

**Comment by hansenandrew** [comment]
Both Binge and Kayo are working again for me.

**Comment by hansenandrew** [comment]
Stopped working again, same error coming up again

**Comment by matthuisman** [comment]
yup. these addons may be deprecated unless Kayo / Streamotion / Akamai decide to play nice.

Im not willing to add a bunch of other requests to make it look like "genuine" app as that just slows down the addon etc.

**Comment by frankgrant** [comment]
That is a shame.

**Comment by matthuisman** [comment]
i may try again in a bit. need a break from it. not fair on the users for it to keep working then breaking.

The answer may be randomness. Choose a few random other URLs that the app calls and call them randomly. We can call the method fuai()

If it's profiling our behaviour, we need to randomise it.

If we can get it to false postive "legit apps", then there would be an uproar and they would need to turn it off.

**Comment by matthuisman** [comment]
replacing this thread with https://github.com/matthuisman/slyguy.addons/issues/586
