### ISSUE TITLE
Iptvmerge can't find Kayo icons

### ISSUE THREAD

**Issue by aerans** [matthuisman/slyguy.addons#582]
Only a minor issue, as I still have EPG entry for each Kayo channel, but it did have icons before. Have tried reinstall but the problem remains. 

I'm using Mythtv as my PVR on OSMC. The Kayo EPG entries are appended to the Myth EPG. Getting messages every 15 minutes or so as it scans for the icons. 

Let me know if you need any diagnostic information.

**Comment by matthuisman** [comment]
all related to https://github.com/matthuisman/slyguy.addons/issues/586 so closing this
