### ISSUE TITLE
Binge TV Login error

### ISSUE THREAD

**Issue by Tallguy297** [matthuisman/slyguy.addons#585]
I get this error when I login...

![BingeTVError](https://github.com/matthuisman/slyguy.addons/assets/49935683/9e285589-7a0f-460b-8774-77f75cdd4177)

I have double checked my login and password details.
Also checked dependencies and made sure all are updated.

Help??

**Comment by matthuisman** [comment]
see existing issue: https://github.com/matthuisman/slyguy.addons/issues/580
wont be fixed anytime soon sorry
