### ISSUE TITLE
Request | Stan: Prefer AWS streams

### ISSUE THREAD

**Issue by kontell** [matthuisman/slyguy.addons#587]
When playing a live stream from Stan it is either served from AWS (awslive02.stan.video) or akamai (streamcoimg-a.akamaihd.net).

The AWS streams are not geo-blocked and perform much better for me (the stream comes from a London server).

The servers seem to be randomly assigned so I've blocked the akamai urls and I keep attempting to start a stream until I get an AWS one.

Would it be possible to have an option in the addon to prefer AWS streams?

**Comment by matthuisman** [comment]
See here
https://www.matthuisman.nz/2022/06/slyguy-addons-smart-url-actions.html

**Comment by kontell** [comment]
That's worked well, thanks.
