### ISSUE TITLE
Foxtel Go login

### ISSUE THREAD

**Issue by krackajack** [matthuisman/slyguy.addons#589]
Getting “access Denied” message.
Seems “you don’t have permission to access on this server”????
Password checked..ok. Password changed..ok. Using this format for PW: Ab123456
Kodi set to English/Australia.
Reset fire stick to factory settings and started fresh. Same issue persists.
Downloaded Kodi using Downloader app…ok
Followed download of sly guy repository carefully and can download other apps ok.
All updates seem ok.
Any help appreciated (more coffee promised).
![IMG_2735](https://github.com/matthuisman/slyguy.addons/assets/127704634/b2335807-ee90-4daa-b720-30d111207a10)
![IMG_2736](https://github.com/matthuisman/slyguy.addons/assets/127704634/17a92f26-247f-45ef-b5f5-b01fe4240c95)
![IMG_2737](https://github.com/matthuisman/slyguy.addons/assets/127704634/5b552c06-cbd9-42dd-99ec-3252e694fb07)

**Comment by matthuisman** [comment]
Look at the pinned GitHub issue

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/586
