### ISSUE TITLE
Spectrum on Stremium

### ISSUE THREAD

**Issue by usphil** [matthuisman/slyguy.addons#590]
I changed the Spectrum TV password and then went to Stremium to update and could no longer see the Spectrum provider. On the Stremium website there is no contact or support section, so I asked here to see if anyone knew this information.

By the way, new Inputstream Adaptive has just been released on Kodi Omega, can you port it to use on Kodi Nexus, to solve the problem of Hulu LiveTV. Because Kodi Omega is not yet stable enough to be fully upgraded.

**Comment by gmjh123** [comment]
Hi. Which version of Kodi Omega has the new inputstream adaptive? Thanks

**Comment by matthuisman** [comment]
Not sure what the bug is here? Seems like a stremium bug? And I can't
backport inputstream adaptive. You'd need to ask the IA guys
