### ISSUE TITLE
Pluto 0.3.8

### ISSUE THREAD

**Issue by flhthemi** [matthuisman/slyguy.addons#6]
Don't know if you're around here much but thought I would try this to let you know the 0.3.8 update I got is causing some sort of error. I was watching a video, not with Pluto, and this big box appeared on my screen saying there was some sort of error  with a lot of code in it. I think it might be occurring when the guide for pluto is updating but just a guess.

**Comment by matthuisman** [comment]
do you have a photo of the error?
Does it happen every X hours? 
or only shown once?

**Comment by flhthemi** [comment]
It happens when I run IPTV merge and use the merge command and as I said on it's own.
Screenshot
![screenshot000](https://user-images.githubusercontent.com/8205131/118061405-e5e3a380-b362-11eb-9893-379754daf38e.png)

**Comment by matthuisman** [comment]
just pushed  0.3.9 that fixes
