### ISSUE TITLE
inputstream helper

### ISSUE THREAD

**Issue by edenmedia** [matthuisman/slyguy.addons#600]
Hi, after your repo automatically updates "InputstreamHelper" with your version, Mediaset and other addons that use inputstream helpers don't work. I had to uninstall your repo and reinstall the official inputstream helper again.
Maybe, (but I'm not sure if feasible) a solution might be to call it by a different Name and ID.

**Comment by matthuisman** [comment]
Can you explain what didn't work? Any error?

**Comment by edenmedia** [comment]
Mediaset Play for example do not wotk at all. Generic error that appear if not inputstream helper is installed

**Comment by matthuisman** [comment]
can you point me to a bit of content in that addon that failed to play with my version of helper?

**Comment by matthuisman** [comment]
also, what version Kodi and what device?

A debug log would solve this issue pretty quickly :)

**Comment by edenmedia** [comment]
I just formatted a device for a new installation Libreelec in order to reproduce the error and post the Log. As soon as I installed your repo I noticed that it did not overwrite the official version of inputstreamHelper but that both were installed. So amazed that everything was working I went back to github and noticed that you had made an update on your inputstreamHelper with a new version.  I think that explains everything. Now they both work. Thanks a million for your time and energy and most of all your quick response to fixing the issue.

**Comment by matthuisman** [comment]
please. just get me a log!
Also what version Kodi etc etc.

There is a reason it has the same id etc.
It shouldnt replace the other unless youve got your kodi setting to "apply updates from any repos"

**Comment by matthuisman** [comment]
also, you can switch between them via the addons "version" menu
This also lets you disable updates so it wont update to my version
![image](https://github.com/matthuisman/slyguy.addons/assets/6225961/1573b6b6-9dd6-434e-a11f-52f699580b47)

I'd really appreciate if you can enable debug logging and then try to play something with my version installed.
And then get me that log.

**Comment by edenmedia** [comment]
I think that I find the problems in the log:
##    from inputstreamhelper import Helper
ModuleNotFoundError: No module named 'inputstreamhelper' ##
I also noticed that when official InputstreamHelper is installed it is present in the "Program add-ons" under my addon
instead when yout InputStream is installed it is only present in the "Services" under my addon

**Comment by matthuisman** [comment]
that addon exposes the same resources which should allow it to be found.

Please advise Kodi version, LibreELEC version and also what device running on

**Comment by edenmedia** [comment]
The version of Libreelec in this case is the version 11.0.3 but same happen wirh the old versions (10.0.4 and 9.2.6) with Intel Nuc device.
Also tried with a firestick and latest Kodi same results _(No Module Named 'inputstreamhelper')_ this appear in the log just after your repo update the 'Inputstreamheper '


> that addon exposes the same resources which should allow it to be found.
> 
> Please advise Kodi version, LibreELEC version and also what device running on

**1)** This is strange because with a clean installation of libreelec or kodi  the official inputstreamhelper is just present in the "Programs add-ons"  of Kodi repository,  instead if I install your repo the Official imputstreamhelper disappear from the "Program add-ons" but in the "Serivices" will be the inputstreamhelper of your repo renamed with  "Slyguy ".

**2)** The version of Libreelec in this case is the version 11.0.3 but same happen wirh the old versions (10.0.4 and 9.2.6) with Intel Nuc device.
Also tried with a firestick and latest Kodi same results _(No Module Named 'inputstreamhelper')_ this appear in the log just after your repo update the 'Inputstreamheper '

**Comment by matthuisman** [comment]
i cant reproduce. ive tried on kodi 20 on android and windows.
both work fine.

I tried mediaset addon from kodi repo (doesnt seem to login correctly and a bunch of stuff doesnt work but thats not the issue) and I checked and Rai Play doesnt even call anything in inpustream.helper

It has a dependency on it but doesnt actually use it.

Therefore, it just seems Kodi isnt installing my version correctly?
What error does Rai Play give you when you try to use it?

I made mine go under services so it doesnt clog up the main menu programs addons.

**Comment by edenmedia** [comment]
You can try for KOD addon? https://kodiondemand.github.io/ . Kod addon have also Rai and Mediaset in it under live section and it  call inputstream and widevine in order to let mediaset work.

**Comment by italfire** [comment]
I also just noted that few addons doesn't work with inputstreamhelper updated with your version.
You can test the issue with the addon Kod with the channels Mediaset Infinity:
 **Kod addon > Channels > Live > Mediaset Infinity > Dirette > any channel (rete 4 or canale 5 etc.)**  with your inputstreamhelper  it doesn't work with the Kodi original inputstreamhelper work just fine

**Comment by matthuisman** [comment]
What the heck is "KOD"?

**Comment by italfire** [comment]
Kod (Kodi On Demand) is an Italian addon with inside Mediaset Infinity and you can test by your self that it  doesn't work with with the Slyguy inputstreamhelper. As Edenmedia said the problem is inputstreamhelper. this is the error in the log **"ModuleNotFoundError: No module named 'inputstreamhelper'"**

**Comment by italfire** [comment]
Good news,  with the original inputstreamhelper the Slyguy video addons (Pluto, Samsunng and others)  still works perfeclly fine.
@Slyguy I hope you can fix this small issue but in any case,  I want to thank you for your addons because they are great

**Comment by matthuisman** [comment]
right, that was the key bit of information i was missing.

That addon relies on the path inside the helper addon to be the same as it for some reason does the sys.path append itself and then calls the code. 

it also means the helper cant rely on any other dependencies as KOD doesnt add those to the path.

[script.module.inputstreamhelper -> v99.0.7](https://github.com/matthuisman/slyguy.addons/commit/f0204a3af74c4a443829c191df519a742c8a8ea5) just pushed that should now work :)

1) removed slyguy common dependency as that wont work due to them not adding to sys.path
2) moved the module to lib directory (same as official)
3) changed it to show in "programs" like the official


Also, i soon will be packaging any slyguy versions of official addons inside their own repos.
This allows installing that repo if you want the slyguy versions.

Would allow having my main repo installed without overwriting the official versions when you have the "install updates from any repos" setting enabled

**Comment by italfire** [comment]
Thank you very much @matthuisman you are brilliant

**Comment by matthuisman** [comment]
next time, a debug log in the first post would solve a lot quicker :)

**Comment by matthuisman** [comment]
this wrapper addon has now moved into its own repository "SlyGuy InputStream Helper Wrapper Repository".
That repo can be installed from the main SlyGuy repository.

This allows users with "install updates from any repo" to not have this addons that share the same ids as official automatically being installed :)

The old version of this addon will be removed from the main repo within the next week
