### ISSUE TITLE
Question: proxy_data from addon settings?

### ISSUE THREAD

**Issue by vajonam** [matthuisman/slyguy.addons#604]
I am creating a new addon, that requires ssl verify to be turned off?
I am creating a playable item, how do I set enable verify_ssl to be false only for this https HLS stream that being ready by the proxy? 

```
    return plugin.Item(
        path = api.play_vod(channel=channel),
        headers = HEADERS,
        inputstream = inputstream.HLS(live=False),
    )
```

I this works if I change the common addon's ssl setting, but can I do this and default this or read it from my addon's settings?

**Comment by vajonam** [comment]
think i found the asnwer.
```
    return plugin.Item(
        path = api.play_vod(channel=channel),
        headers = HEADERS,
        inputstream = inputstream.HLS(live=False),
        proxy_data = { "verify" : settings.getBool("verify_ssl")}
    )
```

however I can't seem to find the keys to set retries / attempts or timeout for this particular stream and pointers there will be appreciated!

**Comment by matthuisman** [comment]
proxy_data = {'timeout': 30}  for timeout
retries cant be set. its hardcoded to 3 in the proxy and only for connectionerrors
