### ISSUE TITLE
Willow TV: When not matches being played have NPE

### ISSUE THREAD

**Issue by vajonam** [matthuisman/slyguy.addons#605]
![image](https://github.com/matthuisman/slyguy.addons/assets/152501/7a0f9428-734e-4a21-990f-d6cc7ea7494b)

Looks like the new code missed a condition when there are no live matches. Previous used to provide a notification.

**Comment by matthuisman** [comment]
thanks. 
fixed in [plugin.video.willow.tv -> v0.1.7](https://github.com/matthuisman/slyguy.addons/commit/a6d844048ca44c11f3533cf920b442aa266d2006)
