### ISSUE TITLE
[Sky Sport Now] Sky Sports 1 not loading. #549

### ISSUE THREAD

**Issue by theccap10** [matthuisman/slyguy.addons#607]
Have started this "new" issue but it is the same issue as #549

New comments in the closed issue.

https://pastebin.com/5ssN5kzH

![image](https://github.com/matthuisman/slyguy.addons/assets/48872872/c8d6694d-4bd8-4826-af1e-4b32180c5bff)

**Comment by DavidCNZ2** [comment]
And it's working this morning
