### ISSUE TITLE
Sky Sport NOW not working

### ISSUE THREAD

**Issue by Jono14231** [matthuisman/slyguy.addons#608]
Hi Matt. Thanks for all your work with this app. Seem to be having issues with accessing most of the sky channels again. ESPN was working but I couldn't get any of the sky channels going.

https://paste.kodi.tv/hexivicapu.kodi

**Comment by Jono14231** [comment]
Hi Matt. It seems to be working as of late last night. Did you want more logs provided if it happens again?

**Comment by conradbullock** [comment]
Confirming that I had the same symptoms and it also started working again for me last night.
I note that even when it wasn't working it seemed to be the Live TV streams that didn't work - the on-demand content under the Sports menu seemed to work OK.
If it happens again I too will capture a log.
