### ISSUE TITLE
how restart stream if it drops?

### ISSUE THREAD

**Issue by vajonam** [matthuisman/slyguy.addons#609]
I have an issue with a streaming provider that has an issue with m3u8 intermittently returning a 401.  restart the streams works but again it stop from time to time? 

What are are my options here when using the proxy, to re-try on failure of a re-fetch of a m3u8 or a .ts? 

```
@plugin.route()
def play_live(channel, priority=1, **kwargs):
    return plugin.Item(
        path = api.play_live(channel=channel),
        headers = HEADERS,
        inputstream = inputstream.HLS(live=True),
         proxy_data = { "timeout": 30 }
    )
```

**Comment by matthuisman** [comment]
none really. you could write a service that listens for playbackstopped and then try restart etc. kodi doesnt really hand it well
