### ISSUE TITLE
disney + star not working ip blocked 

### ISSUE THREAD

**Issue by nickyf114** [matthuisman/slyguy.addons#61]
hi there stream to be a fualt with star on disney + addon  when i click on star i get a error  whats says  

failed to  fetch json data 
make sure your ip address is allowed (not geo-blocked)
i have check on my phone and disney is working fine on that and it working fine on google chrome but i will say wen i try and load discovery + on firefox it will not work i have all so tryed a never ip address but puting my hotsport on my phone but that did not work 

its oney star whats playing up  and some movies like deadpool 2 will not play  but all the over stuff work fine i can watch national geographic on kodi on the disney plugin fine and do not get the error it oney give me the error if you try and click star  can you look in to this for me as it doing this on all my kodi boxs with kodi 18.9 and kodi 19

**Comment by matthuisman** [comment]
why do you mention discovery+?
was that a typo?

**Comment by nickyf114** [comment]
hi sorry that was a typo error

**Comment by matthuisman** [comment]
just pushed 0.9.8 that fixes the Star hub

Not sure what your issue is with Deadpool 2.
Im in NZ and don't get access to that movie so can't test.
make sure your profile has 18+ access

**Comment by nickyf114** [comment]
hi mate all fix thanks for the updateing the addon
