### ISSUE TITLE
PBS Live tv guide off by 1 hour

### ISSUE THREAD

**Issue by ltai0001** [matthuisman/slyguy.addons#610]
Hello
Minor issue with pbs live addon. It is off by 1 hr when comparing show time with current Kodi time. Not sure why but worth looking into it
Appreciate the help

**Comment by matthuisman** [comment]
Tried restarting Kodi?

**Comment by ltai0001** [comment]
Just did and it's all correct now. Did you just change something? Cose I did a restart of Kodi like a week ago...

**Comment by matthuisman** [comment]
was there a daylight savings time change between then and now?
Kodi needs a restart when DST changes
https://www.matthuisman.nz/2018/04/time-change-monitor-kodi-add-on.html can automate that for you

**Comment by ltai0001** [comment]
Daylight saving time change won't happen until this coming weekend...

**Comment by matthuisman** [comment]
Oh. Maybe dst change in the timezone the epg uses then?
