### ISSUE TITLE
[Global search+] Container content is empty.

### ISSUE THREAD

**Issue by HitcherUK** [matthuisman/slyguy.addons#613]
`Container.Content` is empty which means my info labels don't get displayed as I use conditions based in the content.

Global search

![screenshot00001](https://github.com/matthuisman/slyguy.addons/assets/133808/3e430e35-66e1-4b10-a371-8d6b87eca492)

Global search+

![screenshot00002](https://github.com/matthuisman/slyguy.addons/assets/133808/32b32d04-0cfb-41b1-b05d-5b74135b4ec3)

**Comment by matthuisman** [comment]
thanks.

Just pushed v99.0.10 that fixes it :)

**Comment by HitcherUK** [comment]
Thanks.
