### ISSUE TITLE
how did you reverse com.hulu.livingroomplus?

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#615]
the current Hulu code seems to be based off the TV version of the app. However I am not sure how that was accomplished. GenyMotion does not have an option to create a TV device. Android Studio does, but the problem is that the Hulu TV app only works with `armeabi-v7a`. the app does have a universal version, but only with older versions of 2017 and before. with phones, you can emulate ARM using Android 9 or higher, but that didn't seem to work for me with a TV app. so:

1. did you use the really old version of the app with an x86 TV?

2. did you use a current version of the app and just deal with the slowness due to emulation?

3. something else?

**Comment by matthuisman** [comment]
3) Didnt use an emulator :)

**Comment by matthuisman** [comment]
oh wait. maybe not. Im looking at my docs for it and i cant see any MITM saves.

I think i may have pulled out the JS files from the APK and figured it out from those

**Comment by matthuisman** [comment]
you have lots of interesting repos by the way!

**Comment by 3052** [comment]
hm I guess hardware is the only option. I just tried the current app on an ARM emulator. it was slow as hell, to be expected. four minutes just to install. but even then, if you try to start the app, you get:

> Unfortunately, Hulu has stopped.

even with no MITM
