### ISSUE TITLE
Freeview addons AU/NZ suggestion

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#616]
it would be great if channels that are on free to air out so iptv only channels would appear in the addon and get sent to iptv merge

**Comment by matthuisman** [comment]
there is a setting in the IPTV addon i think now to hide "FAST" channels. Can you try that?

**Comment by liam8888999** [comment]
I think it would be the opposite of what I am looking for. I only want to see the fast channels and not fta but I will give it a try

**Comment by liam8888999** [comment]
Yeah. It does the opposite of what I was hoping for

**Comment by liam8888999** [comment]
If channel.get('chino') and not hide_fast in plugin.py seems to work but I'm not sure how to set that as an option or integrate with the hide_fast option correctly but hopefully it will give you a starting point

**Comment by matthuisman** [comment]
oh. ill make it a multiselect then?

All channels
FAST only
Non-FAST only

**Comment by liam8888999** [comment]
that sounds perfect

**Comment by matthuisman** [comment]
done :) a Show Channels setting adding to both IPTV NZ and AU
