### ISSUE TITLE
Paramount+ License Error

### ISSUE THREAD

**Issue by Publish3r** [matthuisman/slyguy.addons#618]
Latest Paramount+ Addon, latest Widevine, Platform Windows.
HTTP returned code 403

**Comment by matthuisman** [comment]
kodi debug log please. what country? US or INT?

**Comment by sneakypuss** [comment]
Australia/INT
latest widevine, kodi and addons

Widevine license request failed

Dont know if I've done the log correctly but attached.

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/13342850/kodi.log)

**Comment by gmjh123** [comment]
Fyi. Same error on Android TV and Fire stick. USA based

**Comment by rhinhold** [comment]
I'm receiving the same failed license request in Paramount. But also some other unrelated issues. I just happen to be installing new device when I saw the Widevide error,  so not sure if this is something I should dig further into yet. I'll hold off on further setup until we here from the Man :)
US, Kodi 20.2, Firestick 4K version 2

Thanks,

**Comment by MetalChris** [comment]
Seeing the same error as sneakypuss in the U.S.

**Comment by matthuisman** [comment]
thanks all. no more need for +1 posts :)
ill take a look when i get a chance

**Comment by matthuisman** [comment]
as the error is happening on android as well - this tells us its not a WV CDM update required.
Paramount must have changed something :)

**Comment by rhinhold** [comment]
At least I don’t use it very often :)
Thanks for the quick update.
Robert

On Nov 13, 2023, at 8:51 PM, Matt Huisman ***@***.***> wrote:

﻿

as the error is happening on android as well - this tells us its not a WV CDM update required.
Paramount must have changed something :)

**Comment by gmjh123** [comment]
> as the error is happening on android as well - this tells us its not a WV CDM update required. Paramount must have changed something :)

Does that mean you can't patch/fix it?

**Comment by matthuisman** [comment]
Should be fixable

**Comment by gmjh123** [comment]
👍

**Comment by matthuisman** [comment]
fixed with [slyguy.paramount.plus -> v0.7.4](https://github.com/matthuisman/slyguy.addons/commit/41b6d7dfab7dc20cd51e846a45b46614bb56cf48)

**Comment by gmjh123** [comment]
Thanks very much. Greatly appreciated as always

**Comment by MetalChris** [comment]
You're the man Matt!

**Comment by phage80** [comment]
I am still getting this error on v0.7.4 with some stuff.
