### ISSUE TITLE
Hulu audio quality

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#619]
seems like the default audio is low quality:

~~~xml
<Representation id="018b1ffa-bae4-8943-3da6-000c75657b25" codecs="mp4a.40.5" bandwidth="68007"
startWithSAP="1" audioSamplingRate="48000">
~~~

did you figure out a solution for this?

**Comment by 3052** [comment]
ah I see here:

https://github.com/matthuisman/slyguy.addons/blob/054cbaec110d7e921b15384a3daaf78301aa0421/slyguy.hulu/resources/lib/api.py#L370

**Comment by matthuisman** [comment]
what was the fix? enable ec3 in settings?

**Comment by 3052** [comment]
from my own research it seems they just dont offer a higher quality with the 2 channel. so the 6 channel is the "better quality". annoying but thats the situation. I checked the APK to confirm. if anyone finds a way to return more audio formats thats cool, but I dont think its possible

**Comment by 3052** [comment]
it seems not all items have EC3

https://hulu.com/watch/c5682975-40cf-4a49-93d4-af29bc930964

do you know some fix?
