### ISSUE TITLE
HBO Max no longer working after latest update

### ISSUE THREAD

**Issue by xmalbertox** [matthuisman/slyguy.addons#62]
### Subject of the issue
HBO Max no longer working after latest update, earlier before the add-on updated a server error requiring an API update showed up, so I imagine that this new error is due to some oddity in their new API.  

### Your environment
* Kodi Version - 19.1 (installed trough flathub)
* SlyGuy Common Version - 0.43.1
* HBO Max Version - 0.5.2
* OS - ArchLinux (Kernel Version 5.13)
* Location - Brazil

### Steps to reproduce
Launch the HBO Max add-on and try to navigate to any folder.

### Expected behaviour
Should be able to navigate and play content

### Actual behaviour
A Server error message for HBO GO shows up:

> ![2021 09 09-17 11 09 screenshot](https://user-images.githubusercontent.com/11772286/132756834-a64fc0dc-a17d-4f02-a422-a8f3f9570cfc.png)

I have confirmed that my subscription is working both on the PC browser and on the android app.

**Comment by matthuisman** [comment]
just pushed 0.5.3.
please try that

if that doesn't work, then ill need a full debug log.
I also have no vpns that work in brazil which makes it near impossible to test

**Comment by alinefr** [comment]
0.5.3 did the fix for me in Brazil. Thank you!

**Comment by matthuisman** [comment]
Great :)
