### ISSUE TITLE
Sling Freeview channels won't play on Stremium

### ISSUE THREAD

**Issue by bds3151** [matthuisman/slyguy.addons#627]
Sling Freeview channels error with a message about missing MOOV indicator in the kodi log through Stremium. Sling channels through the regular paid for account work fine. Some examples are Hell's Kitchen (Filmrise), History Time, and the Real Disaster Channel.

**Comment by matthuisman** [comment]
NO!
IM NOT STREMIUM.
GO CONTACT THEM ABOUT THOSE STREAMS NOT WORKING ON THEIR WEBSITE
