### ISSUE TITLE
Memory leak in update checker

### ISSUE THREAD

**Issue by Didero** [matthuisman/slyguy.addons#628]
I'm running Kodi through OSMC on a Raspberry Pi 3, and I've noticed the memory usage slowly creeping up, with about 0.1 to 0.3% more RAM usage every hour. It's not much, but the RPi 3 also doesn't have a lot of RAM, so after a week or two, memory is too full and video playback starts to suffer.
Through a process of elimination I've determined that the memory leak is from the SlyGuy Common addon, since when I disabled that addon, the memory leak didn't occur even after letting OSMC run idle for a day.
To further pinpoint the cause, I played around with the settings of the addon, and when I changed the 'HTTP Retries' setting in the 'Advanced' tab from 1 to 0 and letting OSMC run idle for most of a day, the memory leak was also gone. When I changed that setting to 10, the hourly memory increase got larger.
During all my testing, I didn't do anything else with the Raspberry Pi besides logging in through SSH to check RAM usage occasionally.
So my conclusion is that there is some sort of memory leak in the update code relating to retries. Could you please look into it? Thanks in advance.
Finally, thanks for all your work, we can now watch Disney+ on our old app-less TV, and my mom loves it!

**Comment by matthuisman** [comment]
thanks for raising this issue.

Do you have a debug log?
I want to see why increasing the retries affects it. I assume one of the urls is failing?

**Comment by Didero** [comment]
Sorry, I should've included a log in the first place. I've attached the debug log, after it's been running overnight:
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/13466462/kodi.log)

**Comment by matthuisman** [comment]
ok. so i cant see any retries so its odd that more retries leads to higher usage.

Anyway, ill try find a way to record the mem usage so i can try removing different bits of code and see what stops it :)
Ive seen a few bugs about requests not closing sessions correctly. so maybe something like that

**Comment by Didero** [comment]
Thanks for looking into it!
Sorry my log wasn't more helpful. If there's anything more I can do to help pinpoint the problem, let me know.

**Comment by Didero** [comment]
The memory usage of Kodi on my Raspberry Pi doesn't slowly go up anymore, so the leak seems fixed.
Thanks for looking into this and for finding a solution!
