### ISSUE TITLE
Subtitles out of sync on Disney+

### ISSUE THREAD

**Issue by pmsobrado** [matthuisman/slyguy.addons#629]
What the title says, at least on spanish region. I have to adjust subs to -6000 ms (they are 6 seconds ahead, more or less). The funny thing is that, when adjusted, if I go back to the beginning of the video, they desynchronize again for another 6 seconds. So what I'm doing for now is, adjust -6000 ms, then exit, then play again, and now it plays fine.

Thanks in advance.

**Comment by matthuisman** [comment]
could be the same issue as https://github.com/matthuisman/slyguy.addons/issues/500

**Comment by pmsobrado** [comment]
I don't think so, also, I have other addons that also use input stream plugin and does not have that problem :(

**Comment by matthuisman** [comment]
Yes. But are other add-ons using hls with widevine and multiple periods?

**Comment by matthuisman** [comment]
what version kodi / inpustream adaptive using?
If Kodi 20, Try 19 as 19 doesnt have the other issue in inpustream.adaptive

Playback problems are mostly out of my control unfortunately.

**Comment by pmsobrado** [comment]
I'm using Kodi 20.1.0, I can't go back to 19 because I have a lot of configurations and addons, and I remember updating to 20 from 19 because of an specific addon, I think it was Prime Video, in order to get 4K playback.

Disney+ version is 0.14.6, InputStream Adaptative is 20.3.14, and InputStream Helper is 0.6.1+matrix.1. I also have an addon called InputStream FFmpeg Direct.

I think something may have change on Disney's end? The subtitle delay appeared from one day to another.

I guess you cannot test with the spanish catalog, right?

Thanks in advance.

**Comment by pmsobrado** [comment]
Anyone else with this issue?

**Comment by matthuisman** [comment]
See the linked inputstream issues.
Think it's fixed in latest Omega version

**Comment by pmsobrado** [comment]
I'll check there, thanks.

**Comment by zanshem** [comment]
In view of the unsolvable error when playing the subtitles, it would be advisable to integrate the [ttml2ssa](https://github.com/Paco8/ttml2ssa) add-on from Paco8. This makes the subtitles play smoothly.

**Comment by matthuisman** [comment]
IA 21.4.5 
+
Kodi setting --> Player --> Subtitles --> Override Subtitles fonts --> From the dropdown menu choose: Positions

should fix this issue in Omega

**Comment by RoBiN-HoOd-1** [comment]
> What the title says, at least on spanish region. I have to adjust subs to -6000 ms (they are 6 seconds ahead, more or less). The funny thing is that, when adjusted, if I go back to the beginning of the video, they desynchronize again for another 6 seconds. So what I'm doing for now is, adjust -6000 ms, then exit, then play again, and now it plays fine.
> 
> Thanks in advance.

can anyone share me the shortcut keys to adjust my subtitles thanks.
