### ISSUE TITLE
[Binge / Kayo / Flash] License renewal fails on 32bit Android

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#63]
Kodi 19.1
Log: https://pastebin.com/raw/68mZWwjQ

**Comment by scottydulton** [comment]
Any findings with this one Matt?

**Comment by matthuisman** [comment]
@scottydulton 
could you please try latest version of the Binge add-on (0.3.4) and see if that is fixed?

**Comment by scottydulton** [comment]
Will try soon and get back to you mate thanks.

**Comment by scottydulton** [comment]
Hey @matthuisman, 
Still no good, froze after 5 or so minutes. ive enabled debug logging and got a fresh full log from today for you.

[https://pastebin.pl/view/ba606a93](url)

**Comment by matthuisman** [comment]
can you please update to latest versions (just pushed)
then enable logging > component > curl 
then get mew a new log :)

**Comment by scottydulton** [comment]
Sorry mate been working I will get it done tonight for you

**Comment by scottydulton** [comment]
Hey @matthuisman  it froze again but this time after about 30-40 mins, the log was just too big for pastebin and i wasnt sure what to remove so i just added a zip file lol
[kodi.zip](https://github.com/matthuisman/slyguy.addons/files/7229515/kodi.zip)
l

**Comment by matthuisman** [comment]
Oh... So maybe it's now fixed?
Can you keep trying?
It was always 5mins on the dot previously?

**Comment by scottydulton** [comment]
nah for me most of the time was sooner rather then later, but sometimes i would get half hour out of it, i tried twice today, froze both times around 30 i can do some more tonight if u like wont be till later on though

**Comment by giddiup65** [comment]
@matthuisman tryed myself 3 times,  froze within 5-10 mins each time

**Comment by scottydulton** [comment]
Hey @matthuisman i replicated this issue on kodi - windows 10, turns out it is seeing im using the max number of streams. 

ERROR <general>: CCurlFile::Open failed with code 403 for http://127.0.0.1:52103/plugin://slyguy.binge/?_=license_request:
                                                   {"code":130401,"message":"Too many concurrent streams."}
2021-09-26 11:20:15.118 T:10804   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure

I have my account setup to 3 kodis at my house however they arent all watching at the same time, my plan allows 2 screens

**Comment by matthuisman** [comment]
oh right - that makes sense now,
I was wondering why i could not replicate,
I'll see what I can do about that :)

**Comment by scottydulton** [comment]
Hopefully something simple :)

**Comment by scottydulton** [comment]
@matthuisman did you find anything regarding this?

**Comment by matthuisman** [comment]
not really. does their app work if your streaming on X amount of other devices?

**Comment by giddiup65** [comment]
@matthuisman I have a binge account that allows 2 screens that  I share with a sister and parents. We have all had this freezing issue for a while and doubt if we were all using binge concurrently. To verify I created a trial using my wifes details and set it up as a 2 screens account, but only playing it on 1 screen and it still produces the same result, within about an hour each time it froze, I experienced zero buffering up to the point it froze..this on a 4k firestick  using kodi 19.1

**Comment by scottydulton** [comment]
@matthuisman yeh it does mate, ive tested on multiple screens in web browser/phone, however theres no official App compatible for firestick yet

**Comment by matthuisman** [comment]
could you guys try this build of Inputstream Adaptive and see if it helps / fixes?
https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-814/1/artifact/cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-19.0.0.zip

**Comment by scottydulton** [comment]
@matthuisman will try now, i was going to say too i feel like it hasnt done this forever, i feel like it was around the time of the issue with NBA no sound and all the changes to IA regarding HLS, but i could be 100% wrong

**Comment by giddiup65** [comment]
@matthuisman thanks ill try tonight

**Comment by scottydulton** [comment]
@matthuisman  still failed mate

**Comment by matthuisman** [comment]
oh, thats good i guess as that PR i removed in the test did fix other stuff

**Comment by giddiup65** [comment]
Yeah mine failed too

**Comment by giddiup65** [comment]
@matthuisman ok so loaded kodi onto a nvidea shield and a samsung mobile.. put binge on both and had same issue as with my firestick. They didn't freeze at the same time but all froze between 5 and 45 mins of each other.
Could it be an Android thing as opposed to a firestick thing?

**Comment by matthuisman** [comment]
@scottydulton I think now that Kayo is using the same DRM / endpoints - these are the same issue
https://github.com/matthuisman/slyguy.addons/issues/402
https://github.com/xbmc/inputstream.adaptive/issues/1147

**Comment by Carty89** [comment]
Gday mate Kayo Freezing again

cheers

**Comment by matthuisman** [comment]
not related sorry

**Comment by Carty89** [comment]
Ok cheers mate do I upload it here?

**Comment by matthuisman** [comment]
yup. if your using a shared login etc, then you will simply be hitting the concurrent stream limit

**Comment by Carty89** [comment]
Cheers mate can’t be that I don’t give out my kayo  details so it’s only what I’m watching. 

Do I just follow these instructions on my firestick?

![4EA70D24-CD17-4BDF-8035-7170E350B7AC](https://user-images.githubusercontent.com/125644192/222665760-872cf1f3-f7c6-4f34-b95d-ffdab4d1eb72.png)
![5E0AF553-9FCD-478A-9583-4ACF3229BFD4](https://user-images.githubusercontent.com/125644192/222665785-dcd14491-6bc8-4c07-8222-1921e5edff84.png)

**Comment by matthuisman** [comment]
follow this:
https://kodi.wiki/view/Log_file/Easy
