### ISSUE TITLE
Optus Sport not working in Kodi 18.9?

### ISSUE THREAD

**Issue by Bob-git1** [matthuisman/slyguy.addons#632]
Hi, I have an Android box that is specifically set up with Kodi 18.9 to be able to use a Balkan TV addon, as it won't work on any later versions of Kodi. 
Until recently, the Optus Sport addon was working fine on Kodi 18.9, but a few days ago it starting throwing errors and will not play any streams, either live or on demand.
Apologies, the box is at my dad's house so I don't have any error logsvyet, but I will get them in the next few days. 
Just wanted to check if anyone else has experienced the same issue.

**Comment by matthuisman** [comment]
I pushed an update that should fix that. Please make sure updated to latest

**Comment by Bob-git1** [comment]
Thanks Matt, I will try it.

**Comment by matthuisman** [comment]
[v0.8.6](https://github.com/matthuisman/slyguy.addons/commit/d1660158c083907fb52fce2ca940f9bf938f1683) which was pushed 3 days ago

**Comment by Bob-git1** [comment]
Hi Matt, I checked with latest version v0.8.6 and still same issue. In the end I set up on another box with latest Kodi and Optus is working fine now.
