### ISSUE TITLE
Can't login to kayo sport

### ISSUE THREAD

**Issue by TechDude64** [matthuisman/slyguy.addons#635]
I am trying to login into the Kayo Sport on Libre ELEC on a Raspberry Pi 3B, and I am getting this error when I try to login via email and password and login in with a device code:
https://imgur.com/a/PlcnhWb

I have tried reinstalling the plugin and rebooting Kodi multiple times.

I am running version 0.15.3 on Kodi version 20.2.

**Comment by matthuisman** [comment]
Please see the existing pinned issue
