### ISSUE TITLE
Disney Plus + Hulu Beta

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#638]
Hi. This isn't an issue but a question. Disney has introduced a Hulu hub to watch Hulu content on their app. Is it possible to update the Disney add on to have this Hulu hub? I ask as the HDR and Dolby Vision is much better on the Disney add on. Thanks very much.

**Comment by matthuisman** [comment]
i probably can, but i would need access to a login with Disney+ & Hulu so I can develop / test.
If you can help with that: blog@matthuisman.nz

**Comment by gmjh123** [comment]
Yes I can help. Do you want my login?

**Comment by matthuisman** [comment]
Yes please. Just temporarily. Please change your password to something you
don't use elsewhere for peace of mind. :)

**Comment by gmjh123** [comment]
Ok. Done

**Comment by matthuisman** [comment]
work on this progressing quickly.

I am not going to implement some features as I believe after the Beta - all this new code wont even be used and all the content will be merged and go through the same old api end points.

Features that wont be implemented for Disney + hulu beta:

1) Skip intro / credits
2) sync resume (local resume will work)
3) play next episode / movie
4) imax ratio (dont think hulu content has this anyway)

**Comment by gmjh123** [comment]
Ok excellent. I don't think skipping the intro or credits ever worked on
the add ons anyway.

**Comment by matthuisman** [comment]
added with [slyguy.disney.plus -> v0.15.0](https://github.com/matthuisman/slyguy.addons/commit/aeeea9352626710262900c213ff2d5b4cdb09507)
