### ISSUE TITLE
Access Denied error - FoxtelGO

### ISSUE THREAD

**Issue by MartyK87** [matthuisman/slyguy.addons#639]
Hi there

Cannot login at all to Foxtel Go on kodi.

![err](https://github.com/matthuisman/slyguy.addons/assets/96560243/6568c874-fab8-44f4-a5f8-a924068cad20)

**Comment by matthuisman** [comment]
please check for other issues before posting.
Its even a pinned issue:
https://github.com/matthuisman/slyguy.addons/issues/586
