### ISSUE TITLE
Disney+ Addon not showing title on search function

### ISSUE THREAD

**Issue by diegoflyer** [matthuisman/slyguy.addons#641]
I have Disney+ addon on Kodi Nexus 20.2 running in OS 64 bit raspberry pi.
After some weeks that everything was running correctly now I am not able to use the search function.
I can search and I have the list of results but no picture and no name of the Film / Series found.

I tried to remove the addon and all the data but no change on this behavior.

I had a similar issue with Libreelec and kodi 19 and after switch to new os64bit and kodi 20 was solved, anyway I cannot from my SD card every 2-3 weeks.

Is there any way to fix this?
Can I check or post some log to understand why this happen?

**Comment by matthuisman** [comment]
Post Kodi debug log. Google how to create / get that.

**Comment by matthuisman** [comment]
Actually. I get the same. No need for log. I'll get it fixed over next few
days.n

**Comment by diegoflyer** [comment]
@matthuisman  here the log where I try to seasrch "natale" and "gold":
https://paste.kodi.tv/umufuhikoz.kodi
and here is the screen:
![image](https://github.com/matthuisman/slyguy.addons/assets/46562259/09866091-2c0d-4490-9622-9f90bc23a2ee)

**Comment by bttfba** [comment]
Matt, I contacted you in private to raise an issue on Disney+ and I see now that my issue is exactly the same described here: no names and pictures from Search, even if the results are there correctly (just launching one of the results, it opens a stream containing coherent item with the search results)
I'm in Italy and using a regular Disney+ access.
Not sure the log is useful, anyway I have it. The issue started in the last weekend, probably on Friday night or Saturday 8-9 December 2023.
Thanks
Fabio

**Comment by matthuisman** [comment]
Please see my comment. I've confirmed issue and will fix over next few days
🙂

**Comment by matthuisman** [comment]
fixed with https://github.com/matthuisman/slyguy.addons/commit/64d3695aa068d7bca7b0442edb24ad4505d629c6
