### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by derrgoo** [matthuisman/slyguy.addons#643]
Today I was watching Pluto on kodi 21.2 beta. Having many stoppage of plays going into a commercial. Would have to restart the stream. 

Just for the heck of it rebuilt it with 20.2. No freezing. 👍

**Comment by matthuisman** [comment]
oh. maybe 20.2 has some sort of fix for discontuity?

**Comment by derrgoo** [comment]
It seems to act very much better. 21.2 is just black screen freezing. I will stay on 20.2 just for your add on.
