### ISSUE TITLE
Disney+ / add and remove from Watchlist not working.

### ISSUE THREAD

**Issue by Kampfader** [matthuisman/slyguy.addons#644]
I hope these photos are sufficient.

![Screenshot_20231217-010632](https://github.com/matthuisman/slyguy.addons/assets/23200748/4c5b0649-a19c-4a02-bd90-20d990bc14d1)
![Screenshot_20231217-010706](https://github.com/matthuisman/slyguy.addons/assets/23200748/2db300b5-a5ae-48d1-b423-7ce204ef0d53)

**Comment by gmjh123** [comment]
Can't you either bookmark or favourite it?

**Comment by matthuisman** [comment]
watchlist fixed in [slyguy.disney.plus -> v0.15.5](https://github.com/matthuisman/slyguy.addons/commit/14bc69156e511da35be27a7cfead73c8280715bd)

**Comment by Kampfader** [comment]
> Can't you either bookmark or favourite it?

I use OSMOSIS Addon for kodi library

Watchlist is only for Movies
Bookmark is for Series

Thanks @matthuisman
