### ISSUE TITLE
Can't play certain series on Disney+

### ISSUE THREAD

**Issue by pelag0s** [matthuisman/slyguy.addons#645]
I get `Cannot find stream` errors when trying to play any episode from "The Orville" season 3 on Disney+. Did not see this error before. Previous seasons seem to play correctly.

**Comment by matthuisman** [comment]
what country are you in?

**Comment by matthuisman** [comment]
fixed with [slyguy.disney.plus -> v0.15.6](https://github.com/matthuisman/slyguy.addons/commit/4d2d943fd2700a33c2fe301bff62e996eef4254e)
