### ISSUE TITLE
IPTV Merge request - Pause merging while watching a stream

### ISSUE THREAD

**Issue by stuckinthe** [matthuisman/slyguy.addons#648]
I am using your links for SamsungTV Plus. I have set a cron job to download your xml files every 3 hours since they need to be refreshed often since the only put out a few hours at a time. I have also set IPTV Merge to Run Merge every 3 hours. If I am watching liveTV, the merge causes the channel to stop or hang since iptv merge is restarting the Simple Iptv.

**Comment by liam8888999** [comment]
After setting up iptv merge go into the settings and turn off the option to reload iptv simple after merge, then go into the IPTV simple settings and there is an option to reload playlist and xmltv automatically and it lets you set how often. This doesn't stop the channel from playing as it actually doesn't restart iptv simple just updates on the background

**Comment by matthuisman** [comment]
latest version switches to setting a 10min refresh and not reloading iptv simple. unless force merge via the addon
