### ISSUE TITLE
Sky sport now, Can't watch sky sport 5, 

### ISSUE THREAD

**Issue by siberkolosis** [matthuisman/slyguy.addons#649]
Today, Sky sport now add-on , Can't watch sky sport 5 channel. I am using VPN. Kodi On my Android phone and mi stick.

**Comment by siberkolosis** [comment]
its working now..

**Comment by matthuisman** [comment]
yeh. there seems to be intermittant issue where their streams have something incompatble. unfortunately it never happens when Im around to get a copy of the manifest etc

**Comment by siberkolosis** [comment]
my stream interrupted after over 24 hours. not work for all channel.  
solution is logout and login again with usernama and password.

**Comment by matthuisman** [comment]
i may need to add code to keep the token fresh while playing / not using the addon
