### ISSUE TITLE
Problem Star+ in Kodi  Google chromecast 4k

### ISSUE THREAD

**Issue by espaun206** [matthuisman/slyguy.addons#655]
Hi
Audio for live events comes ahead of the image
like the live image gave some microcuts

I have a Amazon fire tv max and this doesn't happen it only happens on Google chromecast 4k

on both I have kodi 20.2

**Comment by matthuisman** [comment]
i wont be able to help with such an issue sorry. something to do with kodi or inputstream adaptive or hardware
