### ISSUE TITLE
Epg went down

### ISSUE THREAD

**Issue by derrgoo** [matthuisman/slyguy.addons#656]
Maybe just my box's but trying to grab epg on Pluto and says it can't find the ip address linked to it.

**Comment by matthuisman** [comment]
what exact url and what is the error?

**Comment by derrgoo** [comment]
I am on kodi 21.2 which I just switched to today. Please see pic below of a fresh install on base skin. It seems to try to pull but stops and no epg shows up. https://github.com/matthuisman/slyguy.addons/assets/63697905/408a3ba9-a8ab-441c-a0f2-f6705da8a93a

**Comment by matthuisman** [comment]
sorry, i dont see the issue.
I see it fetching https://i.mjh.nz/PlutoTV/us.xml.gz  which downloads fine for me

In the main menu - if you see "setup iptv simple client", then click that

**Comment by derrgoo** [comment]
Okay got part of it. ![image](https://github.com/matthuisman/slyguy.addons/assets/63697905/4d6eb6e8-4e36-4ef9-b379-0a79500f08c5)

**Comment by derrgoo** [comment]
I switched back to kodi 20.2 and all worked as it should. (Closed and thanks)
