### ISSUE TITLE
PlutoTV playlists / add-on OFFLINE until further notice

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#657]
News article about what and why:
https://torrentfreak.com/dazn-dmca-notice-hits-pluto-tv-playlist-linking-to-dazns-own-streams-240108/

Have taken offline to keep Vultr happy and hopefully not take down my hosting.

in the meantime users could try https://nocords.xyz/ instead

I'll search for alternatives and keep everyone posted here

**Comment by matthuisman** [comment]
users could try https://nocords.xyz/ instead

**Comment by jac4e** [comment]
Is the software you use to generate the m3u's for pluto open source, similar to [maddox/pluto-to-channels](https://github.com/maddox/pluto-for-channels)?

**Comment by maurirope** [comment]
> Is the software you use to generate the m3u's for pluto open source, similar to [maddox/pluto-to-channels](https://github.com/maddox/pluto-for-channels)?

+1 for this repo. Spun-up a container, locked network for jellyfin access only and working great. It will return the streams for my region only though (UY). I havent found a way to pull up brazil regions that I want.

**Comment by matthuisman** [comment]
ill try get a docker solution sorted so users can simply generate their own

**Comment by ChiFungLam** [comment]
> users could try https://nocords.xyz/ instead

got this:
"
Sorry, you have been blocked
You are unable to access nocords.xyz
"
;<

**Comment by matthuisman** [comment]
oh wow. i dont get that all.
Is that a cloudflare message or their site returning it?

**Comment by ChiFungLam** [comment]
> oh wow. i dont get that all. Is that a cloudflare message or their site returning it?

seems from cloudflare (can't upload screen capture to show the screen)

**Comment by boeder8** [comment]
> > users could try https://nocords.xyz/ instead
> 
> got this: " Sorry, you have been blocked You are unable to access nocords.xyz " ;<

Yeah was getting that yesterday but the site loads using VPN. Not sure how viable that is long-term.

Hoping Matt comes up with a good solution in the next days/weeks..

**Comment by mgxtv** [comment]
> users could try https://nocords.xyz/ instead

Can you upload Pluto MX, ES, BRA, IT epg?

**Comment by mgxtv** [comment]
> https://torrentfreak.com/dazn-dmca-notice-hits-pluto-tv-playlist-linking-to-dazns-own-streams-240108/
> 
> Have taken offline to keep Vultr happy and not take down my hosting. I'll search for alternatives :)
> 
> in the meantime users could try https://nocords.xyz/ instead

But you must be delete only DAZN link

**Comment by mgxtv** [comment]
Can anybody share me Pluto TV MX Epg?

**Comment by derrgoo** [comment]
![image](https://github.com/matthuisman/slyguy.addons/assets/63697905/ed2bde37-3fbf-4a02-b75a-baaeec31b374)

Even with vpns.

**Comment by ChiFungLam** [comment]
> ![image](https://private-user-images.githubusercontent.com/63697905/295117607-ed2bde37-3fbf-4a02-b75a-baaeec31b374.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODE5ODEsIm5iZiI6MTcwNDc4MTY4MSwicGF0aCI6Ii82MzY5NzkwNS8yOTUxMTc2MDctZWQyYmRlMzctM2ZiZi00YTAyLWI3NWEtYmFhZWVjMzFiMzc0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNjI4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGJhYTg1ZTM5NjMzNDI3ZDVjYjIzNWU2M2ViMTI4NGM4ZmJhYmI5YjIwNTZlY2RmZjNkNGZhNDE0NzI0ZDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WMLzeTnPc-9skyLlFPpYheJtvSn0WTRARQwnoFcpajY)
> 
> Even with vpns.

May be tons people go there within these 2 days

**Comment by jeepcook** [comment]
Hello,
We are in a bad situation. But is there a problem if you generate xml epgs? The url you gave doesn't support french epg and others.
Thanks

**Comment by 4v3ngR** [comment]
i've also hacked together a node script that generates the m3u8 and xml for different regions (to get other regions, an IP address from that region is needed).

https://github.com/4v3ngR/pluto_tv_scraper

I hope this helps others.

**Comment by th3p0l4rb34r** [comment]
> i've also hacked together a node script that generates the m3u8 and xml for different regions (to get other regions, an IP address from that region is needed).
> 
> https://github.com/4v3ngR/pluto_tv_scraper
> 
> I hope this helps others.

Hey cool tool it actually helped me get the MX m3u8 and xml.

**Comment by jeepcook** [comment]
> i've also hacked together a node script that generates the m3u8 and xml for different regions (to get other regions, an IP address from that region is needed).
> 
> https://github.com/4v3ngR/pluto_tv_scraper
> 
> I hope this helps others.

Hello, Thanks for these great work.

Is it possible to use same tvg-id as the one used by Matt.

Example:
- with your script every tvg-id are followed by the country code: 64edf6eaa7ec0d000812f58c-uk
- with Matt script the tvg-id is just 64edf6eaa7ec0d000812f58c

Thanks

**Comment by 4v3ngR** [comment]
> > i've also hacked together a node script that generates the m3u8 and xml for different regions (to get other regions, an IP address from that region is needed).
> > https://github.com/4v3ngR/pluto_tv_scraper
> > I hope this helps others.
> 
> Hello, Thanks for these great work.
> 
> Is it possible to use same tvg-id as the one used by Matt.
> 
> Example:
> 
> * with your script every tvg-id are followed by the country code: 64edf6eaa7ec0d000812f58c-uk
> * with Matt script the tvg-id is just 64edf6eaa7ec0d000812f58c
> 
> Thanks

Previously I found that pluto TV sometimes uses the same channel id for different channels in different locations. My local setup merges several playlists and xml files into one, and I wanted to ensure the ids were globally unique.

If you want, you could edit lib/plutotv/api.js and remove the '-${region}' suffixes from the ids in the m3u8 and xmltv functions.

**Comment by jeepcook** [comment]
Ok I understand your choice. I never detected the same if for different channels but you yes, so your choice is better.

**Comment by rippledmindd** [comment]
![kodi pluto Matt](https://github.com/matthuisman/slyguy.addons/assets/110704458/032f9cfb-1d71-438b-9251-fa8f366c0e1c)
issues with kodi and slyguy add ons

**Comment by derrgoo** [comment]
Read the title of the thread. 👍

**Comment by matthuisman** [comment]
some people.....

**Comment by rippledmindd** [comment]
I thought i was giving you feedback of issues by sending you a screenshot
stupid me

**Comment by WeirdG** [comment]
Thanks Matt. It's a shame Torrentfreak brought more attention to your work. Thanks for sharing a backup.

**Comment by boeder8** [comment]
> Thanks Matt. It's a shame Torrentfreak brought more attention to your work. Thanks for sharing a backup.

Exactly. Damn TF, that pissed me off!

**Comment by BoomGold23** [comment]
Still not able to access nocords.xyz
:<

**Comment by boeder8** [comment]
> Still not able to access nocords.xyz :<

Try different VPN servers. US ones generally work for me. 

It's a good alternative but far FAR inferior to what Matt had in terms of quantity and EPGs. Power to him. Hope he finds a way to bring it back..

**Comment by jeepcook** [comment]
Just use the 4v3ngR software and you will have exactly the same files as the one generated by Matt. I'm using it still few days and I 've detected no problem.

**Comment by ChiFungLam** [comment]
> Just use the 4v3ngR software and you will have exactly the same files as the one generated by Matt. I'm using it still few days and I 've detected no problem.

Great, see if someone package it into a docker solution so that everyone can install their own version e.g. on Vercel

**Comment by boeder8** [comment]
> Just use the 4v3ngR software and you will have exactly the same files as the one generated by Matt. I'm using it still few days and I 've detected no problem.

Currently a noob and no idea how to use it but I will definitely try to learn :)

**Comment by derrgoo** [comment]
Does this need to be updated daily?

**Comment by jeepcook** [comment]
> Does this need to be updated daily?

More than once a day. At least 3 times I think. So that's why you have to implement the tool on your system.

**Comment by derrgoo** [comment]
Looks like easier just to watch Pluto app lol

**Comment by 4v3ngR** [comment]
For those that are interested, I've pushed the scraper to the npmjs repo. There's no longer any need to check out the source code and do npm install etc. Do note that both npm and node (version >= 14) is required. Once node is installed on your system, a quick `npm install -g plutotv-scraper` is all that is needed to run it. There's also exttra options to support features other wanted.

running `plutotv-scraper --help` will provide some details of the options.

I'll also note that there is a "feature" where it will load config.json from the current directory. I'm not yet sure if this is a bug or a feature. For now it is a feature.

I also changed the license from AGPL to MIT, so everyone is free to use it however they want.

Finally, thanks to Matt for providing the original streams for so many years.

**Comment by rocknrollradio** [comment]
I read many posts, but I can't understand why can't someone upload another working Pluto addon

**Comment by Toei79** [comment]
> I read many posts, but I can't understand why can't someone upload another working Pluto addon

its just in front on you

**Comment by derrgoo** [comment]
Plex offline now?

**Comment by davidmguest** [comment]
The playlists and epgs for Plex, Roku and Samsung now appear to have vanished

**Comment by davidmguest** [comment]
The Australian and NZ playlists and epgs have gone as well .
It looks to me like this is affecting all lists where Matt had his own urls redirecting to the official ones.
The Stirr list is still up (for the moment), but that use the official urls.

I wonder if a return to using the official urls without redirection might be acceptable to the providers/host?

**Comment by Toei79** [comment]
yep skies falling!

**Comment by matthuisman** [comment]
https://twitter.com/MattHuismanNZ/status/1747447831877832986

**Comment by derrgoo** [comment]
Thanks for update. Please update here as well. I don't follow Twitter 👍

**Comment by matthuisman** [comment]
the update is all should be back (except Pluto)

**Comment by boeder8** [comment]
> the update is all should be back (except Pluto)

Awesome! Huge thanks! Is there an issue with Pluto that is different from the one highlighted earlier?

**Comment by matthuisman** [comment]
![giphy](https://github.com/matthuisman/slyguy.addons/assets/6225961/0a91c51d-3f22-429e-9c3e-ba4f15f5dc4d)

**Comment by derrgoo** [comment]
Great job!!!👏
