### ISSUE TITLE
[Disney+] This add-on path is  no longer valid

### ISSUE THREAD

**Issue by LordHorst** [matthuisman/slyguy.addons#659]
Whenever I go to a list with movies anywhere in the plugin (doesn't matter if it's bookmarks, watchlist, recommended, etc.) I get the error 

"This add-on path is no longer valid
If your using favorites, remove the favorite and then re-create it via the add-on"
![screenshot00000](https://github.com/matthuisman/slyguy.addons/assets/36306279/6a283c32-115f-4768-9175-ecfb1a7c6b02)

Yes, the grammar error is from the message itself, see screenshot.
I don't even know if it's your plugin that gives the error message, but I don't see it anywhere else in Kodi.

In the logs I see this line:
`error <general>: GetDirectory - Error getting plugin://slyguy.disney.plus/extrafanart/`
but nothing else that relates to the plugin, or the error.

My specs: LibreElec 11.0.4, Kodi 20.2, Disney+ Plugin 0.15.7

**Comment by matthuisman** [comment]
/extrafanart isn't a path I've coded.
Suggest you try a different skin for a start

**Comment by LordHorst** [comment]
The message does indeed come from a different source, it disappears with a different skin. Thanks, I'll keep digging then!

**Comment by matthuisman** [comment]
My add-on does create the error when it gets a path it doesn't understand
