### ISSUE TITLE
HBO Max shows `KeyError 'url'` when play content

### ISSUE THREAD

**Issue by jiangpengcheng** [matthuisman/slyguy.addons#66]
### Subject of the issue

HBO Max cannot  play any content

### Your environment

- Kodi Version - 19.1
- SlyGuy Common Version - 0.43.9
- HBO Max Version - 0.5.4
- OS - Android 11.0.0

### Steps to reproduce

Launch the HBO Max add-on and try to play any content

### Expected behaviour

Should be able to play content

### Actual behaviour

Below error shows up:

![Screenshot_2021-09-17-09-42-02-378_org xbmc kodi](https://user-images.githubusercontent.com/1858477/133710980-ddc32660-115d-4298-9863-1ba1ff996c64.jpg)

**Comment by jiangpengcheng** [comment]
after enable `ignore_subs`, it works

**Comment by matthuisman** [comment]
fixed now with v0.5.5
https://github.com/matthuisman/slyguy.addons/commit/9cd9844339e5d012f680628ff9c91d8d7d1fb55f
