### ISSUE TITLE
cacert needs updating

### ISSUE THREAD

**Issue by waskodi** [matthuisman/slyguy.addons#662]
I have tried on two different devices with the same error "Failed to install due to invalid structure".

I think it is due to an expired cacert.pem file.

**Comment by matthuisman** [comment]
Kodi Debug log please

**Comment by matthuisman** [comment]
that sounds like a kodi bug as well. if its failing to install the zip. Nothing I can do about that

**Comment by waskodi** [comment]
I tried it on a PI5 with Libreelec, Ubuntu 23 and Win10 Kodi 20.3 with the same results.

    On Sunday, January 14, 2024 at 12:44:10 AM CST, Matt Huisman ***@***.***> wrote:  
 
 


that sounds like a kodi bug as well. if its failing to install the zip. Nothing I can do about that

**Comment by matthuisman** [comment]
you still havnt told me what you are doing to cause it.

Again, you must install the zip from below:
https://slyguy.uk/repository.slyguy.zip

YOU CAN NOT INSTALL  ZIP FROM GITHUB
