### ISSUE TITLE
IPTV AU Addon (MeTV) coming up blank

### ISSUE THREAD

**Issue by missjane63** [matthuisman/slyguy.addons#663]
The channel MeTV in the IPTV AU addon is coming up blank (no video or audio).  It was working before I updated to Kodi 20.3.  Another user in Australia (I'm not) confirmed the same but using Kodi 20.2

Kodi 20.3/Win 7

**Comment by matthuisman** [comment]
they may have removed their live stream. cant seem to get it to work using their android app either.

**Comment by matthuisman** [comment]
looks like the channel has been removed from their app / streaming.
I have removed it from my playlists
