### ISSUE TITLE
Paramount Plus Addon Stopped Working

### ISSUE THREAD

**Issue by bananakinn** [matthuisman/slyguy.addons#664]
Been using the addon regularly and suddenly stopped working today, gave a JSON error and now when i try to login via the addon it states Paramount+ is not available in my region. Viewing through P+ site works fine.

**Comment by austreams** [comment]
> Been using the addon regularly and suddenly stopped working today, gave a JSON error and now when i try to login via the addon it states Paramount+ is not available in my region. Viewing through P+ site works fine.

can confirm this - i have same issue works on browser not kodi

**Comment by matthuisman** [comment]
What version Kodi?

**Comment by bananakinn** [comment]
20.0

i'll try updating to 20.3 to see if that helps and report back

**Comment by austreams** [comment]
v20.1 nexus
Sent from my iPhone

On 16 Jan 2024, at 11:21 am, bananakinn ***@***.***> wrote:

﻿

20.0

i'll try updating to 20.3 to see if that helps and report back

**Comment by matthuisman** [comment]
suspect paramount has changed something

**Comment by dljones8053** [comment]
Get this error in the Kodi log file hope this helps.
2024-01-15 22:48:05.940 T:9920    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-01-15 22:48:10.965 T:18120   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://slyguy.paramount.plus/?_=featured
2024-01-15 22:48:10.999 T:9920    error <general>: CGUIMediaWindow::GetDirectory(plugin://slyguy.paramount.plus/?_=featured) failed

**Comment by gmjh123** [comment]
> suspect paramount has changed something

Fixable?

**Comment by Clintwits** [comment]
Same here, using Kodi 20.3 on both PC and android tv (Nvidia Shield) JSON error at first and now the "Not available in Region" message

**Comment by matthuisman** [comment]
fixed with [slyguy.paramount.plus -> v0.7.6](https://github.com/matthuisman/slyguy.addons/commit/76b03705b456bca5df112a0e4b080f2b2523e83b)

**Comment by gmjh123** [comment]
> fixed with [slyguy.paramount.plus -> v0.7.6](https://github.com/matthuisman/slyguy.addons/commit/76b03705b456bca5df112a0e4b080f2b2523e83b)

Excellent. Confirmed as working on Android. Thanks very much
