### ISSUE TITLE
10Play no longer working

### ISSUE THREAD

**Issue by j-broo** [matthuisman/slyguy.addons#665]
Not sure if they have tightened up VPN sensing or if they changed something on the backend that the addon uses?

It now says only available for Australian residents. 9Now and 7+ still work.

I tested with Windscribe and Speedify. Slyguy addon for 10Play is 0.1.2.

**Comment by matthuisman** [comment]
try their website with the same vpn and you'll have the answer

**Comment by matthuisman** [comment]
ive tested using my connecting via an aussie retail isp connection and it works :) so sounds like they blocking your vpn

**Comment by j-broo** [comment]
Thanks for testing. That sucks.
