### ISSUE TITLE
IPTV Merge - Boot at merge removed

### ISSUE THREAD

**Issue by Lala1976** [matthuisman/slyguy.addons#667]
Since IptvMerge has updated the "run merge at boot" is gone. now I have to manually run merge and after a few days the epg is gone again.

**Comment by matthuisman** [comment]
why does setting a time between merges not work?
If you set that to 3 hours and kodi boots up after 3 hours, itll run the merge

**Comment by matthuisman** [comment]
then set the time to 24 hours?

**Comment by Lala1976** [comment]
I did, but it didn't work. After a few days epg was empty. Can't i go back to an older version, and were can I find the older version that still has merge on boot in it?

**Comment by matthuisman** [comment]
i can add it back in, but if the time since last merge is greater than your set time on boot - it should do the same thing.

If you wait 10mins after the boot - does the epg come back?
As we wait for IPTV Simple to check the files and that can take 10mins.

**Comment by Lala1976** [comment]
Ok I set it to 3 hours now. Will watch it for a few days. I first set it to 12 hours and didn't work. If it's possible to put it back, I can choose what settings we use.
