### ISSUE TITLE
Paramount Plus Widevine License Request Fail [windows]

### ISSUE THREAD

**Issue by bananakinn** [matthuisman/slyguy.addons#668]
Yesterday I started to get an error for "Widevine license request failed" when trying to playback anything off of the Paramount+ plugin using Windows 10 + Kodi 20.3 . I have also tried on an Android TV device and I do not get any errors, playback is fine.

**Comment by bananakinn** [comment]
oh perfect yea that was the fix. there was an updated widevine available :) all works now

thank you!!

**Comment by matthuisman** [comment]
I haven't added a new one in some time so I'm guessing Google has blacklisted an older one. Can you advise what version you were on that wasn't working?

**Comment by matthuisman** [comment]
Maybe even the position? Was you on 2nd to latest?

**Comment by matthuisman** [comment]
nevermind, i see there is only 1 other that isnt revoked. ive now revoked the older one that should make others have to update. thanks

**Comment by bananakinn** [comment]
4.10.2557.0 was the one i was using that didnt work... there was only one version available to update to (4.10.2710.0)
