### ISSUE TITLE
Paramount Plus login issues again

### ISSUE THREAD

**Issue by austreams** [matthuisman/slyguy.addons#672]
exactly same issue as #664
when login it says geo block but website works fine for logins.

**Comment by matthuisman** [comment]
im not seeing the issue. logging in ok with AU or USA ip

**Comment by matthuisman** [comment]
oh. i got an error further along.

try [slyguy.paramount.plus -> v0.7.7](https://github.com/matthuisman/slyguy.addons/commit/c441583e6947e95518d493592f54e87f81fa7d1f)

**Comment by austreams** [comment]
thanks legend
Sent from my iPhone

On 28 Jan 2024, at 7:48 pm, Matt Huisman ***@***.***> wrote:

﻿

oh. i got an error further along.

try slyguy.paramount.plus -> v0.7.7<https://github.com/matthuisman/slyguy.addons/commit/c441583e6947e95518d493592f54e87f81fa7d1f>
