### ISSUE TITLE
Pluto.TV Addon: DAZN Channels could no longer played

### ISSUE THREAD

**Issue by werimail** [matthuisman/slyguy.addons#673]
Hi @matthuisman  , I noticed in the Pluto.TV addon that the DAZN (for examle "DAZN Darts x Pluto TV" or "DAZN International Football x Pluto TV") channels could no longer be played. The error message “Unable to play” always appears. Do you have an idea why that is?

[kodi_slyg_pluto_dazn.log](https://github.com/matthuisman/slyguy.addons/files/14111812/kodi_slyg_pluto_dazn.log)

Greetings Weri

**Comment by werimail** [comment]
Yes @kyl416 , I saw #657 . This entry has now been closed with the result that everything is working again. This is also the case, with the exception of the DAZN channels. Maybe @matthuisman  no longer wants to support this because of the topic described?

Greetings Weri

**Comment by matthuisman** [comment]
thats not the case. the dazn channels are there. its just they need to switch to v2 hls manifest

**Comment by werimail** [comment]
> thats not the case. the dazn channels are there. its just they need to switch to v2 hls manifest
Ah ok @matthuisman , where can this setting be made? Or does your addon need to be adapted for this?

Greetings Weri

**Comment by werimail** [comment]
Hi @matthuisman I noticed that after a certain time the stream from DAZN Darts x PlutoTV simply stops and ends up back in the Kodi main menu. It is irrelevant which Kodi version is used. Is this due to the addon or Inputstream.adaptive? 
Greetings Weri
[kodi_plutlo_omega.log](https://github.com/matthuisman/slyguy.addons/files/14185228/kodi_plutlo_omega.log)

**Comment by werimail** [comment]
> Hi @matthuisman I noticed that after a certain time the stream from DAZN Darts x PlutoTV simply stops and ends up back in the Kodi main menu. It is irrelevant which Kodi version is used. Is this due to the addon or Inputstream.adaptive? Greetings Weri
> 
> [kodi_plutlo_omega.log](https://github.com/matthuisman/slyguy.addons/files/14185228/kodi_plutlo_omega.log)

Hi @matthuisman I have created an additional debug.log for the problem presented. 

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/14551853/kodi.log)
Greetings Weri

**Comment by matthuisman** [comment]
itll be the ad breaks / x-discontuity. So inputstream.adaptive needs to support it fully
nothing i can do my end sorry
