### ISSUE TITLE
Slyguy Common Error

### ISSUE THREAD

**Issue by austreams** [matthuisman/slyguy.addons#675]
since latest updates half of your addons are no longer working so i open slyguy common and goto update sly guy addons and it just errors. iptv merge errors same with other addons.
i also tried check kodi log for slyguy errors and it just errors.

**Comment by matthuisman** [comment]
Log please

**Comment by austreams** [comment]
how do i get you a log mate happy to do it now

**Comment by matthuisman** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by austreams** [comment]
[kodi.txt](https://github.com/matthuisman/slyguy.addons/files/14175000/kodi.txt)

**Comment by matthuisman** [comment]
Very odd error. I'd recommend trying to reinstall slyguy dependencies and
slyguy common
