### ISSUE TITLE
TVNZ+ playback failed error

### ISSUE THREAD

**Issue by Topspin226** [matthuisman/slyguy.addons#679]
I am getting a 'playback failed' error with the TVNZ+ add-on through Kodi on my MacBook Pro. I am in Australia using Windscribe VPN. I can access TVNZ+ content through a browser, but it won't work through the Kodi add-on. This makes me think it's not something to do with geo-blocking/the VPN.

Here is my Kodi log: https://paste.kodi.tv/ibacenamoc

Any help would be appreciated.

**Comment by matthuisman** [comment]
Go into add-on settings> reinstall widevine CDM. See if your on latest. If
not, select and install it. Then try

**Comment by Topspin226** [comment]
Thanks for the response Matt. I have gone into the add-on settings to check and it says under Available Widevine CDM Versions: Darwin x86_64 - 4.10.2710.0 (INSTALLED). When I click on that it says "Widevine CDM (4.10.2710.0) Installed OK. If videos do not play, please restart Kodi and try again." I have restarted and tried again, but I'm still getting the same playback failed error.

**Comment by matthuisman** [comment]
your log shows
`                      </HEAD><BODY>
                                                   <H1>403 ERROR</H1>
                                                   <H2>The request could not be satisfied.</H2>
                                                   <HR noshade size="1px">
                                                   Request blocked.
                                                   We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
                                                   <BR clear="all">
                                                   If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
                                                   <BR clear="all">
                                                   <HR noshade size="1px">
                                                   <PRE>
                                                   Generated by cloudfront (CloudFront)
                                                   Request ID: ogzaBzLl-ZFDffj8N2eg7qbHiMXKWKKDe2ITXhuZwasiM_3cT6q41g==
                                                   </PRE>`

**Comment by matthuisman** [comment]
looks like its blocked.

**Comment by matthuisman** [comment]
so your running kodi on the exact same OS. ie. Kodi in one window and browser in another?
Both using the exact same VPN server?

**Comment by matthuisman** [comment]
oh. i see in log using vpn manager. remove that. could be causing issues

**Comment by Topspin226** [comment]
> so your running kodi on the exact same OS. ie. Kodi in one window and browser in another? Both using the exact same VPN server?

Yes, same computer and same VPN server. 

> oh. i see in log using vpn manager. remove that. could be causing issues

I installed that to see if it would work having the VPN installed directly in Kodi, but I couldn't figure out how to set it up properly, so it's not configured. I will remove it anyway.

**Comment by matthuisman** [comment]
Maybe it's a Mac thing that Kodi doesn't use the VPN connection? Maybe
google that? Someone may have had same issue.

You could also try using my smart URLs which can force my add-ons to use a
particular interface

**Comment by Topspin226** [comment]
I have figured out the issue. There was a setting on my VPN account that needed to be enabled. I can now access the TVNZ+ streams via Kodi. Thanks for your help Matt.

**Comment by matthuisman** [comment]
Excellent to hear. Enjoy!

**Comment by Topspin226** [comment]
I am now getting a new error that just says 'Unauthorised' when I try to watch something through my VPN. Would you be able to confirm if you're also seeing this? I can playback fine via web browser through my VPN.

**Comment by matthuisman** [comment]
Try login in the add-on?

**Comment by Topspin226** [comment]
Thanks Matt, that fixed it. However, I am getting a new issue where the video just freezes during an ad break and does not come back to the live event. I have to stop and restart playback to get back to live. This is currently happening on the Indian Wells Tennis live stream.

**Comment by matthuisman** [comment]
It may be ssai (server side ad injection). Kodi / inputstream.adaptive
doesn't really support it too well. You could try latest Kodi omega. It may
be better. Or try toggling the use inputstream adaptive setting in add-on
settings. Either way, not much I can do about that issue unfortunately

**Comment by Topspin226** [comment]
Ah, okay. That must be what it is. It is very irritating indeed. Will give those suggestions a try. Thanks for your help.

**Comment by matthuisman** [comment]
Are you playing a linear stream or is it a live sport stream? Eg. Access
via live channels or a dedicated listing? You could try the live channel
stream instead if there is one. Eg. Duke.

**Comment by Topspin226** [comment]
It's via the sports streaming menu. Sport > Live and Upcoming. Unfortunately the tennis is not available via one of the live channels.

**Comment by matthuisman** [comment]
[plugin.video.tvnz.ondemand -> v0.20.7](https://github.com/matthuisman/slyguy.addons/commit/2431714b2198986c9675c728749f0a3ddb4cb078) now enforces login for all content to save this same issue popping up in future

**Comment by Topspin226** [comment]
This is for the Unauthorised playback error right Matt, not the SSAI issue?

**Comment by matthuisman** [comment]
Yes correct

**Comment by waynethomas69** [comment]
Am I reading this correctly, that the issue was the user needed to be logged into their TVNZ+ account? I think I have the same issue (content on the TVNZ+ website which requires the user to be logged in), but I can't for the life of me find the addon setting to actually login (or re-login).
Looking in ~/.kodi/userdata/addon_data/plugin.video.tvnz.ondemand/settings.xml there appears to be a shared token in userdata, but no way to populate it.

**Comment by matthuisman** [comment]
the addon just users a global shared user. no need to login.
If your getting content to fail to play, raise a new issue.
If your not in NZ / using a vpn - thats most likely the cause. tvnz blocks a lot of common vpns
