### ISSUE TITLE
Error obtaining Widevine license (too many streams)

### ISSUE THREAD

**Issue by rbadenhorst** [matthuisman/slyguy.addons#683]
Hi,

I'm getting this error non-stop today. In the past it's come up before but usually disappears after a few retries.

Looking at the kodi log, I see another error earlier in the log where it's trying to connect to i-live-cache.akamaized.net (or r-live in some earlier attempts).

I've checked and I can connect to 443 on this host with netcat, the port is open. Is there anything I can check from my side?
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/14318990/kodi.log)

**Comment by rbadenhorst** [comment]
not sure if this relates to my platform, raspberry Pi / libreelec. I found this 

https://github.com/xbmc/inputstream.adaptive/issues/1398
https://github.com/xbmc/inputstream.adaptive/wiki/Widevine-ARM64-support

Will check if it's different if I run kodi on mac/windows.

**Comment by matthuisman** [comment]
DStv its expected. Need to wait a few mins between playing streams I believe

**Comment by rbadenhorst** [comment]
This time it turned out to be more like 6 hours. What is the purpose of the call to that hostname that was giving the error? Is it related to the widevine license or unrelated. 

Thanks for the plugin though, really helps us who don't reside in SA anymore.

**Comment by matthuisman** [comment]
Are you using a shared login? Was someone streaming using same login
elsewhere?

**Comment by rbadenhorst** [comment]
Yes, so I guess that would be the reason. When it says too many streams it means the same as you'd see on the app when it says someone else is already watching or something to that effect. Need to get my brother to go watch in his lounge instead of in bed on his laptop, lol.

**Comment by rbadenhorst** [comment]
Thanks for the responses
