### ISSUE TITLE
Dstv Now add-on Live tv error

### ISSUE THREAD

**Issue by Runheart007** [matthuisman/slyguy.addons#684]
Hi Matt.

Installed the slyguy add-on for Dstv Now yesterday and most of it works well thank you.

I am having trouble when accessing live tv with only a few channels coming through and the rest giving an error in playback an that I should consult my Kiko log.

I am using PrivateVPN when accessing Dstv and it works well.

Please see lig screenshot attached.

Would really appreciate your guidance.
![IMG_4614](https://github.com/matthuisman/slyguy.addons/assets/155484199/727008f0-7afd-4c63-b6b3-ca0bb53ca64a)

**Comment by matthuisman** [comment]
likely they blocking your vpn

Best to ask over here where a lot of users are:
https://mybroadband.co.za/forum/threads/release-dstv-now-kodi-add-on.977513/
