### ISSUE TITLE
Widevine checksum fail

### ISSUE THREAD

**Issue by maddavo** [matthuisman/slyguy.addons#688]
I had older LibreELEC/Kodi SD Cards, now I'm restarting with a fresh new image of LibreELEC 11.0.6 and Kodi 20.3 on a Pi 4.

I've installed Slyguy repository and installed Addons for Disney+, Netflix, Foxtel, 7,9,10 .  Now I need to get Widevine working but I'm getting this error whenever I try playing a video /install/reinstall Widevine :
![20240229_155841](https://github.com/matthuisman/slyguy.addons/assets/1432875/2ba0ee2e-2607-4553-be86-d7e447958b53)

I seem to recall having a similar issue before, I forget how to fix this.  Some help pls ?

**Comment by matthuisman** [comment]
looks like its not downloading the file correctly? ive confirmed that 9aff9fa... is the correct md5 checksum

Maybe get me a kodi debug log so I can see the requests etc its making?

**Comment by matthuisman** [comment]
oh.i can replicate locally :) let me investigate

**Comment by matthuisman** [comment]
found the bug :) 

FIXED NOW. Please try

**Comment by maddavo** [comment]
Yep Matt, u beaut!
