### ISSUE TITLE
Hulu - error accessing season 11 of one piece

### ISSUE THREAD

**Issue by flyingsaucer938134** [matthuisman/slyguy.addons#689]
When I click on the icon for season 11 of one piece I get a "Failed to fetch JSON data" error.
I've watched several of the previous seasons on the kodi app without problem, and I'm able to watch season 11 episodes on the official TV app.
[kodi.log](https://github.com/matthuisman/slyguy.addons/files/14485792/kodi.log)

**Comment by matthuisman** [comment]
fixed with [slyguy.hulu -> v0.3.1](https://github.com/matthuisman/slyguy.addons/commit/7fd08eff22ad299b23bd90be8dbb0b8e7647b5ab)
