### ISSUE TITLE
Having to delete/reinstall 9Now & all ANZAC channels on SlyGuy 

### ISSUE THREAD

**Issue by Srcassis** [matthuisman/slyguy.addons#693]
Each time I start up Kodi (Diggz Builds), I’m having to delete/reinstall all SlyGuy addons & repository &  reinstall from zip. Works fine afterwards (with VPN) while it’s on. If I shut down or reboot Kodi it’s “Groundhog Day”. Haveta redo the entire process. Wondering if this maybe an issue with Kodi or the SlyGuy Repo/addons. Please advise if anyone’s had similar experience

**Comment by matthuisman** [comment]
No other issues. Suspect something in that build is messing stuff up

**Comment by Srcassis** [comment]
Thanks for the quick reply! R/ShaneSent from my iPhoneOn 10 Mar 2024, at 14:55, Matt Huisman ***@***.***> wrote:﻿
Closed #693 as completed.

**Comment by matthuisman** [comment]
also make sure you are not out of space.
You also dont mention what happens to require everything to be re-done.
Does everything just disappear? does the vpn stop working etc etc
