### ISSUE TITLE
TVHEADEND - 7Mate

### ISSUE THREAD

**Issue by audas** [matthuisman/slyguy.addons#694]
Hi,
I am very new to all this and am using TVHEADEND with a raspberry pi hat and feeling fairly stupid. 
I have most channels up and running but channel 7, ABC and some other local Australian ones.

Also struggling with EPG using the XML files- however I am presuming I will have to install the XML plug in for linux for that to work.

Just hoping to get the 7mate going for footy.

I am in Australia, using local DNS servers without any VPN running etc.

I am not able to get the streams going directly from the links in the embedded files at all. 

Such as 

"sevenprd01,CAS27.m3u8"

I followed some previous suggestions to extend the time period to allow them to be re-scanned and change it from IDLE to pending.

Sorry if this is just way out of scope.

Thanks.

**Comment by matthuisman** [comment]
7mate wont show the footy anyway. they dont have the rights to live stream it via online
