### ISSUE TITLE
plextv Ghost Hunters channel cannot watch or viewing

### ISSUE THREAD

**Issue by mrusli70** [matthuisman/slyguy.addons#695]
I install the slyguy kodi add ons and the plextv ghost hunters tv programme cannot seems to view at all.

**Comment by mrusli70** [comment]
plexlive tv under usa live cannot watch ghost hunters.channel  sometimes giving errors that indicates failed to connect to host:i.mjh.nz check your internet connection

**Comment by matthuisman** [comment]
geolocked to usa. need usa ip to watch. i confirmed i can watch with a usa vpn
