### ISSUE TITLE
SkysportNow bug

### ISSUE THREAD

**Issue by AaronM-NZ** [matthuisman/slyguy.addons#696]
Trying to do anything gives error. Tried clearing cache, couple dif devices, same error. Thanks!
![1710640792773471521183235155285](https://github.com/matthuisman/slyguy.addons/assets/132176866/5e13eba4-4a55-44ec-a1d1-25bb9edfd223)

**Comment by matthuisman** [comment]
Have you tried logout and login again?

**Comment by AaronM-NZ** [comment]
That worked - thanks!
