### ISSUE TITLE
Paramount+: link.theplatform.com returns US manifests on international accounts

### ISSUE THREAD

**Issue by StollD** [matthuisman/slyguy.addons#697]
When I play the first episode of Star Trek Discovery Season 4 from my german account, the german language tracks are missing. Only the english audio and subtitles are available.

The reason seems to be that the plugin always tries to fetch the manifest from the CDN for the US version of Paramount+. This works fine in most cases, when they use the same files for the US version and the international one. But in this case, the US version has Dolby Vision and the international one doesn't. So the CDN only has the US version.

I used this hack to make it play the correct version by ignoring theplatform.com:

```diff
diff --git a/slyguy.paramount.plus/resources/lib/api.py b/slyguy.paramount.plus/resources/lib/api.py
index df2f987..674e664 100644
--- a/slyguy.paramount.plus/resources/lib/api.py
+++ b/slyguy.paramount.plus/resources/lib/api.py
@@ -339,6 +339,7 @@ class API(object):
         }
         url = self._config.get_link_platform_url(video_id)
         try:
+            raise Exception()
             resp = self._session.get(url, params=params)
             resp.raise_for_status()
             root = parseString(resp.content)

```

I would have sent a pull request with a better fix, but sadly I didn't have any good ideas how to make the use of theplatform.com optional without rewriting the entire play method.

**Comment by matthuisman** [comment]
I can just remove use of platform. But then you get worse quality I believe

**Comment by StollD** [comment]
I just tried both, and the bitrate is the same (or at least very similar) according to Kodi.

One difference I noticed is that platform gives me *all* languages (french, spanish, ...), while the fallback only gives me german + english. The web player does the same.

**Comment by matthuisman** [comment]
maybe its only USA where the platform enables higher quality.
The fallback is the correct way their apps use etc. platform was like a workaround to get better quality.

Your syaing the web player gets the same German + English only?
Thats fine i guess

**Comment by matthuisman** [comment]
[slyguy.paramount.plus -> v0.7.9](https://github.com/matthuisman/slyguy.addons/commit/8962f794cc14aa626d433f9cb53ddd10c340d8bc) pushed that makes it only use link.theplatform for USA accounts :)

should make a bit faster for INT playback to start as well

**Comment by StollD** [comment]
Sorry for the late answer. Can confirm that it works fine now. Thank you for the quick fix!
