### ISSUE TITLE
VPNs not able to access DisneyPlus movies out of region, TV series are OK

### ISSUE THREAD

**Issue by 8traxrule** [matthuisman/slyguy.addons#698]
I already messaged Matt about this and he said it has been fine on his end, but I'm hoping someone else may be able to at least give me a clue as to what's going on:

I'm in the US and use NordVPN on an NVidia Shield (Android Device). I just activated trials of SurfShark and ExpressVPN, but those behaved the same way. I contacted NordVPN tech support and they had me change a few settings which didn't help and they could not give me any further answers. ExpressVPN admitted defeat and actually cancelled my trial for me.

NordVPN was working fine for a while but the issue recently is that when I set the VPN to another country, I can get that country's options through the DisneyPlus addon (such as the "Star" section which doesn't exist in the US) but any movies that are not available on the US service will not play- I get an "UNEXPECTED ERROR" message which is very long but begins with "**File "plugin.py", line 744, in _play for row in data.get('items', []):**" and 5 other similar lines following it. Movies that ARE available in the US from Disney (but not on Hulu) will still play normally, and series with multiple episodes DO play normally even if they're not available in the US. I'm suspecting that TV episodes are structured differently than movies and that's where the problem lies. Unfortunately I'm not technically adept enough to know for sure.

I can still access everything through the native Android DisneyPlus app, but for a number of reasons I much prefer to use the Kodi addon and wouldn't even subscribe if I didn't have that option. If this is beyond what can be done here then I'm sorry for wasting everyone's time, but would certainly appreciate if anyone might have at least an idea why this has been happening after working fine for several months.

**Comment by austreams** [comment]
the accounts are region locked i believe mate that’s your problem. if you want access to AU content use an AU account.
Sent from my iPhone

On 20 Mar 2024, at 3:56 pm, Matt Huisman ***@***.***> wrote:

﻿

full kodi debug log?

**Comment by 8traxrule** [comment]
I've been trying for days to properly save a debug log, but will this work- it's from Kodi Logfile Uploader which gives a URL for my log:

https://paste.kodi.tv/ipapunisiy

If I did it correctly, it shows that I have my VPN set to Australia and I try to play some movies that are not on the US Disney service which produces the error message. I then play a TV episode which isn't on the US service and that DOES play. I also play a movie that IS on the US service and that plays.

I think it's the way movies are a single item that is causing the issue. TV shows are sorted by seasons and then episodes, and those are playing fine. I have the VPN and just a small number of addons installed on my Fire Stick as a backup, and the same problem is happening on that.

Thanks again for your help and sorry for my lack of technical knowledge.

**Comment by matthuisman** [comment]
i cant see where you are navigating to the content..
Different regions use different content ids. if you have favourites or some sort of service linking directly to old ids - your going to have issues

**Comment by matthuisman** [comment]
oh. the erorr is coming from the code thats trying to get the next auto play movie.

If you turn off auto play next movie in the addon settings - does it work then??

**Comment by matthuisman** [comment]
[slyguy.disney.plus -> v0.16.2](https://github.com/matthuisman/slyguy.addons/commit/8cc935a084527668719aa8b97f59d9e8bc4ca3ee) fixes that bug so it wont error now if there is no up next for movie
