### ISSUE TITLE
peacock tv

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#699]
I was wondering if you have some interest in implementing this. I already implemented it myself based on the web/android app, but they recently changed the login to require a JavaScript header, so now I am forced to read in a cookie instead of user/pass

I found that they do offer a code flow with the TV app:

https://peacocktv.com/activate
https://peacocktv.com/tv

but I am not able to intercept it, because it seems virtual TV devices starting with Android 10 cant do root, and the peacock TV app seems to break unless you use Android 10 or up.

**Comment by matthuisman** [comment]
there is already an addon: https://github.com/Paco8/plugin.video.skyott

**Comment by 3052** [comment]
right, but with the recent change the login no longer works for that addon. if I remember right you have experience with TV apps, and Paco8 does not

**Comment by 3052** [comment]
I can offer a significant donation if you can help with this

**Comment by matthuisman** [comment]
have you asked Paco8?

**Comment by 3052** [comment]
yeah I posted an issue, but he says it works for him. I showed that his code did work for me a few times, but I think the server is A/B testing or something, because it will randomly fail if you dont provide the JavaScript headers. so I would like to just use the code method from the TV, but I can only intercept Android 9 TV and I think the app requires Android 10

**Comment by 3052** [comment]
can you help?

**Comment by matthuisman** [comment]
i did find my old code and confirmed i do have flow for device code and even username / password using the tv app api endpoints.

**Comment by 3052** [comment]
email/password flow is working now, but it seems they might be A/B testing the JavaScript headers, so I definitely want the code flow as an option if possible

**Comment by 3052** [comment]
I made some progress, but the app keeps crashing:

~~~json
{
  "pollingPeriodSecs" : 2,
  "remainingOtpTtlSecs" : 217,
  "oneTimePassword" : "sp6j7c",
  "status" : "COMPLETED",
  "householdId" : "7c4c4eb0-0bc9-4806-b1c2-e37122134818"
}
~~~
