### ISSUE TITLE
[Disney+] Crash when changing audio stream

### ISSUE THREAD

**Issue by thombet** [matthuisman/slyguy.addons#70]
Hello @matthuisman,

I would like to report a bug in the Disney+ add-on.

When I play a video and I try to change the audio stream (to change the language) Kodi crashes.

I'm on OSMC with Kodi 19.1 and here is the debug log: http://paste.kodi.tv/fotuhorazu

I have Disney+ 0.9.9 and InputStream Adaptive 2.6.18

Thanks in advance for your help.

**Comment by matthuisman** [comment]
this will be out of my hands unfortunately.

i suspect either an inputstream adaptive or osmc issue.

has it just started happening?

**Comment by thombet** [comment]
Thanks for the fast feedback.

The issue started in the last 8-10 hours.
I checked in the Netflix add-on and I don't have the problem: does it mean InputStream Adaptive is out of the list?

**Comment by matthuisman** [comment]
there has been no updates to my add-ons for 48 hours...
So maybe there was an OSMC update?
did you update the widevine lately?

**Comment by thombet** [comment]
Thanks for the information even though it is not related to your add-ons!

I didn't update anything (OSMC nor InputStream Adaptive) recently but you're probably right: it may be related to the issue you referenced in InputStream Adaptive because I get crashes when I simply stop the playback.

I am using Widevine 4.10.1679.0 though...

When I opened the ticket it was really blocking because the default language for audio was wrongly configured in Kodi but now I can work around this issue by enforcing the language before playback in Kodi settings.
While configuring the default audio language I found out that the default language for subtitles configured in Kodi is not used on the Disney+ add-on: I configured it to French but the first subtitle in the list is selected instead. I saw there are settings about subtitles language in Disney+ but they are left empty on my side. Are these settings overwriting the Kodi default settings even when not used?

**Comment by thombet** [comment]
I didn't find anything in the OSMC forum about the issue I reported so I tried to test more and actually it seems the problem occurs only for 1 show: Marvel's What If.

I tried with other shows and movies and I am able to change the language of the audio stream without any crash!
Can you please try on your side to change the audio stream for this show?

**Comment by matthuisman** [comment]
@thombet 
are you still getting crashes?
Have you tried Widevine 4.10.2252.0 ?

**Comment by thombet** [comment]
Thanks for binging back this topic.
I just tested and I don't get crashes anymore (even on the "What If..." show) even though I am still using Widevine 4.10.1679.0

Thanks for your support.
