### ISSUE TITLE
plugin.video.stan.au: Streamco.Login.RateLimitExceeded

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#701]
using this code:

~~~py
from lib import api

hello = api.API()
hello.login('EMAIL', 'PASSWORD')
~~~

I get this result:

~~~
{'errors': [{'code': 'Streamco.Login.RateLimitExceeded'}]}
Traceback (most recent call last):
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\hello.py", line 6, in <module>
    hello.login('EMAIL', 'PASSWORD')
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\lib\api.py", line 95, in login
    self._oauth(payload)
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\lib\api.py", line 152, in _oauth
    raise APIError(_(_.LOGIN_ERROR, msg=msg))
lib.api.APIError: 30003
~~~

I know the credentials are valid, because I can use them with the official web client and Android client

**Comment by matthuisman** [comment]
RateLimitExceeded = try a different IP address?

**Comment by 3052** [comment]
same result for both of these:

au-bne-wg-301
au-bne-wg-302

note I think the error is misleading, as from my experience the error is generated if the request is incorrect, such as missing request header or missing query string value

**Comment by matthuisman** [comment]
could be. might need user agent change or something

**Comment by 3052** [comment]
note the web and phone clients both need reCAPTCHA, so that might be it

**Comment by matthuisman** [comment]
oh. ive disabled the user/pass from the addon already.

Please just use the addon as-is :)

I suspect discovered this previously
