### ISSUE TITLE
Incorrect EPGs for some Samsung Channels

### ISSUE THREAD

**Issue by davidmguest** [matthuisman/slyguy.addons#702]
Where a Pluto and Samsung have different versions of the same channel and the Samsung version is based on a Pluto feed, the Samsung EPG contains the same details as the Pluto EPG even though the programming is different.

One example is Classic TV: 
Pluto Version: https://r.mjh.nz/PlutoTV/5d134a74ca91eedee1630faa-alt.m3u8 fed from https://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/5d134a74ca91eedee1630faa/master.m3u8?...

Samsung Version: https://i.mjh.nz/SamsungTVPlus/GBAK3504525A.m3u8 fed from https://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/5e1c62c000dd7a0009039432/master.m3u8?...

These two versions have different programming, but EPG id GBAK3504525A (for the Samsung Version) contains the same program details as EPG id 5d134a74ca91eedee1630faa (for the Pluto Version)
The program details in both EPGs match the programming for the Pluto Version.
The details in the Samsung EPG do not match the programming in the Samsung version.

I have also found similar examples with:
Conspiracy (Pluto: 5d4ae94ef1a1bbb350ca41bb Samsung: GBBA33000356L)
Consulenze Illegali (Pluto: 60b9dc99521a1400079bdfba Samsung: ITBC3000004PL)

This issue appears to only exist when the Pluto ID of the stream feeding the Samsung version is higher that the Pluto Id of the Pluto version.

Is this an issue with the extraction of the EPG info, or with the EPG info as provided by Samsung?

**Comment by matthuisman** [comment]
Samsung epg comes directly from Samsung. Pluto epg comes from Pluto. There
is no sharing. If one is wrong, then that's the provider doing it
incorrectly and out of my hands
