### ISSUE TITLE
plugin.video.stan.au: lib.api.APIError: 30003

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#703]
using this code:

~~~py
from lib import api

hello = api.API()
code, url = hello.device_code()
input(code)
result = hello.device_login(url)
print(result)
hello.play('1768588')
~~~

I get this result:

~~~
YXHQ95PJ
True
Traceback (most recent call last):
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\hello.py", line 8, in <module>
    hello.play('1768588')
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\lib\api.py", line 243, in play
    self._check_token(force=True)
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\lib\api.py", line 77, in _check_token
    self._oauth(payload)
  File "D:\Desktop\slyguy.addons-master\plugin.video.stan.au\resources\lib\api.py", line 152, in _oauth
    raise APIError(_(_.LOGIN_ERROR, msg=msg))
lib.api.APIError: 30003
~~~

during the input I visit https://www.stan.com.au/activate and enter the code, and get "your code has been verified"

**Comment by matthuisman** [comment]
Does it work via Kodi?

**Comment by matthuisman** [comment]
Closed? Did the add-on work? As it wasnt for me when I tried quickly last night

**Comment by 3052** [comment]
the above doesn't work, and I dont have time to test it with Kodi. I got it working in my own code, so I dont really care if it works here anymore. I am happy to help troubleshoot via the command line, but I have zero interest in installing and/or testing via Kodi

**Comment by matthuisman** [comment]
I build Kodi add-ons. I'm starting to think your using this for pirating
which I'm not interested in. Good luck with it

**Comment by 3052** [comment]
I am interested in downloading media, so that I can play it with players other than the standard web client. I prefer MPC-HC. I am not interested in sharing media that I download, or selling the media. its just for personal use.

**Comment by matthuisman** [comment]
Is your code public? Can you point to the repos?

**Comment by 3052** [comment]
why do you want to see it?

**Comment by matthuisman** [comment]
Two way street right?

**Comment by 3052** [comment]
OK you just made me nervous with the piracy comment. I am not trying to break any laws, but I do think I have a moral right to play media on the player of my choice

https://github.com/3052/media/tree/main/stan

**Comment by matthuisman** [comment]
I just didn't think any other players could deal with the widevine?? So
that's new to me

**Comment by 3052** [comment]
I have code that can make Widevine license requests

**Comment by matthuisman** [comment]
Yes. But he player would still need to use something to talk to the
widevine CDM etc right? Kodi uses inputstream. Does your player support
Widevine?

**Comment by 3052** [comment]
my code makes a Widevine license request, which returns an encrypted key. the key is decrypted with a locally downloaded or dumped CDM. once the key is decrypted it can be used to decrypt the media, which can then be played on a player of choice

**Comment by matthuisman** [comment]
Oh right. L3 only then I suspect as I know L3 was "broken"

**Comment by 3052** [comment]
correct

**Comment by 3052** [comment]
correct, but even with L3 you can get 1080p and similar, not sure about 4K but I don't care about that anyway, too big for my needs

**Comment by matthuisman** [comment]
On some services yes. But like HBO max limits quite a bit for L3. Not sure
about Peacock

**Comment by 3052** [comment]
Peacock gets 1080p no problem. I haven't looking into HBO yet cause they don't have a trial I think

**Comment by matthuisman** [comment]
did you work out peacock? I had python script to do the device login flow years ago. not sure if it will still work.
It was a pain to get working if I recall

**Comment by 3052** [comment]
Peacock was doing A/B testing for a new login flow two weeks ago. for those in the test group, certain request headers are now generated by JavaScript, and are essentially impossible to bypass. so currently I am just inputting the `idsession` cookie into my tool and doing it that way. if someone can proxy the TV app we can use the code login via https://peacocktv.com/activate. I tried it myself but I can only capture Android 9 TV apps

**Comment by matthuisman** [comment]
stan kodi addon device login now fixed
