### ISSUE TITLE
plugin.video.stan.au: programs source

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#706]
can you explain where this endpoint came from:

https://github.com/matthuisman/slyguy.addons/blob/1a07ad153cbd47bcbdfc8279763f9a59eb6b8ff5/plugin.video.stan.au/resources/lib/api.py#L238

it seems the current web and Android clients both use:

~~~
/programs/v1/legacy/programs/{program_id}.json
~~~

**Comment by matthuisman** [comment]
No idea sorry. Too long ago
