### ISSUE TITLE
Need Help!!

### ISSUE THREAD

**Issue by TheGridRepo** [matthuisman/slyguy.addons#710]
Hey Mate been struggling with an old k18 addon which was abandoned, i somewhat brought back to life for k20 with minor little bugs i cant seem to figure out was wondering if you can help a bother out since im sure your way more experience in python then i am.
[plugin.video.pirateslife4me-12.0.zip](https://github.com/matthuisman/slyguy.addons/files/14845842/plugin.video.pirateslife4me-12.0.zip)

the way i see it the issue is in the way its reading resolverurl.lib kodi.py  in my default.py  to get the GetTorLinks

def main_menu39():

    kodi.create_item({'mode': ""}, '[COLOR gold]Pirate Bay XXX Top Uploader Borusssia 1 to 30[/COLOR]', is_folder=False, is_playable=False)

    GetTorLinks('https://pirateproxylive.org/user/Borusssia/0/3')

**Comment by matthuisman** [comment]
not interested sorry. maybe ask in kodi forums

**Comment by TheGridRepo** [comment]
Ok thanks aways. Just thought I'd ask 

Sent from AOL on Android 
 
  On Tue, Apr 2, 2024 at 10:26 p.m., Matt ***@***.***> wrote:   


not interested sorry. maybe ask in kodi forums

**Comment by matthuisman** [comment]
no harm in asking - but i can just tell by the name and code its a pirate addon that i dont want to go near.
1) illegal
2) code will be shit

**Comment by TheGridRepo** [comment]
Not for distribution but personal use.

Sent from AOL on Android 
 
  On Tue, Apr 2, 2024 at 10:31 p.m., Pietro ***@***.***> wrote:   It's an old pirate Bay addon

Sent from AOL on Android 
 
  On Tue, Apr 2, 2024 at 10:29 p.m., Matt ***@***.***> wrote:   


no harm in asking - but i can just tell by the name and code its a pirate addon that i dont want to go near.
   
   - illegal
   - code will be shit
