### ISSUE TITLE
Hulu freezing after update to Omega

### ISSUE THREAD

**Issue by ZaphodBeeblebrox24** [matthuisman/slyguy.addons#713]
I use several slyguy addons including Disney+, Paramount+ and Hulu. All work ok with Omega except for Hulu which plays the intro and then freezes before streaming the content.

Anyone else seeing this with Omega?

**Comment by matthuisman** [comment]
best to open an issue in inputstream.adapative.
That is what is used for playbacl

**Comment by matthuisman** [comment]
see existing issue: https://github.com/matthuisman/slyguy.addons/issues/584

**Comment by ZaphodBeeblebrox24** [comment]
Is this the same issue as it isn't live streams?

**Comment by matthuisman** [comment]
Is Nexus working for vod?
