### ISSUE TITLE
9NOW live channels playback error

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#716]
playback error on all live channels in the 9now app

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/14957917/kodi.log)

**Comment by scottydulton** [comment]
i was using nexus 20.1

**Comment by scottydulton** [comment]
tested omega this morning still same issue

**Comment by matthuisman** [comment]
Do the 9 channels play ok in yh IPTV Au add-on?

**Comment by scottydulton** [comment]
yes they do i didnt think to check that

**Comment by matthuisman** [comment]
fixed with [slyguy.9now -> v0.1.9](https://github.com/matthuisman/slyguy.addons/commit/7f9b3264035f604563dae2de28c4728ff14588aa)

**Comment by Boghopperie** [comment]
Sorry, how do I get the slyguy.9now onto my Kodi installation. I can't find it in the repo.

**Comment by matthuisman** [comment]
https://www.matthuisman.nz/2021/02/9now-kodi-add-on.html

**Comment by Boghopperie** [comment]
Thank you 👍👍
