### ISSUE TITLE
Hulu VOD hanging on Omega

### ISSUE THREAD

**Issue by ZaphodBeeblebrox24** [matthuisman/slyguy.addons#717]
I am using the Hulu addon to watch VOD. On Nexus it worked fine but now on Omega it hangs kodi and never starts playing past the Hulu intro. Amazon, Netflix, Disney+ and Paramount+ all work fine. I am using Coreelec 21 on an Odroid N2+.

Debug logs:

https://paste.coreelec.org/Dh8F1I

**Comment by matthuisman** [comment]
The add-on is the same between nexus and omega. So suggest this is another
inputstream adaptive bug

**Comment by ZaphodBeeblebrox24** [comment]
Not much help there either.. I only have some RPI4s and my Odroid N2+

https://github.com/xbmc/inputstream.adaptive/issues/1530

**Comment by matthuisman** [comment]
It'll take time....weeks, maybe months. If you want quick fix, revert to
Nexus

**Comment by ZaphodBeeblebrox24** [comment]
Understood

**Comment by matthuisman** [comment]
Actually, you should be able to install the older inputstream adaptive
version onto Omega

**Comment by ZaphodBeeblebrox24** [comment]
Rolled back to 21.3.1.1 and the behavior i actually worse, it doesn't even show the intro Hulu video before hanging and requiring kodi be killed from the command line

**Comment by matthuisman** [comment]
No..you'll need to rollback to a nexus version probably by manually
downloading the nexus zip and installing it.

**Comment by ZaphodBeeblebrox24** [comment]
Download the zip from https://github.com/xbmc/inputstream.adaptive/tree/20.3.18-Nexus and tried to install it, sadly i just errored:

2024-04-16 15:41:05.153 T:3931    error <general>: Repository add-on repository.atreides.tools uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-04-16 15:41:05.153 T:3931    error <general>: Repository add-on repository.atreides.tools does not have any directory matching 21.0.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-04-16 15:41:05.154 T:3931    error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-04-16 15:41:05.154 T:3931    error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.0.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-04-16 15:41:05.159 T:3931    error <general>: Repository add-on repository.jenrepo uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.

**Comment by matthuisman** [comment]
sorry, to confirm you tried installing on of these https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/20.3.18-Nexus/1/artifacts ? and it didnt work?

**Comment by ZaphodBeeblebrox24** [comment]
Just tried with [cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-20.3.18.zip](https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/20.3.18-Nexus/1/artifact/cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-20.3.18.zip)

and got error:

2024-04-16 19:49:16.965 T:3931    error <general>: CAddonInfoBuilder::ParseXML: addon.xml from 'inputstream.adaptive' for binary type 'kodi.inputstream' doesn't contain library and addon becomes ignored
2024-04-16 19:49:28.891 T:4883    error <general>: Repository add-on repository.atreides.tools uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-04-16 19:49:28.891 T:4883    error <general>: Repository add-on repository.atreides.tools does not have any directory matching 21.0.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-04-16 19:49:28.892 T:4883    error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-04-16 19:49:28.892 T:4883    error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.0.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-04-16 19:49:28.896 T:4883    error <general>: Repository add-on repository.jenrepo uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.

**Comment by zuzia-dev** [comment]
I have the same problem in Debian 12, KODI v21 Omega, ISA v21.4.5. I can't use an older version of ISA because some add-ons stop working.

“Alien” movie, HEVC codec. KODI Hangs.
```
warning <general>: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
    info <general>: Creating InputStream
warning <general>: AddOnLog: inputstream.adaptive: Warning "inputstream.adaptive.manifest_type" property is deprecated and will be removed next Kodi version, the manifest type is now automatically detected.
                                                   If you are using a proxy remember to add the appropriate "content-type" header to the HTTP manifest response
                                                   See Wiki page "How to provide custom manifest/license" to learn more about it.
info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 2, Streams in first period: 3, Type: VOD)
info <general>: Creating Demuxer
info <general>: Opening stream: 1001 source: 256
info <general>: Creating video codec with codec id: 173
info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: HEVC (High Efficiency Video Coding)
info <general>: Creating video thread
info <general>: running thread: video_thread
info <general>: Opening stream: 1002 source: 256
info <general>: Finding audio codec for: 86056
info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
info <general>: Creating audio thread
info <general>: running thread: CVideoPlayerAudio::Process()
info <general>: VAAPI::Close
info <general>: Creating audio stream (codec id: 86056, channels: 2, sample rate: 48000, no pass-through)
info <general>: CActiveAESink::OpenSink - initialize sink
info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
error <general>: Sink Timer expired for more than buffer time: 0.15s
info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: HEVC (High Efficiency Video Coding)
info <general>: GL: Selecting YUV 2 RGB shader
info <general>: GL: Using GL_ARB_pixel_buffer_object
info <general>: Using GL_TEXTURE_2D
info <general>: GL: Selecting YUV 2 RGB shader
info <general>: GL: Using GL_ARB_pixel_buffer_object
info <general>: script.module.slyguy - WV License response OK and returned data
info <general>: Opening stream: 2001 source: 256
info <general>: Creating video codec with codec id: 173
```

H.264 codec. Video plays but no audio tracks.
```
warning <general>: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
info <general>: Creating InputStream
warning <general>: AddOnLog: inputstream.adaptive: Warning "inputstream.adaptive.manifest_type" property is deprecated and will be removed next Kodi version, the manifest type is now automatically detected.
                                                   If you are using a proxy remember to add the appropriate "content-type" header to the HTTP manifest response
                                                   See Wiki page "How to provide custom manifest/license" to learn more about it.
info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 2, Streams in first period: 3, Type: VOD)
info <general>: Creating Demuxer
info <general>: Opening stream: 1001 source: 256
info <general>: Creating video codec with codec id: 27
info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
info <general>: Creating video thread
info <general>: running thread: video_thread
info <general>: Opening stream: 1002 source: 256
info <general>: Finding audio codec for: 86056
info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
info <general>: Creating audio thread
info <general>: running thread: CVideoPlayerAudio::Process()
info <general>: COutput::OnStartup: Output Thread created
info <general>: Creating audio stream (codec id: 86056, channels: 2, sample rate: 48000, no pass-through)
info <general>: CActiveAESink::OpenSink - initialize sink
info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
info <general>: GL: Selecting YUV 2 RGB shader
error <general>: Sink Timer expired for more than buffer time: 0.15s
info <general>: GL: Using GL_ARB_pixel_buffer_object
info <general>: Using GL_TEXTURE_2D
info <general>: GL: Selecting YUV 2 RGB shader
info <general>: GL: Using GL_ARB_pixel_buffer_object
info <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
info <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41708
info <general>: script.module.slyguy - WV License response OK and returned data
info <general>: Loading skin file: VideoOSD.xml, load type: KEEP_IN_MEMORY
info <general>: CVideoPlayerAudio::Process - stream stalled
info <general>: script.module.slyguy - WV License response OK and returned data
info <general>: Skipped 1 duplicate messages..
info <general>: Opening stream: 2001 source: 256
info <general>: Creating video codec with codec id: 27
info <general>: AddOnLog: inputstream.adaptive: VideoCodec::Open
warning <general>: AddOnLog: inputstream.adaptive: ToCdmVideoCodecProfile: Unknown codec profile 0
info <general>: Closing stream player 1
info <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
info <general>: Waiting for audio thread to exit
info <general>: thread end: CVideoPlayerAudio::OnExit()
info <general>: Closing audio device
warning <general>: ActiveAE - large audio sync error: -1674.455991
info <general>: Deleting audio codec
info <general>: Opening stream: 2002 source: 256
info <general>: CActiveAESink::OpenSink - initialize sink
info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
info <general>: CDVDSubtitlesLibass: Using libass version 1701000
info <general>: CDVDSubtitlesLibass: Creating ASS library structure
info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
info <general>: CDVDSubtitlesLibass: Creating new ASS track
info <general>: VAAPI::Close
info <general>: COutput::OnExit: Output Thread terminated
info <general>: VAAPI::Close - closing decoder context
info <general>: GL: Selecting YUV 2 RGB shader
info <general>: GL: Using GL_ARB_pixel_buffer_object
info <general>: Using GL_TEXTURE_2D
```

**Comment by successtheman** [comment]
I don't seem to have this issue on any Android based players but it is definitely present on my Windows PC

**Comment by matthuisman** [comment]
closing this due to suspect being IA issue (see linked issue above)

**Comment by matthuisman** [comment]
as per https://github.com/xbmc/inputstream.adaptive/issues/1530#issuecomment-2262638077, I've now implemented that fix / workaround in slyguy proxy so hopefully this issue is now fixed :)
