### ISSUE TITLE
Paramount+ login problem

### ISSUE THREAD

**Issue by andreacocci95** [matthuisman/slyguy.addons#720]
When I try to access Paramount+ I see that login call return 400 status code. Can you solve it? Thanks.

**Comment by matthuisman** [comment]
what country are you physically in? are you using vpn? have you tried their website and confirmed it works for you?

**Comment by andreacocci95** [comment]
I'm from Italy. I'm using a VPN. If use it and trying to access from website or paramount+ mobile apps, it works without problems.

**Comment by matthuisman** [comment]
ive just tested the addon using Nord VPN to Italy and was able to login fine.
Id suspect something isnt working with Kodi + VPN integration

**Comment by matthuisman** [comment]
im in nz and VPN to USA also works

**Comment by andreacocci95** [comment]
I studied your code. If I call directly this api 400 return. Ten days ago everything works fine.

https://www.paramountplus.com/apps-api/v2.0/androidtv/auth/login.json?locale=en-us&at=ABC+2JjrOUYWbaaqKmzwPdppq0RDB2WdufcFmIsSnJDmDEQpVgyAjQpqpEDksKZNMKQ=&j_username=xxx@xxx.xx&j_password=xxxxxxxxxxx&deviceId=m7hOUZLifrf9ZGOM

What do I do wrong?

**Comment by andreacocci95** [comment]
ok, thanks anyway.
