### ISSUE TITLE
Disneyplus: no subtitles in kodi 21

### ISSUE THREAD

**Issue by robcast** [matthuisman/slyguy.addons#721]
The disneyplus plugin v0.16.2 works fine for me in kodi 20.5, but it there are no subtitles in kodi 21.0.

Environment:
- Country: Germany
- inputstream adaptive:  21.4.4.1 (kodi 21) vs. 20.3.18.1 (kodi 20)
- libass version:  1701000 (kodi 21) vs. 1700000 (kodi 20)
- kodi: 21.0 vs. 20.5
- disneyplus plugin: 0.16.2
- OS: Coreelec, ARM64 (ODROID C4)

Any ideas?

**Comment by matthuisman** [comment]
Yes. It'll be latest inputstream adaptive which is used for playback. Out
of my hands unfortunately

**Comment by matthuisman** [comment]
IA 21.4.5 should fix it:
https://github.com/xbmc/inputstream.adaptive/commit/1bad7424bfc6960051cf0bd2d07ef1613ef0fd6b

You may need to ask CoreELEC guys to bump their IA version

**Comment by robcast** [comment]
Just to confirm that inputstream-adaptive 21.4.5 did fix the problem.
