### ISSUE TITLE
Disney+ Italy -> Series -> All Series = JSON ERROR

### ISSUE THREAD

**Issue by savissimo** [matthuisman/slyguy.addons#722]
In Kodi I cannot update the addon for Disney+ to a version more recent than 0.16.2. After trying several times, I found that in https://slyguy.uk/.repo/addons.json the addon is published at version 0.16.2. Is this an error in the repo or am I looking in the wrong place?

**Comment by matthuisman** [comment]
What makes you think there is a newer version?

**Comment by matthuisman** [comment]
0.16.2 is the latest

**Comment by savissimo** [comment]
Sorry, I may have misread #355, because I got that same error on Disney+. Could you look into that please? 

Here is the error:

Error : Failed to fetch JSON data
Make sure your IP address is allowed(not geo-blocked).Try accessing the content
through other means(Official app/website) to test if it's a kodi add-on issue.

**Comment by matthuisman** [comment]
No known issues.
Suspect if your using VPN, they blocking that.

Provide a FULL Kodi debug log if you want to take the issue further

**Comment by savissimo** [comment]
Hello @matthuisman, sorry it took me so long, I was away from the box. 

[Here](https://paste.kodi.tv/odeduqihip.kodi) is a link to a full debug log for the issue. I have no VPN and I can use Disney+ without any issue on at least three different devices on the same network. Also notice that I can watch content, but if I browse to Series and then to All Series A-Z (or another similar menu) then I get this error. 

Should I post a new issue instead? Should I edit the title of this one?

**Comment by matthuisman** [comment]
ok. your issue was you set your app language in the addon settings to "italiano" instead of "it"

I have now pushed [slyguy.disney.plus -> v0.16.3](https://github.com/matthuisman/slyguy.addons/commit/d0e3d05893d79416b91a9b10a50dfaada4092b9c)  which removes the app language setting so it will always just use the language the profile is set to to stop this happening in future.

**Comment by savissimo** [comment]
Thank you very much! I admit I had set that language with a random value, because there was no defined set of accepted values (at least not in Kodi itself). Thank you for taking the time to help me!
