### ISSUE TITLE
Unable to Log into HBO MAX Plugin

### ISSUE THREAD

**Issue by Kenny606** [matthuisman/slyguy.addons#723]
I installed your plugin on LibreElec last night however I keep getting incorrect username and password if I use my email and password.

So I decided to try the Device Code method however the url provided just forwards to max.com
So I tracked down this url for TV signin: https://www.max.com/sign-in
Assuming the above is the correct update url which it seems to be,
I then clicked Start Activation which sent me to https://auth.max.com/link

When I tried to enter the code provided it looks like they changed the page it won't accept any letters only digits.

I'm in the US if that matter.
MAX don't seem to mind the VPN on my router I can login with my browser and play anything I want.

Any help is appreciated. Thanks for all your development.

**Comment by matthuisman** [comment]
MAX != HBO MAx
See https://github.com/matthuisman/slyguy.addons/issues/454
