### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by derrgoo** [matthuisman/slyguy.addons#724]
Hi Matt,

With plex adding so many new live channels do you think those will be added to the addon in time? Thank you

**Comment by matthuisman** [comment]
Please give example of a channel that's on Plex website but not on add-on
and I can investigate why not

**Comment by derrgoo** [comment]
[](https://youtu.be/QSUEgCl7AG8?si=lXMi7YEzS6OW1n_1)

I was just watching techdoctor uk and he claimed 1,000 new channels. lol I have not compared yet.

**Comment by derrgoo** [comment]
https://youtu.be/QSUEgCl7AG8?si=1tBQ73hD_BlvzvdN

**Comment by matthuisman** [comment]
Please do some on investigate before opening issue
