### ISSUE TITLE
Kodi Internet Proxy stops TV streaming from IPTV Merge config

### ISSUE THREAD

**Issue by siliconhippy** [matthuisman/slyguy.addons#727]
I originally tried the IPTV Merge Kodi Forum but unluckily the Kodi password  entry or retrieval process is horrible...been though this before.

1. I have Kodi 20.5 Windows 10 configured with IPTV Merge, including my custom m3u playlist, Plex Live,, and Pluto.TV merged.

IPTV Merge TV channels play fine in PVR Simple , just as for the Plex Live, Samsung, Pluto, IPTV AU slyguy plugins.

2. My custom m3u playlist is the output of a streamlink.github.io GUI, called TVLINK 4.1.2 (default settings)  at https://forum.alexelec.tv/index.php?topic=324.msg4086#msg4086.

This allows me to use youtube channels with browser links in PVR Simple, without need for plugin.video.youtube link customization.

3 However, when I enable the Kodi Internet Proxy settings (Squid Proxy running in AWS Virginia), all IPTV Merge channels, and all slyguy plugins above  stop working ("Playback Failed.")

4. (FYI.) Also, I have  Kodi Jellyfin (not JellyCon) plugin installed, and have enabled the Kodi Sync Queue plugin installed at the Jellyfin server at AWS, Frankfurt.

Jellyfin movies stream OK, with or without the Kodi Proxy enabled. 
But the same m3u playlist in Jellyfin m3u tuner, does not stream any TV channels, with or without Kodi Proxy enabled. 

6. So is there any solution here ? 
Maybe this has something to do with the proxy not able to process HLS traffic with quick open/close of HLS segment connections; and maybe mpegts raw continuous stream could work better ? (Or maybe not !)

**Comment by matthuisman** [comment]
I don't think I understand. If your man in the middle, then you'll need to disable verify http certs in the slyguy common settings. 

If you don't want slyguy add-ons to use the proxy you set in Kodi settings then change the proxy setting in slyguy common from "Kodi" to a empty value
