### ISSUE TITLE
Slyguy  error

### ISSUE THREAD

**Issue by bds3151** [matthuisman/slyguy.addons#728]
When kodi opens I get a slyguy common error message.

**Comment by matthuisman** [comment]
full kodi debug log or else i cant do anything

**Comment by bds3151** [comment]
On kodi log viewer can I just hit upload?
    On Monday, April 29, 2024 at 07:29:47 PM PDT, Matt Huisman ***@***.***> wrote:  
 
 


full kodi debug log or else i cant do anything

**Comment by matthuisman** [comment]
not sure sorry.

just follow https://kodi.wiki/view/Log_file/Easy

**Comment by bds3151** [comment]
Ok I uploaded to https://paste.kodi.tv/ahikarosar.

**Comment by matthuisman** [comment]
that url isnt working. just blank page.
Maybe try again

**Comment by bds3151** [comment]
Yeah, apparently the logfile uploader add on isn't workking. I tried it twice.
    On Monday, April 29, 2024 at 08:17:35 PM PDT, Matt Huisman ***@***.***> wrote:  
 
 


that url isnt working. just blank page.
Maybe try again

**Comment by bds3151** [comment]
Ok got iy this time.... https://paste.kodi.tv/upasihodim
    On Monday, April 29, 2024 at 08:17:35 PM PDT, Matt Huisman ***@***.***> wrote:  
 
 


that url isnt working. just blank page.
Maybe try again

**Comment by bds3151** [comment]
I didn't know Kodi had to be in debug mode to send the log. Since it said in the instructions not to exit kodi I couldn't show the start up error but instead tried to stat a Pluto channel and got an error.

**Comment by matthuisman** [comment]
you need to update slyguy.dependencies.
All slyguy addons should be kept autoupdate on so they all update together

**Comment by bds3151** [comment]
How do I do that? Kodi shows no updates pending. I changed to update automatically but it still not working. I also went into the the common add on and pushed the update button and nothing happened.
    On Monday, April 29, 2024 at 08:53:39 PM PDT, Matt Huisman ***@***.***> wrote:  
 
 


you need to update slyguy.dependencies.
All slyguy addons should be kept autoupdate on so they all update together

**Comment by matthuisman** [comment]
its not the common addon. its the slyguy.dependencies addon.
it should be on autoupdate and if the repo is installed - it should auto update.

**Comment by bds3151** [comment]
Ok thx. I got it working by manually updating IPTV Merge. 
    On Monday, April 29, 2024 at 09:14:09 PM PDT, Matt Huisman ***@***.***> wrote:  
 
 


its not the common addon. its the slyguy.dependencies addon.
it should be on autoupdate and if the repo is installed - it should auto update.
