### ISSUE TITLE
Disney plus crashes Kodi on playback

### ISSUE THREAD

**Issue by RealAmethyst** [matthuisman/slyguy.addons#733]
When starting to watch something using Disney plus, Kodi will crash when trying to start playback. I have tested this on HBO and it works fine there. I'm using Kodi 21 on windows 10.

**Comment by zuzia-dev** [comment]
https://github.com/matthuisman/slyguy.addons/issues/731

**Comment by matthuisman** [comment]
see above issue. this is duplicate
