### ISSUE TITLE
Sky sport now

### ISSUE THREAD

**Issue by Major87** [matthuisman/slyguy.addons#734]
Live channels not working for some reason. Everything else works.

**Comment by matthuisman** [comment]
Full Kodi debug log please

**Comment by matthuisman** [comment]
ive just tried and kodi 20 is ok and 21 isnt
suspect issue in inputstream.adaptive which is used for playback
Suggest sticking with Kodi 20 for now

**Comment by matthuisman** [comment]
kodi 21 playback should now be fixed with [plugin.video.sky.sport.now -> v0.5.9](https://github.com/matthuisman/slyguy.addons/commit/bff95a2ca3d69d3b55e9e980337b1a8d6b22b755)
