### ISSUE TITLE
Slyguy Bein Sport

### ISSUE THREAD

**Issue by ILbruno** [matthuisman/slyguy.addons#739]
Hi,
when I try to access the bein sport connect apac app I get the following message:

Failed ti tetch JSON data 
Make sure your IP address Is allowed (not geo-blocked)
Try accessing the content via other means (official app / website) ti test It it's a Kodi add-on issue

I use nordvpn with country thailand.

can you help me?

Thank you

**Comment by matthuisman** [comment]
They be blocking your VPN or wrong country. Find a VPN that works with
their website and it then should work with the add-on

**Comment by ILbruno** [comment]
Thank you
can you recommend a VPN compatible with bein to avoid having the current blocks?

thanks to the availability


Il mar 14 mag 2024, 21:12 Matt Huisman ***@***.***> ha
scritto:

> They be blocking your VPN or wrong country. Find a VPN that works with
> their website and it then should work with the add-on
>

**Comment by matthuisman** [comment]
I'm not sure what work sorry as I'm in NZ
