### ISSUE TITLE
[Video Tester] Kodi hangs on ISA - Dash with Widevine

### ISSUE THREAD

**Issue by stuckinthe** [matthuisman/slyguy.addons#740]
Probably not an issue with your plugin but I just wanted to see if you have any input. Running Arch Aarch64 on a Rpi5. Before I was running glibc-widevine and this worked. I upgraded the system and now you don't need a special version of glibc for widevine so I installed with the latest glibc and the widevine package. When I try ISA - Dash with Widevine, it just freezes Kodi. I ran with logs and it checked the libwidevine file and it said all was okay. It doesn't give any errors in the log file. All other options work (HLS, etc). Could be an issue with ISA but I don't know for sure.

**Comment by matthuisman** [comment]
could you test with another addon that uses Widevine?
If that doesnt work - then suspect its not the video tester addon

**Comment by stuckinthe** [comment]
I have the same issue with PVR Simple. It could be my issue as well as I botched the upgrade as I still had glibc-widevine installed which broke almost all functions since my glibc-widevine was old. I saw how to fix but I wasn't sure exactly what it was doing so I made a mistake on the first repair as I did it on the wrong architecture as I thought it was pulling packages from the cache instead of the server. Are you running Arch?

**Comment by matthuisman** [comment]
Me? I dont run arch unfortunately.

**Comment by stuckinthe** [comment]
Thanks for the help. Yes I was wondering if you were running arch since if it's broken for you then it surely is broken for me.

**Comment by matthuisman** [comment]
when you say ARCH? your meaning arch linux?

**Comment by stuckinthe** [comment]
Yes, sorry I should be more specific Arch Linux ARMv8.

**Comment by matthuisman** [comment]
where was the confirmation that glibc workarounds are no longer needed?

**Comment by stuckinthe** [comment]
It says it here:

https://aur.archlinux.org/packages/widevine

Also, the glibc-widevine AUR has been deleted.

**Comment by matthuisman** [comment]
that is for browsers.

You shouldnt use that with Kodi.
Just let my Widevine helper script download and install the Widevine CDM for Kodi to use

**Comment by stuckinthe** [comment]
Thanks for the help. I ended up getting my system back up and running by following this.

https://wiki.archlinux.org/title/Pacman#Pacman_crashes_during_an_upgrade

Everything seems to be running okay except for widevine. I used the widevine package and then copied it to my cdm folder. I also tried by using the video tester and the inputstream helper.

I get these errors with the video tester and IS Helper installation.

2024-05-14 17:44:19.105 T:14796   error <general>: AddOnLog: inputstream.adaptive: Initialize: Initialize: Failed to load library: /home/alarm/.kodi/cdm/libwidevinecdm.so: DT_RELR without GLIBC_ABI_DT_RELR dependency
2024-05-14 17:44:19.105 T:14796   error <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/home/alarm/.kodi/cdm/libwidevinecdm.so)
2024-05-14 17:44:19.105 T:14796   error <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed

**Comment by matthuisman** [comment]
did you try this: https://aur.archlinux.org/packages/widevine#comment-972850

**Comment by stuckinthe** [comment]
I ended up doing this in the other link I provided. I had a previous card with Arch Linux ARM8v on it so I mounted the microSD and then I uninstalled glibc-widevine and installed glibc and then my system was able to boot. I checked to see if I have any broken packages. It says I don't have any.

**Comment by stuckinthe** [comment]
I have a RPI 5 so I was using the 16k kernel. Either glibc without the patch or widevine doesn't work with the 16k kernel. I went back to the non 16k kernel.

**Comment by matthuisman** [comment]
thanks for reporting back your fix. Good for others in future who strike the same issue

**Comment by matthuisman** [comment]
found this:
https://www.da.vidbuchanan.co.uk/blog/netflix-on-asahi.html

And he wrote this:
https://gist.github.com/DavidBuchanan314/c6b97add51b97e4c3ee95dc890f9e3c8

**Comment by matthuisman** [comment]
hmm, looks like the new AUR widevine should patch as well:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=widevine#n83

However, my DRM that kodi uses wont be patching

**Comment by matthuisman** [comment]
oh they only did the 3 days ago:
https://aur.archlinux.org/cgit/aur.git/commit/?h=widevine&id=c5aeffb3b5406d7aab6097dcc357560125708e86

**Comment by matthuisman** [comment]
you could try this:
[libwidevinecdm.so.txt](https://github.com/matthuisman/slyguy.addons/files/15328745/libwidevinecdm.so.txt)
(remove the .txt extension and overrwrite kodis one)

**Comment by stuckinthe** [comment]
Your libwidevinecdm.so works on my 16K kernel! Thank you so much.

The PKGBUILD applies the python patch in the david buchanan link. For some reason, the patch wasn't working. I thought I did the upgrade glibc and widevine two days ago so I should have gotten the repaired python script version but since yours works I'm not going to worry about it anymore.

**Comment by matthuisman** [comment]
did you test the above with non-16k and 16k? 
Id like to be sure it works on both so I can just have that as the version that downloads

**Comment by matthuisman** [comment]
ive just pushed the modified arm64 to the download server for the kodi addons.

Please test by using kodi to reinstall widevine cdm.
It will either download or if the checksum is already the same (suspect so), then itll just say installed immediately

Be really cool if you could test on non-16k.

**Comment by stuckinthe** [comment]
Actually I tried it out on the 4k kernel first and it worked. I think I read in one of your links that the 16k should work on the 4k so I tested it on the 4k just to see if worked before I changed kernels and headers. I made sure I did a uname -r to make sure I didn't get mixed up on my kernels. So yes your version works on 4k and 16k. Thanks again.

**Comment by matthuisman** [comment]
legend :) Ive updated my script to auto fix it whenever a new one makes its way into ChromeOS
So the version installed via my kodi addon should from now on be "fixed" :)

Thanks for letting me know. I had no idea of "16k" pagesize until today

**Comment by stuckinthe** [comment]
I'm glad I could help. Thanks for all you do. Kodi wouldn't be the same without your contributions.
