### ISSUE TITLE
DTS/IMAX audio on Disney+

### ISSUE THREAD

**Issue by kyl416** [matthuisman/slyguy.addons#742]
Any chance you can make the DTS/IMAX audio tracks available in the Disney+ kodi addon?

It should be available for Queen Rock Montreal:
https://www.disneyplus.com/browse/entity-ebfc8e47-7e5c-404d-84b3-b6681284b1bf

Here's the announcement about it that lists some compatible devices and additional titles:
https://press.disneyplus.com/news/disney-plus-queen-rock-montreal-imax-enhanced-sound-dts

**Comment by matthuisman** [comment]
could you please test [slyguy.disney.plus -> v0.16.4](https://github.com/matthuisman/slyguy.addons/commit/225202a8c6e5616adb27ab118c66cd958ebfacce)

It is getting the DTS-X audio into the playlist, but that track doesnt show on my Kodi 21.
However, I believe Inputstream Adaptive is detecting it as if it cant detect codec it defaults to AAC.
And im not seeing it all.

Makes me think its Kodi itself that is now showing it to me as my hardware doesnt support it.

But, let me know if it works for you :)

**Comment by matthuisman** [comment]
Do you have a device that actually supports DTS-X?

**Comment by matthuisman** [comment]
yup. I think Omega tried to add support for it and maybe not working :)
Ill open an issue with them later tonight

Nexus - probably wouldnt worry about as they wont backport fixes for that.
I can proxy and change the CODECS string to something it supports, but not sure if there is anything that would work

**Comment by matthuisman** [comment]
as per https://github.com/xbmc/inputstream.adaptive/pull/1558#issuecomment-2117153231, its going to be awhile and only Kodi 22 that can support this.

Therefore, i've set the setting visible to false in the addon in the meantime.

Closing this ticket as the add-on is supporting it - but it needs IA and Kodi to also support it
