### ISSUE TITLE
Radio AU

### ISSUE THREAD

**Issue by dawsonjw** [matthuisman/slyguy.addons#744]
Hi
     Thanks for the great addon.  
     
Just wondering if it is possible to allow for multiple selections of the region option?  I have tried adding different stations from different regions and bookmarking them but this makes the addon crash if you select a station not in the currently selected region. 

One other question.  I use artist slideshow to display images while music is playing and I have noticed that sometimes it will display the wrong artist and not update as a new song / artist begins. That is, it gets stuck on an artist. Stopping and starting radio au a number of times will sometimes fix the problem. Is it RADIO AU sending the wrong information to artist slideshow or is the problem in artist slideshow?  Just interested in how this works. 

Cheers 

John

**Comment by matthuisman** [comment]
good question. I thought i would have a region "ALL" in this and the IPTV Au addon but i dont for whatever reason.
Ill see if I can add that.

**Comment by matthuisman** [comment]
just pushed [plugin.audio.au.radio -> v0.13.3](https://github.com/matthuisman/slyguy.addons/commit/b6fcf16fe1d1b9c00a7ee7f546763b544b98d7ca) 

That
1) fixes bookmarks so they always work regardless of selected region
2) added a "All" region

For your other question - thats more a Kodi forum question probably.
Not sure how well they meant to support artwork / tracklisting.

**Comment by dawsonjw** [comment]
Hi     Thanks for that.  Will give it a test Cheers JohnSent from my iPhoneOn 16 May 2024, at 5:56 PM, Matt Huisman ***@***.***> wrote:﻿
just pushed plugin.audio.au.radio -> v0.13.3
That

fixes bookmarks so they always work regardless of selected region
added a "All" region

For your other question - thats more a Kodi forum question probably.
Not sure how well they meant to support artwork / tracklisting.

**Comment by matthuisman** [comment]
added the same to IPTV AU as well
