### ISSUE TITLE
Disney Atmos Audio

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#747]
Hi Matt. I did a search on this and found that Dolby Atmos on Disney was fixed by you over a year ago. I can get Dolby Atmos on your paramount plus add-on and on any other add-on as well as external sources with Kodi. But I cannot get any Dolby Atmos from the current build of Disney plus. 

Can you, or anyone else, advise me as to how to get Dolby Atmos on the Disney add-on?  I tried looking up what format Disney uses for the atmos stream but couldn't find anything. Thanks very much

**Comment by matthuisman** [comment]
What time is your subscription?
They only enable it on the higher tiers I believe

**Comment by gmjh123** [comment]
Oh ok. Yes it's the basic subscription. For some reason I assumed the add-on would bypass that. (Like it bypasses other restrictions related to basic and premium) I have an Amazon prime add-on which bypasses higher subscriptions and let's me watch Dolby Vision and Dolby Atmos content. If your Disney add-on doesn't have any similar capability then that would explain it and you can close this. Thanks.

**Comment by matthuisman** [comment]
Nope. Its locked down by Disney and I don't intend to bypass any
restrictions.
