### ISSUE TITLE
Request: Max addon and Sky showtime.

### ISSUE THREAD

**Issue by RealAmethyst** [matthuisman/slyguy.addons#749]
Hi. HBO Max just got changed in my country and I only used it via Kodi. Would it be possible to make a Max addon? I also have Sky Showtime, but I have found no working addon that works on windows. Is it possible to have sky showtime on Kodi?
Thanks.

**Comment by matthuisman** [comment]
See exisiting thread for max. 
No to sky showtime. There exisiting add-on. Sky themselves restrict it to android
