### ISSUE TITLE
Stan Addon - Can't watch full tennis replays

### ISSUE THREAD

**Issue by drelephant** [matthuisman/slyguy.addons#752]
Using the Stan addon for watching the Roland Garros tennis now, I'm unable to watch the full matches.

When I go to Sport-Tennis-Roland Garros Singles Replays & Extras, and then pick a match, it plays the highlights instead of the full replay.

I notice that if I go to the link on the web, eg [this](https://play.stan.com.au/programs/4997118/seasons/extras/episodes/4997120), there are three entries for each match - the full replay, the mini match, and the highlights package.

It seems there's no way to choose which of these to watch from kodi.

Is there any way I can choose which one I want to watch? I mostly want to watch the full matches.

The only way I can find is to add it to "My List" from the web, and then go to "My List" in kodi. But that's pretty inconvenient.

**Comment by matthuisman** [comment]
fixed with [plugin.video.stan.au -> v0.4.7](https://github.com/matthuisman/slyguy.addons/commit/7d9f394a510152dc6ca35ccf7a79a37b8da835ba)

**Comment by drelephant** [comment]
Fixed in less than a day! Can't complain about that service! Thanks so much!
