### ISSUE TITLE
Udemy errors

### ISSUE THREAD

**Issue by Gabrieleln** [matthuisman/slyguy.addons#753]
I am not able to use udemy addons any more due to errors in the courses list and video play.

Key error: 'results'
File 'plugin.py', line 71, in my_courses items = _process_courses(data['results'])
File 'plugin.py', line 208, in decorated_function folder, more_results = f(**kwargs)
File 'plugin.py', line 59, in decorated_function folder, item = f(*args,**kwargs)
File 'router.py', line 115, in dispatch function(**params)
File 'signals.py', lime 41, in throwable yield

I love to use your plugin could you fix it?

Thank you very much

**Comment by matthuisman** [comment]
is this still an issue?
Was it with every course?
