### ISSUE TITLE
WideVineCDM install checksum error

### ISSUE THREAD

**Issue by samdobson** [matthuisman/slyguy.addons#754]
Hi,

I can't get WideVineCDM installed. Apparently the checksums don't match.

Did something happen recently to the ARM linux builds to make the checksums go out of sync?

```
$ wget -q https://slyguy.uk/.decryptmodules/widevine/4.10.2662.3-linux-armv7.so; md5sum 4.10.2662.3-linux-armv7.so
5d240fe2a58848e80f285f7f71f0b1c4  4.10.2662.3-linux-armv7.so
```

https://slyguy.uk/.decryptmodules/modules.json.gz has:

```
 {
     "widevine": {   
         "platforms": {
             ...
             "Linuxarmv7": [
                 {   
                     "md5": "9aff9fa1f4d1b97532a6f5c8ef2cc914",
                     "src": "4.10.2662.3-linux-armv7.so",
                     "ver": "4.10.2662.3"
                 },
             ...
             ], 
             ... 
         }       
     }               
 }
```

<img width="695" alt="Screenshot 2024-06-01 at 21 24 37" src="https://github.com/matthuisman/slyguy.addons/assets/1309834/9c79a5ff-f367-4462-bf00-ae03e3254683">

**Comment by matthuisman** [comment]
thanks for letting me know :)

Now fixed. Was a problem with my automated script not correctly updating an existing md5
