### ISSUE TITLE
9Now - Video stops when stream goes into ad break

### ISSUE THREAD

**Issue by dawsonjw** [matthuisman/slyguy.addons#755]
Hi Matt
            I have noticed the Channel 9 stream seems to stop when stream transitions from program to ad break.  This happens quite frequently but not every time.  
            
Also noticed that video will pause for a few seconds every now and then.  It seems to auto recover from this.  I have tried to select a different video stream rate  but  9now only seems to offer a single 1080 stream. 

Oh, my Sony also has 9Now app and these issues do not occur. It only happens within kodi.  

cheers 

John

**Comment by matthuisman** [comment]
Itll be an inputstream.adaptive issue which is used for playback. Try
disable "use inputstream for live" in add-on settings

**Comment by dawsonjw** [comment]
Hi Matt.   Thanks for that. I’ll give that a try.  Oh, I have also noticed that the region selection for 9Now does not seem to be honoured.  I live in the ACT but programming seems to be NSW. Cheers JohnSent from my iPhoneOn 3 Jun 2024, at 4:14 PM, Matt Huisman ***@***.***> wrote:﻿
Itll be an inputstream.adaptive issue which is used for playback. Try

disable "use inputstream for live" in add-on settings

**Comment by matthuisman** [comment]
does ACT actually have different streams on the 9now website / app?

**Comment by dawsonjw** [comment]
Hi Matt,           According to their website it does.  See linkhttps://help.9now.com.au/hc/en-us/articles/115013086287-Why-does-Live-TV-use-my-location#:~:text=Please%20note%20you%20can't,that%20you%20have%20changed%20location.Cheers JohnSent from my iPhoneOn 3 Jun 2024, at 6:11 PM, Matt Huisman ***@***.***> wrote:﻿
does ACT actually have different streams on the 9now website / app?

**Comment by matthuisman** [comment]
I mean, if you go to their website from ACT and play a stream - is it actually ACT?
I can only provide what they provide.

As far as I can tell, there are no specific ACT feeds online for 9 streams

**Comment by dawsonjw** [comment]
Hi Matt             It would seem that the stream is not selectable by the user as it determines the stream from the ip address you are connected from.  See the link previously attached.  Sorry , I was under the impression that your app could somehow override this as you showed it as selectable. The app within the TV has no selection available. Cheers John Sent from my iPhoneOn 4 Jun 2024, at 7:56 AM, Matt Huisman ***@***.***> wrote:﻿
I mean, if you go to their website from ACT and play a stream - is it actually ACT?
I can only provide what they provide.
As far as I can tell, there are no specific ACT feeds online for 9 streams

**Comment by matthuisman** [comment]
are you not in ACT?
I need confirmation that an ACT stream actually exists before i spend time investigating
I dont believe that page as ive never seen a 9 stream for ACT available to date

**Comment by dawsonjw** [comment]
Hi Matt               I can confirm that I live in Canberra. From what kly416 says it seems there is no ACT specific stream. Back to my original question regarding the stalling of the feed at ad breaks…. I turned off the input stream adaptive for live streams but it still stalls at the ad break.  VOD streams however seem to work fine with ISA turn on for VOD. Cheers JohnSent from my iPhoneOn 4 Jun 2024, at 10:23 AM, Matt Huisman ***@***.***> wrote:﻿
are you not in ACT?
I need confirmation that an ACT stream actually exists before i spend time investigating
I dont believe that page as ive never seen a 9 stream for ACT available to date

**Comment by matthuisman** [comment]
Maybe try the linear streams in IPTV au? They hopefully don't have the
server side ad insertion which causes havoc with ffmpeg and inputstream
adaptive. Vod is not affected

**Comment by dawsonjw** [comment]
Hi Matt,
              Just as an FYI, I have done some further testing on the pauses and ad break issues in the app. I have found that using the Aussie addons version of 9now these issues don’t exist.  Probably the older version is working very differently.  Hopefully this helps

cheers 

John

**Comment by matthuisman** [comment]
Are you using Kodi omega?

**Comment by dawsonjw** [comment]
Hi Matt             Yes that’s correct. Kodi OmegaJohnSent from my iPhoneOn 5 Jun 2024, at 6:59 PM, Matt Huisman ***@***.***> wrote:﻿
Are you using Kodi omega?

**Comment by matthuisman** [comment]
ive just pushed [slyguy.9now -> v0.2.5](https://github.com/matthuisman/slyguy.addons/commit/8a285b80adb6754931e920a32c2493fa6ab54e4d) which adds a "use legacy live streams" setting (default to false).

When enabled that will use the same live streams that it used to use / the aussie addons 9now uses.
They are lower quality on some of the channels but if more reliable -its a tradeoff :)
