### ISSUE TITLE
failed to connect to host: i.mjh.nz in all Plugins

### ISSUE THREAD

**Issue by tusquitoni** [matthuisman/slyguy.addons#758]
Hello,

I have problems with everything I install from the repository. Both Pluto TV and Samsung TV Plus plugins give me error "failed to connect to host: i.mjh.nz" when trying to open. What could be the problem? I understand that other users have found it to work. Thank you very much.

**Comment by matthuisman** [comment]
i.mjh.nz by default uses 1.1.1.1 to DNS resolve. Is that blocked on your
network?

**Comment by tusquitoni** [comment]
Correct ... is my net ... i connect with mobile and work ... thank you!!

**Comment by matthuisman** [comment]
Go into slyguy common settings - advanced and disable DNS override

**Comment by tusquitoni** [comment]
Works Perfect!! Thank you so much!!

**Comment by PachiPant** [comment]
Buenas,.
Como entro en configuración cde slyguy
