### ISSUE TITLE
slyguy.hbo.max invalid_credentials

### ISSUE THREAD

**Issue by 3052** [matthuisman/slyguy.addons#759]
I get this result with username password:

{
    "code": "invalid_credentials",
    "message": "The email address or password is incorrect. Please try again.",
    "statusCode": 401
}

I can share my credentials if need be

https://github.com/matthuisman/slyguy.addons/blob/0a31d15289b2f1e252438a6138d610e247ea16c3/slyguy.hbo.max/resources/lib/api.py#L169-L177

**Comment by matthuisman** [comment]
This is HBO max add-on. If your using Max, then see pinned issue
