### ISSUE TITLE
Disney+ 4K HDR without native Widevine L1 from device?

### ISSUE THREAD

**Issue by pmsobrado** [matthuisman/slyguy.addons#76]
Hi, this is more a question than an issue but I found no other place to ask. I have a GT KING PRO, which has Widevine  L1 certifications, although not valid for Netflix, etc. I'm running standalone CoreELEC on it. I saw your Disney+ addon and I can play it on CoreELEC at 720p max, anyting above that shows a black screen. I guess this is certification issues as my device doesn't have the proper ones but then, what is the purpose of your "Common" addon? I see a menu to install certificates from there, how does that work? Is it possible to have a working 4K video without native certificates in the device?

Thanks in advance.

**Comment by matthuisman** [comment]
GT KING PRO will have a fake "l1 license".
Currently only Android TV devices like Nvidia Shield, Mi Box have L1 widevine.

The setting "Install Widevine DRM" isnt installing certs.
Its installing the widevine drm blob. Which is L3.

**Comment by pmsobrado** [comment]
OK, perfectly clear now. Thanks for all.
