### ISSUE TITLE
10 Play VODs blocked (possibly)

### ISSUE THREAD

**Issue by stephematician** [matthuisman/slyguy.addons#761]
Looks like we're getting blocked and I'm on an Australian ISP; was working yesterday.

Similar to https://github.com/matthuisman/slyguy.addons/issues/665 says "10 Play is available for Australia residents only."

**Comment by matthuisman** [comment]
what does their website do?

**Comment by matthuisman** [comment]
working fine for me with residential AU ip address.

**Comment by stephematician** [comment]
Same as yesterday for me. Website works; Live TV works, but no VODs.

kodi.log pasted here: https://paste.kodi.tv/uxegokosaq.kodi - line 430 is when I entered the addon and attempted to play VOD.

**Comment by matthuisman** [comment]
oh "VOD" was the missing information
Thanks for the log :)

**Comment by stephematician** [comment]
Yeah it was a bit silly of me; I was in a hurry when I first reported. If you have any trouble reproducing and need more details from my end, let me know!

**Comment by matthuisman** [comment]
i cant replicate. VOD playing ok for me.

Give me a specific VOD that doesnt work and how to get to it

**Comment by stephematician** [comment]
Tried Twin Peaks just now - same result. Tried the 'reset app' as well, no dice.

**Comment by matthuisman** [comment]
twin peaks? what season / episode?

**Comment by stephematician** [comment]
Season 1, any episode. Season 2 as well. Bold and the Beautiful. I'm fairly sure any VOD i try will not work.

The video bitrate selection is a giveaway, I can only see 0.17M.bit option and they are all essentially static with the text "10 Play is available for Australia residents only."

**Comment by matthuisman** [comment]
tested twin peaks, ok for me

**Comment by matthuisman** [comment]
what is your "state" set to in addon settings?

**Comment by stephematician** [comment]
"Any". I tried "NSW" before, too, but similar result. My IP is within Australia.

**Comment by matthuisman** [comment]
i cant reproduce so cant help sorry

**Comment by stephematician** [comment]
Is there any thing I can check with regards to logging or debugging?

**Comment by matthuisman** [comment]
enable kodi debug logging and youll get more information regarding the requests.

also see what visiting https://10play.com.au/geo-web gets you.

**Comment by stephematician** [comment]
![image](https://github.com/matthuisman/slyguy.addons/assets/12695305/d2602bd3-5bb0-4b0c-b128-5397281aae32)

I tried from my desktop device (instead of LibreElec), and I get the same result.

**Comment by matthuisman** [comment]
Kodi on your desktop also doesnt work?
And your sure their website on your desktop does work?

enable kodi debug logging and youll get more information regarding the requests.

**Comment by stephematician** [comment]
Craps out around line 1026: https://paste.kodi.tv/maromoyepo.kodi

That's running on my desktop.

**Comment by matthuisman** [comment]
https://10-selector.global.ssl.fastly.net/s/kYEXFC/media/9000000000075631.m3u8?mbr=true&manifest=m3u&format=redirect&vtoken=1718135160_ada90b76ea6c3a324311933d56b0d521fc145c0b2a0c21aa085228e9c3b612f9

is giving back the "not in oz stream"

You need to figure out why that detects you as not in AU

**Comment by matthuisman** [comment]
on your desktop. in your browser. click that above url. What is the name of the file it downloads?

**Comment by stephematician** [comment]
> on your desktop. in your browser. click that above url. What is the name of the file it downloads?

As you said - the not-in-oz m3u8.

When I sign in to 10play via my browser, I'm able to watch the video.

**Comment by matthuisman** [comment]
the 10play website uses lower quality streams that go via GOOGLE DAI.
They dont use the above fastly selector.

Does the 10play android app work for you?

**Comment by matthuisman** [comment]
ive just pushed [slyguy.10play -> v0.1.3](https://github.com/matthuisman/slyguy.addons/commit/52891cdff9913a2c7dacb32ebaae673e07b7be86) that will revert to the google dai stream if it detects the selector url isnt working. It is lower quality but should at least match the website quality for you

please try this and report back

**Comment by stephematician** [comment]
I'm not sure if this is related to the update _as I hadn't attempted exactly this before_ however: the stream _does_ come back up (a bit randomly) if I attempt to access it multiple times - cancelling whenever I see _only_ the 0.17Mbit stream option. I haven't checked if this is using Google DAI or not, the bitrate(s) when its working are up to 3.8MBit/sec. I'll have a chance to look more closely tomorrow. Thanks for the help so far!

**Comment by stephematician** [comment]
So in summary, prior to v0.1.3:

1.  10 Play VODs (sometimes) failed on both desktop (Ubuntu and Kodi v20.2), and Pi (LibreElec + Kodi v19.4).
2.  The bitrate selection screen shows only one option when the video fails (0.17MBit/s) which is a 10 sec clip showing the 10 Play logo and "Not available outside Australia".
3.  Sometimes, VODs succeeded, with bitrate options up to about 4MBit/s.

In v0.1.3:

1.  10 Play VODs work reliably, however all of today, the bitrate was capped at 2MBit/s (using DAI according to logs).
    -   Probably a false negative for IP address assigned by my ISP - even though they should all register in Australia.

So it more or less works, with a hit to the bitrate as expected if it falls back to DAI.

My guess is that there isn't anything more that can be done from the add-on side.

The lesson? I probably should use a VPN 😆
