### ISSUE TITLE
Hulu on Disney+ only display 10 episodes per season

### ISSUE THREAD

**Issue by jgslade** [matthuisman/slyguy.addons#762]
Both 9-1-1 and 9-1-1 Lone Star on Disney+ in the US are displaying 10 episodes per season. They both have 10 episodes in the first season, but have more than 10 in the subsequent seasons, except season 7 of 9-1-1 which has 10 episodes.  Both of these shows are from hulu and are included with the Disney+ with Hulu subscription.

I checked some other shows that are from hulu and they seem to be only showing 10 episodes as well. I checked Abbott Elementary and Last Man Standing, both display 10 episodes per season, but have more than 10 on the Disney+ website.

![Screenshot_%T_%d-40](https://github.com/matthuisman/slyguy.addons/assets/29897815/3a2c7afb-52ff-4032-a05d-53a0dc3e037a)
![Screenshot_%T_%d-41](https://github.com/matthuisman/slyguy.addons/assets/29897815/99975c46-1cd1-4423-9ded-1ac308c6a5ee)
![Screenshot_%T_%d-43](https://github.com/matthuisman/slyguy.addons/assets/29897815/13c6d6e7-7c67-46a5-bd81-9e74edfc057d)
![Screenshot_%T_%d-42](https://github.com/matthuisman/slyguy.addons/assets/29897815/4b033ed2-f8fa-4197-a17d-8ae55c78d624)

Here is the log file in case it's helpful.
[kodi.log](https://github.com/user-attachments/files/15809882/kodi.log)

**Comment by fabrebatalla18** [comment]
Fix:

On "explore_season" function (https://github.com/matthuisman/slyguy.addons/blob/51db3ff3d2784ccb57037f33013713dffbf4698c/slyguy.disney.plus/resources/lib/api.py#L494) you need to change this:

```
def explore_season(self, season_id):
	params = {
		'limit': 999,
		'offset': 0,
	}
	endpoint = self._endpoint(self.get_config()['services']['explore']['client']['endpoints']['getSeason']['href'], version=EXPLORE_VERSION, seasonId=season_id)
	return self._json_call(endpoint, params=params)['data']['season']
```

**Comment by matthuisman** [comment]
thanks :) id probably want to add pagination as well, or for eps i usually just loop until all done.
But the chances of more than 999 episodes is slim so this is probably fine :)

**Comment by matthuisman** [comment]
just pushed [slyguy.disney.plus -> v0.16.7](https://github.com/matthuisman/slyguy.addons/commit/09054b4122d10e39a15a219ca233b3ecccef152f) 
I did that without any testing as im away from home - so hopefully it doesnt break the entire addon somehow :)
let me know

**Comment by matthuisman** [comment]
found time to test and confirm now fixed. thanks for the report and code :)
