### ISSUE TITLE
Disney crashes on all files [When quality is set to Disabled / Bypass]

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#765]
Hi Matt. I remember you half joking about doing something to the Disney app that you hope wouldn't make it broken. Well unfortunately all files stop playing and crash kodi after about 30 seconds to a minute. Happens on Android TV Chromecast and fire stick. 
(Title should read crashes not crushes)

**Comment by matthuisman** [comment]
The latest Disney+ addon moved Quality select to be a donor only feature.
If not a donor - the feature is disabled.

It appears there may be a bug in Inputstream Adaptive that isn't happy when it gets the entire manifest with all the qualities / streams.

I suspect its the IA adapative bitrate switching feature.

Are you able to try different inputstream.adaptive settings to see if it fixes?
eg.  change it from adaptive bitrate to something else. They even have a quality select feature now i believe

**Comment by gmjh123** [comment]
> The latest Disney+ addon moved Quality select to be a donor only feature. If not a donor - the feature is disabled.
> 
> I think this is the cause of the issue. User on kodi forums went back to older version and set quality to disabled and got crashes as well https://forum.kodi.tv/showthread.php?tid=353316&pid=3201024#pid3201024
> 
> It appears there may be a bug in Inputstream Adaptive that isn't happy when it gets the entire manifest with all the qualities / streams.
> 
> I suspect its the IA adapative bitrate switching feature. When it now has multiple different qualities - its trying to switch between them and crashing
> 
> Are you able to try different inputstream.adaptive settings to see if it fixes? eg. change it from adaptive bitrate to something else. They even have a quality select feature now i believe

Yes changing inputstream adaptive to 'ask quality' fixes this issue. But a better workaround is choosing 'Manual OSD' and putting the 2 maximum resolution fields in that option as 4k. That also works and doesn't pause playback by asking what quality you want. Thanks very much.

**Comment by GG-76** [comment]
Hi, I've been reading this thread and I'm a bit confused. Currently, the addon also crashes for me. I have a clean installation of kodi21 and the latest version of the addon, where the quality is displayed - Ask quality, which I cannot change, so I understand why. If I leave it set in ISA adaptive, then Kodi crashes, if I set it according to the OSD workaround and max 4K, then everything is played in FHD, I can only change it manually, which I probably don't want to do every time. So, is there any possibility to set it so that I always have the maximum possible resolution, also taking into account that the ISA setting also affects other addons? Thank you.

**Comment by gmjh123** [comment]
So you're in the configure part of input stream adaptive add on and you can't change it to ask quality? I don't know how. 
On the OSD' option, do you have the option 'manual stream selection mode' to 'audio/video streams '. And 'ignore hdcp status' activated?

**Comment by GG-76** [comment]
maybe I explained it wrong. I can set anything in ISA. But I don't want to set the quality every time I start playback, I want the maximum possible quality to be always selected, for that reason I had adaptive set in ISA, but now it's crashing with this option.
I'm interested in how else to get Kodi to automatically play in the highest possible quality.
When I set the OSD, max 4k in both settings and I also have 'ignore hdcp status' activated, the video stream marked as (default) is always selected and it is always max FHD, when I change it to the maximum available 4K, then I turn off playback and start playback again, it already remembers the last one selected, but I need the best one to be selected as the default stream and that's not happening now :(

**Comment by gmjh123** [comment]
> maybe I explained it wrong. I can set anything in ISA. But I don't want to set the quality every time I start playback, I want the maximum possible quality to be always selected, for that reason I had adaptive set in ISA, but now it's crashing with this option. I'm interested in how else to get Kodi to automatically play in the highest possible quality. When I set the OSD, max 4k in both settings and I also have 'ignore hdcp status' activated, the video stream marked as (default) is always selected and it is always max FHD, when I change it to the maximum available 4K, then I turn off playback and start playback again, it already remembers the last one selected, but I need the best one to be selected as the default stream and that's not happening now :(

I'm not sure why you only get HD when choosing the OSD auction. I always get 4k or Dolby vision if it's available. If you choose ask quality, it literally only takes a second longer for you to choose the first option given to you which is the highest one.

**Comment by GG-76** [comment]
I also don't know why it marks FHD as the default and it is selected for playback... it's probably not that the ask quality takes a little longer, but that it's very annoying to select the quality of the stream every time it's played, which I haven't had to do so far. .. and I didn't really understand if this is an error in the context of adaptive quality at the moment, or if I'm not a donor, I won't be able to use adaptive quality in ISA anymore?

**Comment by matthuisman** [comment]
see here: https://www.matthuisman.nz/2019/09/new-quality-select-in-my-add-ons.html
Donor can disable it, have it select best, select based on bandwidth or have it ask.
Even when its set to Best etc, there is context menu option added that allows doing ASK if needed.
Lots of options

Non-donor gets just disabled all the time. so IA is passed the entire manifest and its upto it to choose a quality

**Comment by gmjh123** [comment]
> see here: https://www.matthuisman.nz/2019/09/new-quality-select-in-my-add-ons.html Donor can disable it, have it select best, select based on bandwidth or have it ask. Even when its set to Best etc, there is context menu option added that allows doing ASK if needed. Lots of options
> 
> Non-donor gets just disabled all the time. so IA is passed the entire manifest and its upto it to choose a quality

Hi Matt. I'm a donor and I don't see this option on the playback options of your slyguy common settings

**Comment by matthuisman** [comment]
What option? The quality option is set on a per-addon basis currently. In the disney+ settings - once your a donor - you can choose Disabled / Ask / whatever eles

**Comment by gmjh123** [comment]
> What option? The quality option is set on a per-addon basis currently. In the disney+ settings - once your a donor - you can choose Disabled / Ask / whatever eles

Oh okay sorry. I thought you meant it was in the common settings not on a per add-on basis.

**Comment by matthuisman** [comment]
not yet. I am working on my own custom settings system that will allow to have all the common settings and then addons can
1) inherit the common setting or 2) override it with their own value

Plus lets me do a bunch of other cool stuff in regards to callbacks etc.
No more "restart kodi to make this take affect"

**Comment by matthuisman** [comment]
Also to note, only 3x of my addons currently have the "supporter" stuff enabled.
MAX, Disney+ and IPTV Merge.

 For all other add-ons - the quality select can be used without it.
 Thats because it requires code change / setting changes to move it over to supporter only.

**Comment by matthuisman** [comment]
IA 21.5.0 released with the adaptive crashing fixed.
But it may have introduced an audio 5.1 bug (investigating now)
