### ISSUE TITLE
Problem with DSTV EPG

### ISSUE THREAD

**Issue by markmutai** [matthuisman/slyguy.addons#77]
The EPG for dstv now hasn't been working for the last few days. I've tried resetting and re-installing everything - DSTV Now, IPTVMerge & IPTV Simple Client - but still doesnt work. I can see on the EPG section of IPTVMerge, the "dstv now" source is in red. I'm assuming that's showing something is wrong on the other end and not locally? or is there something im missing

**Comment by matthuisman** [comment]
this should now be fixed in 0.15.8
By default 0.15.8 will always use the online cached ZA epg.
There is a new setting that can disable the feature. The default is enabled.
