### ISSUE TITLE
7plus - Home & Away replays fail to play

### ISSUE THREAD

**Issue by stevieland58** [matthuisman/slyguy.addons#773]
Get a location error when trying to watch Home & Away replays.

**Comment by matthuisman** [comment]
if your using a vpn, does their website work using the same vpn?

**Comment by stevieland58** [comment]
I'm not using a VPN, I'm I'm the same country as the app.
I know the app recently updated so maybe it has something to do with that.

**Comment by matthuisman** [comment]
oh ok :) thank you!
Ill investigate

**Comment by stevieland58** [comment]
I'll close this as it's working now. 
I believe they moved the link around in the update and my favourite wasn't working now, so I re added it and it's working.

Sorry for any inconvenience.
