### ISSUE TITLE
Max does not auto pick / marks 4K qualities as yellow

### ISSUE THREAD

**Issue by matejdro** [matthuisman/slyguy.addons#774]
https://github.com/matthuisman/slyguy.addons/assets/507922/748e0925-b338-4a10-a4d2-6421aa386bca

Best quality options appear as yellow and they do not get auto-selected when picking "Best". But selecting them manually works fine.

Any idea what could cause this?

**Comment by matthuisman** [comment]
yellow means the system has detected them as not compatible.

Go check out the playback settings in Slyguy common :)
Maybe "ignore display resolution" has been disabled or a max width / height
has been set.

Im actually working on a big brand new settings system that wont use Kodi
settings but my own plugin settings.
This will allow for easily inheriting all the common settings or override
them on a per-addon basis :)

**Comment by matthuisman** [comment]
@matejdro did you find what was causing it? can we close this?

**Comment by matejdro** [comment]
Yes, enabling "ignore display resolution" helped. Thanks!

**Comment by matthuisman** [comment]
Great. With that disabled, it'll only select resolutions upto the display
size.

**Comment by matejdro** [comment]
Huh that's weird, because the display is definitely 4K. Maybe it uses android UI resolution (which as far as I'm aware, runs in 1080p)?

**Comment by matthuisman** [comment]
the code uses xbmc.getInfoLabel('System.ScreenWidth') and xbmc.getInfoLabel('System.ScreenHeight')
So i suspect they must be returning a lower number
Kodi might show these somewhere in the system info

**Comment by matejdro** [comment]
Yes, this appears to be the case:

![image](https://github.com/matthuisman/slyguy.addons/assets/507922/55a0d587-e367-4e35-8ade-3dd369fadeac)

![image](https://github.com/matthuisman/slyguy.addons/assets/507922/47a53007-caa6-4fcd-a0f0-cbc4d1ef73d5)
