### ISSUE TITLE
MAX - problem with HEVC codec on Linux device

### ISSUE THREAD

**Issue by zuzia-dev** [matthuisman/slyguy.addons#776]
My configuration: Linux Debian 12 64-bit, KODI v21 Omega, InputStream Adaptive 21.4.10. The H265/HEVC option is enabled on MAX but streams with the HEVC codec are not available in any InputStream Adaptive configuration. I've checked every possible configuration, but it doesn't change anything.

![Max-playback-quality-H264](https://github.com/matthuisman/slyguy.addons/assets/52371987/7df0ddd6-1f3e-4189-a700-cfa8d863e305)

After activating the donor ID and setting the best option, the HEVC codec is now available. 

![Max-quality-the-best](https://github.com/matthuisman/slyguy.addons/assets/52371987/5738034a-ae5f-4e46-bc63-4793b1f8a7d4)
![Max-playback-quality-with-the-best](https://github.com/matthuisman/slyguy.addons/assets/52371987/9f705db1-0365-4631-8db2-5f1162930ada)

Logs with the H264 codec: [kodi.log](https://raw.githubusercontent.com/zuzia-dev/srcs/main/kodi.log)

@matthuisman 
Should I change and test anything else? Please be patient because I don't know if I understand the problem correctly so I want to make sure before reporting the bug to the InputStream Adaptive developers.

**Comment by matthuisman** [comment]
I replied about this on that other issue.

**Comment by matthuisman** [comment]
See https://github.com/matthuisman/slyguy.addons/issues/454#issuecomment-2191207600

**Comment by matthuisman** [comment]
Summary. Inputstream adaptive quality select dialog is not showing them. It's a bug with their select code. Open issue with then
