### ISSUE TITLE
New Max 0.1.0 crashes kodi

### ISSUE THREAD

**Issue by batarela** [matthuisman/slyguy.addons#777]
When trying to play movies or episodes kodi crashes.

My configuration is Kodi 21, Windows 11.

Thanks

**Comment by zuzia-dev** [comment]
Check this thread: https://github.com/xbmc/inputstream.adaptive/issues/1589

**Comment by matthuisman** [comment]
Full Kodi debug log plz

**Comment by matthuisman** [comment]
ISA adaptive issue as above. Closing this

**Comment by matthuisman** [comment]
solution was to install latest VC Redist: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
