### ISSUE TITLE
Samsung TV  Plus - Brazil

### ISSUE THREAD

**Issue by flaocta** [matthuisman/slyguy.addons#78]
Hi! I would like to get, if possible, the Brazilian channels in the add-on Samsung TV Plus. Is there this possibility? Congratulations for your work!

**Comment by matthuisman** [comment]
I can only scrape what the mobile app uses (not tv app)
https://play.google.com/store/apps/details?id=com.samsung.android.tvplus
Pretty sure the mobile app is not yet available in Brazil so not possible?
If the above is available in Brazil, let me know and I can start scraping it
