### ISSUE TITLE
NZ freeview - iptv current channel details masked

### ISSUE THREAD

**Issue by mr-pineapple-nz** [matthuisman/slyguy.addons#780]
When playing a channel in IPTV the current channel info is masked. However, if I change browse channel in IPTV (using up/down arrows) it displays others.
See attached picture.
![IMG_20240626_080839](https://github.com/matthuisman/slyguy.addons/assets/74445573/bda4df6a-adcf-435a-a7e5-2ea4352b7e06)

OS: OSMC
Kodi version: 20.5.0
Hardware: Pi4

**Comment by matthuisman** [comment]
Kodi or skin or osmc issue. Id  get in touch with them . Try osmc first
