### ISSUE TITLE
Max addon: Add Dolby Vision / Dolby Atmos support for "Old Standard" plan (Netherlands)

### ISSUE THREAD

**Issue by MauriceW67** [matthuisman/slyguy.addons#782]
Already posted on the Kodi forum (https://forum.kodi.tv/showthread.php?tid=378013&pid=3202779#pid3202779), but will repeat here:

In my country (Netherlands) we were switched from HBO Max to Max a few weeks ago.

I have a "special" subscription that I got when the service started as HBO Max a few years ago where I pay half-price "forever". This subscription was converted to what is now called the "Old Standard" tier.

The regular (new) Standard tier does not include Dolby Vision or Dolby Atmos, but my Old Standard tier does. I've checked this in the new blue "Max" app on my Shield and I get Dolby Vision there.

However, with the new Max addon, I only get 4K in HDR and not Dolby Vision. Also, I need to have the proxy enabled in Slyguy Common, because with the proxy disabled, the highest I get is 1080p.

I tested this with the House of the Dragon TV show.

Any chance this could be fixed?

**Comment by matthuisman** [comment]
keep proxy enabled. its required. never disable.

Have you enabled Atmos & Dolby vision in the MAX addon settings?
If your subscription supports it, it should be returned.

**Comment by MauriceW67** [comment]
@matthuisman Yes, Atmos & DV are enabled in the Max addon settings. I found another strange thing: if I disable HDR10 and keep DV enabled, the addon still plays video in HDR if I select the 4K stream.

In the InputStream:Adaptive settings, I have set the "Stream selection type" setting to "Ask quality" by the way. Could it have something to do with the fact that the feature of being able to select the quality in your addon is now a donor only feature?

The Play Store link for the app I'm using is this: https://play.google.com/store/apps/details?id=com.wbd.hbomax

I can provide you with my login details if you want. Is it ok if I send them to your blog@matthuisman.nz e-mail address?

**Comment by matthuisman** [comment]
there are issues with the inpustream adaptive quality select.
If your a slyguy donor - you get to use the slyguy quality select which works a lot better.
This may even be your issue

**Comment by MauriceW67** [comment]
I am using the new Max addon for sure. The old HBO Max addon no longer works for me (it's giving API errors).

Like I said, my country (Netherlands) switched to the new Max platform a few weeks ago. The only problem is that in The Netherlands, there is already a public broadcasting company called "MAX", so HBO was forced to keep using the "HBO Max" name here.

But the app I linked to is the new blue one. The old purple one is this one (which doesn't work in my country anymore):

https://play.google.com/store/apps/details?id=com.hbo.hbonow&hl=en

Apparently there is another blue app just called "Max" with a different id:

https://play.google.com/store/apps/details?id=com.wbd.stream&hl=en

So it looks like the first one I linked to was created especially for The Netherlands, but anyhow it does use the new Max platform.

Anyway, I will try your suggestions for InputStream Adaptive and let you know.

**Comment by matthuisman** [comment]
ok. that makes sense.

Yes, confirm the Dolby vision / atmos are actually not there when using manual.
If they arn't, then please email me on blog@matthuisman.nz with a login to test with

**Comment by MauriceW67** [comment]
I'm back again :)

I tested with a few episodes of House of the Dragon Season 1.

So with everything set to Manual OSD, the DD+ Atmos audio track is selected by default, which is OK.

The video stream selection shows 40 streams in total, two of which are 4K. The addon chooses stream no. 11 by default, which is the HDR one. When I switch to the other 4K stream with no. 22, the output switches to DV.

Note that the stream descriptions do not contain any information about the video format, only the resolution is shown.

**Comment by matthuisman** [comment]
Ok,.so sounds like add-on is fine
You may need to open issues with inputstream.adaptive

**Comment by MauriceW67** [comment]
So you are saying that the choice of which stream to play is done by IS:A and not by your addon?

Just to clarify so I can open a proper issue with them.

**Comment by matthuisman** [comment]
Yes. Unless using slyguy quality control, it's IA that chooses which of the
streams to play.
