### ISSUE TITLE
paramount doesn't start

### ISSUE THREAD

**Issue by manjump** [matthuisman/slyguy.addons#785]
Hi,

I use this add-on on Kodi omega.
I use with the player of Kodi and Kodi crash when I start a movie.
I use with MPC player (playercorefactory modified) and the movie doesn't start
The log is big, but it seems the problem starts about 14h53
[kodi.log](https://github.com/user-attachments/files/16085461/kodi.log)

Thanks

**Comment by matthuisman** [comment]
Kodi 21 Windows has an issue:

See here https://github.com/xbmc/inputstream.adaptive/issues/1589

solution was to install latest VC Redist: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by manjump** [comment]
Thanks, it works now

**Comment by lundeen-bryan** [comment]
I installed the 64 bit version and rebooted my pc then started kodi and plutotv app. The app started frozen and then crashed. This particular fix doesn't seem to solve the problem for me. Is there any other reason I can look in to?

**Comment by matthuisman** [comment]
Pluto add-on is currently broken. No fix until I get time. There is an exisiting issue about pluto
