### ISSUE TITLE
Multifactor Access on Udemy Kodi Addon

### ISSUE THREAD

**Issue by IzhakAmittai** [matthuisman/slyguy.addons#786]
Hi Matt,

I'm very interested to continue using Udemy Kodi-Addon
However, your addon does not support the multi-factor entrance, 
which means I receive the multifactor email, but I don't have an option to use it, 
so I don't have an access to my account on your addon, and I really wants to

Hope you'll fix it soon and let me know

**Comment by matthuisman** [comment]
2FA support added in [plugin.video.udemy -> v0.12.2](https://github.com/matthuisman/slyguy.addons/commit/12efdb9100cea5e53a256ac63e7db848f9b03fd0)

**Comment by IzhakAmittai** [comment]
Thank you very much!!!

 
 

Sent: Tuesday, October 08, 2024 at 12:08 PM

**Comment by matthuisman** [comment]
No worries. Sorry it took so long
