### ISSUE TITLE
kodi crashing when opening stream on paramount+ and pluto addons

### ISSUE THREAD

**Issue by bananakinn** [matthuisman/slyguy.addons#787]
been using both addons regularly for a while, but now when i try to watch something on either paramount or pluto addons kodi completely crashes. im on a win 10 x64 machine running kodi omega. i created a fresh instance of kodi and problem still presists. i even installed the latest graphics drivers thinking that could be an issues but no fix. was able to get the addons to work properly on other devices (win 11 laptop & android shield tv) so it seems like some kind of issue specific to that machine but i cant place my finger on the culprit. hoping you may have a suggestion?

**Comment by matthuisman** [comment]
https://github.com/matthuisman/slyguy.addons/issues/785#issuecomment-2207290551
