### ISSUE TITLE
Pluto TV Addon

### ISSUE THREAD

**Issue by UPRHome** [matthuisman/slyguy.addons#792]
Cannot get the Pluto TV addon to work. This has been going on for a week or so.
Playback either stops working after a few seconds or it completely crashes the system. 
Using RPi 4B device running LibreELEC 11.0.6 and using default Estuary skin (started off using Aeon Nox Silvo with same results)
Did a completely clean installation with only Slyguy repo and Pluto TV and Samsung TV+ addons (as a sidenote, Samsung TV+ works perfectly fine) 
Have tried different settings with regard to playback with same results. Have all the recent updates to Slyguy Common and running new version of both addons.
Is there something else I can do to fix playback? Hoping to get this fine addon back in the mix.
Thanks

**Comment by UPRHome** [comment]
Forgot to add the log file
[kodi.log](https://github.com/user-attachments/files/16119891/kodi.log)

**Comment by usphil** [comment]
I also have the same error on CoreElec 20.5

**Comment by matthuisman** [comment]
see https://github.com/matthuisman/slyguy.addons/issues/791

You also dont seem to have inputstream adaptive installed. be a good idea to install that
