### ISSUE TITLE
Is it possible to choose the IMAX DTS Audio on choosen Content

### ISSUE THREAD

**Issue by xMisterW** [matthuisman/slyguy.addons#798]
Is it possible to choose the IMAX DTS Audio on choosen Content?

**Comment by matthuisman** [comment]
What add-on?

**Comment by xMisterW** [comment]
the disney plus addon. There are on dts using devices the possibility to use dts imax in some imax enhanced titles

**Comment by matthuisman** [comment]
Kodi doesn't yet support it. Once Kodi does, the setting will be enabled

**Comment by matthuisman** [comment]
Look through the closed issues here. There was one about it that explains
it

**Comment by matthuisman** [comment]
see here: https://github.com/matthuisman/slyguy.addons/issues/742
