### ISSUE TITLE
Pluto TV channels are freezing all the time

### ISSUE THREAD

**Issue by jcjdammers** [matthuisman/slyguy.addons#799]
I have installed the Pluto TV addon, and tried many of the channels, but after playing for a few seconds it freezes all the time.
I am using LibreELEC 12.0 with Kodi (Omega) v21.0.
Any help is appreciated, thanks.

**Comment by Chibouki7** [comment]
I also experience this on LibreELEC 12.0, Raspberry Pi 3B+.  Samsung TV works fine on the same device. Using the Pluto list in a Linux player also works fine.

**Comment by matthuisman** [comment]
users have reported the ALTERNATE streams in the add-on work Smile
[https://forum.kodi.tv/showthread.php?pid...pid3204962](https://forum.kodi.tv/showthread.php?pid=3204962#pid3204962)

Therefore, I've just updated the generator script to use alt streams for both non-alt and alt (making that setting in the plugin irrelevant)

This should fix the plugin and also people using the playlist outside of kodi

**Comment by Chibouki7** [comment]
It works, thank you!

**Comment by matthuisman** [comment]
i checked, and my playlists outside of Kodi where already using the ALT streams, so thats why I havn't heard too many people complain :)

**Comment by matthuisman** [comment]
alt streams = samsung tv version of pluto streams. No adverts - just the logo
