### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by betatester3016** [matthuisman/slyguy.addons#8]
Is it possible to have the [CBC addon](https://kodi.wiki/view/Add-on:Canadian_Broadcasting_Corp_(CBC)) work with [iptv merge](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html)? Or is this more a question for the [IPTV Manager](https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons) maintainer?

**Comment by matthuisman** [comment]
its probably better for official addons to support the official way (IPTV Manager)
Once they support that - they support IPTV Merge as well :)

its also on the add-on to add support - not manager to add support

So, your best bet is to ask here for them to add IPTV Manager support
**https://github.com/micahg/plugin.video.cbc**

**Comment by betatester3016** [comment]
Thank you for taking the time to respond, Much appreciated.
