### ISSUE TITLE
Error opening TV series in 9Now

### ISSUE THREAD

**Issue by psyren89** [matthuisman/slyguy.addons#801]
Trying to open any season of any TV series in the 9Now addon gives the following error:
```
9Now (0.2.5/0.94.0) - Unexpected Error

KeyError: 'tvSeries'

  File "plugin.py", line 121, in episodes
    title = "data['tvSeries']['name'],
  File "plugin.py", line 210, in decorated_function
    folder, more_results = f(**kwargs)
  File "plugin.py", line 61, in decorated_function
    item = f(*args, **kwargs)
  File "router.py", line 127, in dispatch
    function(**params)
  File "signals.py", line 50, in throwable
    yield
```

**Comment by matthuisman** [comment]
Is their website working? Pretty sure they were being affected by the
worldwide IT outage

**Comment by psyren89** [comment]
Streaming via their native (Android) app or their website works fine!

**Comment by psyren89** [comment]
Should have mentioned in the original post - I was using an Nvidia Shield TV Pro.
I just tried again using Kodi on Windows and there doesn't seem to be a problem. Will report back later once I try again on the Shield.

**Comment by matthuisman** [comment]
Hmmm there shouldn't be differences. Check no different DNS or VPN etc.
also check running latest of all addond

**Comment by psyren89** [comment]
Both running without VPNs using Quad9 DNS (configured at router).
Manually updated all addons to latest versions on the Shield before making this report, too.

**Comment by psyren89** [comment]
Just tried again on the Shield - it's working again. Not sure what happened last night...

**Comment by matthuisman** [comment]
Was it only down last night? If so, probably the IT outage. But you did say
the website was fine. So 🤔🧐
