### ISSUE TITLE
session.getaddrinfo fails on non-IPV6 systems

### ISSUE THREAD

**Issue by iheinrich** [matthuisman/slyguy.addons#805]
Latest slyguy auto-update broke all IPTV channels, probably more, with errors in log: 
File "addons/script.module.slyguy/resources/modules/slyguy/session.py", line 209, in getaddrinfo
socket.gaierror: [Errno -9] Address family for hostname not supported

System is Linux with custom kernel compiled without IPV6.

On closer inspection [script.module.slyguy/resources/modules/slyguy/session.py](https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/session.py) contains two locations that seem to exist to catch this.
For example [session.py lines 102 to 105](https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/modules/slyguy/session.py#L102-L105):
```lang=python
        try:
            return [x[4][0] for x in socket.getaddrinfo(host, None, family)]
        except:
            return []

```

Adding "try ... except" around line 209 fixes this too, at least for me.

**Comment by matthuisman** [comment]
hmm. can you please provide a kodi debug log?
Or the snippet just before the exception where it logs the DNS queries etc
im just not sure how its getting ipv6 addresses to start with.

**Comment by matthuisman** [comment]
think i found the issue.
Please test with latest [script.module.slyguy -> v0.84.2](https://github.com/matthuisman/slyguy.addons/commit/72b24367d2dcdb896f0a14badfd688e61af50ff5)

**Comment by iheinrich** [comment]
[script.module.slyguy -> v0.84.2](https://github.com/matthuisman/slyguy.addons/commit/72b24367d2dcdb896f0a14badfd688e61af50ff5) fixed the issue.
Thanks a lot!
