### ISSUE TITLE
Disney+ crashes Kodi after 2 Minutes playing

### ISSUE THREAD

**Issue by archtur** [matthuisman/slyguy.addons#807]
Environment

- LibreElec 12
- Disney+ AddOn 0.16.12
- SlyGuy Common 0.84.6
- Widevine CDM Version via Disney+ Plugin: 4.10.2662.3
- all Plugin updates to latest release (2024-07-22)

Steps to reproduce
1. Start LibreElec
2. Open Disney+ and choose Orville Season 1, one of the first episodes - most probably it is also reproducable with other content.
3. play for ~ 2 Minutes -> Kodi is crashing and auto restarting

**Comment by matthuisman** [comment]
what is your version of inputstream.adaptive? thats the most important. Its used for playback
Can you please supply a kodi debug log as welll

**Comment by matthuisman** [comment]
oh, i know
**Please see https://github.com/matthuisman/slyguy.addons/issues/765**
