### ISSUE TITLE
Disney+ marked as watched not possible

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#808]
- I cannot mark an episode as watched anymore in the context menu.
- An episode doesn't get marked as watched even when watching it until the end.

**Comment by MauriceW67** [comment]
As you suggested on the Kodi forum, I disabled Sync Playback and the option to mark an episode as watched is visible again in the context menu.

I'm a bit confused on how this is supposed to work though. What is the function of the Sync Playback option exactly? Is it not bi-directional?

It now looks like with the option enabled, you cannot see which episodes you've already watched in Kodi. And with the option disabled, you can see the watched status in Kodi, but it won't be synced back to your Disney+ account?

**Comment by matthuisman** [comment]
It's meant to. But that's broken due to their api changes. There is another
ticket about it somewhere. Even tempted to remove it. It doesn't really fit
into how Kodi works

**Comment by matthuisman** [comment]
closing as duplicate of https://github.com/matthuisman/slyguy.addons/issues/757
