### ISSUE TITLE
SlyGuy Common - fails to obtain FileLock for DB

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#809]
https://forum.kodi.tv/showthread.php?tid=353316&pid=3204889#pid3204889

I had trouble launching the slyguy video addons last night. Could this be related to the slyguy common update? Debug log:
https://paste.kodi.tv/eroleremec

When I try to load the addon (Disney+, Hulu, etc.) or any favorites that would play / navigate into the addon I get the spinning wheel of death forever. I copying from a backup but it auto-updated the slyguy common on startup.

edit: I was able to downgrade slyguy common to 0.79.4 and it appears to be working normally right now. I look forward to trying your updates again soon, though!

**Comment by matthuisman** [comment]
cant see it opening the db.
we should log before getting lock so we can confirm its stuck there.
Android 32bit. Maybe unix lock not working on it?

**Comment by matthuisman** [comment]
https://github.com/tox-dev/filelock/issues/349

maybe i use Kodi to do a lock instead.
Using a skin setting?

**Comment by Zuikkis** [comment]
I have this same problem with IPTV Merge... With Nvidia Shield Pro.

SlyGuy Common can't lock the database and fails.

**Comment by matthuisman** [comment]
can you provide a kodi debug log?
IPTV Merge doesnt yet use the new settings so unsure why common cant lock

**Comment by Zuikkis** [comment]
`EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'filelock._error.Timeout'>
                                                   Error Contents: The file lock '/storage/emulated/0/Kodi/files//.kodi/userdata/addon_data/script.module.slyguy/settings.db.lock' could not be acquired.
                                                   
`

I didn't (yet) upload the full log, but here's the relevant part.

I also tried to install the Disney+ plugin just to see if it makes any difference to have a plugin that actually uses the new settings. But that didn't work either, same error.

**Comment by matejdro** [comment]
Here is also a debug log from me trying to open Nebula: https://paste.kodi.tv/woxuwirene.kodi

**Comment by matthuisman** [comment]
Please try [script.module.slyguy -> v0.84.35](https://github.com/matthuisman/slyguy.addons/commit/3ec74f69d0ff260c2fc1f0c9f6eb62ee7487e016) that i just pushed

**Comment by matthuisman** [comment]
oops, that had issues.
Try: [script.module.slyguy -> v0.84.37](https://github.com/matthuisman/slyguy.addons/commit/a148d560e9886779549191fcd3116e1c8bef9a0e)

**Comment by matejdro** [comment]
Thank you, it works!
