### ISSUE TITLE
IPTV AU addon

### ISSUE THREAD

**Issue by alien8tor** [matthuisman/slyguy.addons#810]
Just wondering anyone has problems with iptv au addon, majority of the channels were all working fine yesterday, today i've noticed channel 9 network channels aren't working, could some one please take a look at this.

**Comment by wbpxre150** [comment]
Channel 9 not working here either.

**Comment by matthuisman** [comment]
closing as existing issue: https://github.com/matthuisman/i.mjh.nz/issues/113
