### ISSUE TITLE
*/Melbourne/raw-tv.m3u8 not loading any 9now channels

### ISSUE THREAD

**Issue by thepomlandman** [matthuisman/slyguy.addons#813]
Hi Sly Guy (Matt), longtime user first time caller. Love your work mate.

Can you have a look into why the 9now channels don't seem to be loading under the raw-tv.m3u8 playlist?

**Comment by matthuisman** [comment]
Because they require a certain user agent.if your using tivimate, then use
the Kodi playlist as that'll set the user agent. Otherwise refer to your
player program to set a browser user agent

**Comment by thepomlandman** [comment]
What should I change the 'User-Agent' field to within tivimate? I have
changed to kodi playlist, but still not loading 9now channels.

**Comment by matthuisman** [comment]
Restart tivimate clear cache after change

**Comment by thepomlandman** [comment]
Clearing cache worked a treat.. thanks ever so much mate. ;-)

**Comment by matthuisman** [comment]
No worries. Tivimate supports the Kodi format so use those playlists if
using my stuff :) easier than adding user agent yourself
