### ISSUE TITLE
MAX addon Paris 2024?

### ISSUE THREAD

**Issue by klugd** [matthuisman/slyguy.addons#815]
Is it possible somehow watch the Olympic games provided by Max via the Max plugin in Kodi?

thx

**Comment by klugd** [comment]
https://github.com/matthuisman/slyguy.addons/blob/master/slyguy.max/resources/lib/plugin.py
under the 30. row into the else section this seams to usable:
   folder.add_item(label=_(_.PARIS, _bold=True), path=plugin.url_for(page, route='paris-2024'))

**Comment by matthuisman** [comment]
just pushed [slyguy.max -> v0.1.4](https://github.com/matthuisman/slyguy.addons/commit/b4aeb67a36320a99db15e437ae71109b27fa9807) which will add the menu items dynamically based on your region which should give you the Paris 2024 entry

Note: live / channels are not fully supported yet. If it works - great :)
