### ISSUE TITLE
9NOW no longer able to play live streams

### ISSUE THREAD

**Issue by cryologic** [matthuisman/slyguy.addons#816]
Nine has changed setup, probably due to Olympic coverage. 
Clicking on "Live TV" link throws up "9Now (0.2.7/0.84.21)-Unexpected Error)
"TypeError:'NoneType' object is not subscriptable"

**Comment by matthuisman** [comment]
should be fixed with [slyguy.9now -> v0.3.0](https://github.com/matthuisman/slyguy.addons/commit/680ee566a670385d8a7d98234dfde7703267bdc6)
Youll now need to login

**Comment by cryologic** [comment]
Yep, all good. Excellent! Thanks
