### ISSUE TITLE
Stan Addon - missing category for the Paris 2024 Olympics

### ISSUE THREAD

**Issue by bazeman300** [matthuisman/slyguy.addons#817]
Hi Matt

I've been having trouble finding Olympics events in the Stan Addon. Having a quick look at the web version of Stan I could see a separate category for the Olympics alongside Sport, TV, Movie, etc., that isn't showing in the Addon.

Any chance this category could be added please? The addon works great otherwise.

PS. I've appreciated your add-ons and have sent you coffees, thanks for all your work!

**Comment by matthuisman** [comment]
this was fixed in [plugin.video.stan.au -> v0.5.0](https://github.com/matthuisman/slyguy.addons/commit/c97882ae70ddbf4fef51c4773527c2cfa4df7c58)

**Comment by bazeman300** [comment]
Thanks, it's working great! 👍

**Comment by matthuisman** [comment]
you should also now be able to access 4K on the sport on any kind of device
