### ISSUE TITLE
HBO max 'ES Language' failing to load data correctly in streaming.

### ISSUE THREAD

**Issue by askotx** [matthuisman/slyguy.addons#82]
I noted that spanish language was added recently to HBO max, that's great, but, (yes, there is a 'but'), addon stopped working, now it displays an error message **[#30004: API request failed | Fallo petición API]**, there's a workaround to make it work again: I need to change kodi's global language to english, not practical but hey it's a temporary solution.

**Comment by matthuisman** [comment]
what country are you in?

**Comment by askotx** [comment]
My country is Mexico (es_mx)
Kodi language was set to Spanish [not Spanish (Mexico) nor Spanish (Argentina)]. Then I had to set to English (default) to make HBO max addon working again.

**Comment by matthuisman** [comment]
if you go to HBO max website or app, what languages are available to change to?

**Comment by askotx** [comment]
This options are displayed on hbo max website:
-Same as device
-English (US)
-Spanish (Latinoamericano) [Selected]
-Portugues (Brasil)

**Comment by matthuisman** [comment]
could you please try latest 0.7.3 version of add-on and see if that fixes it?
you can follow below to force update:
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by askotx** [comment]
https://user-images.githubusercontent.com/2125887/139788469-082a00a5-ce43-44e8-9a6f-50895711a02c.mp4

New version, unfortunately same error

**Comment by matthuisman** [comment]
Can you confirm your accessing the addon normally? Not via shortcuts or
widgets? When testing, please just access it via add-ons. And then navigate
from there

**Comment by askotx** [comment]
Still the same, steps:
-Reboot
-Go to addons
-My addons
-Videos addons
-HBO max
-Abrir (Open)
-Añadidos recientemente (Just added)
-Error 30004 api request failed

New info: If I set language to Spanish (Mexico) UI in hbo max keeps text in english, and it works again, I dont know if addon it's trying to get data from HBO max Spain

**Comment by askotx** [comment]
https://user-images.githubusercontent.com/2125887/139798943-8847964f-3267-4151-8bdf-ee0b913a6b7c.mp4

You can see spanish (latinamerican) text on top-center and top-left and HBO max english text in attached video

**Comment by espinosaivan** [comment]
If you set your language to es_mx i can copy the translation to meet your locale so it will showed in spanish too.

**Comment by matthuisman** [comment]
@askotx 
please try 0.7.4

with this version, you can select the language via the settings.
by default its on "Auto" which will try to match it based on Kodis gui language (current behaviour)

Can you check Auto works when you have your kodi language set to Spanish.
Just to make sure I fixed that bug. It should revert to English.

**Comment by askotx** [comment]
![20211102_162424 1](https://user-images.githubusercontent.com/2125887/139965704-db98903f-d775-4c02-8643-4ab4ac7631c5.jpg)

Selected kodi's global language is Spanish (No Spanish MX nor Spanish AR)

-HBO max user interface is now in spanish [+]
-HBO max [Language] set to Spanish (Latinoamericano) [Selected] [+]
Result = Working + English audio
-But if I set Audio track from 'en' to 'es', spanish audio is auto selected so this option works fine, this is better.

Now, If I set HBO max Language to [Auto] instead of English (US), Spanish (Latinoamericano) or Portugues (Brasil), then error in uploaded picture is displayed

**Comment by matthuisman** [comment]
that error was my mistake. fixed with 0.7.5

**Comment by askotx** [comment]
Everything is working accordingly to it's respective Language:

-Addon display text is in spanish
-[Auto] language option it's working according to Kodi's language, -no more error.
-Finally, audio track is selected automatically to language, (before 0.7.4, it wasn't)

**Comment by matthuisman** [comment]
Great. So this issue can be closed?

**Comment by askotx** [comment]
Yes!!
