### ISSUE TITLE
Please why KODI MAX app can’t watch movie?

### ISSUE THREAD

**Issue by Dingchunqiu-pw** [matthuisman/slyguy.addons#824]
it always remind MAX-Error Access Denied Missing Package. How can i solve it?
![20f77a5b1846494030d4e3ac112eb7c](https://github.com/user-attachments/assets/48fe321c-e932-476c-baf4-59a2e4c60447)

**Comment by matthuisman** [comment]
Sounds like subscription doesn't have the correct access?

**Comment by Dingchunqiu-pw** [comment]
But i can use normal use in MAX

**Comment by matthuisman** [comment]
what subscription plan do you have and what country are you in?

**Comment by Dingchunqiu-pw** [comment]
i am in china ,my subscription plan is Ulitimate Ad-Free

**Comment by Dingchunqiu-pw** [comment]
![图片](https://github.com/user-attachments/assets/de95666c-817f-4492-acdd-1687ac80b120)

**Comment by matthuisman** [comment]
do you vpn to a country to use it or is MAX available in China?

**Comment by Dingchunqiu-pw** [comment]
i have vpn

**Comment by Dingchunqiu-pw** [comment]
i have linked USA

**Comment by Dingchunqiu-pw** [comment]
ok! I have solved it!

**Comment by Dingchunqiu-pw** [comment]
it semms like the account's problems. i changed another account ,it works. thanks!!!!

**Comment by matthuisman** [comment]
ok great :) Enjoy!

**Comment by Dingchunqiu-pw** [comment]
OKOK Thank you very much
