### ISSUE TITLE
Request: Auto-play next episode/don't start the current episode again

### ISSUE THREAD

**Issue by PstasDev** [matthuisman/slyguy.addons#826]
I was using the addon for **Max** and when the whole episode was over, it didn't quit, but started the same episode all over. I'm sure that it's not supposed to do this, because with other addons or with local shows, I can manage to make it auto-play the next episode or to quit after the episode is over.

I hope that can be done and it's not much of an effort so it will be done.

Thank you so much if it gets implemented! 

PS.: I would do it myself, but I don't have any experience with Kodi add-ons

**Comment by gmjh123** [comment]
> I was using the addon for **Max** and when the whole episode was over, it didn't quit, but started the same episode all over. I'm sure that it's not supposed to do this, because with other addons or with local shows, I can manage to make it auto-play the next episode or to quit after the episode is over.
> 
> I hope that can be done and it's not much of an effort so it will be done.
> 
> Thank you so much if it gets implemented!
> 
> PS.: I would do it myself, but I don't have any experience with Kodi add-ons

I've just tried this with a random show on the max addon, and the show just stopped and went back to the main screen as it should. I thought maybe there was a setting for this action to work in the max addon, but when I try to look at the settings it said "this add on can't be configured". Which may be another issue entirely.

**Comment by PstasDev** [comment]
@gmjh123 I'm sure that the settings are working, at least for me they do. My initial thought, why they don't work for you is that you might miss some packages made by the author. As far as I know, the slyguy.module.slyguy is what contains the code for the settings, I suggest you to try fix it with this in mind. 

Also as I said, they work for me and I am genuinely satisfied with them, I could easily set up my preffered language and everything for the audio lines and for the subtitles!

**Comment by gmjh123** [comment]
> @gmjh123 I'm sure that the settings are working, at least for me they do. My initial thought, why they don't work for you is that you might miss some packages made by the author. As far as I know, the slyguy.module.slyguy is what contains the code for the settings, I suggest you to try fix it with this in mind.
> 
> Also as I said, they work for me and I am genuinely satisfied with them, I could easily set up my preffered language and everything for the audio lines and for the subtitles!

My sly guy add-ons and the sly guy common dependencies are all set to automatically update to the latest version. In fact it did an update on these this morning. So I've got the latest version of everything. So as I said, it's possible this is a new and separate issue.

**Comment by PstasDev** [comment]
@gmjh123 Okay, then good luck for you with that!

**Comment by PstasDev** [comment]
@gmjh123 Hey! I think I found the solution to your problem. Did you try to press a left on the shows list and press the last button "Add-on settings"? Because if I press that I get that error that you mentioned too, but the Add-on settings aren't there. You have to navigate back to the root of the add-on via the .. options on the top of the list of episodes/shows and in the root folder, where you have the options to choose from the categories, you have a search, a profile change and the actual settings menu around the bottom. I think you should check out that one

**Comment by gmjh123** [comment]
> @gmjh123 Hey! I think I found the solution to your problem. Did you try to press a left on the shows list and press the last button "Add-on settings"? Because if I press that I get that error that you mentioned too, but the Add-on settings aren't there. You have to navigate back to the root of the add-on via the .. options on the top of the list of episodes/shows and in the root folder, where you have the options to choose from the categories, you have a search, a profile change and the actual settings menu around the bottom. I think you should check out that one

Ah yes I see that now. I'm not sure why they've been moved there, there must have been some discussion that I missed. So thanks for that. Anyway, we're still left with the problem that all my Max shows end as they should do, and yours don't.

**Comment by matthuisman** [comment]
In kodi settings, have you got Settings > Player Settings > Videos > Play next video automatically enabled?

Local shows work differently to plugins.
What other plugin auto-plays the next episode?

When you please an episode, do you use the context menu "Play videos from here"?
I think that should add all the items after it to the playlist

**Comment by PstasDev** [comment]
Yes, I enabled this for every media type and still doesn't work.

I don't know it's exact source, but it's a Netflix link for Kodi.

Also the option "Play videos from here" doesn't appear in the any context menu. Only options to bookmark, mark as watched, play only this one, etc.

**Comment by matthuisman** [comment]
thanks :) Ill take a look

Some addons i added play next behaviour which would then even work across diffent folders (seasons)
But thats not implemented in MAX yet.

However, I would think the basic feature should work if kodi can take care of the playlist / next stuff

**Comment by PstasDev** [comment]
Thank you for your further attention to this. I don't really get why the context menu options show up myself.

**Comment by GG-76** [comment]
Hi, I noticed that I have the same problem. In the MAX setting, I don't have the option to turn off playing the next episode and other options at all. On the contrary, I have these options in the Disney+ settings, but it behaves strangely, when one option is changed, others also change, and above all, when I go back and return to the Disney+ settings folder, nothing is saved. It's just this one settings folder that does it. Does anyone have it too? I have the same problem on two devices...

**Comment by matthuisman** [comment]
again, MaX doesn't have this feature yet so won't have a setting for it.

Regarding Disney+, your changing the setting to Yes and it's not saving that choice? What other settings is it changing?

**Comment by GG-76** [comment]
I have already figured out what causes this strange behavior. I'm using the Arctic Zephyr Reloaded Kodi skin and it doesn't save those choices in the Disney+ folder. When I change Kodi to the default Estuary, it doesn't happen and what I change stays saved. But this was not happening before changing the appearance of the settings :(

**Comment by matthuisman** [comment]
that settings not persisting was actually a bug in slyguy common. fixed with latest common. Unrelated to the skin :)

**Comment by GG-76** [comment]
strange because the setting kept me in the default skin. Anyway, after the last update of slyguy common, it's fine now and it always saves for me, than thanks for quick fix.

**Comment by matthuisman** [comment]
so to confirm, its saving correctly in Arctic Zephyr now too?

**Comment by GG-76** [comment]
Yes, works correctly in Arctic Zephyr to. Thank you.

**Comment by matthuisman** [comment]
thanks. im going to hide these comments about that issue to keep this issue on topic :)

**Comment by matthuisman** [comment]
oh wait - you dont have this setting enabled by any chance?
Max -> settings -> interface ->Video view for media ?

If so, thats probably your issue.
If thats set, the content type isnt "episode" (its video)

**Comment by matthuisman** [comment]
also note: In Kodi 21 - if play next episode automatically is enabled - it removes the "play from here" as that becomes default behaviour.  You instead get a "play only this"

**Comment by matthuisman** [comment]
no response so closing
