### ISSUE TITLE
Pluto Channels Freezing

### ISSUE THREAD

**Issue by bubsterdoofus** [matthuisman/slyguy.addons#828]
All Pluto streams are freezing 5 to 20 seconds after starting. Happens on two different Windows machines , one W10, one W11, both running Kodi v.21. Tried with and without VPN. Samsung TV and Plex streams running fine on those machines. Pluto streams running fine on Android device using same WiFi/router. Started maybe 3 weeks ago. Always worked fine before that.

**Comment by matthuisman** [comment]
there is an existing issue: https://github.com/matthuisman/slyguy.addons/issues/799
