### ISSUE TITLE
Unable to install max from the repo

### ISSUE THREAD

**Issue by RealAmethyst** [matthuisman/slyguy.addons#829]
I am unable to install the max addon from the repository. It just says instalation failed. I am running latest stable Kodi 21 on windows 10.

**Comment by matthuisman** [comment]
restart kodi and try again. no known issues.
maybe look at the kodi log

**Comment by RealAmethyst** [comment]
Not sure where the kodi log file are stored. I have tried a restart, did not work.

**Comment by RealAmethyst** [comment]
[kodi.log](https://github.com/user-attachments/files/16467079/kodi.log)
found it.

**Comment by matthuisman** [comment]
its trying to download a very old version: https://slyguy.uk/.repo/repository.slyguy/slyguy.max/slyguy.max-0.1.0.zip
which has been removed. Latest is 0.1.5

Suggest you try navigate to slyguy repo, open context menu and click "check for updates"

**Comment by RealAmethyst** [comment]
Thank you! That fixed it.
