### ISSUE TITLE
Stremium channels start from beginning instead of live.

### ISSUE THREAD

**Issue by MajinLugia** [matthuisman/slyguy.addons#831]
This issue started happening last week where stremium channels start from the beginning of the program instead of being “live”, this happens both in pvr and the stremium plugin.

**Comment by matthuisman** [comment]
PS: the issue of the settings not saving has been fixed in latest slyguy common

Also, this issue of streams starting from start should also be fixed.
However, i still see some delay in starting the streams due to the timing being off.
Ill try to fix that tonight after work and then close this issue :)
Please keep the login working until I can fix that issue

**Comment by MajinLugia** [comment]
You seriously rock! And yes I noticed the stream was a minute behind but a whole lot better than being all the way behind! And no problem, I’ll keep the login working!

**Comment by MajinLugia** [comment]
Also, the moment when the next programming starts, it gets stuck at buffering.

**Comment by matthuisman** [comment]
That'll be inputstream adaptive I suspect. Probably out of my hands

**Comment by matthuisman** [comment]
could you just test in Kodi 20 if possible and see if that has the same buffering at next program?

**Comment by matthuisman** [comment]
also, what version inputstream.adaptive using?

**Comment by MajinLugia** [comment]
I have downgraded to 21.4.10 version of inputstream adaptive on android. So far I’m not experiencing any buffering at the end of the program but I’ll report back if I do experience any buffers. I’ll have to test out Kodi 20 on my android tv device tomorrow but its looking like it may be a inputstream adaptive issue.

**Comment by matthuisman** [comment]
oh, that may be due to my latest slyguy change
what version slyguy common running?

**Comment by MajinLugia** [comment]
I am using version 0.84.53 of slyguy common. Should I update to the latest version of inputstream adaptive to see if there is any buffering once the program ends?

**Comment by matthuisman** [comment]
yes please :)

**Comment by MajinLugia** [comment]
Unfortunately, after updating inputstream adaptive, it got stuck on a buffer so its looking like its indeed an inputstream adaptive issue.

**Comment by matthuisman** [comment]
ok, so latest slyguy with 21.4.10 is OK, but latest slyguy with 21.5.1 = error

**Comment by matthuisman** [comment]
[slyguy.stremium -> v0.2.1](https://github.com/matthuisman/slyguy.addons/commit/a704e4d17760c59b9fe4acf26b4ec763f617c821) just pushed that should make playback start quicker

**Comment by MajinLugia** [comment]
I was testing the streams this morning and there is a buffer when the programming ends followed by the buffer ending and closing out the stream with inputstream adaptive 21.4.10 and the latest version. I’ll have to test Kodi 20 later on and send you the results.

**Comment by matthuisman** [comment]
your last comment said 21.4.10 didnt have the issue?

**Comment by matthuisman** [comment]
maybe open a new slyguy issue for this problem :)

**Comment by MajinLugia** [comment]
Okay! I’m testing out the slyguy common you linked as well as running Kodi 20 on another screen and I’ll post the results on a new issue.

**Comment by matthuisman** [comment]
Kodi 20 didn't have the common change so common version on 20 what make a
difference. But 20 does use an older inputstream adaptive.

But yes, let me know :)

**Comment by MajinLugia** [comment]
I have opened up a new issue.
