### ISSUE TITLE
Disney+ suddenly doesn't keep settings

### ISSUE THREAD

**Issue by jjplano** [matthuisman/slyguy.addons#832]
hi! suddenly, without any changes on the system nor an update (that I'm aware of), the Disney+ addon doesn't saves the settings. every time I open it has reset to default. didn't have any problems till a couple of days ago. 

Raspberry Pi 3 model B
Libreelec 11.0.6
Kodi 20.3
addon version 0.17.0

I'm uploading a log where I started the system, opened the Disney+ addon, went to settings, changed a few things, opened the Max addon, came back to the Disney+ one and it had reset to default

http://paste.libreelec.tv/guiding-coral.log

thanks!

**Comment by gmjh123** [comment]
Have you checked your general Kodi settings to see if they've also being reset to default? I've been having an issue where everything, the media settings, the system settings etc etc, are all set to default after opening Kodi.

**Comment by matthuisman** [comment]
@jjplano could you please enable debug logging in kodi and upload a new log?

**Comment by jjplano** [comment]
> Have you checked your general Kodi settings to see if they've also being reset to default? I've been having an issue where everything, the media settings, the system settings etc etc, are all set to default after opening Kodi.

nothing else changes back to default, not on Kodi, not on any other addon. I don't even have to restart the system for the Disney+ to reset :/

**Comment by jjplano** [comment]
> @jjplano could you please enable debug logging in kodi and upload a new log?

of course, http://paste.libreelec.tv/vital-condor.log

thanks man

**Comment by matthuisman** [comment]
can you try [script.module.slyguy -> v0.84.50](https://github.com/matthuisman/slyguy.addons/commit/7da5e6049e730334c14bccade6ecb551791f1ef2) please :)
just pushed it

**Comment by jjplano** [comment]
> can you try [script.module.slyguy -> v0.84.50](https://github.com/matthuisman/slyguy.addons/commit/7da5e6049e730334c14bccade6ecb551791f1ef2) please :) just pushed it

works great! thank you so much man. your add-ons rock :) (just waiting for a "continue watching" feature on MAX for it to be perfect :D). thanks again for all the amazing work!

**Comment by matthuisman** [comment]
nice :)
