### ISSUE TITLE
[9now] Unable to find brightcove source

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#833]
as per https://forums.whirlpool.net.au/thread/9kvl5k73?p=8

"""Just tried the surfing women's quarter final highlights (featured/Olympic sports/surfing/2024x23....) Got the error above about Brightcove. Tried in the 9now app and it's working.
Live events are working which is the main thing!
My inputstream adaptive updated this arvo to the latest.""

""no problems playing live with addon, app or website, vod is working on app and website.""

**Comment by matthuisman** [comment]
i suggest we try with slyguy proxy disabled (in settings -> player -> advanced)
See if that makes a difference

**Comment by demod-au** [comment]
hey Matt..  before we ran down a rabbit hole, I tried on a PC version of Kodi.  And it is playing VOD.   Same location.  So must be a settings thing.  I'll compare the two and try again.

**Comment by matthuisman** [comment]
[script.module.slyguy -> v0.84.55](https://github.com/matthuisman/slyguy.addons/commit/0d335c55fc18afca56c05f83b4b975cf0c42e968) just pushed.
You should get more information in the brightcove error now. Let me know what it says

**Comment by demod-au** [comment]
The plot thickens.  
This is the error: 
Could not find a media source from Brightcove Server Message: f'client_geo': 'gb', 'error_subcode': 'CLIENT GEO', 'error_code': 'ACCESS_DENIED', 'message': 'Access to this resource is forbidden by access policy.")

When I tried the official app earlier it was on my phone.  The unit I'm having the error on is the firetv cube.  
I installed official on the cube and also received a "you're not in Australia" error.  

The add-on was definitely working last week.  As I was watching the surfing recaps.  Seems like an issue with the fire tv?  

Also tried on an old shield and that also worked fine.  All devices were tested on my home network in AU.

**Comment by matthuisman** [comment]
Interesting. so the official app on the same box also detects you out of region (GB?)

What DNS to you use?
There is a slyguy supporter setting in the addon under network where you can set a DNS server for just that addon.
Maybe try use 1.1.1.1 and see if that fixes it?

**Comment by demod-au** [comment]
1.1.1.1 didn't work.  But I tried pointing that DNS settings to getflix and forced to Australia.  Working!  Gotta say I've never experienced anything like this before, all within the same network and DNS settings!  

Thanks for persisting with me.   
Hopefully the info  helps others.

**Comment by matthuisman** [comment]
are you not in australia?

**Comment by demod-au** [comment]
No . I'm completely in Australia.  Just thought I'd try getflix for giggles

**Comment by matthuisman** [comment]
oh strange...
