### ISSUE TITLE
[Sky Sport Now] VOD fails to play

### ISSUE THREAD

**Issue by Civic1998** [matthuisman/slyguy.addons#834]
Tested on 2 devices, Windows and Android, with Kodi 21. Playback fails to start, then returns to the video selection list. Tested on multiple different streams, same issue. Live broadcasts appear to work fine.

**Comment by matthuisman** [comment]
fixed in [plugin.video.sky.sport.now -> v0.6.6](https://github.com/matthuisman/slyguy.addons/commit/622ed260a729b506e847a83daa55e356c4435457)
