### ISSUE TITLE
9Now - Failed: Couldn't connect to server(7)

### ISSUE THREAD

**Issue by Air-w0lf** [matthuisman/slyguy.addons#835]
This error occurs in the 9Now plugin when trying to play a video and when the slyguy proxy is not forced off. Refer attached log and search for the error message in the title.
[kodi.log](https://github.com/user-attachments/files/16506373/kodi.log)

**Comment by matthuisman** [comment]
i dont understand. your getting the same error with or without slyguy proxy

**Comment by matthuisman** [comment]
id suggest its something with your network

**Comment by matthuisman** [comment]
i can open one of those failed urls without issue
eg.
https://p-9now.akamaized.net/media/v1/hls/v5/clear/4460760524001/e0fd264c-0921-4ce8-8389-21f043bf548f/d9adc4b7-e6a2-497d-973c-de48d43bad7c/segment98.vtt?akamai_token=exp=1723011044~acl=/media/v1/hls/v5/clear/4460760524001/e0fd264c-0921-4ce8-8389-21f043bf548f/d9adc4b7-e6a2-497d-973c-de48d43bad7c/*~hmac=779fba53b5c37a918e165e5569fc1cffeb07f5e1547ea6b4af3f34a4377c36f2
