### ISSUE TITLE
Green-looking picture in playback (Paramount+)

### ISSUE THREAD

**Issue by CodePhase** [matthuisman/slyguy.addons#837]
When attempting to play a show in Paramount+ on Coreelec Kodi 20.5, the picture has an overwhelming green tone.  Some episodes have no video at all, but the audio comes through.  The encoding is shown to be H265.  I wanted to try to set it to something lower, like H264 but couldn't find an option to do that.

I'm running on an Odroid N2+.

**Comment by matthuisman** [comment]
Settings -> Player -> Codecs
You should be able to disable H265 there

**Comment by gmjh123** [comment]
> When attempting to play a show in Paramount+ on Coreelec Kodi 20.5, the picture has an overwhelming green tone. Some episodes have no video at all, but the audio comes through. The encoding is shown to be H265. I wanted to try to set it to something lower, like H264 but couldn't find an option to do that.
> 
> I'm running on an Odroid N2+.

Weird green tone is often caused by Dolby vision or HDR content not being displayed correctly. Is the show you're talking about in Dolby vision?

**Comment by CodePhase** [comment]
> > When attempting to play a show in Paramount+ on Coreelec Kodi 20.5, the picture has an overwhelming green tone. Some episodes have no video at all, but the audio comes through. The encoding is shown to be H265. I wanted to try to set it to something lower, like H264 but couldn't find an option to do that.
> > I'm running on an Odroid N2+.
> 
> Weird green tone is often caused by Dolby vision or HDR content not being displayed correctly. Is the show you're talking about in Dolby vision?

Yes, it displays boxes on the episode that say 'H.265' and 'DOLBY', so I"m guessing so.

> Settings -> Player -> Codecs You should be able to disable H265 there

I tried disabling H.265 and Dolby Vision in the settings but it made no difference.

**Comment by matthuisman** [comment]
might be time for a full kodi debug log please
https://kodi.wiki/view/Log_file/Easy

**Comment by matthuisman** [comment]
also, maybe check the Kodi / Coreelect playback settings
I had a user with a Pi disable DRM Prime and it fixed some playback issues for them
