### ISSUE TITLE
Disney+ - Error: API request failed. Server Error: default

### ISSUE THREAD

**Issue by jjplano** [matthuisman/slyguy.addons#840]
hi! Suddenly I receive that error on the Disney+ latest addon on Kodi 20.3/libreelec11.0.6/raspi3 model b

I tried reset, relogging, reinstall. same error every time. every other addon works as expected.

I've uploaded the log file http://paste.libreelec.tv/frank-clam.log

thanks!

**Comment by matthuisman** [comment]
hmmm. seems like an error there side.
It may also be them deprecating the old api the addon currently uses

What country are you in?

**Comment by jjplano** [comment]
> hmmm. seems like an error there side. It may also be them deprecating the old api the addon currently uses
> 
> What country are you in?

Argentina. on Wednesday it was working perfectly fine =(

**Comment by matthuisman** [comment]
i cant reproduce the error sorry.
I vpn to Argentina, and tried playing the same content as your log and played fine

**Comment by jjplano** [comment]
> i cant reproduce the error sorry. I vpn to Argentina, and tried playing the same content as your log and played fine
> 
> Id suggest you try the same content on their website / app and see if it plays

it's really strange, but it's now fixed. I received the error on every content in the addon, but worked ok on the Android app. I logged in the website, and it worked ok there. I tried the addon again and now it works. 

thanks for the help!
