### ISSUE TITLE
Channel Australia nine missing from freeview

### ISSUE THREAD

**Issue by caitotheonlypotato** [matthuisman/slyguy.addons#841]
Hi.

Channel nine seems to have disappeared from the m3u8 files located as per below

https://i.mjh.nz/au/Brisbane/tvh-tv.m3u8

I also tried Sydney. and the kodi-tv.m3u8 variants
Not sure if this is the correct place to report it.  Apologies if not.

I'm using TVheadend through Kodi,  All other FTA AU stations work perfectly

EDIT:
EPGs still show Channel 9

Cheers
Greg

**Comment by matthuisman** [comment]
https://github.com/matthuisman/i.mjh.nz/issues/116
