### ISSUE TITLE
No IMAX Picture

### ISSUE THREAD

**Issue by xMisterW** [matthuisman/slyguy.addons#842]
Hello,

I have the Same setting the Last Time Video is working but now i don't get the füll IMAX Picture ratio

**Comment by matthuisman** [comment]
What addon ?

**Comment by xMisterW** [comment]
The Disney+ Addon with the IMAX Enhanced Titles

**Comment by matthuisman** [comment]
fixed with [slyguy.disney.plus -> v0.17.1](https://github.com/matthuisman/slyguy.addons/commit/1328d5129fefcfa30664f3f3038c9bde06a31216)
