### ISSUE TITLE
SlyGuy Common shows me a crash popup most mornings

### ISSUE THREAD

**Issue by backyard-bbq** [matthuisman/slyguy.addons#844]
I am not sure if this is related to my setup or if there is an issue in SlyGuy Common. I am running SlyGuy Common 0.84.64 and I use IPTV Merge. The last couple of days when I turn on the TV in the morning I am greeted with a popup that says SlyGuy common has crashed and there should be a fix soon. I also notice my Weather says it is 4000F. In the paste below, you can see that SlyGuy gives me an error and then latter I get an error with the weather plugin and then a bit later I get a different error from SlyGuy common.

https://pastebin.com/ieRWEMyk

**Comment by matthuisman** [comment]
seems an issue with charset_normalizer in python 3.12..
```
                                                     File "/home/alarm/pythonlibs/env/lib/python3.12/site-packages/charset_normalizer/api.py", line 5, in <m>
                                                       from .cd import (
                                                     File "/home/alarm/pythonlibs/env/lib/python3.12/site-packages/charset_normalizer/cd.py", line 14, in <m>
                                                       from .md import is_suspiciously_successive_range
                                                   SystemError: initialization of md__mypyc did not return an extension module
```

**Comment by backyard-bbq** [comment]
I had my distro's (arch linux) charset_normalizer and the pip version installed. I removed the pip version and I haven't had any issues. Thanks for pointing me in the right direction.

**Comment by matthuisman** [comment]
great to hear :) thanks for reporting back
