### ISSUE TITLE
Pluto TV

### ISSUE THREAD

**Issue by 22marco77** [matthuisman/slyguy.addons#85]
would it be possible to insert the channels in Italian? Italy is missing from the list of nations. I would be very grateful if it was inserted. THANK YOU

**Comment by matthuisman** [comment]
done

**Comment by 22marco77** [comment]
Sorry

Il mer 3 nov 2021, 20:55 Matt Huisman ***@***.***> ha scritto:

**Comment by matthuisman** [comment]
sorry for what?

**Comment by 22marco77** [comment]
For that.

Il mer 3 nov 2021, 20:55 Matt Huisman ***@***.***> ha scritto:

**Comment by matthuisman** [comment]
no need to apologise. i was happy to add it.
Enjoy!

**Comment by 22marco77** [comment]
Thank you very much. Greetings from Rome Italy

Il mer 3 nov 2021, 22:16 Matt Huisman ***@***.***> ha scritto:
