### ISSUE TITLE
The H265/HEVC option is ignored in the Max addon

### ISSUE THREAD

**Issue by Paco8** [matthuisman/slyguy.addons#850]
I disabled the H265/HEVC option in the Max settings, but this option seems to be ignored as there are still HEVC video streams. Unfortunately, my Android box doesn't support this codec. To make matters worse, a HEVC stream is selected by default, causing the playback to freeze.

![Captura desde 2024-08-16 14-36-16](https://github.com/user-attachments/assets/c9f6d1a0-d3b7-48d4-b8a5-808629007c66)

![Captura desde 2024-08-16 14-37-06](https://github.com/user-attachments/assets/efbb0ace-fa5a-488d-8551-d37942157ac8)

**Comment by matthuisman** [comment]
what is your quality select option set to? id need to confirm, but pretty sure if thats Disabled / Skip - then the manifest is passed non-altered to inputstream adaptive

**Comment by matthuisman** [comment]
i may need to see if i can still make them work with quality mode set to disabled :)

**Comment by Paco8** [comment]
Quality mode is bypass.

**Comment by matthuisman** [comment]
yup, thatll be it

**Comment by matthuisman** [comment]
[script.module.slyguy -> v0.85.7](https://github.com/matthuisman/slyguy.addons/commit/29c487bff71f30c77d3e473be5822a8d8b19781e) will make the h265 setting work with quality set to bypass now

Itll remove the streams it detects as not compatible as long as there is at least 1 compatible

**Comment by Paco8** [comment]
I did a quick test on Linux. It seems to work fine with Kodi 19, it shows all available h264 streams, but on Kodi 21 it only displays one. If I enable hevc then it shows two streams (one h264 and one hevc). I don't know if this is the intended behavior.

Kodi 19:
![Captura desde 2024-08-19 22-38-34](https://github.com/user-attachments/assets/925aee18-0ca6-4731-9f86-972c7ee7db77)

Kodi 21:
![Captura desde 2024-08-19 22-40-09](https://github.com/user-attachments/assets/5f208058-b210-4f17-9392-08f2fa29d8db)

This is with quality mode set to bypass.

**Comment by matthuisman** [comment]
on kodi 21, do you have different settings maybe?
Check the max width / height / ignore display resolution?
eg. If ignore display resolution is disabled, itll limit quality to the screen size

**Comment by matthuisman** [comment]
ill see if i can reproduce. there shouldnt be any difference in behaviour between 19 and 21.
Unless its inputstream adaptive quality select has issues on 21?
It may be an IA setting or something

if you change IA to "manual OSD" - and then try change via OSD, are all the qualities there?

**Comment by Paco8** [comment]
You're right, my bad. Inputstream adaptive was set to fixed resolution. After changing it to manual OSD now all video streams are shown in the list.

**Comment by matthuisman** [comment]
Excellent :) 
I will close this issue
