### ISSUE TITLE
4K is playing as HD on Disney plus

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#851]
Hi again. All 4k UHD content (not HDR or Dolby vision, just standard 4k) is playing as HD on Disney plus. I've checked that h265 is enabled and the quality is set for best etc If I choose to ask which quality I want on these 4K streams, the best that it will go up to is again 1080p HD. I don't think there's any issue with input stream adaptive, as 4K non HDR content on other add-ons such as paramount plus or playing fine. Thanks very much.

**Comment by matthuisman** [comment]
It sounds like you may have L1 device?
What is your device?

When you ask for quality, can you scroll to bottom of available qualities and then see the 4k in red or yellow?

**Comment by matthuisman** [comment]
And your Disney+ subscription has 4k? I think there basic one doesn't now?

**Comment by gmjh123** [comment]
> And your Disney+ subscription has 4k? I think there basic one doesn't now?

Disney basics still has 4K and Dolby vision. The device is an onn 4K Pro. It plays 4K and Dolby vision on the official app. It was playing 4k on your add-on up until about a week ago. The add-on still plays Dolby vision, but it streams all 4K UHD streams as HD

**Comment by matthuisman** [comment]
Is HDR enabled? I think there 4k streams may be HDR but also non HDR
compatible

**Comment by gmjh123** [comment]
HDR is enabled, but I don't think that's relevant. And as I said earlier,
all of these 4K UHD streams were working fine up until a few days ago. All
4K UHD streams are now streaming in HD. 4K HDR such as Dolby vision is
streaming as it should

**Comment by gmjh123** [comment]
If you want a couple of examples of what I'm talking about, The Bear or Fargo are both shows that should play in 4k UHD but are not HDR or Dolby vision

**Comment by matthuisman** [comment]
i just tried with HDR enabled and I get the 4K on The Bear.

**Comment by gmjh123** [comment]
Okay well I suppose the only thing I can try is a completely fresh install of Kodi. Thanks very much

**Comment by matthuisman** [comment]
no. just enable HDR and H265.
If thats enabled and still dont see, then scroll down to the bottom of qualities.
If the 4k is then in YELLOW - it means your limiting the resolution in settings.

**Comment by matthuisman** [comment]
oh hold on. i might know... let me check something

**Comment by gmjh123** [comment]
No sadly there's no other options other than HD. HDR and Dolby vision play
fine in the Disney add on, it's just that normal 4K won't. I tried enabling
HDR and disabling HDR in the Disney add-on setting, but it didn't make any
difference. This is so odd because it was playing normal 4K fine about a
week ago and I haven't changed anything.

**Comment by matthuisman** [comment]
also, your testing with Bear Season 3 right?
Season 1 is 1080 only it appears

**Comment by matthuisman** [comment]
no. please listen.
Disney+ only provides 4K with "HDR" but that HDR is backwards compatible with non-hdr displays.
So you must have HDR10 enabled in Disney+ addon settings for 4k

**Comment by matthuisman** [comment]
follow these EXACT instructions
1) Disney settings -> Enable HDR10 & Enable H265
2) Go the "The Bear" -> Season 3 and click Episode 1

What quality do you see?

**Comment by gmjh123** [comment]
I followed the instructions exactly, I'm still seeing only HD. One strange
thing I've noticed is that on the Disney add-on, Hulu isn't listed on the
list of hubs there. Might mean nothing of course but I'm still clueless 🥴

**Comment by matthuisman** [comment]
Toggling vpn with this addon won't work. it caches your token. I'd suggest
make sure vpn is off then logout and login again

**Comment by gmjh123** [comment]
Yeah I already knew that about the VPN. The VPN was turned off a long time
ago and I've logged in and out many times since. It might just be a quirk
of the onn 4K Pro when it gets mixed up about codecs and resolution etc
that I could probably only resolve by factory resetting the actual onn 4K
Pro box

**Comment by matthuisman** [comment]
I don't think that's it. My quality select and addon doesn't gather any
info from the device like that.  Did any of the non Hulu content show in
4k? Deadpool 2? Does it show 1080 h265 or h264? Does it say HDR? With Dolby
vision enabled you get all the 4k though? Hmmm

**Comment by gmjh123** [comment]
Deadpool 2 plays in Dolby vision as I expected it to, as everything on
Disney that should be Dolby Vision is Dolby vision. It's purely the Hulu 4K
UHD that just will not play in 4k, only HD.

I remembered there's a documentary on Disney that's in standard 4k UHD
called Billy and Molly. The Disney add-on plays it in standard 4K which
proves there's nothing wrong with my settings.  It's just all the Hulu
standard 4K stuff that it refuses to play 4K

**Comment by CoasterCoder** [comment]
Around when the new settings page launched is when this became an issue. I installed a clean install of kodi on a Fire TV 4K Stick Max. The newest Disney+ addon with the newest slyguy common, won't detect HEVC streams for Hulu 4K SDR content, it only shows H264 up to 1080p. Settings have H265 enabled and HDR10 enabled.

**Workaround**
I figured out that if I downgrade Disney+ version to v0.16.3 AND slyguy common to v0.84.63, Hulu content shows up in 4K H265 SDR. Then update Disney+ to v0.16.12 it still works.

Updating Disney+ to v0.17 or Slyguy Common to v0.84.64 and later breaks HEVC SDR from showing up in the list of streams.

This same issue also effects the Hulu addon. Downgrading Hulu addon to v0.3.1 with slyguy common v0.84.63 restores HEVC 4K SDR streams.

_Hulu TV shows in 4K SDR on Disney+_
Futurama Seasons 11 & 12
A Murder at the End of the World Season 1
Fargo Season 5

**Comment by matthuisman** [comment]
What settings in the older version of the addon get what you want? Also
what country please. If I can reproduce, I can fix :)

**Comment by CoasterCoder** [comment]
This is the United States. Well in the older version I have H265 On, and HDR10/DolbyVision off, I get H265 2160p SDR stream which it what I expect. In the current version with those settings I get H264 1080p with the same title. If I toggle HDR10 On its still in H264. It's something specific to Hulu titles on Disney+.

**Comment by gmjh123** [comment]
> Around when the new settings page launched is when this became an issue. I installed a clean install of kodi on a Fire TV 4K Stick Max. The newest Disney+ addon with the newest slyguy common, won't detect HEVC streams for Hulu 4K SDR content, it only shows H264 up to 1080p. Settings have H265 enabled and HDR10 enabled.
> 
> **Workaround** I figured out that if I downgrade Disney+ version to v0.16.3 AND slyguy common to v0.84.63, Hulu content shows up in 4K H265 SDR. Then update Disney+ to v0.16.12 it still works.
> 
> Updating Disney+ to v0.17 or Slyguy Common to v0.84.64 and later breaks HEVC SDR from showing up in the list of streams.
> 
> This same issue also effects the Hulu addon. Downgrading Hulu addon to v0.3.1 with slyguy common v0.84.63 restores HEVC 4K SDR streams.
> 
> _Hulu TV shows in 4K SDR on Disney+_ Futurama Seasons 11 & 12 A Murder at the End of the World Season 1 Fargo Season 5

Well I was beginning to think it was only me that suffered from this infuriating glitch. Thanks for sharing.

**Comment by matthuisman** [comment]
[slyguy.disney.plus -> v0.17.3](https://github.com/matthuisman/slyguy.addons/commit/c429714ee7933cb87fa76ef752ba0ec3900f1afa) should fix Disney+

[slyguy.hulu -> v0.4.3](https://github.com/matthuisman/slyguy.addons/commit/57dec075ca6d9488107e5770436f91c98523b0d9) should fix Hulu

Please test and report back

**Comment by gmjh123** [comment]
> [slyguy.disney.plus -> v0.17.3](https://github.com/matthuisman/slyguy.addons/commit/c429714ee7933cb87fa76ef752ba0ec3900f1afa) should fix Disney+
> 
> [slyguy.hulu -> v0.4.3](https://github.com/matthuisman/slyguy.addons/commit/57dec075ca6d9488107e5770436f91c98523b0d9) should fix Hulu
> 
> Please test and report back

Yes that fixed it. Thanks very much. Great work as always.

**Comment by CoasterCoder** [comment]
> [slyguy.disney.plus -> v0.17.3](https://github.com/matthuisman/slyguy.addons/commit/c429714ee7933cb87fa76ef752ba0ec3900f1afa) should fix Disney+
> 
> [slyguy.hulu -> v0.4.3](https://github.com/matthuisman/slyguy.addons/commit/57dec075ca6d9488107e5770436f91c98523b0d9) should fix Hulu
> 
> Please test and report back

Thanks for fixing this issue. :) All quality settings are working as expected.
