### ISSUE TITLE
Unable to find MattHuisman.nz Repository under SlyGuy repo

### ISSUE THREAD

**Issue by gszentesi** [matthuisman/slyguy.addons#855]
Hi,

I am trying to fix them HBO max on my Kodi. It started not to work about 4 or 6 months ago, I think the issue route cause is the change of url-s of hbo max services, since hbomax.com is just simply not exists, but max.com.

I found this description to fix it: https://www.matthuisman.nz/2024/06/max-kodi-add-on.html
I tried to follow it step-by-step, but I cannot find MattHuisman.nz Repository.
I have SlyGuy repo installed, but there is no MattHuisman repo under Install from repository.
I tried to reinstall SlyGuy without result.

Anybody could help please?

Thanks
G

**Comment by matthuisman** [comment]
oh, those instructions are slightly wrong.
the MAX addon is in slyguy repo

**Comment by matthuisman** [comment]
i have updated that page :)

**Comment by gszentesi** [comment]
Thanks, I cehck it now

**Comment by gszentesi** [comment]
Thank you very much @matthuisman , it is working again!
