### ISSUE TITLE
cffi error for new update 3c655b5

### ISSUE THREAD

**Issue by zndlf** [matthuisman/slyguy.addons#856]
I have a problem with the new version in commit 3c655b5d064ba67d758194fc325c97969a481851
I get an error `No module named '_cffi_backend'`
I am using ubuntu 24.04 with kodi installed from repositories (v. 20.2). The module cffi is installed.
I have downgraded to commit 675028c159a18577e9874477bd61ef50f5eca750 for slyguy.dependencies  and script.module.slyguy and it works again.

I attach the part of the log with more details on error
[kodi.log](https://github.com/user-attachments/files/16660503/kodi.log)

**Comment by matthuisman** [comment]
thanks. ive now remove pysql on latest [slyguy.dependencies -> v0.0.21](https://github.com/matthuisman/slyguy.addons/commit/c16eb5c03594c1ab8dbf5d70a355baa2d1afbc8e)
