### ISSUE TITLE
[Disney+ 0.17.3 / OSMC 2024.05-1] Black screen when playing a movie

### ISSUE THREAD

**Issue by ctuluxfr** [matthuisman/slyguy.addons#857]
Hello,
I installed the Disney+ addon on my OSMC install and sadly I can't play movies.
The audio plays on but there is no video, just a black screen.
I'm using a Raspberry Pi 3B+ with the latest version of OSMC, Slyguy Common, Repo, Dependencies, Disney+ and Widevine CDM installed
Could ypu please help me ?
Thanks in advance.
Sincerly,
Ctulux

**Comment by matthuisman** [comment]
Maybe turn off HDR in the settings?

**Comment by ctuluxfr** [comment]
I don't think my hardware is supporting HDR.
But disabling DRM PRIME seems to have solved the issue.
I'll test that on the long terme.
Thank you for your help !
