### ISSUE TITLE
7 plus and 9 now dropping stream after about 10 mins

### ISSUE THREAD

**Issue by wbpxre150** [matthuisman/slyguy.addons#859]
As title. When viewing channel 7 or 9 using the logged in add-ons the stream drops after about 10mins. Seems to be an issue with live tv only. Catchup shows are working fine. I have tried reinstalling kodi and your add-ons only and the problem is still occurring. Seems to be due to an update near the end of last month. 

Maybe it's got something to do with this issue? 
https://github.com/xbmc/inputstream.adaptive/issues/1619

**Comment by matthuisman** [comment]
what version of kodi

**Comment by wbpxre150** [comment]
Version 21 on android tv.

**Comment by matthuisman** [comment]
is it when adverts start?

**Comment by wbpxre150** [comment]
No. I just loaded channel 7 again, maybe it's just before the ads.

**Comment by matthuisman** [comment]
you dont have any network wide ad blocker?

**Comment by wbpxre150** [comment]
I did have a DNS adblocker but I disabled it. It's still dropping.

**Comment by matthuisman** [comment]
full kodi debug log please. make sure debug logging enabled and then create the issue and send me the log
https://kodi.wiki/view/Log_file/Easy

**Comment by wbpxre150** [comment]
[Uploading kodi.old.log…]()

**Comment by wbpxre150** [comment]
[kodi.old.log](https://github.com/user-attachments/files/16757439/kodi.old.log)

**Comment by wbpxre150** [comment]
Maybe you have already fixed this. I am watching channel 9. There are now sounds on the ads, and they freeze all the time,but the stream isn't dropping. I'll try channel 7 next and upload the log file if the stream drops.

**Comment by matthuisman** [comment]
just pushed [script.module.slyguy -> v0.85.14](https://github.com/matthuisman/slyguy.addons/commit/70f50b2de23129b12aef967e65076c86562ac6ff) that should solve those issues :) Let me know

**Comment by wbpxre150** [comment]
Not sure how to do the update, so I can't test this. Channel 7 still dropping

**Comment by matthuisman** [comment]
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by matthuisman** [comment]
want to make sure your on [0.85.16](https://github.com/matthuisman/slyguy.addons/commit/bc0e7533e552ccc79c8976ce30abf5d9827b362b) 

if still drops once on that, then new debug log

**Comment by wbpxre150** [comment]
Ok I'm on that version now. Running channel 7 with debug logging to test. Hopefully it's fixed

**Comment by wbpxre150** [comment]
Seems to be working again. However I think the quality dropped down. Is that supposed to happen?

**Comment by matthuisman** [comment]
Are you initially choosing a quality? And then it's changing during
playback?

**Comment by matthuisman** [comment]
Try going to inputstream adaptive settings and settings its mode to manual
osd. See if that stops it.

**Comment by wbpxre150** [comment]
That's fixed the quality and the stream didn't drop for over an hour now. So I think this is fixed.

**Comment by matthuisman** [comment]
please note:
[script.module.slyguy -> v0.85.31](https://github.com/matthuisman/slyguy.addons/commit/548c0cac418b84d06efeb1a94eacf5c8e5c7cd84) just pushed which re-introduces the shared session which was the cause of this original issue.

However, it has a few tweaks that should fix that.
1) sets keep alive on socket
2) will retry on closed socket

Please let me know if you start having this same issue again
