### ISSUE TITLE
ESPN: KeyError: ‘buckets’

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/slyguy.addons#86]
Version 0.2.2 - won’t launch Live on LibreELEC or Android 19.3. Image attached. 
![37994888-E963-4B9A-A8F5-1E2971B56360](https://user-images.githubusercontent.com/54520364/140616528-d51cac1d-7719-4d67-93f5-f2bd070f68c5.jpeg)

**Comment by matthuisman** [comment]
im testing this now and seems to be working fine... ?

**Comment by lionsnob** [comment]
Confirmed it’s working for me again. Sorry for wasting your time!

**Comment by matthuisman** [comment]
oh, its not wasting time at all.
there must have been something that caused it.

all I can think of no events on at the time.
Are you using ESPN+ or TV Provider login?

**Comment by lionsnob** [comment]
TV. It was during the peak of the college football day.
