### ISSUE TITLE
 module 'apsw' has no attribute 'sqlitelibversion'

### ISSUE THREAD

**Issue by zndlf** [matthuisman/slyguy.addons#860]
I am getting an error with new version:
slyguy.dependencies/resources/modules/playhouse/apsw_ext.py, line 35
`server_version = tuple(int(i) for i in apsw.sqlitelibversion().split('.'))`
gives an error AttributeError: module 'apsw' has no attribute 'sqlitelibversion'
For some reason, inside kodi that line is not working, but I do not know why
In a python3 shell I can do without problem
```
import apsw
server_version = tuple(int(i) for i in apsw.sqlitelibversion().split('.'))
```
which gives in my case the tuple (3,45,1)
Replacing in file slyguy.dependencies/resources/modules/playhouse/apsw_ext.py, line 35 by
`server_version = (3,45,1)`
solves in my case the problem, but no idea why it does not find apsw.sqlitelibverion

**Comment by matthuisman** [comment]
thanks for letting me know. i didnt up end using playhouse so have just pushed update to common to remove its import :)
