### ISSUE TITLE
Max add-on streams always freezing between 30-40 minutes of playback

### ISSUE THREAD

**Issue by toguraum** [matthuisman/slyguy.addons#863]
Hello, here is the log below, the freeze occurred on my stream at around the 19:50 mark in the log, though it may have lost connection around 19:42, I don't know how to interpret the log. It was a little over 30 minutes of playback, freezing like it always does. 

https://paste.kodi.tv/coquxoyase

Thank you!

**Comment by matthuisman** [comment]
maybe fixed with latest slyguy commons pushed tonight.
please update to [script.module.slyguy -> v0.85.16](https://github.com/matthuisman/slyguy.addons/commit/bc0e7533e552ccc79c8976ce30abf5d9827b362b) and try again and let me know

**Comment by toguraum** [comment]
Thank you so much, I just watched a 1:40min movie without any problems! Problem solved!!
