### ISSUE TITLE
script.globalsearch [Clear Search]

### ISSUE THREAD

**Issue by usphil** [matthuisman/slyguy.addons#864]
script.globalsearch does not have clear history searches feature. Can you add it?

**Comment by matthuisman** [comment]
sure can :) i also wanted way to have same "fav" searches that always at top etc.

A lot easier now as the searches now stored in DB

**Comment by matthuisman** [comment]
Clear History added to settings in [script.globalsearch -> v99.1.2](https://github.com/matthuisman/slyguy.addons/commit/79211113088d94a4fad86cc49a50f25bb4ffa66c)
