### ISSUE TITLE
playlists for SamsungTVPlus Channels doesn't work anymore

### ISSUE THREAD

**Issue by werimail** [matthuisman/slyguy.addons#866]
The playlists for SamsungTVPlus Channels can no longer be found. 
This applies to both: https://i.mjh.nz/SamsungTVPlus/all.m3u8 and https://jmp2.uk/SamsungTVPlus/all.m3u8

Greetings Weri

**Comment by matthuisman** [comment]
https://github.com/matthuisman/i.mjh.nz/issues/127
