### ISSUE TITLE
9PlayNow not working

### ISSUE THREAD

**Issue by thetroll288** [matthuisman/slyguy.addons#867]
Hey Matt,

I have used your addon for years to watch shows from Channel 9 in Australia but it has suddenly stopped working.  Is something up with it?  Thanks.

**Comment by matthuisman** [comment]
Very unhelpful issue. What isn't working specifically

**Comment by thetroll288** [comment]
Nothing.  It will not load the TV program.  All I get is a blank screen.

**Comment by matthuisman** [comment]
Be specific. So you can login? You can see different content? Do live
channels work? Does vod work? Are you physically in Australia?

**Comment by successtheman** [comment]
For Samsung TV plus I'm getting a "gzip.BadGzipFile" error and it says it's not a gzipped file. Could be related?

**Comment by matthuisman** [comment]
Not related. You need to update it though to fix that

**Comment by thetroll288** [comment]
I can watch 9Live but cannot access any of the On-Demand programs.

I can also watch Channel 10's on-demand programs.

Thanks.
