### ISSUE TITLE
Max content duration/timecode is wrong

### ISSUE THREAD

**Issue by pmsobrado** [matthuisman/slyguy.addons#870]
Hello, I'm currently using the Max addon in a Fire TV 4K Max with Kodi 19. When seeing some content, let's say an episode with 40 minutes duration, once it finishes, the episode just starts again, but there's no effect on the screen, is like it was part on the same video. If I look to the timecode, it shows like if I was in the middle of the video, 20 minutes. Trying to go back or foward makes the episode go crazy, sometimes I'm at the start, then about the end, then on the middle... If I watch the episode from beginning to end without going back and forth, I can see it normally, but it will play twice, like I mention.

Is this a known bug of some sort?

Thanks.

**Comment by matthuisman** [comment]
What version Kodi on what device?

**Comment by pmsobrado** [comment]
It's on my first sentence :(

**Comment by matthuisman** [comment]
Oh right. Pretty old Kodi. I'd suggest backing up and see if things are better in Kodi 21

**Comment by pmsobrado** [comment]
I have too many configs right now to switch but yeah, maybe that fixes it. I will try in the future. Thanks!

**Comment by matthuisman** [comment]
closing this for now. if you do test later kodis with newer inputstream adaptve and have same issue, let me know

**Comment by pmsobrado** [comment]
I'm afraid I don't have the time to migrate all my addons and custom configs to Kodi 20, but will post back when I try it.
