### ISSUE TITLE
Are max.com's bookmarks supposed to be "my stuff"?

### ISSUE THREAD

**Issue by xcarol** [matthuisman/slyguy.addons#871]
I am trying to access My Stuff in the Max add-on. I supposed it would be Bookmarks, but when I enter in Bookmarks nothing happens. If Bookmarks are not the same as My Stuff, how could I add a Bookmark from Mobile app to get it later at Kodi?
Thanks in advance.

**Comment by matthuisman** [comment]
They are not the same. Bookmarks are local only. There is an existing issue requesting watchlist for max so closing this as duplicate
