### ISSUE TITLE
[Disney Plus] "Add to Watchlist" context menu missing in search

### ISSUE THREAD

**Issue by Kampfader** [matthuisman/slyguy.addons#877]
this context menu is only missing if you are searching for titles. It doesn't matter if it's a movie or series."

**Comment by matthuisman** [comment]
that will be due to search using the new "Explore" api which I dont yet have watchlist support for

https://github.com/matthuisman/slyguy.addons/issues/763 is tracking migrating fully to that which will solve this issue
