### ISSUE TITLE
[Nebula] Passing to next page in list of videos doesn't show next page

### ISSUE THREAD

**Issue by jvsala** [matthuisman/slyguy.addons#878]
I have a very strange problem with the latest 0.3.1 version. When I am in a list of videos (be it 'My videos' or any other) and I select to go to the next page it shows me the exact same list of videos. It was like it hadn't passed the page. But it seems that it registers as it has passed because if I pass page 2 times I need to get back 2 times to go back to the menu. So, it is doing something. Just it doesn't show what it should.

Another strange thing I noticed. If the list isn't large enough to expand beyond two pages, I get correctly the 2nd page. It shows all the videos correctly when I go to next page. So, it seems to only happen when at least you have 2 full pages and there is a third.

I am using it with Kodi 21 under Android. Recently updated to Kodi 21.1 with no change in the problem.

**Comment by matthuisman** [comment]
thank you :) 
appears a few things are changing with their api

[slyguy.nebula -> v0.3.2](https://github.com/matthuisman/slyguy.addons/commit/9da0c5b9e204a74ac144792ec37dcc74327a5b39)
should sort it out
