### ISSUE TITLE
channel 9 no sound

### ISSUE THREAD

**Issue by wbpxre150** [matthuisman/slyguy.addons#879]
Channel 9 using 9now plugin does not have sound. Will post debug.log shortly.

**Comment by wbpxre150** [comment]
[kodi.log.txt](https://github.com/user-attachments/files/16795944/kodi.log.txt)
Sound doesn't start straight away with video then it fast forwards for a while, then starts working properly.

**Comment by matthuisman** [comment]
Oh, that will be out of my hands unfortunately. Be a Kodi or inputstream
adaptive "quirk" I suspect

**Comment by matthuisman** [comment]
you could try turn off "inputstream for HLS" in the addon settings -> player -> advanced.
That will make Kodi use its ffmpeg for playback which may work better :)

**Comment by wbpxre150** [comment]
Doing that stops it from playing all together.
