### ISSUE TITLE
KODI crash after playing video

### ISSUE THREAD

**Issue by diegoflyer** [matthuisman/slyguy.addons#88]
Dear,
I don't remember any modification connected with this issue that started 1 week ago more or less.
After playing any video on Disney+ Kodi crash and reboot, is there any known reason?
Thanks!

**Comment by matthuisman** [comment]
Full debug log

**Comment by diegoflyer** [comment]
ATTACHED THE DEBUG, it happens the same when I try to start a video from the previous point where I left...

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/7575395/kodi.log)
[kodi_crashlog_20211120223527.log](https://github.com/matthuisman/slyguy.addons/files/7575396/kodi_crashlog_20211120223527.log)

**Comment by matthuisman** [comment]
there is an open issue for this here:
https://github.com/xbmc/inputstream.adaptive/issues/783

I'll close this issue and carry on there
