### ISSUE TITLE
7Plus / Disney+ buffers when using proxy

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/slyguy.addons#884]
https://forum.kodi.tv/showthread.php?tid=361207&pid=3209526#pid3209526

shield 2015 on Android 9

Python Version: 3.11.7 (main, Aug 17 2024, 07:19:42) [Clang 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0

With proxy
https://paste.kodi.tv/opojotebot
Constant buffering, cache drops from 100% to 0 within seconds.

No proxy
https://paste.kodi.tv/yulewezeca
No buffering, cache 99-100%, Quality 720p.

**Comment by matthuisman** [comment]
to the user questions

Has this always been the case or started recently?
Or are you a new user?

**Comment by Arkadia2008** [comment]
No buffering on a system I haven't updated over the last 2 months with Proxy on, still running SlyGuy Common 0.83.7 and 7Plus 0.3.7.

Seems to have started about the time you migrated the settings to SlyGuy Common.

I'm an experienced user (since 2009) but not a developer.

Same buffering issue with 9Now

**Comment by matthuisman** [comment]
disney+ as well for this user:
https://forum.kodi.tv/showthread.php?tid=353316&pid=3209441#pid3209441

**Comment by matthuisman** [comment]
@Arkadia2008 we will need to do some back and forth to find where the issue was introduced.

Please test this 0.99.1
[script.module.slyguy-0.99.1.zip](https://github.com/user-attachments/files/17009887/script.module.slyguy-0.99.1.zip)
that reverts proxy.py only back to commit d22805f73eec2bd40c9c2af8f4c958a9824599d6 but rest is latest common.

Im suspecting that should be OK

**Comment by matthuisman** [comment]
also, you say "cache 99-100%"  - where do you view this amount?

**Comment by Arkadia2008** [comment]
Same buffering on Shield 2019 with 0.99.1 installed and proxy on.

Arctic Zephyr Reloaded skin has a player cache info bar.

[[](url)](https://paste.kodi.tv/cixilojike)

**Comment by Arkadia2008** [comment]
Not sure, if this has anything to do with the issue, but I'm outside Australia with Smart DNS set up on my Android devices.
If I use the SlyGuy Common Network settings to configure my Smart DNS Server, the buffering stops.

I was using Smart URL Action, but the 7Plus userdata folder is still missing.

**Comment by matthuisman** [comment]
thank you for testing :)
Ill get another version for you to try later today.

Your smart dns point me to a change in the session object when dealing with the default dns resolver

**Comment by matthuisman** [comment]
ok, new version to try 0.99.2
[script.module.slyguy-0.99.2.zip](https://github.com/user-attachments/files/17026685/script.module.slyguy-0.99.2.zip)

this brings proxy.py back to head but reverts session.py back before the big dns changes that came in with new settings

Please test with 7plus and 9now without using DNS setting etc (same conditions that causes buffering)

**Comment by matthuisman** [comment]
hmmm. your device that still works, is that running the same version of Kodi and more importantly inputstream.adaptive addon?
Maybe its that and not slyguy code?

**Comment by Arkadia2008** [comment]
No buffering and strange behavior on Kodi 21.0 still running InputStream Adaptive 21.4.10 and script.module.slyguy 0.83.7.

Is this a Kodi 21.1/InputStream Adaptive issue?

To make sure, this is not a Maven Kodi Build problem, I installed "native" Kodi 21.1 on Shield 2019, same buffering with Proxy on and standard settings.
Without Supporter ID and Proxy on, resolution was limited to 320x180.

No buffering and HD with Proxy off.

There is no 7Plus userdata folder on new Kodi installations to add a text file for Smart URL Actions.

By the way, no buffering on Disney+ with Kodi 21.1, all updates installed and Proxy on.

**Comment by matthuisman** [comment]
The one that works doesn't have a smart urls file right? You have to
compare the same conditions (both without any smart urls)

**Comment by matthuisman** [comment]
Probably easier if you just get me a debug log from the working device

**Comment by Arkadia2008** [comment]
I tried to, but all of a sudden all SlyGuy add-ons are no longer working with InputStream Adaptive 21.4.10 and script.module.slyguy 0.83.7.

Every time I try to start playback Kodi is crashing.

This is on a Windows 11 System not Android, no Smart URL Action text file.

Add-ons were working fine only a few days ago, I didn't change or update anything.

I'm not one to give up easily, but I'm about to, never had anything like this in all those years.

**Comment by matthuisman** [comment]
hmm, odd. maybe we need to slowdown and start keeping track of things better.

Do you still have the device that is working (not buffering)
Can you get a log from that?
I just want to see the versions of everything that its running

Inputstream adaptive is a binary addon. So only the correct arch and correct kodi major version will run correctly.
21.4.10 IA will only run on Kodi 21. Also need to make sure your using the 64bit version etc etc

**Comment by matthuisman** [comment]
I am uploading the older versions here to make easier to test:
[script.module.slyguy-0.83.7.zip](https://github.com/user-attachments/files/17093820/script.module.slyguy-0.83.7.zip)
[slyguy.7plus-0.3.7.zip](https://github.com/user-attachments/files/17093829/slyguy.7plus-0.3.7.zip)

**Comment by Arkadia2008** [comment]
Too late, already updated, but kept a debug log.

[kodi.log](https://github.com/user-attachments/files/17095201/kodi.log)

Good news is that Kodi is no longer crashing, bad news same buffering issues with 7Plus.

Buffering stops with Proxy off.

No Smart URL Action text file added, 7Plus userdata folder still exists, only seems to be deleted on Android Systems.

I will do some testing later.

**Comment by matthuisman** [comment]
@Arkadia2008 i managed to build a 21.4.10 of IA and have uploaded above.
That should be everything you need to test :)

Be interested in hearing if the latest of all slyguy work OK with older IA etc etc

Thanks for your continued effort to help me debug this

**Comment by Arkadia2008** [comment]
No buffering on Windows with script.module.slyguy-0.83.7, slyguy.7plus-0.3.7 and IA 21.5.4.

[](url)https://paste.kodi.tv/ruyujizewe

More tests the day after tomorrow.

**Comment by Arkadia2008** [comment]
Same buffering with latest SlyGuy Commen and old IA.

[](url)https://paste.kodi.tv/buqavokuli

**Comment by matthuisman** [comment]
thank you.
So does seem its common.
Please keep everything as newest and we can just change common versions

The below has old proxy.py and old session.py
[script.module.slyguy-0.99.3.zip](https://github.com/user-attachments/files/17156336/script.module.slyguy-0.99.3.zip)

**Comment by Arkadia2008** [comment]
Right now 7Plus seems to be blocked, I tried with dns4me and Smart DNS Proxy, will resume testing when it's working again.

**Comment by matthuisman** [comment]
question, when your not using the smart urls, how have you got your smart dns setup?
network wide or some sort of app on the computer?

**Comment by Arkadia2008** [comment]
Smart dns is configured on my devices, for some services I use Smart URL Action to redirect to a second smart dns provider I subscribe to, but not for 7Plus.

**Comment by Arkadia2008** [comment]
Good news, no buffering with script.module.slyguy-0.99.3.

[](url)https://paste.kodi.tv/taduvepohe

**Comment by matthuisman** [comment]
ok great :) we have a good starting point to now see what changes in those caused it :)

**Comment by matthuisman** [comment]
script.module.slyguy-0.99.4
  - add a few more master changes from proxy that seem "safe"
  - suspect this should work fine
[script.module.slyguy-0.99.4.zip](https://github.com/user-attachments/files/17240900/script.module.slyguy-0.99.4.zip)

**Comment by Arkadia2008** [comment]
0.99.4 works fine but buffering is back with latest zip.

script.module.slyguy-0.99.4

[](url)https://paste.kodi.tv/furilubapi

script.module.slyguy-0.99.5

[](url)https://paste.kodi.tv/upuragoxif

**Comment by matthuisman** [comment]
Buffering on 0.85.29?
What about on 0.99.5 above?

**Comment by matthuisman** [comment]
Also to save time, don't worry about providing the logs. Just a yes/no for buffering or not will do now :)

**Comment by Arkadia2008** [comment]
0.99.5
Proxy on buffering
Proxy off no buffering 

0.85.29
Proxy on buffering
Proxy off no buffering

All tested on Windows 11

**Comment by matthuisman** [comment]
Thanks. There wasn't many changes between 94 and 95 so I'll get a few more versions in between to narrow it down

**Comment by matthuisman** [comment]
0.99.6
Should still buffer.
But i have included more debug lines so if you could get a debug log with this one please :)
[script.module.slyguy-0.99.6.zip](https://github.com/user-attachments/files/17275498/script.module.slyguy-0.99.6.zip)

**Comment by matthuisman** [comment]
also, please test REPO version [script.module.slyguy -> v0.85.31](https://github.com/matthuisman/slyguy.addons/commit/548c0cac418b84d06efeb1a94eacf5c8e5c7cd84)

This reverts back to using a shared session :)
I suspect that may work for you (hopefully)

**Comment by Arkadia2008** [comment]
Success, v0.85.31 seems to be working again on Windows and Android, no more buffering with SlyGuy Proxy on.

Do you still want me to test v0.99.6?

**Comment by matthuisman** [comment]
Thats great news 😊 
No need to t st 0.99.6.

I would be interested in seeing your debug log for 0.85.31 just out of curiosity if possible

**Comment by Arkadia2008** [comment]
0.99.6 was still buffering.
[](url)https://paste.kodi.tv/ukizuzocah

0.85.32 works fine.
[](url)https://paste.kodi.tv/utohozuwih

One small thing, the 7Plus userdata folder is still missing on new Kodi installations.

Thank you for the time and effort you put into the development and maintenance of your addons.

**Comment by matthuisman** [comment]
thanks. so its the socket connection time that was the issue.
Taking about 0.9 to 1.2secs every request (search for Connect took)
By going back to the old way of re-using session - it only does that once for domain
Result is each download takes about 1sec shorter with the new version

Thank you for persisting with me.
I was under the impression the performance impact would have been minimal but i guess different connections / services plays a role.

Regarding the userdata folder, thats probably correct. 
As there is no settings.xml anymore - there is no reason to create it.
However, for using urls.txt it is required.
I guess I could always create it, but then for most it would just sit there empty.
Needs some thought :)
