### ISSUE TITLE
Running Setup IPTV Merge from Slyguy's Pluto TV ver 0.7.2 doesn't work

### ISSUE THREAD

**Issue by mstrauss2018** [matthuisman/slyguy.addons#885]
After running Setup IPTV Merge, if I go to the IPTV Merge addon and open EPG, it's blank and if I go to PLaylists it does show Pluto TV but the font is red and if I highlight it, to the left it show Errno 2

[Errno 2] No such file or directory.
Then it give a local path on my computer. E:\\Kodi\\portable_data\\userdata\\profiles\Movies & TV Shows\\addon_data\\plugin.program.iptv.merge (I cant read the rest of it). This folder has 5 files in it. 1 of them is epg.xml and another is playlist.m3u8. I switched to file and pointed it to the playlist.m3u8 and still got the same error.

I tried troubleshooting with matthuisman and he recommeded that I open a new case here.

Logefiles are located here: https://paste.kodi.tv/unazoxujeh

Thanks for the assist

Mike

**Comment by matthuisman** [comment]
@mstrauss2018 could you please turn on kodis debug logging and then re-create the log for me https://kodi.wiki/view/Log_file/Easy
That will give a lot more output

**Comment by matthuisman** [comment]
oh, I can reproduce by using a profile name the same as yours (I never used profiles before)
Ill investigate

**Comment by matthuisman** [comment]
ok, it was the & in the folder name that was causing issues.

Have just pushed [plugin.program.iptv.merge -> v0.27.2](https://github.com/matthuisman/slyguy.addons/commit/14415f3f663520627e399136cff646b11ddfb917) which will fix that and should fix all your issues :)

Enjoy!

**Comment by mstrauss2018** [comment]
Thanks Matt and I'm not surprised by the cause. I always seem to stumble on weird programming bugs.

Thanks for the fix, but my deep knowledge of kodi and it's addons is minimal at best. How do I apply the fix?

**Comment by matthuisman** [comment]
the addon should auto update
otherwise see here: https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by mstrauss2018** [comment]
Thanks, I followed all the procedures and in the last one (versions), it said updated.
I deleted the playlist then re-added from addon and it is no longer broken.
I went to EPG and clicked Add EPG - Add-on but it says "No compatible add-ons found. Make sure the add-on is installed and enabled"
i checked the TV guide and though Pluto TV is listed, it says empty playlist.

**Comment by matthuisman** [comment]
dont worry about EPG. 
EPG is automatically done via the Pluto addon playlist entry

probably best to just start from scratch at this point.
You shouldnt need to touch anything else playlist related.

Simply Pluto tv -> Pvr -> setup iptv merge

Maybe try Kodi setings -> pvr -> clear data

**Comment by mstrauss2018** [comment]
Dude, there it is. Thanks

Did
Simply Pluto tv -> Pvr -> setup iptv merge

Maybe try Kodi setings -> pvr -> clear data

**Comment by matthuisman** [comment]
no worries :)
Enjoy
