### ISSUE TITLE
9Now - Brightcove access denied

### ISSUE THREAD

**Issue by grapenose** [matthuisman/slyguy.addons#886]
Not able to play media. Getting message Could not find media source from Brightcove. Access _Denied.
Have just installed this to watch a particular show. Went through comments in Whirlpool but nothing.
Tried Sony Bravia and Amazon Cube, both the same

**Comment by matthuisman** [comment]
are you physically in australia? can you play the same content OK on the 9now website?
If not - then its because they are geoblocking you

**Comment by grapenose** [comment]
Yes in Australia and I can play content on 9now using a windows PC.

**Comment by matthuisman** [comment]
are you [geoff2011](https://forums.whirlpool.net.au/user/408616) ?

**Comment by matthuisman** [comment]
also, it should give you an output like this:
Server Message: {'client_geo': 'nz', 'error_subcode': 'CLIENT_GEO', 'error_code': 'ACCESS_DENIED', 'message': 'Access to this resource is forbidden by access policy.'}

What does your say?
Are you running the latest version of the 9now addon?

**Comment by grapenose** [comment]
I'm getting the above message.
Running the latest version of 9now

**Comment by grapenose** [comment]
I'm geoff2011

**Comment by matthuisman** [comment]
you get the same error as me - saying client_geo is NZ?
How are you using your smart dns in Kodi?

**Comment by grapenose** [comment]
Sorry I did not check the client its geo "gb" on both Amazon Cube and Sony Bravia, I assume this is Great Britain
My DNS does not have 9now ticked but I do have U (UKTV ) ticked. For my DNS there is a potential conflict with these two. Will Try to untick U and see if this makes a difference.
Yep that worked. I now have access to 9 Now.
So not the app but my DNS. Will contact them.
Thanks for your help

**Comment by matthuisman** [comment]
great :)
Yes, the brightcove url endpoint is shared by multiple services unfortunately
