### ISSUE TITLE
Can't login to HBO MAX, wrong password

### ISSUE THREAD

**Issue by jachym** [matthuisman/slyguy.addons#888]
Many thanks for this addons repository.

I've tested the HBO Max service, but can't login. The message I get is: 

```
API Request failed
Server error: The email address or password is incorrect.
Please try again.
```

This seems most unlikely, since I've tested it several times on more devices and the password and e-mail do match. Version I use is 0.12.0 - so I hope pretty up-to-date.

Any hint?

**Comment by matthuisman** [comment]
Are you using the correct addon? There is a new Max addon that replaced HBO
max in most countries
