### ISSUE TITLE
Request for Max User Login Support

### ISSUE THREAD

**Issue by dmbina** [matthuisman/slyguy.addons#889]
Hey @matthuisman,

First, thank you so much for developing the MAX add-on. Second, this is more of a question than an issue. The add-on has only two login options (device and TV provider). Is it possible to add another option to log in with our credentials (username and password)? I am more interested in how your api.py will look like if you add a function to login with creds. I think the function might look like that:

    def user_login(self):
        payload = {"credentials":{"username":"<USERNAME>","password":"<PASSWORD>"}}
        resp = self._session.post(self._endpoint('/login'), json=payload) #endpoint = https://default.any-<homeMarket>.<env>.<domain>/login
        if resp.status_code == 204:
            return False
        elif resp.status_code != 200:
            raise APIError(_.USER_LOGIN_ERROR)

        data = resp.json()
        self._login(data)
        return True

I just don't know what other headers and payload parameters are needed to make a successful POST request. Can you help? Again, it is not an enhancement request; I just want to create a python script that allows me to login with my MAX user account.

**Comment by matthuisman** [comment]
Likely not possible. Often username password require captcha / JavaScript
stuff

**Comment by dmbina** [comment]
Yes, I used Postman to make the POST login request and I received an error
message stating that arkose is required. I deduced that I had to solve the
Arkose Labs captcha. I found a way to solve the captcha and add the arkose
token to the header. Now, I got a different error message saying that hmac
is required.

What’s the POST request like from the Android TV where you capture the API
calls?

**Comment by matthuisman** [comment]
You can see that by looking at the current addon source. No hmac was
require

**Comment by dmbina** [comment]
Yes, exactly. So thats why I asked you to try to login using an
email address and password from the Max app on the Android TV and tell me
what you see in the login request (mainly the headers and payload).

**Comment by matthuisman** [comment]
I don't have it setup. Why not look at the website flow?

**Comment by dmbina** [comment]
Yes, that’s exactly what I was doing. I didn’t see any request headers
related to hmac.

**Comment by matthuisman** [comment]
hope this helps:
![image](https://github.com/user-attachments/assets/21a83e71-774c-4c90-81ec-e039895feb9b)
