### ISSUE TITLE
"Playback failed" on all udemy videos

### ISSUE THREAD

**Issue by mekler22** [matthuisman/slyguy.addons#891]
Using Kodi 19.5 (kd player version), and it fails to play videos in any resolution under udemy addon, after logging in correctly.

**Comment by matthuisman** [comment]
please provide full kodi debug log

**Comment by mekler22** [comment]
[kodi.log](https://github.com/user-attachments/files/17272288/kodi.log)

**Comment by matthuisman** [comment]
thanks. fixed now in [script.module.slyguy -> v0.85.30](https://github.com/matthuisman/slyguy.addons/commit/e74bac65b1941f87798a5b19d9c7dd59c2121a24)
