### ISSUE TITLE
[feature req] Use custom EPG for addons

### ISSUE THREAD

**Issue by enerdude** [matthuisman/slyguy.addons#893]
Hi in my case I am talking specifically about the dstv now addon.
The EPG for the addon has had some missing EPG info for some channels for a while now.
I have found a site like https://www.bevy.be/crazy-epg-web/ where I can choose my own channels and change the channel ids to match the dstv now addon playlist.

However, when using iptv-merge it seems to ignore my added epg and still does not show EPG info for example M-net movies 3 (chan id MCH) which is in my added EPG.

Maybe add a setting for custom EPG to the settings of the addon and then iptv-merge can check for this setting?

Thanks in advance

**Comment by matthuisman** [comment]
How will it link your epg channels to it's own? I can add a setting to
disable using the epg provided by the plugin source. But you'd need to
figure out how to link them

**Comment by matthuisman** [comment]
but yes, ill try add a new setting tonight in the source to ignore internal epgs :)
You can then add your EPG under EPGs and wont have to compete with the one linked internally

**Comment by matthuisman** [comment]
PS: why does your username seem so familiar
Oh - Kodi forums: https://forum.kodi.tv/search.php?action=results&sid=bf1a326c17b8eac660f27a05fe909b93

**Comment by enerdude** [comment]
> but yes, ill try add a new setting tonight in the source to ignore internal epgs :) You can then add your EPG under EPGs and wont have to compete with the one linked internally

Thanks. Would be nice if one could set it to combination of both too, e.g. channels not found in the internal EPG will be taken from the added EPG (provided obviously the channel ids match) but guess this would need a change in iptv simple client. And at the same time the EPG higher up in the list gets priority if the same channel exits in both the internal and added EPG

**Comment by enerdude** [comment]
Here is a sample xml I downloaded today.  Included is some of the missing channels as well as a few that overlaps with the internal EPG.
Let me know if you need a current one then I can send one with updated time data inside
[dstvbevy.zip](https://github.com/user-attachments/files/17286271/dstvbevy.zip)

**Comment by matthuisman** [comment]
that logic would be in iptv simple :)
But ill at least add the option to disable the internal epg as there is no way to do that

**Comment by matthuisman** [comment]
"Ignore playlist EPGs" setting adding to playlist config in [plugin.program.iptv.merge -> v0.27.3](https://github.com/matthuisman/slyguy.addons/commit/312562b2933b3a9475c3a90c41d9a0a57833f4a1)
