### ISSUE TITLE
[IPTV Merge] On Kodi 22.0 you lose all the TV data in the TV tab

### ISSUE THREAD

**Issue by goldengate2121** [matthuisman/slyguy.addons#895]
I have a Rpi5+ running gentoo. I installed Kodi 22 along with Simple IPTV, ISA, FFmpegdirect. 

I initially setup Simple IPTV to pull the guide from a local file for both epg and playlist. Everything works without issue. I then installed IPTV Merge. I set everything up and I set it to refresh every minute just for testing. I then let it sit for a few minutes and nothing happened. I then watched a channel and then on the next refresh I ended up with an error that said PVR guide data can't be loaded and then everything in the TV tab goes empty. 

I uninstalled IPTV Merge and the slyguy commons but this didn't fix the issue. I tried deleting the .kodi directory and then restarting with just Simple IPTV and using the original m3u and xml files but this didn't work. I then reinstalled Kodi and Simple IPTV and deleted the .kodi directory and rebuilt with just simple iptv and this works. I installed kodi.proxy and I use this for guide merge and this doesn't cause an issue. I'm thinking the issue could be with the m3u as I would try to reboot before I tried my other fixes and Kodi would crash when trying to view a channel.

I'm not sure if you started looking at Kodi 22 yet. I realize I am wading into the deep end with Kodi 22 Alpha so all is good. I just wanted to let you know.

**Comment by matthuisman** [comment]
what version IPTV Simple is that using?

I can see there was 22.2.2 released 11 hours ago that may fix the issue? 
https://github.com/kodi-pvr/pvr.iptvsimple/commit/914acb14ecd9abd97ce398628e3e2b27effbc61c

**Comment by phunkyfish** [comment]
> what version IPTV Simple is that using?
> 
> I can see there was 22.2.2 released 11 hours ago that may fix the issue? [kodi-pvr/pvr.iptvsimple@914acb1](https://github.com/kodi-pvr/pvr.iptvsimple/commit/914acb14ecd9abd97ce398628e3e2b27effbc61c)

Yes, fixed in 22.2.2 of iptvsimple.

**Comment by matthuisman** [comment]
The author replied and confirmed that 22.2.2 should fix your issue
