### ISSUE TITLE
Pluto TV: No EPG after addon update

### ISSUE THREAD

**Issue by mfreeman72** [matthuisman/slyguy.addons#896]
Since the update to your Pluto TV addon that came through on October 9th, I no longer have EPG data. Running a merge on IPTV Merge, the merge process shows that it is getting the playlist for all addons, but show that it gets the EPG data for all addons *except* Pluto TV. All Pluto TV channels show "No information available". It was working fine before the update, and I have made no changes, except that the addon was updated.

**Comment by matthuisman** [comment]
Problem with IPTV simple addon. See other GitHub issue

**Comment by matthuisman** [comment]
Oh. Also add Pluto tv as epg source in IPTV merge. Needs to be in playlist and epg now

**Comment by mfreeman72** [comment]
I just tried adding the addon as an EPG source. IPTV Merge process now shows it's trying to load the EPG for Pluto TV, but after the merge process is done and Kodi reloads the PVR data, it's still showing "No information available" on all Pluto TV channels.

**Comment by mfreeman72** [comment]
Nevermind. It's working now.
