### ISSUE TITLE
Error : URL not found

### ISSUE THREAD

**Issue by Mike2024-dot** [matthuisman/slyguy.addons#897]
Hi, 
Thanks for having such a great addon. We have been using the 7 plus, 9now and 10play now for while now and it has been working ok. However just in the last few days when trying to access each of the addon's it comes up with an error of : URL not found.
I did a reinstall of Slyguy to Kodie and it is still the same .
I have also another Kodie installed on a raspberry pie and it also comes up with the same error.
I live in Australia so shouldn't be a geo blocked issue as has been working perfectly ok up until a few days ago.
I tried with a VPN but still the same.
Also the other 2 addons from Aussie addons works perfectly for the ABCIVEW & SBS on demand, so think this is a Slyguy issue.
Any help would be appreciated thanks.

**Comment by Mike2024-dot** [comment]
Just guessing here but would it be a daylight saving issue or is it just coincidence. Hasn't worked since Monday since daylight saving came in the other states. I am in QLD.

**Comment by matthuisman** [comment]
Please provide a Kodi debug log showing the error

**Comment by Mike2024-dot** [comment]
Thanks Matt, took me ages to work out how to do this.
[kodi.log](https://github.com/user-attachments/files/17348885/kodi.log)

**Comment by matthuisman** [comment]
nothing of interest in that log. please enable Kodi debug logging and generate it again
https://kodi.wiki/view/Log_file/Easy

**Comment by matthuisman** [comment]
actually, i see your on Kodi 18
Your issue should be fixed with latest [script.module.slyguy -> v0.85.33](https://github.com/matthuisman/slyguy.addons/commit/bd378c9332e0f3c8617816b361fcec4cb8386190)

**Comment by Mike2024-dot** [comment]
ok thanks, all good now
