### ISSUE TITLE
Dstv now playlist / EPG discrepency on Channel 152 AfricaMagic Epic

### ISSUE THREAD

**Issue by enerdude** [matthuisman/slyguy.addons#898]
Hi Matt

Been speaking to [Tinuva](https://github.com/tinuva/) that generates the EPG for DSTV Now.  We had a few channels' EPG data missing which he very nicely fixed for us up to the point that only 1 channel misses EPG info as specified in subject of this issue - the tvg-id in your dstv now playlist is "35B"

Problem comes with the id in his EPG being IA9 (which has the correct EPG info) but does not match with your tvg-id so no EPG info shows up in IPTV simple client when merged.

The api url he uses for generating EPG info is 
`https://www.dstv.com/umbraco/api/TvGuide/GetChannels?country=zaf&unit=dstv`

Can you maybe throw any light on this issue as we cannot see dstv using two different ids on their system?

**Comment by matthuisman** [comment]
was this sorted?

**Comment by enerdude** [comment]
Not Yet

**Comment by matthuisman** [comment]
i checked and the epg row data i get for this channel is
![image](https://github.com/user-attachments/assets/acb5872e-af7c-4e2e-8898-7ac370a9690d)

"IA9" is not mentioned anywhere

Im happy to swap the IDs the playlist uses to the channel numbers if @tinuva wants to do the same?
Then they should all match

**Comment by tinuva** [comment]
So just to make sure I understand. The idea is to use the channel number as the channel id in the final xml?

eg. currently it is
```
<channel id="AME"><display-name>Africa Magic Showcase</display-name><icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/AME.png"/><url>https://dstv.com</url></channel>
<channel id="IA9"><display-name>Africa Magic Epic</display-name><icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/IA9.png"/><url>https://dstv.com</url></channel>
<channel id="AFM"><display-name>Africa Magic Family</display-name><icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/AFM.png"/><url>https://dstv.com</url></channel>
```

will become:
```
<channel id="151"><display-name>Africa Magic Showcase</display-name><icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/AME.png"/><url>https://dstv.com</url></channel>
<channel id="152"><display-name>Africa Magic Epic</display-name><icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/IA9.png"/><url>https://dstv.com</url></channel>
<channel id="154"><display-name>Africa Magic Family</display-name><icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/AFM.png"/><url>https://dstv.com</url></channel>
```

**Comment by enerdude** [comment]
> "IA9" is not mentioned anywhere
> 
> Im happy to swap the IDs the playlist uses to the channel numbers if @tinuva wants to do the same? Then they should all match

What url are you using

There is some discrepency cause on
https://www.dstv.com/umbraco/api/TvGuide/GetChannels?country=zaf&unit=dstv

you will see

<Channel1>
<ChannelDetail>Go big with the most epic Nollywood movies telling authentic stories that will speak to your soul.</ChannelDetail>
<ChannelGenre xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" i:nil="true"/>
<ChannelLogo i:nil="true"/>
<ChannelLogoDark>/media/kvhp4rti/africa_magic_epic_channel_logo_1500x1500_dark_backround.png</ChannelLogoDark>
<ChannelWebsiteLink/>
<DStvNowLink>https://now.dstv.com/livetv/play/9908da19-b506-44d5-92c6-64ab5ca05ae5</DStvNowLink>
<Genre i:nil="true"/>
<Logo>https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/IA9.png</Logo>
<Name>Africa Magic Epic</Name>
<Number>152</Number>
<Tag>IA9</Tag>
<ThumbnailImageUrl>https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/img/360832_The_throne_January_2021.jpg</ThumbnailImageUrl>
<VotingLink/>
</Channel1>

**Comment by enerdude** [comment]
The only id I can see that matches between the 2 sources is "9908da19-b506-44d5-92c6-64ab5ca05ae5"

**Comment by matthuisman** [comment]
I'm using an api that gives me the streaming urls as well. I won't be
changing that.

The channel number matches. Why not use that as the id is what I asked

**Comment by matthuisman** [comment]
@tinuva yes, exactly that :)

**Comment by enerdude** [comment]
I think in the meantime we should not worry about this 1 channel, we seem to have bigger issues as we can't seem to have stable EPG data downloaded for 3 days on a daily basis.  On any given day 1,2 or 3 days worth of data is downloaded, sometimes into the past or even into the future, which causes no EPG information in IPTV Simple Client.

**Comment by tinuva** [comment]
> @tinuva yes, exactly that :) We could add some common prefix list dstv-{chno} to stop any collisions with other epgs?

Can we use a format like this?
```
        <channel id="101.dstv_com">
                <display-name lang="en">M-Net HD</display-name>
                <icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/channel/HDT.png"/>
        </channel>
```

The reason for this idea is, I found another project that I think will work out better to generate the epg.
epg-grabber: https://github.com/tinuva/epg-grabber

Code base is cleaner and easier to maintain. Speaking of the complaint by @enerdude which I realised, is because of 1 or more bad backends on the dstv side, which responds with valid json format, with 0 channels in it. 
So because of that, I had to spend a lot more time to figure it out, and it turned out easier to debug with the python project for me personally.

If we use this format, I should actually be able to contribute my code back to that project after cleaning the parts up that run this as github workflows etc.

**Comment by matthuisman** [comment]
101.dstv_com looks fine to me :)
Ill implement that my side

**Comment by matthuisman** [comment]
@tinuva just pushed  [plugin.video.dstv.now -> v0.18.3](https://github.com/matthuisman/slyguy.addons/commit/e8cb650ec8aa87d4f572e9723529745c4ca9f2ba) that switches the addon to use the new style tvh-id

Please update your epg at https://tinuva.github.io/epg/guides/za/dstv.com.epg.xml to match

**Comment by tinuva** [comment]
Just checking, but looks like I still see the old channel ids on 0.18.3 here.

I also reset the iptv merge addon and then reconfigured it from the dstv addon. 

Is there something else I need to do, to see the change?

![PXL_20241220_103927291](https://github.com/user-attachments/assets/1c546ef6-29f0-4e24-8607-5863156185b1)

**Comment by enerdude** [comment]
> Just checking, but looks like I still see the old channel ids on 0.18.3 here.
> 
> I also reset the iptv merge addon and then reconfigured it from the dstv addon.
> 
> Is there something else I need to do, to see the change?
> 
> ![PXL_20241220_103927291](https://private-user-images.githubusercontent.com/5417682/397711829-1c546ef6-29f0-4e24-8607-5863156185b1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTYyMjUsIm5iZiI6MTczNDY5NTkyNSwicGF0aCI6Ii81NDE3NjgyLzM5NzcxMTgyOS0xYzU0NmVmNi0yOWYwLTRlMjQtODYwNy01ODYzMTU2MTg1YjEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMTE1ODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTlhOWIzYzZjMjkzZTYxMWU0MzBlNDY3NTcwNmNhOGVjMmVmZmQyNTYxYTQ4MzZiOTRhNDQ1ZmMyNDgzMzYwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.d85SUfMHGaEHFcWES-eWsAaHajsxhbMA_a-s-lIzbyk)

As far as I know that is the id used by the dstv api (same as the their tv guide ids) for playing a channel.  The change was done in the actual generated playlist that you can find on windows at
%appdata%\Kodi\userdata\addon_data\plugin.program.iptv.merge\playlist.m3u8
and on android at
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.program.iptv.merge/playlist.m3u8

BTW, where did you get that view that show the direct url, I usually get it from adding a channel to my favourites and then viewing the favourites.xml under the kodi userdata folder?

**Comment by matthuisman** [comment]
@tinuva
Its the "EPG ID" just below playlist id in your screenshot that should now show the 101.dstv_com etc.

@enerdude 
thats when you "manage tv" in IPTV merge -> DSTV
Itll show info about each channel in the description.

**Comment by enerdude** [comment]
> @tinuva Its the "EPG ID" just below playlist id in your screenshot

For interest sake, where is the "EPG ID" or playlist id in the screenshot, cause I see nothing in there.

**Comment by matthuisman** [comment]
Sorry, playlist (not playlist is)
The epg Id is below it (not shown)

**Comment by enerdude** [comment]
> Sorry, playlist (not playlist is) The epg Id is below it (not shown)

I guess you mean 'not playlist id'
I still don't see anything, below 'playlist' is 'plugin.video.dstv.now' and nothing else:

![image](https://github.com/user-attachments/assets/53a603e6-e321-47ca-99e1-c1de240f0258)

**Comment by matthuisman** [comment]
Maybe skin is cutting it off

**Comment by matthuisman** [comment]
Check you haven't set something like ignore epg ids in the DStv source. If
in doubt, remove that source and re-add

**Comment by enerdude** [comment]
Ok so its not really important, as I said before I checked the new ids in playlist.m3u8 but I'm just puzzled that yours is different from mine and @Tinuva's.

I have a fresh installation on windows as well as Android (using the default skin)  and on both it is absent.

**Comment by enerdude** [comment]
Ok must be some bug in kodi.  I was running Kodi in a window on windows.  When I switch to full screen via '\' and move up and down it starts appearing, then switching back to windowed mode via '\' and move up and down it disappears again.

Om my android setup (which can't really run windowed) it still does not appeared.  Pressing '\' on android just seam to change the font slightly but it stays fullscreen and obviously cut off at the bottom.

**Comment by chidozie447** [comment]
please what's the current IPTV link for dstv channels

**Comment by chidozie447** [comment]
please I need dstv IPTV url

**Comment by matthuisman** [comment]
There is none. You use the addon with a valid subscription

**Comment by chidozie447** [comment]
helo @tinuva  @matthuisman @enerdude @johnny5-is-alive

**Comment by matthuisman** [comment]
Your spamming so im blocking you
