### ISSUE TITLE
Disney plus missing playback settings

### ISSUE THREAD

**Issue by gmjh123** [matthuisman/slyguy.addons#899]
Hi. All Disney plus TV series, there is no option for 'mark as watched' or 'reset resume position'. Is this already known?

**Comment by matthuisman** [comment]
Those don't exist for plugins on a whole series.

Best we can do is have it on each episode.
Is it there on episodes?

**Comment by gmjh123** [comment]
Yes that's what I meant. It isn't there for any individual episodes.

**Comment by matthuisman** [comment]
Have you got Disney+ sync disabled?

**Comment by gmjh123** [comment]
Ah. So it looks like I have to have Disney sync disabled for these options
to appear?

**Comment by matthuisman** [comment]
yup, those options are provided for kodi so relate to kodis internal DB tracking status.
Did they show up when you disabled sync?

**Comment by gmjh123** [comment]
> yup, those options are provided for kodi so relate to kodis internal DB tracking status. Did they show up when you disabled sync?

Yes it works now. Thanks very much

**Comment by matthuisman** [comment]
will close this issue :)
