### ISSUE TITLE
M3U file not loading channels

### ISSUE THREAD

**Issue by Lelibell** [matthuisman/slyguy.addons#9]
Hi Slyguy,

Having issues getting IPTV merge to resolve channels from this .m3u playlist. Everything seems to be fine doing it from VLC desktop and i cant find any malformed EPG channel reference issues. For whatever reason the addon just doing like it.

My Test Playlist with Fixes: https://github.com/Lelibell/Greek-IPTV-Test/blob/main/ChannelsWithEPG.m3u

Originally forked from here: https://github.com/free-greek-iptv/greek-iptv/blob/master/android.m3u

**Comment by matthuisman** [comment]
whats the issue? the channels don't show in Kodi or?

**Comment by matthuisman** [comment]
if its EPG issue, for starters you have no **tvg-id** attributes for each channel. they need that to correctly link to the correct channel from the EPG itself.
