### ISSUE TITLE
Ri5  peewee.OperationalError no such table or settings. 

### ISSUE THREAD

**Issue by muddyjimmy** [matthuisman/slyguy.addons#903]
Slyguy is not working raspberry pi 5.  On both nexus and omega
Peewee.OperationalError
![20241027_080019](https://github.com/user-attachments/assets/6ccb20cf-f1a9-40fc-9133-218206b00690)
![20241027_080056](https://github.com/user-attachments/assets/b2e90ac7-500f-4e92-9ec3-86e8a1c3c04a)

**Comment by muddyjimmy** [comment]
![20241027_083905](https://github.com/user-attachments/assets/2072ff5a-b104-4af6-bfc1-09cab468c02b)
![20241027_083935](https://github.com/user-attachments/assets/e0e1e603-e763-4f24-99df-1cec04eeed77)

**Comment by matthuisman** [comment]
Try delete the settings.db file in userdata / slyguy.common directory

**Comment by muddyjimmy** [comment]
that worked. thank you for all you do.

**Comment by matthuisman** [comment]
No worries 🙂
