### ISSUE TITLE
Please return BINGE to SlyGuy!

### ISSUE THREAD

**Issue by nesjws** [matthuisman/slyguy.addons#904]
Hey! I’m not really sure how this github stuff works but…

With the demise of Telstra TV, i’m sure many people (including myself) would love to see a return of Binge to the SlyGuy platform.

I understand if your unable to, but i would very much appreciate it!

**Comment by matthuisman** [comment]
please see existing issue https://github.com/matthuisman/slyguy.addons/issues/586
