### ISSUE TITLE
MAX and test video stream does not working

### ISSUE THREAD

**Issue by lordrak007** [matthuisman/slyguy.addons#905]
Just receive error: One or more failed to play ...

All logs after click to play HLS in test video plugin:
ď»ż2024-10-29 18:39:33.736 T:20888    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.tester/?_=play_video&_play=1&index=0
2024-10-29 18:39:33.738 T:20400    info <general>: Creating InputStream
2024-10-29 18:39:33.738 T:20400    info <general>: Creating Demuxer
2024-10-29 18:39:33.761 T:20400   error <general>: CVideoPlayer::OpenDemuxStream - Error creating demuxer
2024-10-29 18:39:33.761 T:20400    info <general>: CVideoPlayer::OnExit()
2024-10-29 18:39:33.846 T:20888    info <general>: CVideoPlayer::CloseFile()
2024-10-29 18:39:33.846 T:20888    info <general>: VideoPlayer: waiting for threads to exit
2024-10-29 18:39:33.847 T:20888    info <general>: VideoPlayer: finished waiting

Whats wrong? Other plusing working as expected.
Thank you

**Comment by matthuisman** [comment]
Full kodi debug log plz

**Comment by lordrak007** [comment]
Ah, sure
[kodi.zip](https://github.com/user-attachments/files/17561380/kodi.zip)

**Comment by matthuisman** [comment]
have you set a bad kodi proxy value in kodi settings?

**Comment by lordrak007** [comment]
No, i just used proxy for while and now it is disabled. I also tried clear settings on proxy page.
And i also test setup proxy again and use it but same result. Other plugins works, MAX and test video plugins does not.
I test kodi 22 and 21.

**Comment by matthuisman** [comment]
can you enable Kodi debug logging and then re-create the log?

**Comment by lordrak007** [comment]
here
https://paste.kodi.tv/ijotewifil.kodi

**Comment by matthuisman** [comment]
seems nothing can talk to the slyguy proxy on port 52183
Do you have something else running on http://127.0.0.1:52183 ?

**Comment by lordrak007** [comment]
No, nothing else. I used netstat -an | findstr 521 command and this port is used only when Kodi is running.
Can i call uri http://127.0.0.1:52183/ some how to test it?

**Comment by lordrak007** [comment]
I just test call http://127.0.0.1:52183/  in web browser and got some file, which looks like service with ffmpeg ... is that correct?

**Comment by matthuisman** [comment]
was Kodi running at the time?

**Comment by lordrak007** [comment]
Yes

**Comment by matthuisman** [comment]
great. now in the debug kodi log, that proxy web server should have logged something?

**Comment by lordrak007** [comment]
Only this: https://paste.kodi.tv/gujiduwufe

**Comment by lordrak007** [comment]
A found something: https://paste.kodi.tv/bigedonegu.kodi
On the first line, kodi cannot access localhost on port 52183.
On line 26 i took URI from 1st line and access it wia web browser. So Kodi, (maeby some part of you plugin?) cant access to 127.0.0.1:52183 but it is general accessible. Have you idea why?

**Comment by lordrak007** [comment]
Hmm, when i open URI bellow in VLC it working. Do problem must be between proxy on 127.0.0.1:52183 and Kodi (plugin) itself.
http://127.0.0.1:52183/https://cdn.bitmovin.com/content/assets/art-of-motion-dash-hls-progressive/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by matthuisman** [comment]
Are you sure Kodi has no proxy / internet setting enabled? Seems odd that it couldn't take to 127.0.0.1

**Comment by lordrak007** [comment]
I am prety sure. I know only one place where proxy for Kpdi can be setup - in settings - internet...
Or is there another option for kodi?
I also found interesting setting in your plugin about proxy. When i disable slyguy proxy, slyguy test video plugin start working but MAX still does nothing.

**Comment by matthuisman** [comment]
yes, quite a few addons need my proxy to work.
We need to figure out why kodi cant talk to it

**Comment by lordrak007** [comment]
But i have not idea how to check this. Have some suggestion?

**Comment by matthuisman** [comment]
@lordrak007 I have asked on the kodi dev slack channel.
Have you tried with Kodi 21 stable by any chance?
I wonder if its a 22 bug maybe.

Also, when you install Kodi / start it - sometimes you get a firewall pop-up to allow access.
Maybe you need to select yes on that?

**Comment by matthuisman** [comment]
Please also try install this version of slyguy common and see if it helps
[script.module.slyguy.zip](https://github.com/user-attachments/files/17625000/script.module.slyguy.zip)

This has two changes
1) start the webserver listing on 0.0.0.0 (all hosts) instead of 127.0.0.1
2) changed the port to 8081

see if this causes windows to show a Accept/Deny firewall message.
If you see that, click yes

**Comment by matthuisman** [comment]
bump @lordrak007  :)

**Comment by lordrak007** [comment]
Sorry, to much work and family. I will do the tests ...

**Comment by lordrak007** [comment]
I did these tests:
1) tries Kodi v21 - does not work
2) update your module - does not work
3) disable Firewall - does not work
4) Run windows Sanbox, copy Kodi 22 there (portable run) and it does work!

So problem must by in my OS Setup, but i have no idea where and why. I have disabled FW (non windows defalt FW) mapping network connectoins and i see nothing. No problem.
Very strange for me is why same link (from log file) workign using VLC and not in Kodi.

**Comment by matthuisman** [comment]
Does Kodi on portable mode work? -p ?
Without the windows sandbox?

**Comment by matthuisman** [comment]
and you have tried starting from a complete fresh install of Kodi without an existing userdata?
To rule out some setting or add-on causing issues?

**Comment by lordrak007** [comment]
Yes i used portable mode. And i tried fresh Kodi 21 in portable mode only with slyguy and there was problem also.

**Comment by matthuisman** [comment]
Hmm. I'm out of ideas sorry. Never seen it before

**Comment by matthuisman** [comment]
Your not using Kodi windows store version? Make sure using the installer
exe from their websites

**Comment by matthuisman** [comment]
@lordrak007 
Could you try the http webserver in the Kodi YT plugin?
See if that works.

It looks like for calling there webserver, they use the netloc address and not 127.0.0.1
So, itd use your 192.XX or whatever your local IP address is:
https://github.com/anxdpanic/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/kodion/network/http_server.py#L657

Ill upload a slyguy common tonight that uses xbmc.getIPAddress() instead of 127.0.0.1 and see if that works for you.

**Comment by matthuisman** [comment]
OK, try this and see if it helps:
[script.module.slyguy.zip](https://github.com/user-attachments/files/17695594/script.module.slyguy.zip)

**Comment by lordrak007** [comment]
Hmm, thank you but it does not working. I have no idey why internal process cannot access the proxy server.
When i access url (from log file) via vlc ir works. (http://192.168.0.17:52183/https://cdn.bitmovin.com/content/assets/art-of-motion-dash-hls-progressive/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
Problem is probably in my OS, but i have no idea where problem is. I also tries disable FW and Antivirus...

**Comment by matthuisman** [comment]
do you have a log with that latest slyguy common?
I want to make sure its calling the same as you have above.

**Comment by matthuisman** [comment]
when you first run kodi - it usually asks you to allow something? maybe you clicked no?

**Comment by lordrak007** [comment]
No, you probably mean windows Firewall, so no. I am using Trend Micro and it did not ask and there is not information about blocking.

**Comment by matthuisman** [comment]
strange. can you get me a new log by any chance ?

**Comment by matthuisman** [comment]
im going to close this issue now. I've tried everything I can think possible.

Please report back if you ever figure out the issue
