### ISSUE TITLE
Disney+ `background` KeyError

### ISSUE THREAD

**Issue by fulder** [matthuisman/slyguy.addons#906]
I think there's a bug while trying to enter some season in Disney+ where the background property doesn't exists. I'm getting the KeyError exception for the `background` key on the following line:

https://github.com/matthuisman/slyguy.addons/blob/868a04012fd5e25359a602ecd75e53d359ae19f9/slyguy.disney.plus/resources/lib/plugin.py#L929

couldn't find any issues regarding this. 

It is reproducible for e.g. "American Horror Stories" and Season 2 and 3.

**Comment by matthuisman** [comment]
what country are you in please?

**Comment by matthuisman** [comment]
fixed in [slyguy.disney.plus -> v0.17.4](https://github.com/matthuisman/slyguy.addons/commit/b6a8181ae369679e22cbc520154f9cc786aa1677)

**Comment by fulder** [comment]
Thanks for the quick fix, it works fine now :+1:
