### ISSUE TITLE
Request AddOn for Samsung TV Plus

### ISSUE THREAD

**Issue by mchalep** [matthuisman/slyguy.addons#908]
Hi, I was wondering if the NEW channel “ghost” is going to be added to Samsung TV Plus. Would be very grateful if this could be considered for addition.

Regards

Patrick

**Comment by matthuisman** [comment]
i dont manually add channels. they are automatically scraped. If that channel is not using Widevine DRM and is in one of the regions I scrape, it will automatically be added

**Comment by mchalep** [comment]
Thanks Matt. Great work you guys do on the add ons.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
