### ISSUE TITLE
Disney+ error: API request failed

### ISSUE THREAD

**Issue by jjplano** [matthuisman/slyguy.addons#913]
hi! I'm receiving this error while trying to play any title on Disney+

I'm in South America, using Kodi 20.3 on a raspi3 with libreelec 11.0.6

this is the events log http://paste.libreelec.tv/polished-hen.log

thanks in advance!

**Comment by jjplano** [comment]
it's working again...

**Comment by matthuisman** [comment]
Oh. I didn't make any changes. But thanks for letting me know
