### ISSUE TITLE
ESPN+ Streams are No Longer in HD

### ISSUE THREAD

**Issue by pixel8323** [matthuisman/slyguy.addons#914]
I have your ESPN add-on (v0.4.1) installed on Kodi v21.1 on a Windows 10 PC. I'm noticing that ESPN+ streams are limited to 896 x 512 (SD) resolution at 29.97 FPS even though I have the quality select mode set to "Best" in the SlyGuy Common quality settings. In the past, I was able to stream at 720p and 59.94 FPS. All of my InputStream Adaptive (v21.5.7) settings are at the default values. Any idea as to why HD streams no longer work?

**Comment by TopekaRoy** [comment]
I'm having the same issue. see screenshot
![ESPN+](https://github.com/user-attachments/assets/a24e1c50-8335-4c9d-a06a-adb09c0e9e01)

**Comment by matthuisman** [comment]
has ESPN themselves dropped the quality?
Can you confirm 720p is available elsewhere? eg. their website?

**Comment by matthuisman** [comment]
https://www.reddit.com/r/ESPN/comments/1gul91i/espn_terrible_picture_quality_on_computer/

**Comment by TopekaRoy** [comment]
Neither the website nor the Android app allows you to choose the bitrate/resolution, nor can I find any indication of what the current streaming quality is. However, just looking at it, it looks like both are still streaming in HD.

**Comment by matthuisman** [comment]
you can use chrome webdev tools to see the requests their webpage makes. then look for the m3u8 and in that, you should see the qualities

**Comment by TopekaRoy** [comment]
I was hoping pixel8323 would weigh in. I tried to find the info you requested using webdev tools, but I couldn't find any .m3u8 file even using <control+f> to search for the string. The code is a bit over my head, though. I know BASIC and .html, but I'm not familiar with java script or cascading style sheets. I did take a screen shot of the same event (full screen) in the Windows browser and in Kodi @ 896x504 res and the web stream was clearly sharper. I can provide those if you want to take a look. It seems unlikely that ESPN would quit providing HD streams with the resources of Disney/ABC/Hulu, especially in light of the fact that they are about to raise their subscription prices (again!) from $10.99 to $11.99 per month.

I also have a Paramount+ sub and I noticed the highest resolutions are still available there.

**Comment by pixel8323** [comment]
Although I haven't tried ESPN+ recently in a web browser, I can say (based on my visual observations) that the ESPN Android TV app definitely provides HD streams along with a higher frame rate. 720p at 60 FPS is what ESPN has used for years and that has not changed with their official apps.

**Comment by matthuisman** [comment]
i tried looking into this now but unfortunately the login i was provided some years ago no longer works

if anyone can help with a ESPN+ or a compatible TV Provider login - please see here:
https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by TopekaRoy** [comment]
I'm not sure that would work. I just tried to log in on a new device and they emailed me a 6 digit code. They might cancel my account if they detect I'm logging in from the United States and New Zealand at the same time. Does ESPN still a 30 day free trial?
![Screenshot 2024-11-21 at 10-51-44 Your one-time passcode for ESPN - roylefredrickson@gmail com - Gmail](https://github.com/user-attachments/assets/03d5c04f-510b-4ad5-947a-86189873fe34)

**Comment by matthuisman** [comment]
Don't think that's needed for a tv provider login (att, dish etc) I think
that's what I used to use.

I do have my own free login but couldn't find any free content to test
quality on

**Comment by TopekaRoy** [comment]
Oh, I can't help you with that, anyway. I don't have an authorized TV provider for the ESPN cable channels. I get those through a cheap overseas IPTV service. I subscribe to ESPN+ for all the additional (mostly college games) content, but that doesn't include ESPN, ESPN2, ESPNU and ESPNews. :)

**Comment by TopekaRoy** [comment]
The HD streams are back! I don't know if you did something or if ESPN did, but thank you for all your hard work.

**Comment by matthuisman** [comment]
😆 I didn't do anything. That's odd. Must have been ESPN issue then?

**Comment by TopekaRoy** [comment]
Must've been. Let's see how long it lasts. LOL.

**Comment by matthuisman** [comment]
I'll close this for now. We can reopen if issue cones back
