### ISSUE TITLE
Addons do not work in RetroPie (Inputstream.Adaptive 2.4.4)

### ISSUE THREAD

**Issue by crimsonblue17** [matthuisman/slyguy.addons#918]
RetroPie is stuck on Kodi version 17.8 and Inputstream.Adaptive version 2.4.4. The addons will install and can sign in, but no video ever plays. will there be any support for this platform?

**Comment by matthuisman** [comment]
Not at all. That's much too old. You should be able to use some addon's but
any that require Widevine are not going to work
