### ISSUE TITLE
Disney+ problem

### ISSUE THREAD

**Issue by erikatremblay** [matthuisman/slyguy.addons#92]
hello, i have a beelink GT King and i have installed the disney + app in kodi 18.9.  I have a problem I log into my account and I select a video.  once I play the video it either doesn't start or it starts without a picture with sound but after 8 seconds it stops and after that time continues to pass with no sound and no picture.  nothing works its done that on all categories and all links.  I checked my inputstream and it's ok I searched in a lot of forums and couldn't find an answer to my problem. Can you help me. 

Thank you

**Comment by matthuisman** [comment]
Try going to add-ons > inputstream > inputstream adaptive > configure > advanced and enable "try use non secure decoder if possible"

If you don't have that setting, try going to add-ons > services > sluguy common > configure and then change the widevine level to level 3. Then restart kodi

**Comment by erikatremblay** [comment]
Thank you very much!! I just do this : sluguy common > configure and then change the widevine level to level 3. Then restart kodi

and disney+ work #1 you’re the best!

**Comment by matthuisman** [comment]
Quick question. Is your device running android?

**Comment by erikatremblay** [comment]
> 

Yes why?

**Comment by matthuisman** [comment]
Just curious
