### ISSUE TITLE
IPTV AU, NZ + others not choosing best stream quality

### ISSUE THREAD

**Issue by jordandalley** [matthuisman/slyguy.addons#920]
Hi matt,

Love your work! I've just noticed recently that the addons seem to be ignoring the stream quality selection. Even if I select 'Ask' the streams just play, and they don't always pick the best quality.

Platform: Android TV 11
Kodi: 21.1
Inputstream Adaptive: 21.5.7
IPTV AU: 0.20.2
IPTV NZ: 0.19.3
Sky Go: 0.3.1

Seems consistent on Channel 7 and Sky Sport 1.

I've tried resetting the addons to no avail.

Let me know if you need any additional information or tests?

Cheers,
Jordan.

**Comment by matthuisman** [comment]
Have you disabled slyguy proxy by accident?

**Comment by jordandalley** [comment]
Nope, it's enabled.

**Comment by matthuisman** [comment]
What version slyguy common?

**Comment by jordandalley** [comment]
0.85.48

**Comment by jordandalley** [comment]
Solved by giving the TV a full restart. Sorry for wasting your time!
