### ISSUE TITLE
Paramount + Error in plugin.py: Null Object Causes lower() Method Failure in def show()

### ISSUE THREAD

**Issue by micheleciondolo** [matthuisman/slyguy.addons#922]
When I try to access the list of streams, for example for the Champions League, the Python script plugin.py throws an error because it attempts to apply the lower method on a null object.

It would take very little to modify the script and make it work. You just need to change the line inside def show() to:

if config.get('display_seasons') and 'episodes' in (config.get('section_type') or '').lower():

Unfortunately, the file is inaccessible on Android TV.
can you update the script'???? :)

**Comment by matthuisman** [comment]
so the error is on section_type?

**Comment by micheleciondolo** [comment]
yep you can edit line 437 slyguy.addons/tree/master/slyguy.paramount.plus/resources/lib/plugin.py
:)

Thankkk you!

you can do a test selecting UCL Champions League from the list of the shows on paramount plus.

if you change in 
if config.get('display_seasons') and 'episodes' in (config.get('section_type') or '').lower():

you get rid of finding the section type. :)

**Comment by matthuisman** [comment]
yup. i just wanted to check what config dict was before implementing fix. Does look like valid sections can have section_type None so have implemented your suggested fix.

Update pushed on [slyguy.paramount.plus -> v0.9.6](https://github.com/matthuisman/slyguy.addons/commit/f7556681436d05a28f6e5b5cb2ae8d8766edb580)

How to force update:
https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html

**Comment by matthuisman** [comment]
thank you :)

**Comment by micheleciondolo** [comment]
thank youuu
