### ISSUE TITLE
Installed Disney+ no login on main menu

### ISSUE THREAD

**Issue by dljones8053** [matthuisman/slyguy.addons#927]
Signed up for HULE and Disney+ yesterday as HULU is working fine but Disney+ I cannot login also I notices no Settings option on main menu or login option. Is their a xml file that can be changed to correct this behavior?

Thanks
Daryl

**Comment by matthuisman** [comment]
What do you see when you open the Disney Addon? It should just be login and
settings

**Comment by dljones8053** [comment]
Hey Matt

I finally broke down and uninstalled everything on your plugin and the
repository. Once I installed everything it’s all working now. If I could
have found the Disney xml config file I would have figured it out.

Daryl

**Comment by matthuisman** [comment]
There is no Disney config xml

**Comment by dljones8053** [comment]
Good reason I couldn’t find it so where are the configuration files if you
don’t mind me asking?

**Comment by matthuisman** [comment]
All the addon settings are stored in a db that lives in slyguy common
directory
