### ISSUE TITLE
ESPN section within Disney+ kodi addon.

### ISSUE THREAD

**Issue by chinosoliard** [matthuisman/slyguy.addons#928]
At least in Argentina, ESPN was accessible via Star+, after merging "disney+" and "star+" in a single service, the service is still accessible. However, in the plugin, I was not able to access any ESPN content, even after adding some to "my list", those are not being displayed.

I am sharing as screenshot. You can see ESPN section at the top, and ESPN content at button.

![image](https://github.com/user-attachments/assets/fa71d290-80c4-4948-bd2b-c0994bd1cb5c)

Side note: ESPN+ is not the same than ESPN within Disney+.

**Comment by matthuisman** [comment]
there is already an issue for this: https://github.com/matthuisman/slyguy.addons/issues/923
so closing as duplicate
