### ISSUE TITLE
Thanks bro. It does the job and I got it working

### ISSUE THREAD

**Issue by omarmuthana112** [matthuisman/slyguy.addons#929]
Thanks bro. It does the job and I got it working

_Originally posted by @alienmaster9 in https://github.com/matthuisman/slyguy.addons/issues/748#issuecomment-2121480248_
            

Can you sir please provide me the way to make license request ?

**Comment by matthuisman** [comment]
do not open issues like this

**Comment by omarmuthana112** [comment]
Sorry sir, I just wanted to check if I miss something while requesting
keys. Because I made the same request you did but I get empty response sir.
Can you help me sir
