### ISSUE TITLE
Stremium New Paywall for the channels synced via providers

### ISSUE THREAD

**Issue by Timbo303** [matthuisman/slyguy.addons#93]
Currently makes the app broken since no channels from sling load. Only the custom channels and public channels work since these aren't behind a paywall. This is very easy to reproduce. Sadly this means stremium is a no go for me seeing how channelsdvr does integration better and it works with my hdhomerun on top of that. Fun while it lasted.

**Comment by mfreeman72** [comment]
So that explains why it was giving me an error last night. That stinks. Still, it's only $5/month. Might not be too bad a thing, as long as it can still work with the addon. Any word on this, Matt?

**Comment by matthuisman** [comment]
First I've heard of any issues.
So sling etc no longer work via streamium?
Do they work still on their website?

**Comment by Timbo303** [comment]
Sling works on their site but you have to pay $5/month.

**Comment by matthuisman** [comment]
On top of paying for sling already?
Is it $5 for each provider? Or just a one-off to get access to them?

**Comment by Timbo303** [comment]
Yes you pay sling technically already. Now to use sling with stremium, stremium is charging $5/month I will show you picture.

**Comment by matthuisman** [comment]
Oh I see. They have changed their plans. Need basic plan to add 3rd party
providers.

I'm not sure if they still work then.  I don't even have any logins for the
3rd party providers.

**Comment by Timbo303** [comment]
Notice the connect 3rd party providers on the $5/month plan but not the free one.

![Screenshot_20211202-121245_Chrome](https://user-images.githubusercontent.com/28489517/144479450-ba9d1211-4915-41fa-b90b-9116e0c5803a.jpg)

**Comment by matthuisman** [comment]
You could take a punt and try? If it didn't work, I'm sure I could make it work again if I had temporary access to a login to test with

**Comment by Timbo303** [comment]
Try a free trial of philo they are the easiest to get unlimited free trials I believe.

**Comment by matthuisman** [comment]
Could do a stremium free trial of basic plan and free trial of philo?

**Comment by Timbo303** [comment]
Thats

> Could do a stremium free trial of basic plan and free trial of philo?

That is probably a great idea granted you know what the problem is in the code if there is any. You would have to retry over and over with new accounts if you can't do it 7 days.

**Comment by matthuisman** [comment]
just did a small update to the add-on so it now gives a proper error if a channel requires a plan
(same error get on website)

Pretty sure the call will just return the same data that used to work once sub'd. but ill try get a trial to confirm

**Comment by matthuisman** [comment]
just confirmed that Philo at least still works so I suspect the rest will too once you have a Basic sub

**Comment by wbeard52** [comment]
I have a Vidgo account that I purchased separately from Stremium.  The integration still works after the paywall went up.
