### ISSUE TITLE
MAX - not playing when using kodi favorites

### ISSUE THREAD

**Issue by notoco** [matthuisman/slyguy.addons#934]
After adding videos to favorites in Kodi (not to bookmarks in MAX), the videos do not play.

```
<favourites>
    <favourite name="Na skraju jutra" thumb="http://127.0.0.1:52103/https://images.cdn.prd.api.discomax.com/2024/10/14/cdeded37-79cb-3636-85e9-5f6e69e34f01.jpeg?w=600|user-agent=okhttp/4.9.3&amp;session_type=art&amp;session_addonid=slyguy.max">PlayMedia("plugin://slyguy.max/?_=play&amp;_play=1&amp;id=8d4640d7-fb4c-4ea8-bdc5-2c63a8b5ffe0")</favourite>
</favourites>
```

The same movie plays fine from Max addon.
In logs there is:
```
2024-12-15 18:00:02.623 T:38       info <general>: script.module.slyguy - Proxy Started: http://127.0.0.1:52103/
(...)
2024-12-15 18:00:54.758 T:60      error <general>: CCurlFile::Open - <http://127.0.0.1/e7e4f92f-88db-46ca-bfea-e493fd516747/v/0_708211/v1.mp4> Failed with code 0:
```

something with proxy?
Kodi 21.1 on linux, with last videwine - it works about one/two months ago.

**Comment by notoco** [comment]
Ok - last working with kodi favorites version of script.module.slyguy is v0.85.26 - after this commit favorites not playing:
<https://github.com/matthuisman/slyguy.addons/commit/f611e4ee946745e365cb4e7dca1eada53d463ff7>

**Comment by notoco** [comment]
And - in last version of script.module.slyguy works when you comment this line:
<https://github.com/matthuisman/slyguy.addons/blob/master/script.module.slyguy/resources/lib/proxy.py#L921>

**Comment by matthuisman** [comment]
I'll take a look tonight 🙂

**Comment by notoco** [comment]
I'll take a look tonight 🙂

**Comment by matthuisman** [comment]
just try from creating a fresh favorite from within kodi (context -> add favorites)
then try play that favorite.

If that works - work from there

**Comment by notoco** [comment]
I installed Kodi again, this time with *.deb. 
I couldn't repeat it. There must have been something going on in Kodi itself. Thanks for your help.
