### ISSUE TITLE
CuriosityStream multiple bugs

### ISSUE THREAD

**Issue by Sirove** [matthuisman/slyguy.addons#95]
Hello there, I got two bugs persistent over weeks even though the reinstall of all SlyGuy addons (everything is up to date):

1. ![nextpage](https://user-images.githubusercontent.com/24733228/144604012-3b0cc7ce-5c17-4211-8e3d-77617d7f208d.png)
2. last playback positions don't get remembered 
and even after finishing a documentary it's still necessary to "mark as watched" manually.

**Comment by matthuisman** [comment]
issue 1 is fixed with version 0.1.9

For issue 2 - do you have "Sync with curiosity" enabled or disabled in addon settings?
If enabled, try disable it and then see if watched / resume all work ok

**Comment by Sirove** [comment]
I can confirm issue 1 is fixed with update!

You’re right about the "sync with curiosity" switch. It solves the problem!
