### ISSUE TITLE
IPTV Merge - support/recognize plugin.video.jiotv

### ISSUE THREAD

**Issue by rrjanbiah** [matthuisman/slyguy.addons#98]
(Originally posted here based on the plugin page link https://www.reddit.com/r/MattHuisman/comments/ceqvxc/iptv_merge_kodi_addon/hnore27/?context=3, but based on your other note in the Reddit, posting here)

The plugin doesn't seem to recognize https://github.com/botallen/plugin.video.jiotv (This seems to be popular in India. @iMro0t primary repo is https://github.com/botallen/repository.botallen )

Context (If in case, there are any other options for the same): I was trying to merge it with `https://iptv-org.github.io/iptv/index.category.m3u` to get all possible channels.

**Comment by matthuisman** [comment]
You'll need to ask the Dev of that addon

**Comment by matthuisman** [comment]
actually, seems it already generates a playlist so I have now added support in IPTV Merge with v0.20.8 (https://github.com/matthuisman/slyguy.addons/commit/62be6c04a231a7cf2342ce64a18f06bd0b8b8cc4)

Once updateds, you should be able to **Playlists > Add Playlist > Add-on > jiotv**

**Comment by rrjanbiah** [comment]
Wow, thanks for your super fast support. Due to power outage here, I couldn't test it yet. Will try to test and update you as soon as I can. Thanks again.

**Comment by rrjanbiah** [comment]
@matthuisman Thank you so much. It seems to work, but I want to share few notes:

1. Jio TV plugin is not recognized under the EPG option
2. So, I referred somewhere and manually added `https://kodi.botallen.com/tv/epg.xml`, but that failed with `not well-formed (invalid token): line 1, column 0`
3. But, strangely, I'm able to view Jio TV programs under the channel guide! (not sure, how it happens)
4. I had to keep only the Pluto TV and Jio TV under the playlist. If I add more addons (say, Plex, NZ, AU), the PVR client is stuck at 0% starting

Also, is it possible to add support for other IPTVs say, The Crew, TVTap, etc? If so, I can open another ticket with all the plugins list.

Thanks again.

**Comment by matthuisman** [comment]
1) That is fine, the EPG link is inside the playlist so no need for EPG entry
2) no need for that
3) yes, due to #1 
4) try clearing the PVR data in kodi settings. IPTV Simple can jam up

5) No sorry

**Comment by rrjanbiah** [comment]
Thank you

**Comment by rrjanbiah** [comment]
@matthuisman Few more notes that you may be interested in:

1. Jio TV guides became blank now (So, looks like yesterday it was fetched from some cache... and EPG is required and not available with the playlist)
2. I again added, `https://kodi.botallen.com/tv/epg.xml` through URL option. Got the same old `not well-formed (invalid token): line 1, column 0` error. Now, I circumvented by forcing the type to `Gzip` instead of `Auto`. Looks like the `Auto` logic has some issues. So, it finally fetched the guides.
3. Note that, previous error is displaying here (i.e., `not well-formed (invalid token): line 1, column 0`) till we run the merge, even after switching `Gzip` or make any changes to the URL
4. When running merge, most of the time it get stuck at 50% or so. At that time, if we click "Settings" (available next to the merge option), it helps to move ahead. Not sure, what is going on here.
5. I handpicked few kids and Christian channels through `https://channelizer.tv/url/-CysUrzE` (they're shutting down unfortunately) and done merge. It worked great. But, the guides are missing. So, I think, EPG is required here too. Looks like your plugins alone not requiring separate EPG.
6. Regarding the playback quality option, all options such as `Lowest`, etc are clear, except the `Bypass`. I can't seem to find it anywhere except https://github.com/matthuisman/slyguy.addons/pull/59#:~:text=What%20does-,Bypass,-do%20regarding%20playback (You may consider mentioning that in the plugin page https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html )

**Comment by matthuisman** [comment]
1) his playlist does provide the EPG https://kodi.botallen.com/tv/epg.xml in it see here: https://github.com/botallen/plugin.video.jiotv/blob/main/resources/lib/main.py#L352
The issue is that AUTO tries to guess if gzipped based on the filename.
https://kodi.botallen.com/tv/epg.xml actually redirects to a .gz on github but then that redirects to a githubusercontent final url that does not end with gz. So merge just thinks its not compressed
2) Same issue as above. 
3) Correct, the message shown next to a source is the message from the last run. You need to run merge to get it to try again. Merges are expensive, you dont want them to automatically run when a source is change
4) Clicking settings wouldnt change anything. not sure whats going on there. 
5) Only playlists that include a link to an EPG file will have EPG. eg. #EXTM3U x-tvg-url="https://kodi.botallen.com/tv/epg.xml"
6) https://www.matthuisman.nz/2019/09/new-quality-select-in-my-add-ons.html

Anyway, to fix 1 & 2 - I'll update soon to instead of checking filename, it will actually read the first few bytes of the file to detect the compression

**Comment by matthuisman** [comment]
ok, 0.21.2 of IPTV Merge just pushed.
This will fix issue 1.
Now you can remove the EPG entry and it will correctly use the one provided by the playlist

**Comment by rrjanbiah** [comment]
@matthuisman 

I can confirm that your archive detection is working good. Tested by disabling EPG, clearing guides cache, running merge, clearing guides cache.

> Clicking settings wouldnt change anything. not sure whats going on there.

Right now, I have Pluto TV, Jio TV and `https://channelizer.tv/url/-CysUrzE`. It always get stuck at 2/3 Jio TV at 66%. Clicking "Settings" is the only way to move forward. Tested around 7 times; by waiting ~2-20 minutes randomly. As I have this workaround, I'm happy. You may want to keep this in mind.

> Quality select options explained here: https://www.matthuisman.nz/2019/09/new-quality-select-in-my-add-ons.html

Thanks for sharing this, I couldn't find it earlier. However, in this page, you have explained the `Bypass` in the global settings page. If in the global settings you have `Ask (default)`, it will prompt with the dialog as you've shown in the first screenshot. I think, the meaning of `Bypass` is different as you explained in https://github.com/matthuisman/slyguy.addons/pull/59 Or, you may be right, but not clear for a non-native speaker; in that case, please ignore.

Thanks again for your support

**Comment by matthuisman** [comment]
are you using Kodi 18 or 19?
What device?

**Comment by rrjanbiah** [comment]
@matthuisman 

It is Kodi 19.

Device is Fire TV stick (3rd gen, 2021) https://www.amazon.in/dp/B08R6QR863

**Comment by matthuisman** [comment]
is it only Jio TV that has issues?
If you remove / disable that source and add a bunch of others - does it work fine?

**Comment by rrjanbiah** [comment]
Genius! It happens with the Jio TV alone. I have loaded all your plugins and `https://iptv-org.github.io/iptv/index.language.m3u`; they all ran without the stuck

**Comment by matthuisman** [comment]
great, so thats a clue :)
ill look into why Jio TV is freezine

**Comment by rrjanbiah** [comment]
@matthuisman Great, thanks
