### ISSUE TITLE
Pluto TV - Integrating channel guide

### ISSUE THREAD

**Issue by rrjanbiah** [matthuisman/slyguy.addons#99]
Apologies, if this is already possible (complete newbie here). But, I noticed that I have to open the Pluto TV addon and then have to choose the channels.

For instance, this https://github.com/botallen/repository.botallen (by @iMro0t), especially the Jio TV addon (which I use) has directly integrated the channel guide in the home screen (not sure, if the terminology is correct here.. but hope, you can understand it) without needing to open the addon. Would that be difficult here?

**Comment by matthuisman** [comment]
You'll need to ask the Dev of those add-ons
